CKEDITOR.dialog.add("scaytcheck",function(l){function z(){return"undefined"!=typeof document.forms["optionsbar_"+b]?document.forms["optionsbar_"+b].options:[]}function A(a,b){if(a){var e=a.length;if(void 0==e)a.checked=a.value==b.toString();else for(var d=0;d<e;d++)a[d].checked=!1,a[d].value==b.toString()&&(a[d].checked=!0)}}function q(a){f.getById("dic_message_"+b).setHtml('<span style="color:red;">'+a+"</span>")}function r(a){f.getById("dic_message_"+b).setHtml('<span style="color:blue;">'+a+"</span>")}
function s(a){a=(""+a).split(",");for(var b=0,e=a.length;b<e;b+=1)f.getById(a[b]).$.style.display="inline"}function t(a){a=(""+a).split(",");for(var b=0,e=a.length;b<e;b+=1)f.getById(a[b]).$.style.display="none"}function u(a){f.getById("dic_name_"+b).$.value=a}var v=!0,h,f=CKEDITOR.document,b=l.name,n=CKEDITOR.plugins.scayt.getUiTabs(l),g,w=[],x=0,p=["dic_create_"+b+",dic_restore_"+b,"dic_rename_"+b+",dic_delete_"+b],y=["mixedCase","mixedWithDigits","allCaps","ignoreDomainNames"];g=l.lang.scayt;var C=
[{id:"options",label:g.optionsTab,elements:[{type:"html",id:"options",html:'<form name="optionsbar_'+b+'"><div class="inner_options">\t<div class="messagebox"></div>\t<div style="display:none;">\t\t<input type="checkbox" name="options"  id="allCaps_'+b+'" />\t\t<label style = "display: inline" for="allCaps" id="label_allCaps_'+b+'"></label>\t</div>\t<div style="display:none;">\t\t<input name="options" type="checkbox"  id="ignoreDomainNames_'+b+'" />\t\t<label style = "display: inline" for="ignoreDomainNames" id="label_ignoreDomainNames_'+
b+'"></label>\t</div>\t<div style="display:none;">\t<input name="options" type="checkbox"  id="mixedCase_'+b+'" />\t\t<label style = "display: inline" for="mixedCase" id="label_mixedCase_'+b+'"></label>\t</div>\t<div style="display:none;">\t\t<input name="options" type="checkbox"  id="mixedWithDigits_'+b+'" />\t\t<label style = "display: inline" for="mixedWithDigits" id="label_mixedWithDigits_'+b+'"></label>\t</div></div></form>'}]},{id:"langs",label:g.languagesTab,elements:[{type:"html",id:"langs",
html:'<div class="inner_langs">\t<div class="messagebox"></div>\t   <div style="float:left;width:45%;margin-left:5px;" id="scayt_lcol_'+b+'" ></div>   <div style="float:left;width:45%;margin-left:15px;" id="scayt_rcol_'+b+'"></div></div>'}]},{id:"dictionaries",label:g.dictionariesTab,elements:[{type:"html",style:"",id:"dictionaries",html:'<form name="dictionarybar_'+b+'"><div class="inner_dictionary" style="text-align:left; white-space:normal; width:320px; overflow: hidden;">\t<div style="margin:5px auto; width:95%;white-space:normal; overflow:hidden;" id="dic_message_'+
b+'"> </div>\t<div style="margin:5px auto; width:95%;white-space:normal;">        <span class="cke_dialog_ui_labeled_label" >Dictionary name</span><br>\t\t<span class="cke_dialog_ui_labeled_content" >\t\t\t<div class="cke_dialog_ui_input_text">\t\t\t\t<input id="dic_name_'+b+'" type="text" class="cke_dialog_ui_input_text" style = "height: 25px; background: none; padding: 0;"/>\t\t</div></span></div>\t\t<div style="margin:5px auto; width:95%;white-space:normal;">\t\t\t<a style="display:none;" class="cke_dialog_ui_button" href="javascript:void(0)" id="dic_create_'+
b+'">\t\t\t\t</a>\t\t\t<a  style="display:none;" class="cke_dialog_ui_button" href="javascript:void(0)" id="dic_delete_'+b+'">\t\t\t\t</a>\t\t\t<a  style="display:none;" class="cke_dialog_ui_button" href="javascript:void(0)" id="dic_rename_'+b+'">\t\t\t\t</a>\t\t\t<a  style="display:none;" class="cke_dialog_ui_button" href="javascript:void(0)" id="dic_restore_'+b+'">\t\t\t\t</a>\t\t</div>\t<div style="margin:5px auto; width:95%;white-space:normal;" id="dic_info_'+b+'"></div></div></form>'}]},{id:"about",
label:g.aboutTab,elements:[{type:"html",id:"about",style:"margin: 5px 5px;",html:'<div><div id="scayt_about_'+b+'"></div></div>'}]}],E={title:g.title,minWidth:360,minHeight:220,onShow:function(){var a=this;a.data=l.fire("scaytDialog",{});a.options=a.data.scayt_control.option();a.chosed_lang=a.sLang=a.data.scayt_control.sLang;if(a.data&&a.data.scayt&&a.data.scayt_control){var b=0;v?a.data.scayt.getCaption(l.langCode||"en",function(e){0<b++||(h=e,D.apply(a),B.apply(a),v=!1)}):B.apply(a);a.selectPage(a.data.tab)}else alert("Error loading application service"),
a.hide()},onOk:function(){var a=this.data.scayt_control;a.option(this.options);a.setLang(this.chosed_lang);a.refresh()},onCancel:function(){var a=z(),f;for(f in a)a[f].checked=!1;a="undefined"!=typeof document.forms["languagesbar_"+b]?document.forms["languagesbar_"+b].scayt_lang:[];A(a,"")},contents:w};CKEDITOR.plugins.scayt.getScayt(l);for(g=0;g<n.length;g++)1==n[g]&&(w[w.length]=C[g]);1==n[2]&&(x=1);var D=function(){function a(a){var c=f.getById("dic_name_"+b).getValue();if(!c)return q(" Dictionary name should not be empty. "),
!1;try{var d=a.data.getTarget().getParent(),e=/(dic_\w+)_[\w\d]+/.exec(d.getId())[1];l[e].apply(null,[d,c,p])}catch(F){q(" Dictionary error. ")}return!0}var m=this,e=m.data.scayt.getLangList(),d=["dic_create","dic_delete","dic_rename","dic_restore"],g=[],k=[],c;if(x){for(c=0;c<d.length;c++)g[c]=d[c]+"_"+b,f.getById(g[c]).setHtml('<span class="cke_dialog_ui_button">'+h["button_"+d[c]]+"</span>");f.getById("dic_info_"+b).setHtml(h.dic_info)}if(1==n[0])for(c in y)d="label_"+y[c],g=f.getById(d+"_"+b),
"undefined"!=typeof g&&"undefined"!=typeof h[d]&&"undefined"!=typeof m.options[y[c]]&&(g.setHtml(h[d]),g.getParent().$.style.display="block");d='<p><img src="'+window.scayt.getAboutInfo().logoURL+'" /></p><p>'+h.version+window.scayt.getAboutInfo().version.toString()+"</p><p>"+h.about_throwt_copy+"</p>";f.getById("scayt_about_"+b).setHtml(d);d=function(a,b){var c=f.createElement("label");c.setAttribute("for","cke_option"+a);c.setStyle("display","inline");c.setHtml(b[a]);m.sLang==a&&(m.chosed_lang=
a);var d=f.createElement("div"),e=CKEDITOR.dom.element.createFromHtml('<input class = "cke_dialog_ui_radio_input" id="cke_option'+a+'" type="radio" '+(m.sLang==a?'checked="checked"':"")+' value="'+a+'" name="scayt_lang" />');e.on("click",function(){this.$.checked=!0;m.chosed_lang=a});d.append(e);d.append(c);return{lang:b[a],code:a,radio:d}};if(1==n[1]){for(c in e.rtl)k[k.length]=d(c,e.ltr);for(c in e.ltr)k[k.length]=d(c,e.ltr);k.sort(function(a,b){return b.lang>a.lang?-1:1});e=f.getById("scayt_lcol_"+
b);d=f.getById("scayt_rcol_"+b);for(c=0;c<k.length;c++)(c<k.length/2?e:d).append(k[c].radio)}var l={dic_create:function(a,b,c){var d=c[0]+","+c[1],e=h.err_dic_create,f=h.succ_dic_create;window.scayt.createUserDictionary(b,function(a){t(d);s(c[1]);f=f.replace("%s",a.dname);r(f)},function(a){e=e.replace("%s",a.dname);q(e+"( "+(a.message||"")+")")})},dic_rename:function(a,b){var c=h.err_dic_rename||"",d=h.succ_dic_rename||"";window.scayt.renameUserDictionary(b,function(a){d=d.replace("%s",a.dname);u(b);
r(d)},function(a){c=c.replace("%s",a.dname);u(b);q(c+"( "+(a.message||"")+" )")})},dic_delete:function(a,b,c){var d=c[0]+","+c[1],e=h.err_dic_delete,f=h.succ_dic_delete;window.scayt.deleteUserDictionary(function(a){f=f.replace("%s",a.dname);t(d);s(c[0]);u("");r(f)},function(a){e=e.replace("%s",a.dname);q(e)})}};l.dic_restore=m.dic_restore||function(a,b,c){var d=c[0]+","+c[1],e=h.err_dic_restore,f=h.succ_dic_restore;window.scayt.restoreUserDictionary(b,function(a){f=f.replace("%s",a.dname);t(d);s(c[1]);
r(f)},function(a){e=e.replace("%s",a.dname);q(e)})};k=(p[0]+","+p[1]).split(",");c=0;for(e=k.length;c<e;c+=1)if(d=f.getById(k[c]))d.on("click",a,this)},B=function(){var a=this;if(1==n[0])for(var g=z(),e=0,d=g.length;e<d;e++){var h=g[e].id,k=f.getById(h);if(k&&(g[e].checked=!1,1==a.options[h.split("_")[0]]&&(g[e].checked=!0),v))k.on("click",function(){a.options[this.getId().split("_")[0]]=this.$.checked?1:0})}1==n[1]&&(g=f.getById("cke_option"+a.sLang),A(g.$,a.sLang));x&&(window.scayt.getNameUserDictionary(function(a){a=
a.dname;t(p[0]+","+p[1]);a?(f.getById("dic_name_"+b).setValue(a),s(p[1])):s(p[0])},function(){f.getById("dic_name_"+b).setValue("")}),r(""))};return E});
