(function(h){"object"==typeof exports&&"object"==typeof module?h(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],h):h(CodeMirror)})(function(h){function C(a,c,b){var d=a.docs[c];d?b(y(a,d)):a.options.getFile?a.options.getFile(c,b):b(null)}function u(a,c,b){for(var d in a.docs){var e=a.docs[d];if(e.doc==c)return e}if(!b)for(b=0;;++b)if(d="[doc"+(b||"")+"]",!a.docs[d]){b=d;break}return a.addDoc(b,c)}function D(a,c){if("string"==typeof c)return a.docs[c];
c instanceof h&&(c=c.getDoc());if(c instanceof h.Doc)return u(a,c)}function M(a,c,b){var d=u(a,c),e=a.cachedArgHints;e&&e.doc==c&&0<=z(e.start,b.to)&&(a.cachedArgHints=null);e=d.changed;null==e&&(d.changed=e={from:b.from.line,to:b.from.line});var f=b.from.line+(b.text.length-1);b.from.line<e.to&&(e.to-=b.to.line-f);f>=e.to&&(e.to=f+1);e.from>b.from.line&&(e.from=b.from.line);c.lineCount()>E&&100<b.to-e.from&&setTimeout(function(){d.changed&&100<d.changed.to-d.changed.from&&F(a,d)},200)}function F(a,
c){a.server.request({files:[{type:"full",name:c.name,text:y(a,c)}]},function(a){a?window.console.error(a):c.changed=null})}function N(a,c,b){a.request(c,{type:"completions",types:!0,docs:!0,urls:!0},function(d,e){if(d)return t(a,c,d);var f=[],g="",v=e.start,m=e.end;'["'==c.getRange(r(v.line,v.ch-2),v)&&'"]'!=c.getRange(m,r(m.line,m.ch+2))&&(g='"]');for(var n=0;n<e.completions.length;++n){var k=e.completions[n],w=O(k.type);e.guess&&(w+=" "+l+"guess");f.push({text:k.name+g,displayText:k.displayName||
k.name,className:w,data:k})}var f={from:v,to:m,list:f},p=null;h.on(f,"close",function(){x(p)});h.on(f,"update",function(){x(p)});h.on(f,"select",function(c,b){x(p);var d=a.options.completionTip?a.options.completionTip(c.data):c.data.doc;d&&(p=B(b.parentNode.getBoundingClientRect().right+window.pageXOffset,b.getBoundingClientRect().top+window.pageYOffset,d),p.className+=" "+l+"hint-doc")});b(f)})}function O(a){a="?"==a?"unknown":"number"==a||"string"==a||"bool"==a?a:/^fn\(/.test(a)?"fn":/^\[/.test(a)?
"array":"object";return l+"completion "+l+"completion-"+a}function G(a,c,b,d,e){a.request(c,d,function(b,d){if(b)return t(a,c,b);if(a.options.typeTip)var g=a.options.typeTip(d);else if(g=q("span",null,q("strong",null,d.type||"not found")),d.doc&&g.appendChild(document.createTextNode(" \u2014 "+d.doc)),d.url){g.appendChild(document.createTextNode(" "));var f=g.appendChild(q("a",null,"[docs]"));f.href=d.url;f.target="_blank"}H(c,g,a);e&&e()},b)}function P(a,c){A(a);if(!c.somethingSelected()){var b=
c.getTokenAt(c.getCursor()).state,b=h.innerMode(c.getMode(),b);if("javascript"==b.mode.name&&(b=b.state.lexical,"call"==b.info)){for(var d,e=b.pos||0,f=c.getOption("tabSize"),g=c.getCursor().line,v=Math.max(0,g-9),m=!1;g>=v;--g){for(var n=c.getLine(g),k=d=0;;){k=n.indexOf("\t",k);if(-1==k)break;d+=f-(k+d)%f-1;k+=1}d=b.column-d;if("("==n.charAt(d)){m=!0;break}}if(m){var w=r(g,d);if((b=a.cachedArgHints)&&b.doc==c.getDoc()&&0==z(w,b.start))return I(a,c,e);a.request(c,{type:"type",preferFunction:!0,end:w},
function(b,d){!b&&d.type&&/^fn\(/.test(d.type)&&(a.cachedArgHints={start:w,type:Q(d.type),name:d.exprName||d.name||"fn",guess:d.guess,doc:c.getDoc()},I(a,c,e))})}}}}function I(a,c,b){A(a);for(var d=a.cachedArgHints,e=d.type,d=q("span",d.guess?l+"fhint-guess":null,q("span",l+"fname",d.name),"("),f=0;f<e.args.length;++f){f&&d.appendChild(document.createTextNode(", "));var g=e.args[f];d.appendChild(q("span",l+"farg"+(f==b?" "+l+"farg-current":""),g.name||"?"));"?"!=g.type&&(d.appendChild(document.createTextNode(":\u00a0")),
d.appendChild(q("span",l+"type",g.type)))}d.appendChild(document.createTextNode(e.rettype?") ->\u00a0":")"));e.rettype&&d.appendChild(q("span",l+"type",e.rettype));c=c.cursorCoords(null,"page");a.activeArgHints=B(c.right+1,c.bottom,d)}function Q(a){function c(c){for(var b=0,e=d;;){var f=a.charAt(d);if(c.test(f)&&!b)return a.slice(e,d);/[{\[\(]/.test(f)?++b:/[}\]\)]/.test(f)&&--b;++d}}var b=[],d=3;if(")"!=a.charAt(d))for(;;){var e=a.slice(d).match(/^([^, \(\[\{]+): /);e&&(d+=e[0].length,e=e[1]);b.push({name:e,
type:c(/[\),]/)});if(")"==a.charAt(d))break;d+=2}e=a.slice(d).match(/^\) -> (.*)$/);return{args:b,rettype:e&&e[1]}}function R(a,c){function b(b){b={type:"definition",variable:b||null};var d=u(a,c.getDoc());a.server.request(J(a,d,b),function(b,e){if(b)return t(a,c,b);if(!e.file&&e.url)window.open(e.url);else{if(e.file){var f=a.docs[e.file],g,n;if(n=f){var k;var h=f.doc;g=e.context.slice(0,e.contextOffset).split("\n");var p=e.start.line-(g.length-1);n=r(p,(1==g.length?e.start.ch:h.getLine(p).length)-
g[0].length);for(var l=h.getLine(p).slice(n.ch),p=p+1;p<h.lineCount()&&l.length<e.context.length;++p)l+="\n"+h.getLine(p);if(l.slice(0,e.context.length)==e.context)k=e;else{h=h.getSearchCursor(e.context,0,!1);for(l=Infinity;h.findNext();){var p=h.from(),q=1E4*Math.abs(p.line-n.line);q||(q=Math.abs(p.ch-n.ch));q<l&&(k=p,l=q)}k?(1==g.length?k.ch+=g[0].length:k=r(k.line+(g.length-1),g[g.length-1].length),g=e.start.line==e.end.line?r(k.line,k.ch+(e.end.ch-e.start.ch)):r(k.line+(e.end.line-e.start.line),
e.end.ch),k={start:k,end:g}):k=null}n=g=k}if(n){a.jumpStack.push({file:d.name,start:c.getCursor("from"),end:c.getCursor("to")});K(a,d,f,g.start,g.end);return}}t(a,c,"Could not find a definition.")}})}S(c)?b():L(c,"Jump to variable",function(a){a&&b(a)})}function K(a,c,b,d,e){b.doc.setSelection(d,e);c!=b&&a.options.switchToDoc&&(A(a),a.options.switchToDoc(b.name,b.doc))}function S(a){var c=a.getCursor("end"),b=a.getTokenAt(c);return b.start<c.ch&&"comment"==b.type?!1:/[\w)\]]/.test(a.getLine(c.line).slice(Math.max(c.ch-
1,0),c.ch+1))}function T(a,c){var b=c.getTokenAt(c.getCursor());if(!/\w/.test(b.string))return t(a,c,"Not at a variable");L(c,"New name for "+b.string,function(b){a.request(c,{type:"rename",newName:b,fullDocs:!0},function(b,d){if(b)return t(a,c,b);U(a,d.changes)})})}function V(a,c){var b=u(a,c.doc).name;a.request(c,{type:"refs"},function(d,e){if(d)return t(a,c,d);for(var f=[],g=0,h=c.getCursor(),m=0;m<e.refs.length;m++){var n=e.refs[m];n.file==b&&(f.push({anchor:n.start,head:n.end}),0<=z(h,n.start)&&
0>=z(h,n.end)&&(g=f.length-1))}c.setSelections(f,g)})}function U(a,c){for(var b=Object.create(null),d=0;d<c.length;++d){var e=c[d];(b[e.file]||(b[e.file]=[])).push(e)}for(var f in b){var g=a.docs[f],h=b[f];if(g){h.sort(function(a,b){return z(b.start,a.start)});for(var m="*rename"+ ++W,d=0;d<h.length;++d)e=h[d],g.doc.replaceRange(e.text,e.start,e.end,m)}}}function J(a,c,b,d){var e=[],f;(f=!b.fullDocs)||delete b.fullDocs;"string"==typeof b&&(b={type:b});b.lineCharPositions=!0;null==b.end&&(b.end=d||
c.doc.getCursor("end"),c.doc.somethingSelected()&&(b.start=c.doc.getCursor("start")));d=b.start||b.end;c.changed?c.doc.lineCount()>E&&!1!==f&&100>c.changed.to-c.changed.from&&c.changed.from<=d.line&&c.changed.to>b.end.line?(e.push(X(c,d,b.end)),b.file="#0",f=e[0].offsetLines,null!=b.start&&(b.start=r(b.start.line- -f,b.start.ch)),b.end=r(b.end.line-f,b.end.ch)):(e.push({type:"full",name:c.name,text:y(a,c)}),b.file=c.name,c.changed=null):b.file=c.name;for(var g in a.docs)f=a.docs[g],f.changed&&f!=
c&&(e.push({type:"full",name:f.name,text:y(a,f)}),f.changed=null);return{query:b,files:e}}function X(a,c,b){for(var d=a.doc,e=null,f=null,g=c.line-1,l=Math.max(0,g-50);g>=l;--g){var m=d.getLine(g);0>m.search(/\bfunction\b/)||(m=h.countColumn(m,null,4),null!=e&&e<=m||(e=m,f=g))}null==f&&(f=l);g=Math.min(d.lastLine(),b.line+20);if(null==e||e==h.countColumn(d.getLine(c.line),null,4))c=g;else for(c=b.line+1;c<g&&!(m=h.countColumn(d.getLine(c),null,4),m<=e);++c);e=r(f,0);return{type:"part",name:a.name,
offsetLines:e.line,text:d.getRange(e,r(c,0))}}function q(a,c){var b=document.createElement(a);c&&(b.className=c);for(var d=2;d<arguments.length;++d){var e=arguments[d];"string"==typeof e&&(e=document.createTextNode(e));b.appendChild(e)}return b}function L(a,c,b){a.openDialog?a.openDialog(c+": <input type=text>",b):b(prompt(c,""))}function H(a,c,b){function d(){a.state.ternTooltip=null;f.parentNode&&(a.off("cursorActivity",d),a.off("blur",d),a.off("scroll",d),Y(f))}a.state.ternTooltip&&x(a.state.ternTooltip);
var e=a.cursorCoords(),f=a.state.ternTooltip=B(e.right+1,e.bottom,c),g=!1,l=!1;h.on(f,"mousemove",function(){g=!0});h.on(f,"mouseout",function(a){h.contains(f,a.relatedTarget||a.toElement)||(l?d():g=!1)});setTimeout(function(){l=!0;g||d()},b.options.hintDelay?b.options.hintDelay:1700);a.on("cursorActivity",d);a.on("blur",d);a.on("scroll",d)}function B(a,c,b){b=q("div",l+"tooltip",b);b.style.left=a+"px";b.style.top=c+"px";document.body.appendChild(b);return b}function x(a){var c=a&&a.parentNode;c&&
c.removeChild(a)}function Y(a){a.style.opacity="0";setTimeout(function(){x(a)},1100)}function t(a,c,b){a.options.showError?a.options.showError(c,b):H(c,String(b),a)}function A(a){a.activeArgHints&&(x(a.activeArgHints),a.activeArgHints=null)}function y(a,c){var b=c.doc.getValue();a.options.fileFilter&&(b=a.options.fileFilter(b,c.name,c.doc));return b}function Z(a){function c(a,c){c&&(a.id=++d,e[d]=c);b.postMessage(a)}var b=a.worker=new Worker(a.options.workerScript);b.postMessage({type:"init",defs:a.options.defs,
plugins:a.options.plugins,scripts:a.options.workerDeps});var d=0,e={};b.onmessage=function(b){var d=b.data;"getFile"==d.type?C(a,d.name,function(a,b){c({type:"getFile",err:String(a),text:b,id:d.id})}):"debug"==d.type?window.console.log(d.message):d.id&&e[d.id]&&(e[d.id](d.err,d.body),delete e[d.id])};b.onerror=function(a){for(var b in e)e[b](a);e={}};this.addFile=function(a,b){c({type:"add",name:a,text:b})};this.delFile=function(a){c({type:"del",name:a})};this.request=function(a,b){c({type:"req",
body:a},b)}}h.TernServer=function(a){var c=this;this.options=a||{};a=this.options.plugins||(this.options.plugins={});a.doc_comment||(a.doc_comment=!0);this.docs=Object.create(null);this.server=this.options.useWorker?new Z(this):new tern.Server({getFile:function(a,d){return C(c,a,d)},async:!0,defs:this.options.defs||[],plugins:a});this.trackChange=function(a,d){M(c,a,d)};this.activeArgHints=this.cachedArgHints=null;this.jumpStack=[];this.getHint=function(a,d){return N(c,a,d)};this.getHint.async=!0};
h.TernServer.prototype={addDoc:function(a,c){var b={doc:c,name:a,changed:null};this.server.addFile(a,y(this,b));h.on(c,"change",this.trackChange);return this.docs[a]=b},delDoc:function(a){if(a=D(this,a))h.off(a.doc,"change",this.trackChange),delete this.docs[a.name],this.server.delFile(a.name)},hideDoc:function(a){A(this);(a=D(this,a))&&a.changed&&F(this,a)},complete:function(a){a.showHint({hint:this.getHint})},showType:function(a,c,b){G(this,a,c,"type",b)},showDocs:function(a,c,b){G(this,a,c,"documentation",
b)},updateArgHints:function(a){P(this,a)},jumpToDef:function(a){R(this,a)},jumpBack:function(a){var c=this.jumpStack.pop(),b=c&&this.docs[c.file];b&&K(this,u(this,a.getDoc()),b,c.start,c.end)},rename:function(a){T(this,a)},selectName:function(a){V(this,a)},request:function(a,c,b,d){var e=this,f=u(this,a.getDoc()),g=J(this,f,c,d);if(a=g.query&&this.options.queryOptions&&this.options.queryOptions[g.query.type])for(var h in a)g.query[h]=a[h];this.server.request(g,function(a,d){!a&&e.options.responseFilter&&
(d=e.options.responseFilter(f,c,g,a,d));b(a,d)})},destroy:function(){A(this);this.worker&&(this.worker.terminate(),this.worker=null)}};var r=h.Pos,l="CodeMirror-Tern-",E=250,W=0,z=h.cmpPos});
