/*
 Zepto v1.0 zeptojs.com | MIT licensed
 Modules: zepto, polyfill, event, data, stack
*/
var $jscomp={scope:{},findInternal:function(c,g,h){c instanceof String&&(c=String(c));for(var m=c.length,l=0;l<m;l++){var n=c[l];if(g.call(h,n,l,c))return{i:l,v:n}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(c,g,h){if(h.get||h.set)throw new TypeError("ES3 does not support getters and setters.");c!=Array.prototype&&c!=Object.prototype&&(c[g]=h.value)};
$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(c,g,h,m){if(g){h=$jscomp.global;c=c.split(".");for(m=0;m<c.length-1;m++){var l=c[m];l in h||(h[l]={});h=h[l]}c=c[c.length-1];m=h[c];g=g(m);g!=m&&null!=g&&$jscomp.defineProperty(h,c,{configurable:!0,writable:!0,value:g})}};
$jscomp.polyfill("Array.prototype.find",function(c){return c?c:function(c,h){return $jscomp.findInternal(this,c,h).v}},"es6-impl","es3");
var Zepto=function(){function c(a){return null==a?String(a):H[T.call(a)]||"object"}function g(a){return"function"==c(a)}function h(a){return null!=a&&a==a.window}function m(a){return null!=a&&a.nodeType==a.DOCUMENT_NODE}function l(a){return"object"==c(a)}function n(a){return l(a)&&!h(a)&&a.__proto__==Object.prototype}function u(a){return a instanceof Array}function p(a){return a.replace(/::/g,"/").replace(/([A-Z]+)([A-Z][a-z])/g,"$1_$2").replace(/([a-z\d])([A-Z])/g,"$1_$2").replace(/_/g,"-").toLowerCase()}
function t(a){return a in I?I[a]:I[a]=RegExp("(^|\\s)"+a+"(\\s|$)")}function D(a){return"children"in a?A.call(a.children):b.map(a.childNodes,function(a){if(1==a.nodeType)return a})}function y(a,d,k){for(f in d)k&&(n(d[f])||u(d[f]))?(n(d[f])&&!n(a[f])&&(a[f]={}),u(d[f])&&!u(a[f])&&(a[f]=[]),y(a[f],d[f],k)):d[f]!==e&&(a[f]=d[f])}function B(a,d){return d===e?b(a):b(a).filter(d)}function v(a,d,k,b){return g(d)?d.call(a,k,b):d}function z(a,d){var k=a.className,b=k&&k.baseVal!==e;if(d===e)return b?k.baseVal:
k;b?k.baseVal=d:a.className=d}function E(a){var d;try{return a?"true"==a||("false"==a?!1:"null"==a?null:isNaN(d=Number(a))?/^[\[\{]/.test(a)?b.parseJSON(a):a:d):a}catch(k){return a}}function F(a,d){d(a);for(var k in a.childNodes)F(a.childNodes[k],d)}var e,f,b,x,r=[],A=r.slice,C=r.filter,w=window.document,J={},I={},K=w.defaultView.getComputedStyle,N={"column-count":1,columns:1,"font-weight":1,"line-height":1,opacity:1,"z-index":1,zoom:1},O=/^\s*<(\w+|!)[^>]*>/,U=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,
P=/^(?:body|html)$/i,V="val css html text data width height offset".split(" "),L=w.createElement("table"),Q=w.createElement("tr"),R={tr:w.createElement("tbody"),tbody:L,thead:L,tfoot:L,td:Q,th:Q,"*":w.createElement("div")},W=/complete|loaded|interactive/,X=/^\.([\w-]+)$/,Y=/^#([\w-]*)$/,Z=/^[\w-]+$/,H={},T=H.toString,q={},M,G,S=w.createElement("div");q.matches=function(a,d){if(!a||1!==a.nodeType)return!1;var k=a.webkitMatchesSelector||a.mozMatchesSelector||a.oMatchesSelector||a.matchesSelector;if(k)return k.call(a,
d);var b;b=a.parentNode;(k=!b)&&(b=S).appendChild(a);b=~q.qsa(b,d).indexOf(a);k&&S.removeChild(a);return b};M=function(a){return a.replace(/-+(.)?/g,function(a,b){return b?b.toUpperCase():""})};G=function(a){return C.call(a,function(d,b){return a.indexOf(d)==b})};q.fragment=function(a,d,k){a.replace&&(a=a.replace(U,"<$1></$2>"));d===e&&(d=O.test(a)&&RegExp.$1);d in R||(d="*");var c,f=R[d];f.innerHTML=""+a;a=b.each(A.call(f.childNodes),function(){f.removeChild(this)});n(k)&&(c=b(a),b.each(k,function(a,
d){if(-1<V.indexOf(a))c[a](d);else c.attr(a,d)}));return a};q.Z=function(a,d){a=a||[];a.__proto__=b.fn;a.selector=d||"";return a};q.isZ=function(a){return a instanceof q.Z};q.init=function(a,d){if(a){if(g(a))return b(w).ready(a);if(q.isZ(a))return a;var k;if(u(a))k=C.call(a,function(a){return null!=a});else if(l(a))k=[n(a)?b.extend({},a):a],a=null;else if(O.test(a))k=q.fragment(a.trim(),RegExp.$1,d),a=null;else{if(d!==e)return b(d).find(a);k=q.qsa(w,a)}return q.Z(k,a)}return q.Z()};b=function(a,d){return q.init(a,
d)};b.extend=function(a){var d,b=A.call(arguments,1);"boolean"==typeof a&&(d=a,a=b.shift());b.forEach(function(b){y(a,b,d)});return a};q.qsa=function(a,d){var b;return m(a)&&Y.test(d)?(b=a.getElementById(RegExp.$1))?[b]:[]:1!==a.nodeType&&9!==a.nodeType?[]:A.call(X.test(d)?a.getElementsByClassName(RegExp.$1):Z.test(d)?a.getElementsByTagName(d):a.querySelectorAll(d))};b.contains=function(a,d){return a!==d&&a.contains(d)};b.type=c;b.isFunction=g;b.isWindow=h;b.isArray=u;b.isPlainObject=n;b.isEmptyObject=
function(a){for(var d in a)return!1;return!0};b.inArray=function(a,d,b){return r.indexOf.call(d,a,b)};b.camelCase=M;b.trim=function(a){return a.trim()};b.uuid=0;b.support={};b.expr={};b.map=function(a,d){var k,e=[],c;if("number"==typeof a.length)for(c=0;c<a.length;c++)k=d(a[c],c),null!=k&&e.push(k);else for(c in a)k=d(a[c],c),null!=k&&e.push(k);return 0<e.length?b.fn.concat.apply([],e):e};b.each=function(a,b){var d;if("number"==typeof a.length)for(d=0;d<a.length&&!1!==b.call(a[d],d,a[d]);d++);else for(d in a)if(!1===
b.call(a[d],d,a[d]))break;return a};b.grep=function(a,d){return C.call(a,d)};window.JSON&&(b.parseJSON=JSON.parse);b.each("Boolean Number String Function Array Date RegExp Object Error".split(" "),function(a,d){H["[object "+d+"]"]=d.toLowerCase()});b.fn={forEach:r.forEach,reduce:r.reduce,push:r.push,sort:r.sort,indexOf:r.indexOf,concat:r.concat,map:function(a){return b(b.map(this,function(d,b){return a.call(d,b,d)}))},slice:function(){return b(A.apply(this,arguments))},ready:function(a){W.test(w.readyState)?
a(b):w.addEventListener("DOMContentLoaded",function(){a(b)},!1);return this},get:function(a){return a===e?A.call(this):this[0<=a?a:a+this.length]},toArray:function(){return this.get()},size:function(){return this.length},remove:function(){return this.each(function(){null!=this.parentNode&&this.parentNode.removeChild(this)})},each:function(a){r.every.call(this,function(d,b){return!1!==a.call(d,b,d)});return this},filter:function(a){return g(a)?this.not(this.not(a)):b(C.call(this,function(d){return q.matches(d,
a)}))},add:function(a,d){return b(G(this.concat(b(a,d))))},is:function(a){return 0<this.length&&q.matches(this[0],a)},not:function(a){var d=[];if(g(a)&&a.call!==e)this.each(function(b){a.call(this,b)||d.push(this)});else{var k="string"==typeof a?this.filter(a):"number"==typeof a.length&&g(a.item)?A.call(a):b(a);this.forEach(function(a){0>k.indexOf(a)&&d.push(a)})}return b(d)},has:function(a){return this.filter(function(){return l(a)?b.contains(this,a):b(this).find(a).size()})},eq:function(a){return-1===
a?this.slice(a):this.slice(a,+a+1)},first:function(){var a=this[0];return a&&!l(a)?a:b(a)},last:function(){var a=this[this.length-1];return a&&!l(a)?a:b(a)},find:function(a){var d=this;return"object"==typeof a?b(a).filter(function(){var a=this;return r.some.call(d,function(d){return b.contains(d,a)})}):1==this.length?b(q.qsa(this[0],a)):this.map(function(){return q.qsa(this,a)})},closest:function(a,d){var k=this[0],e=!1;for("object"==typeof a&&(e=b(a));k&&!(e?0<=e.indexOf(k):q.matches(k,a));)k=k!==
d&&!m(k)&&k.parentNode;return b(k)},parents:function(a){for(var d=[],e=this;0<e.length;)e=b.map(e,function(a){if((a=a.parentNode)&&!m(a)&&0>d.indexOf(a))return d.push(a),a});return B(d,a)},parent:function(a){return B(G(this.pluck("parentNode")),a)},children:function(a){return B(this.map(function(){return D(this)}),a)},contents:function(){return this.map(function(){return A.call(this.childNodes)})},siblings:function(a){return B(this.map(function(a,b){return C.call(D(b.parentNode),function(a){return a!==
b})}),a)},empty:function(){return this.each(function(){this.innerHTML=""})},pluck:function(a){return b.map(this,function(b){return b[a]})},show:function(){return this.each(function(){"none"==this.style.display&&(this.style.display=null);if("none"==K(this,"").getPropertyValue("display")){var a=this.style,b=this.nodeName,e,c;J[b]||(e=w.createElement(b),w.body.appendChild(e),c=K(e,"").getPropertyValue("display"),e.parentNode.removeChild(e),"none"==c&&(c="block"),J[b]=c);a.display=J[b]}})},replaceWith:function(a){return this.before(a).remove()},
wrap:function(a){var d=g(a);if(this[0]&&!d)var e=b(a).get(0),c=e.parentNode||1<this.length;return this.each(function(f){b(this).wrapAll(d?a.call(this,f):c?e.cloneNode(!0):e)})},wrapAll:function(a){if(this[0]){b(this[0]).before(a=b(a));for(var d;(d=a.children()).length;)a=d.first();b(a).append(this)}return this},wrapInner:function(a){var d=g(a);return this.each(function(e){var c=b(this),f=c.contents();e=d?a.call(this,e):a;f.length?f.wrapAll(e):c.append(e)})},unwrap:function(){this.parent().each(function(){b(this).replaceWith(b(this).children())});
return this},clone:function(){return this.map(function(){return this.cloneNode(!0)})},hide:function(){return this.css("display","none")},toggle:function(a){return this.each(function(){var d=b(this);(a===e?"none"==d.css("display"):a)?d.show():d.hide()})},prev:function(a){return b(this.pluck("previousElementSibling")).filter(a||"*")},next:function(a){return b(this.pluck("nextElementSibling")).filter(a||"*")},html:function(a){return a===e?0<this.length?this[0].innerHTML:null:this.each(function(d){var e=
this.innerHTML;b(this).empty().append(v(this,a,d,e))})},text:function(a){return a===e?0<this.length?this[0].textContent:null:this.each(function(){this.textContent=a})},attr:function(a,b){var d;return"string"==typeof a&&b===e?0==this.length||1!==this[0].nodeType?e:"value"==a&&"INPUT"==this[0].nodeName?this.val():!(d=this[0].getAttribute(a))&&a in this[0]?this[0][a]:d:this.each(function(d){if(1===this.nodeType)if(l(a))for(f in a){d=f;var e=a[f];null==e?this.removeAttribute(d):this.setAttribute(d,e)}else d=
v(this,b,d,this.getAttribute(a)),null==d?this.removeAttribute(a):this.setAttribute(a,d)})},removeAttr:function(a){return this.each(function(){1===this.nodeType&&this.removeAttribute(a)})},prop:function(a,b){return b===e?this[0]&&this[0][a]:this.each(function(d){this[a]=v(this,b,d,this[a])})},data:function(a,b){var d=this.attr("data-"+p(a),b);return null!==d?E(d):e},val:function(a){return a===e?this[0]&&(this[0].multiple?b(this[0]).find("option").filter(function(){return this.selected}).pluck("value"):
this[0].value):this.each(function(b){this.value=v(this,a,b,this.value)})},offset:function(a){if(a)return this.each(function(d){var e=b(this);d=v(this,a,d,e.offset());var c=e.offsetParent().offset();d={top:d.top-c.top,left:d.left-c.left};"static"==e.css("position")&&(d.position="relative");e.css(d)});if(0==this.length)return null;var d=this[0].getBoundingClientRect();return{left:d.left+window.pageXOffset,top:d.top+window.pageYOffset,width:Math.round(d.width),height:Math.round(d.height)}},css:function(a,
b){if(2>arguments.length&&"string"==typeof a)return this[0]&&(this[0].style[M(a)]||K(this[0],"").getPropertyValue(a));var d="";if("string"==c(a))b||0===b?d=p(a)+":"+("number"!=typeof b||N[p(a)]?b:b+"px"):this.each(function(){this.style.removeProperty(p(a))});else for(f in a)a[f]||0===a[f]?d+=p(f)+":"+("number"!=typeof a[f]||N[p(f)]?a[f]:a[f]+"px")+";":this.each(function(){this.style.removeProperty(p(f))});return this.each(function(){this.style.cssText+=";"+d})},index:function(a){return a?this.indexOf(b(a)[0]):
this.parent().children().indexOf(this[0])},hasClass:function(a){return r.some.call(this,function(a){return this.test(z(a))},t(a))},addClass:function(a){return this.each(function(d){x=[];var e=z(this);v(this,a,d,e).split(/\s+/g).forEach(function(a){b(this).hasClass(a)||x.push(a)},this);x.length&&z(this,e+(e?" ":"")+x.join(" "))})},removeClass:function(a){return this.each(function(b){if(a===e)return z(this,"");x=z(this);v(this,a,b,x).split(/\s+/g).forEach(function(a){x=x.replace(t(a)," ")});z(this,
x.trim())})},toggleClass:function(a,d){return this.each(function(c){var f=b(this);v(this,a,c,z(this)).split(/\s+/g).forEach(function(a){(d===e?!f.hasClass(a):d)?f.addClass(a):f.removeClass(a)})})},scrollTop:function(){if(this.length)return"scrollTop"in this[0]?this[0].scrollTop:this[0].scrollY},position:function(){if(this.length){var a=this[0],d=this.offsetParent(),e=this.offset(),c=P.test(d[0].nodeName)?{top:0,left:0}:d.offset();e.top-=parseFloat(b(a).css("margin-top"))||0;e.left-=parseFloat(b(a).css("margin-left"))||
0;c.top+=parseFloat(b(d[0]).css("border-top-width"))||0;c.left+=parseFloat(b(d[0]).css("border-left-width"))||0;return{top:e.top-c.top,left:e.left-c.left}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||w.body;a&&!P.test(a.nodeName)&&"static"==b(a).css("position");)a=a.offsetParent;return a})}};b.fn.detach=b.fn.remove;["width","height"].forEach(function(a){b.fn[a]=function(d){var c,f=this[0],r=a.replace(/./,function(a){return a[0].toUpperCase()});return d===e?h(f)?
f["inner"+r]:m(f)?f.documentElement["offset"+r]:(c=this.offset())&&c[a]:this.each(function(e){f=b(this);f.css(a,v(this,d,e,f[a]()))})}});["after","prepend","before","append"].forEach(function(a,d){var e=d%2;b.fn[a]=function(){var a,f=b.map(arguments,function(b){a=c(b);return"object"==a||"array"==a||null==b?b:q.fragment(b)}),k,r=1<this.length;return 1>f.length?this:this.each(function(a,c){k=e?c:c.parentNode;c=0==d?c.nextSibling:1==d?c.firstChild:2==d?c:null;f.forEach(function(a){if(r)a=a.cloneNode(!0);
else if(!k)return b(a).remove();F(k.insertBefore(a,c),function(a){null==a.nodeName||"SCRIPT"!==a.nodeName.toUpperCase()||a.type&&"text/javascript"!==a.type||a.src||window.eval.call(window,a.innerHTML)})})})};b.fn[e?a+"To":"insert"+(d?"Before":"After")]=function(d){b(d)[a](this);return this}});q.Z.prototype=b.fn;q.uniq=G;q.deserializeValue=E;b.zepto=q;return b}();window.Zepto=Zepto;"$"in window||(window.$=Zepto);
(function(c){String.prototype.trim===c&&(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});Array.prototype.reduce===c&&(Array.prototype.reduce=function(g){if(void 0===this||null===this)throw new TypeError;var h=Object(this),m=h.length>>>0,l=0,n;if("function"!=typeof g)throw new TypeError;if(0==m&&1==arguments.length)throw new TypeError;if(2<=arguments.length)n=arguments[1];else{do{if(l in h){n=h[l++];break}if(++l>=m)throw new TypeError;}while(1)}for(;l<m;)l in h&&(n=g.call(c,
n,h[l],l,h)),l++;return n})})();
(function(c){function g(e){return e._zid||(e._zid=D++)}function h(e,c,b,h){c=m(c);if(c.ns)var f=RegExp("(?:^| )"+c.ns.replace(" "," .* ?")+"(?: |$)");return(t[g(e)]||[]).filter(function(e){return e&&(!c.e||e.e==c.e)&&(!c.ns||f.test(e.ns))&&(!b||g(e.fn)===g(b))&&(!h||e.sel==h)})}function m(e){e=(""+e).split(".");return{e:e[0],ns:e.slice(1).sort().join(" ")}}function l(e,f,b){"string"!=c.type(e)?c.each(e,b):e.split(/\s/).forEach(function(e){b(e,f)})}function n(e,f,b,h,r,p){var x=g(e),n=t[x]||(t[x]=
[]);l(f,b,function(b,f){var g=m(b);g.fn=f;g.sel=h;g.e in B&&(f=function(b){var e=b.relatedTarget;if(!e||e!==this&&!c.contains(this,e))return g.fn.apply(this,arguments)});g.del=r&&r(f,b);var l=g.del||f;g.proxy=function(b){var c=l.apply(e,[b].concat(b.data));!1===c&&(b.preventDefault(),b.stopPropagation());return c};g.i=n.length;n.push(g);e.addEventListener(B[g.e]||g.e,g.proxy,g.del&&("focus"==g.e||"blur"==g.e)||!!p)})}function u(e,c,b,p,r){var f=g(e);l(c||"",b,function(b,c){h(e,b,c,p).forEach(function(b){delete t[f][b.i];
e.removeEventListener(B[b.e]||b.e,b.proxy,b.del&&("focus"==b.e||"blur"==b.e)||!!r)})})}function p(e){var f,b={originalEvent:e};for(f in e)!E.test(f)&&void 0!==e[f]&&(b[f]=e[f]);c.each(F,function(c,f){b[c]=function(){this[f]=v;return e[c].apply(e,arguments)};b[f]=z});return b}var t={},D=1,y={},B={mouseenter:"mouseover",mouseleave:"mouseout"};y.click=y.mousedown=y.mouseup=y.mousemove="MouseEvents";c.event={add:n,remove:u};c.proxy=function(e,f){if(c.isFunction(e)){var b=function(){return e.apply(f,arguments)};
b._zid=g(e);return b}if("string"==typeof f)return c.proxy(e[f],e);throw new TypeError("expected function");};c.fn.bind=function(e,c){return this.each(function(){n(this,e,c)})};c.fn.unbind=function(e,c){return this.each(function(){u(this,e,c)})};c.fn.one=function(e,c){return this.each(function(b,f){n(this,e,c,null,function(b,e){return function(){var c=b.apply(f,arguments);u(f,e,b);return c}})})};var v=function(){return!0},z=function(){return!1},E=/^([A-Z]|layer[XY]$)/,F={preventDefault:"isDefaultPrevented",
stopImmediatePropagation:"isImmediatePropagationStopped",stopPropagation:"isPropagationStopped"};c.fn.delegate=function(e,f,b){return this.each(function(g,h){n(h,f,b,e,function(b){return function(f){var g,l=c(f.target).closest(e,h).get(0);if(l)return g=c.extend(p(f),{currentTarget:l,liveFired:h}),b.apply(l,[g].concat([].slice.call(arguments,1)))}})})};c.fn.undelegate=function(e,c,b){return this.each(function(){u(this,c,b,e)})};c.fn.live=function(e,f){c(document.body).delegate(this.selector,e,f);return this};
c.fn.die=function(e,f){c(document.body).undelegate(this.selector,e,f);return this};c.fn.on=function(e,f,b){return!f||c.isFunction(f)?this.bind(e,f||b):this.delegate(f,e,b)};c.fn.off=function(e,f,b){return!f||c.isFunction(f)?this.unbind(e,f||b):this.undelegate(f,e,b)};c.fn.trigger=function(e,f){if("string"==typeof e||c.isPlainObject(e))e=c.Event(e);var b=e;if(!("defaultPrevented"in b)){b.defaultPrevented=!1;var g=b.preventDefault;b.preventDefault=function(){this.defaultPrevented=!0;g.call(this)}}e.data=
f;return this.each(function(){"dispatchEvent"in this&&this.dispatchEvent(e)})};c.fn.triggerHandler=function(e,f){var b,g;this.each(function(l,m){b=p("string"==typeof e?c.Event(e):e);b.data=f;b.target=m;c.each(h(m,e.type||e),function(e,c){g=c.proxy(b);if(b.isImmediatePropagationStopped())return!1})});return g};"focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select keydown keypress keyup error".split(" ").forEach(function(e){c.fn[e]=
function(c){return c?this.bind(e,c):this.trigger(e)}});["focus","blur"].forEach(function(e){c.fn[e]=function(c){c?this.bind(e,c):this.each(function(){try{this[e]()}catch(b){}});return this}});c.Event=function(c,f){"string"!=typeof c&&(f=c,c=f.type);var b=document.createEvent(y[c]||"Events"),e=!0;if(f)for(var g in f)"bubbles"==g?e=!!f[g]:b[g]=f[g];b.initEvent(c,e,!0,null,null,null,null,null,null,null,null,null,null,null,null);b.isDefaultPrevented=function(){return this.defaultPrevented};return b}})(Zepto);
(function(c){function g(g,t){var p=g[u],p=p&&m[p];if(void 0===t)return p||h(g);if(p){if(t in p)return p[t];var y=n(t);if(y in p)return p[y]}return l.call(c(g),t)}function h(g,h,l){var p=g[u]||(g[u]=++c.uuid),t;if(!(t=m[p])){t=m;var v={};c.each(g.attributes,function(g,h){0==h.name.indexOf("data-")&&(v[n(h.name.replace("data-",""))]=c.zepto.deserializeValue(h.value))});t=t[p]=v}g=t;void 0!==h&&(g[n(h)]=l);return g}var m={},l=c.fn.data,n=c.camelCase,u=c.expando="Zepto"+ +new Date;c.fn.data=function(l,
m){return void 0===m?c.isPlainObject(l)?this.each(function(g,m){c.each(l,function(c,g){h(m,c,g)})}):0==this.length?void 0:g(this[0],l):this.each(function(){h(this,l,m)})};c.fn.removeData=function(g){"string"==typeof g&&(g=g.split(/\s+/));return this.each(function(){var h=this[u],l=h&&m[h];l&&c.each(g,function(){delete l[n(this)]})})}})(Zepto);
(function(c){c.fn.end=function(){return this.prevObject||c()};c.fn.andSelf=function(){return this.add(this.prevObject||c())};"filter add not eq first last find closest parents parent children siblings".split(" ").forEach(function(g){var h=c.fn[g];c.fn[g]=function(){var c=h.apply(this,arguments);c.prevObject=this;return c}})})(Zepto);
