/*
 iCheck v1.0.2, http://git.io/arlzeA
 ===================================
 Powerful jQuery and Zepto plugin for checkboxes and radio buttons customization

 (c) 2013 Damir Sultanov, http://fronteed.com
 MIT Licensed
*/
var $jscomp={scope:{},findInternal:function(a,g,c){a instanceof String&&(a=String(a));for(var l=a.length,m=0;m<l;m++){var h=a[m];if(g.call(c,h,m,a))return{i:m,v:h}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,g,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[g]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,g,c,l){if(g){c=$jscomp.global;a=a.split(".");for(l=0;l<a.length-1;l++){var m=a[l];m in c||(c[m]={});c=c[m]}a=a[a.length-1];l=c[a];g=g(l);g!=l&&null!=g&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:g})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6-impl","es3");
(function(a){function g(b,a,k){var e=b[0],d=/er/.test(k)?"indeterminate":/bl/.test(k)?"disabled":"checked",f="update"==k?{checked:e.checked,disabled:e.disabled,indeterminate:"true"==b.attr("indeterminate")||"false"==b.attr("determinate")}:e[d];if(/^(ch|di|in)/.test(k)&&!f)c(b,d);else if(/^(un|en|de)/.test(k)&&f)l(b,d);else if("update"==k)for(var g in f)f[g]?c(b,g,!0):l(b,g,!0);else a&&"toggle"!=k||(a||b.trigger("ifClicked"),f?"radio"!==e.type&&l(b,d):c(b,d))}function c(b,d,k){var e=b[0],c=b.parent(),
f="checked"==d,g="indeterminate"==d,m="disabled"==d,x=g?"determinate":f?"unchecked":"enabled",y=h(b,x+p(e.type)),r=h(b,d+p(e.type));if(!0!==e[d]){if(!k&&"checked"==d&&"radio"==e.type&&e.name){var t=b.closest("form"),q='input[name="'+e.name+'"]',q=t.length?t.find(q):a(q);q.each(function(){this!==e&&a(this).data("iCheck")&&l(a(this),d)})}g?(e[d]=!0,e.checked&&l(b,"checked","force")):(k||(e[d]=!0),f&&e.indeterminate&&l(b,"indeterminate",!1));u(b,f,d,k)}e.disabled&&h(b,"cursor",!0)&&c.find(".iCheck-helper").css("cursor",
"default");c.addClass(r||h(b,d)||"");c.attr("role")&&!g&&c.attr("aria-"+(m?"disabled":"checked"),"true");c.removeClass(y||h(b,x)||"")}function l(b,a,c){var e=b[0],d=b.parent(),f="checked"==a,g="indeterminate"==a,k="disabled"==a,l=g?"determinate":f?"unchecked":"enabled",m=h(b,l+p(e.type)),r=h(b,a+p(e.type));if(!1!==e[a]){if(g||!c||"force"==c)e[a]=!1;u(b,f,l,c)}!e.disabled&&h(b,"cursor",!0)&&d.find(".iCheck-helper").css("cursor","pointer");d.removeClass(r||h(b,a)||"");d.attr("role")&&!g&&d.attr("aria-"+
(k?"disabled":"checked"),"false");d.addClass(m||h(b,l)||"")}function m(b,d){b.data("iCheck")&&(b.parent().html(b.attr("style",b.data("iCheck").s||"")),d&&b.trigger(d),b.off(".i").unwrap(),a('label[for="'+b[0].id+'"]').add(b.closest("label")).off(".i"))}function h(b,a,c){if(b.data("iCheck"))return b.data("iCheck").o[a+(c?"":"Class")]}function p(a){return a.charAt(0).toUpperCase()+a.slice(1)}function u(a,c,g,e){e||(c&&a.trigger("ifToggled"),a.trigger("ifChanged").trigger("if"+p(g)))}var z=/ipad|iphone|ipod|android|blackberry|windows phone|opera mini|silk/i.test(navigator.userAgent);
a.fn.iCheck=function(b,d){var k='input[type="checkbox"], input[type="radio"]',e=a(),h=function(b){b.each(function(){var b=a(this);e=b.is(k)?e.add(b):e.add(b.find(k))})};if(/^(check|uncheck|toggle|indeterminate|determinate|disable|enable|update|destroy)$/i.test(b))return b=b.toLowerCase(),h(this),e.each(function(){var c=a(this);"destroy"==b?m(c,"ifDestroyed"):g(c,!0,b);a.isFunction(d)&&d()});if("object"!=typeof b&&b)return this;var f=a.extend({checkedClass:"checked",disabledClass:"disabled",indeterminateClass:"indeterminate",
labelHover:!0},b),p=f.handle,w=f.hoverClass||"hover",x=f.focusClass||"focus",y=f.activeClass||"active",r=!!f.labelHover,t=f.labelHoverClass||"hover",q=(""+f.increaseArea).replace("%","")|0;if("checkbox"==p||"radio"==p)k='input[type="'+p+'"]';-50>q&&(q=-50);h(this);return e.each(function(){var b=a(this);m(b);var e=this,d=e.id,k=-q+"%",h=100+2*q+"%",h={position:"absolute",top:k,left:k,display:"block",width:h,height:h,margin:0,padding:0,background:"#fff",border:0,opacity:0},k=z?{position:"absolute",
visibility:"hidden"}:q?h:{position:"absolute",opacity:0},p="checkbox"==e.type?f.checkboxClass||"icheckbox":f.radioClass||"iradio",v=a('label[for="'+d+'"]').add(b.closest("label")),u=!!f.aria,A="iCheck-"+Math.random().toString(36).substr(2,6),n='<div class="'+p+'" '+(u?'role="'+e.type+'" ':"");u&&v.each(function(){n+='aria-labelledby="';this.id?n+=this.id:(this.id=A,n+=A);n+='"'});n=b.wrap(n+"/>").trigger("ifCreated").parent().append(f.insert);h=a('<ins class="iCheck-helper"/>').css(h).appendTo(n);
b.data("iCheck",{o:f,s:b.attr("style")}).css(k);f.inheritClass&&n.addClass(e.className||"");f.inheritID&&d&&n.attr("id","iCheck-"+d);"static"==n.css("position")&&n.css("position","relative");g(b,!0,"update");if(v.length)v.on("click.i mouseover.i mouseout.i touchbegin.i touchend.i",function(c){var d=c.type,f=a(this);if(!e.disabled){if("click"==d){if(a(c.target).is("a"))return;g(b,!1,!0)}else r&&(/ut|nd/.test(d)?(n.removeClass(w),f.removeClass(t)):(n.addClass(w),f.addClass(t)));if(z)c.stopPropagation();
else return!1}});b.on("click.i focus.i blur.i keyup.i keydown.i keypress.i",function(a){var d=a.type;a=a.keyCode;if("click"==d)return!1;if("keydown"==d&&32==a)return"radio"==e.type&&e.checked||(e.checked?l(b,"checked"):c(b,"checked")),!1;if("keyup"==d&&"radio"==e.type)!e.checked&&c(b,"checked");else if(/us|ur/.test(d))n["blur"==d?"removeClass":"addClass"](x)});h.on("click mousedown mouseup mouseover mouseout touchbegin.i touchend.i",function(a){var c=a.type,d=/wn|up/.test(c)?y:w;if(!e.disabled){if("click"==
c)g(b,!1,!0);else if(/wn|er|in/.test(c)?n.addClass(d):n.removeClass(d+" "+y),v.length&&r&&d==w)v[/ut|nd/.test(c)?"removeClass":"addClass"](t);if(z)a.stopPropagation();else return!1}})})}})(window.jQuery||window.Zepto);
