/*
 FullCalendar v2.2.5
 Docs & License: http://arshaw.com/fullcalendar/
 (c) 2013 Adam Shaw
*/
var $jscomp={scope:{},findInternal:function(g,n,t){g instanceof String&&(g=String(g));for(var D=g.length,A=0;A<D;A++){var U=g[A];if(n.call(t,U,A,g))return{i:A,v:U}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(g,n,t){if(t.get||t.set)throw new TypeError("ES3 does not support getters and setters.");g!=Array.prototype&&g!=Object.prototype&&(g[n]=t.value)};
$jscomp.getGlobal=function(g){return"undefined"!=typeof window&&window===g?g:"undefined"!=typeof global&&null!=global?global:g};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(g,n,t,D){if(n){t=$jscomp.global;g=g.split(".");for(D=0;D<g.length-1;D++){var A=g[D];A in t||(t[A]={});t=t[A]}g=g[g.length-1];D=t[g];n=n(D);n!=D&&null!=n&&$jscomp.defineProperty(t,g,{configurable:!0,writable:!0,value:n})}};
$jscomp.polyfill("Array.prototype.find",function(g){return g?g:function(g,t){return $jscomp.findInternal(this,g,t).v}},"es6-impl","es3");
(function(g){"function"===typeof define&&define.amd?define(["jquery","moment"],g):g(jQuery,moment)})(function(g,n){function t(a){function b(b,c){g.isPlainObject(c)&&g.isPlainObject(a[b])&&!/(Time|Duration)$/.test(b)?a[b]=t({},a[b],c):void 0!==c&&(a[b]=c)}for(var c=1;c<arguments.length;c++)g.each(arguments[c],b);return a}function D(a){var b=n.localeData||n.langData;return b.call(n,a)||b.call(n,"en")}function A(a,b){b.left&&a.css({"border-left-width":1,"margin-left":b.left-1});b.right&&a.css({"border-right-width":1,
"margin-right":b.right-1})}function U(a){a.css({"margin-left":"","margin-right":"","border-left-width":"","border-right-width":""})}function X(){g("body").addClass("fc-not-allowed")}function K(){g("body").removeClass("fc-not-allowed")}function pa(a,b,c){var d=Math.floor(b/a.length),e=Math.floor(b-d*(a.length-1)),f=[],h=[],k=[],q=0;a.height("");a.each(function(b,c){var l=b===a.length-1?e:d,z=g(c).outerHeight(!0);z<l?(f.push(c),h.push(z),k.push(g(c).height())):q+=z});c&&(b-=q,d=Math.floor(b/f.length),
e=Math.floor(b-d*(f.length-1)));g(f).each(function(a,b){var c=a===f.length-1?e:d,l=h[a],m=c-(l-k[a]);l<c&&g(b).height(m)})}function qa(a){var b=0;a.find("> *").each(function(a,d){var c=g(d).outerWidth();c>b&&(b=c)});b++;a.width(b);return b}function ra(a,b){a.height(b).addClass("fc-scroller");if(a[0].scrollHeight-1>a[0].clientHeight)return!0;ea(a);return!1}function ea(a){a.height("").removeClass("fc-scroller")}function sa(a){var b=a.css("position"),c=a.parents().filter(function(){var a=g(this);return/(auto|scroll)/.test(a.css("overflow")+
a.css("overflow-y")+a.css("overflow-x"))}).eq(0);return"fixed"!==b&&c.length?c:g(a[0].ownerDocument||document)}function ta(a){var b=a.offset().left,c=b+a.width(),d=a.children();a=d.offset().left;d=a+d.outerWidth();return{left:a-b,right:c-d}}function fa(a,b){var c=a.start,d=a.end,e=b.start,f=b.end;if(d>e&&c<f)return c>=e?(c=c.clone(),e=!0):(c=e.clone(),e=!1),d<=f?(d=d.clone(),f=!0):(d=f.clone(),f=!1),{start:c,end:d,isStart:e,isEnd:f}}function V(a,b){a=a||{};if(void 0!==a[b])return a[b];for(var c=b.split(/(?=[A-Z])/),
d=c.length-1,e;0<=d;d--)if(e=a[c[d].toLowerCase()],void 0!==e)return e;return a["default"]}function W(a,b){return n.duration({days:a.clone().stripTime().diff(b.clone().stripTime(),"days"),ms:a.time()-b.time()})}function Ta(a,b){return n.duration({days:a.clone().stripTime().diff(b.clone().stripTime(),"days")})}function ua(a,b){var c,d;for(c=0;c<va.length&&(d=va[c],!ga(d,a,b));c++);return d}function ga(a,b,c){a=null!=c?c.diff(b,a,!0):n.isDuration(b)?b.as(a):b.end.diff(b.start,a,!0);return 1<=a&&0===
a%1?a:!1}function wa(a){return/^\d+\:\d+(?:\:\d+\.?(?:\d{3})?)?$/.test(a)}function Y(a){var b=function(){};b.prototype=a;return new b}function ha(a,b){for(var c in a)xa.call(a,c)&&(b[c]=a[c])}function Z(a,b,c){g.isFunction(a)&&(a=[a]);if(a){var d,e;for(d=0;d<a.length;d++)e=a[d].apply(b,c)||e;return e}}function N(){for(var a=0;a<arguments.length;a++)if(void 0!==arguments[a])return arguments[a]}function B(a){return(a+"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/'/g,"&#039;").replace(/"/g,
"&quot;").replace(/\n/g,"<br />")}function ya(a){return a.charAt(0).toUpperCase()+a.slice(1)}function Ua(a,b){return a-b}function ia(a,b){var c,d,e,f,h=function(){var g=+new Date-f;g<b&&0<g?c=setTimeout(h,b-g):(c=null,a.apply(e,d),c||(e=d=null))};return function(){e=this;d=arguments;f=+new Date;c||(c=setTimeout(h,b))}}function ja(a,b,c){var d=a[0],e=1==a.length&&"string"===typeof d,f,h,k;if(n.isMoment(d))a=n.apply(null,a),za(d,a);else if(f=d,"[object Date]"===Object.prototype.toString.call(f)||f instanceof
Date||void 0===d)a=n.apply(null,a);else{h=f=!1;if(e)if(Va.test(d))d+="-01",a=[d],h=f=!0;else{if(k=Wa.exec(d))f=!k[5],h=!0}else g.isArray(d)&&(h=!0);a=b||f?n.utc.apply(n,a):n.apply(null,a);f?(a._ambigTime=!0,a._ambigZone=!0):c&&(h?a._ambigZone=!0:e&&a.zone(d))}a._fullCalendar=!0;return a}function ka(a,b){var c=!1,d=!1,e=a.length,f=[],h,g;for(h=0;h<e;h++)g=a[h],n.isMoment(g)||(g=p.moment.parseZone(g)),c=c||g._ambigTime,d=d||g._ambigZone,f.push(g);for(h=0;h<e;h++)g=f[h],b||!c||g._ambigTime?d&&!g._ambigZone&&
(f[h]=g.clone().stripZone()):f[h]=g.clone().stripTime();return f}function za(a,b){a._ambigTime?b._ambigTime=!0:b._ambigTime&&(b._ambigTime=!1);a._ambigZone?b._ambigZone=!0:b._ambigZone&&(b._ambigZone=!1)}function Aa(a,b){a.year(b[0]||0).month(b[1]||0).date(b[2]||0).hours(b[3]||0).minutes(b[4]||0).seconds(b[5]||0).milliseconds(b[6]||0)}function M(a,b){return C.format.call(a,b)}function Ba(a,b){var c="",d;for(d=0;d<b.length;d++)c+=la(a,b[d]);return c}function la(a,b){var c;return"string"===typeof b?
b:(c=b.token)?Ca[c]?Ca[c](a):M(a,c):b.maybe&&(c=Ba(a,b.maybe),c.match(/[1-9]/))?c:""}function Da(a,b,c,d,e){a=p.moment.parseZone(a);b=p.moment.parseZone(b);c=(a.localeData||a.lang).call(a).longDateFormat(c)||c;d=d||" - ";c=Ea(c);var f,g,k="",q,l="",z="",n="",I="";for(g=0;g<c.length;g++){f=Fa(a,b,c[g]);if(!1===f)break;k+=f}for(q=c.length-1;q>g;q--){f=Fa(a,b,c[q]);if(!1===f)break;l=f+l}for(f=g;f<=q;f++)z+=la(a,c[f]),n+=la(b,c[f]);if(z||n)I=e?n+d+z:z+d+n;return k+I+l}function Fa(a,b,c){var d;return"string"===
typeof c?c:(c=c.token)&&(d=Xa[c.charAt(0)])&&a.isSame(b,d)?M(a,c):!1}function Ea(a){return a in ma?ma[a]:ma[a]=Ga(a)}function Ga(a){for(var b=[],c=/\[([^\]]*)\]|\(([^\)]*)\)|(LT|(\w)\4*o?)|([^\w\[\(]+)/g,d;d=c.exec(a);)d[1]?b.push(d[1]):d[2]?b.push({maybe:Ga(d[2])}):d[3]?b.push({token:d[3]}):d[5]&&b.push(d[5]);return b}function E(){}function Ha(a,b){return a||b?a&&b?a.grid===b.grid&&a.row===b.row&&a.col===b.col:!1:!0}function Ia(a){return N((a.source||{}).rendering,a.rendering)}function Ya(a){var b=
{},c,d;for(c=0;c<a.length;c++)d=a[c],(b[d._id]||(b[d._id]=[])).push(d);return b}function Za(a,b){return a.eventStartMS-b.eventStartMS}function aa(a,b){return a.eventStartMS-b.eventStartMS||b.eventDurationMS-a.eventDurationMS||b.event.allDay-a.event.allDay||(a.event.title||"").localeCompare(b.event.title)}function $a(a){var b=p.dataAttrPrefix,c,d,e,f;b&&(b+="-");if(c=a.data(b+"event")||null)c="object"===typeof c?g.extend({},c):{},d=c.start,null==d&&(d=c.time),e=c.duration,f=c.stick,delete c.start,
delete c.time,delete c.duration,delete c.stick;null==d&&(d=a.data(b+"start"));null==d&&(d=a.data(b+"time"));null==e&&(e=a.data(b+"duration"));null==f&&(f=a.data(b+"stick"));d=null!=d?n.duration(d):null;e=null!=e?n.duration(e):null;return{eventProps:c,startTime:d,duration:e,stick:!!f}}function ab(a,b){return a.leftCol-b.leftCol}function Ja(a){var b=a.forwardSegs,c=0,d,e;if(void 0===a.forwardPressure){for(d=0;d<b.length;d++)e=b[d],Ja(e),c=Math.max(c,1+e.forwardPressure);a.forwardPressure=c}}function na(a,
b,c){var d=a.forwardSegs;if(void 0===a.forwardCoord)for(d.length?(d.sort(bb),na(d[0],b+1,c),a.forwardCoord=d[0].backwardCoord):a.forwardCoord=1,a.backwardCoord=a.forwardCoord-(a.forwardCoord-c)/(b+1),b=0;b<d.length;b++)na(d[b],0,a.forwardCoord)}function Ka(a,b,c){c=c||[];for(var d=0;d<b.length;d++){var e=b[d];a.bottom>e.top&&a.top<e.bottom&&c.push(b[d])}return c}function bb(a,b){return b.forwardPressure-a.forwardPressure||(a.backwardCoord||0)-(b.backwardCoord||0)||aa(a,b)}function cb(a,b){function c(){return a.is(":visible")}
function d(a){e(0,a)}function e(a,b){L++;v&&b&&v.type!==b&&(u.deactivateButton(v.type),x(),v.start&&v.destroyView(),v.el.remove(),v=null);if(!v&&b){var d=f(b);v=new d["class"](m,d.options,b);v.el=g("<div class='fc-view fc-"+b+"-view' />").appendTo(O);u.activateButton(b)}v&&(0>a?G=v.computePrevDate(G):0<a&&(G=v.computeNextDate(G)),v.start&&!a&&G.isWithin(v.intervalStart,v.intervalEnd)||!c()||(x(),v.start&&v.destroyView(),v.setDate(G),v.renderView(),I(),u.updateTitle(v.computeTitle()),m.getNow().isWithin(v.intervalStart,
v.intervalEnd)?u.disableButton("today"):u.enableButton("today"),!r.lazyFetching||B(v.start,v.end)?La(v.start,v.end):z()));I();L--}function f(a){function b(a){"function"===typeof a?l=a:"object"===typeof a&&g.extend(k,a)}var c=r.defaultButtonText||{},d=r.buttonText||{},e=r.views||{},f=a,h=[],k,l,m,q=!1;if(A[a])return A[a];for(;f&&!l;)k={},b(P[f]),b(e[f]),h.unshift(k),f=k.type;h.unshift({});k=g.extend.apply(g,h);if(l){if(f=k.duration||l.duration)f=n.duration(f),m=ua(f),q=1===ga(m,f);q&&e[m]&&(k=g.extend({},
e[m],k));c=d[a]||(q?d[m]:null)||c[a]||(q?c[m]:null)||k.buttonText||l.buttonText||(f?(f.locale||f.lang).call(f,r.lang).humanize():null)||a;return A[a]={"class":l,options:k,buttonText:c}}}function h(a){return!!f(a)}function k(a){if(c())return a&&q(),L++,v.updateSize(!0),L--,!0}function q(){J="number"===typeof r.contentHeight?r.contentHeight:"number"===typeof r.height?r.height-(y?y.outerHeight(!0):0):Math.round(O.width()/Math.max(r.aspectRatio,.5))}function l(a){!L&&a.target===window&&v.start&&k(!0)&&
v.trigger("windowResize",Ma)}function z(){c()&&(x(),v.destroyViewEvents(),v.renderViewEvents(H),I())}function x(){O.css({width:"100%",height:O.height(),overflow:"hidden"})}function I(){O.css({width:"",height:"",overflow:""})}var m=this;b=b||{};var r=t({},R,b),T;(T=r.lang in S?S[r.lang]:S[R.lang])&&(r=t({},R,T,b));r.isRTL&&(r=t({},R,fb,T||{},b));m.options=r;m.render=function(b){O?c()&&(c()&&q(),e(b)):(a.addClass("fc"),r.isRTL?a.addClass("fc-rtl"):a.addClass("fc-ltr"),r.theme?a.addClass("ui-widget"):
a.addClass("fc-unthemed"),O=g("<div class='fc-view-container'/>").prependTo(a),u=new gb(m,r),(y=u.render())&&a.prepend(y),d(r.defaultView),r.handleWindowResize&&(C=ia(l,r.windowResizeDelay),g(window).resize(C)))};m.destroy=function(){v&&v.destroyView();u.destroy();O.remove();a.removeClass("fc fc-ltr fc-rtl fc-unthemed ui-widget");g(window).unbind("resize",C)};m.refetchEvents=function(){x();v.destroyViewEvents();I();La(v.start,v.end)};m.reportEvents=function(a){H=a;z()};m.reportEventChange=function(){z()};
m.rerenderEvents=z;m.changeView=d;m.select=function(a,b){a=m.moment(a);b=b?m.moment(b):a.hasTime()?a.clone().add(m.defaultTimedEventDuration):a.clone().add(m.defaultAllDayEventDuration);v.select({start:a,end:b})};m.unselect=function(){v&&v.unselect()};m.prev=function(){e(-1)};m.next=function(){e(1)};m.prevYear=function(){G.add(-1,"years");e()};m.nextYear=function(){G.add(1,"years");e()};m.today=function(){G=m.getNow();e()};m.gotoDate=function(a){G=m.moment(a);e()};m.incrementDate=function(a){G.add(n.duration(a));
e()};m.zoomTo=function(a,b){var c,e;b&&h(b)||(b=b||"day",c=u.getViewsWithButtons().join(" "),(e=c.match(new RegExp("\\w+"+ya(b))))||(e=c.match(/\w+Day/)),b=e?e[0]:"agendaDay");G=a;d(b)};m.getDate=function(){return G.clone()};m.getCalendar=function(){return m};m.getView=function(){return v};m.option=function(a,b){if(void 0===b)return r[a];if("height"==a||"contentHeight"==a||"aspectRatio"==a)r[a]=b,k(!0)};m.trigger=function(a,b){if(r[a])return r[a].apply(b||Ma,Array.prototype.slice.call(arguments,2))};
m.isValidViewType=h;m.getViewButtonText=function(a){if(a=f(a))return a.buttonText};var w=Y(D(r.lang));r.monthNames&&(w._months=r.monthNames);r.monthNamesShort&&(w._monthsShort=r.monthNamesShort);r.dayNames&&(w._weekdays=r.dayNames);r.dayNamesShort&&(w._weekdaysShort=r.dayNamesShort);null!=r.firstDay&&(T=Y(w._week),T.dow=r.firstDay,w._week=T);m.defaultAllDayEventDuration=n.duration(r.defaultAllDayEventDuration);m.defaultTimedEventDuration=n.duration(r.defaultTimedEventDuration);m.moment=function(){var a;
"local"===r.timezone?(a=p.moment.apply(null,arguments),a.hasTime()&&a.local()):a="UTC"===r.timezone?p.moment.utc.apply(null,arguments):p.moment.parseZone.apply(null,arguments);"_locale"in a?a._locale=w:a._lang=w;return a};m.getIsAmbigTimezone=function(){return"local"!==r.timezone&&"UTC"!==r.timezone};m.rezoneDate=function(a){return m.moment(a.toArray())};m.getNow=function(){var a=r.now;"function"===typeof a&&(a=a());return m.moment(a)};m.calculateWeekNumber=function(a){var b=r.weekNumberCalculation;
if("function"===typeof b)return b(a);if("local"===b)return a.week();if("ISO"===b.toUpperCase())return a.isoWeek()};m.getEventEnd=function(a){return a.end?a.end.clone():m.getDefaultEventEnd(a.allDay,a.start)};m.getDefaultEventEnd=function(a,b){var c=b.clone();a?c.stripTime().add(m.defaultAllDayEventDuration):c.add(m.defaultTimedEventDuration);m.getIsAmbigTimezone()&&c.stripZone();return c};hb.call(m,r);var B=m.isFetchNeeded,La=m.fetchEvents,Ma=a[0],u,y,O,A={},v,J,C,L=0,G,H=[];G=null!=r.defaultDate?
m.moment(r.defaultDate):m.getNow();m.getSuggestedViewHeight=function(){void 0===J&&c()&&q();return J};m.isHeightAuto=function(){return"auto"===r.contentHeight||"auto"===r.height}}function gb(a,b){function c(c){var d=g('<div class="fc-'+c+'"/>');(c=b.header[c])&&g.each(c.split(" "),function(c){var h=g(),k=!0;g.each(this.split(","),function(c,d){var l,q,z,n,x,I,p;"title"==d?(h=h.add(g("<h2>&nbsp;</h2>")),k=!1):(a[d]?l=function(){a[d]()}:a.isValidViewType(d)&&(l=function(){a.changeView(d)},e.push(d),
x=a.getViewButtonText(d)),l&&(q=V(b.themeButtonIcons,d),z=V(b.buttonIcons,d),n=V(b.defaultButtonText,d),I=V(b.buttonText,d),q=x||I?B(x||I):q&&b.theme?"<span class='ui-icon ui-icon-"+q+"'></span>":z&&!b.theme?"<span class='fc-icon fc-icon-"+z+"'></span>":B(n||d),z=["fc-"+d+"-button",f+"-button",f+"-state-default"],p=g('<button type="button" class="'+z.join(" ")+'">'+q+"</button>").click(function(){p.hasClass(f+"-state-disabled")||(l(),(p.hasClass(f+"-state-active")||p.hasClass(f+"-state-disabled"))&&
p.removeClass(f+"-state-hover"))}).mousedown(function(){p.not("."+f+"-state-active").not("."+f+"-state-disabled").addClass(f+"-state-down")}).mouseup(function(){p.removeClass(f+"-state-down")}).hover(function(){p.not("."+f+"-state-active").not("."+f+"-state-disabled").addClass(f+"-state-hover")},function(){p.removeClass(f+"-state-hover").removeClass(f+"-state-down")}),h=h.add(p)))});k&&h.first().addClass(f+"-corner-left").end().last().addClass(f+"-corner-right").end();1<h.length?(c=g("<div/>"),k&&
c.addClass("fc-button-group"),c.append(h),d.append(c)):d.append(h)});return d}this.render=function(){var a=b.header;f=b.theme?"ui":"fc";if(a)return d=g("<div class='fc-toolbar'/>").append(c("left")).append(c("right")).append(c("center")).append('<div class="fc-clear"/>')};this.destroy=function(){d.remove()};this.updateTitle=function(a){d.find("h2").text(a)};this.activateButton=function(a){d.find(".fc-"+a+"-button").addClass(f+"-state-active")};this.deactivateButton=function(a){d.find(".fc-"+a+"-button").removeClass(f+
"-state-active")};this.disableButton=function(a){d.find(".fc-"+a+"-button").attr("disabled","disabled").addClass(f+"-state-disabled")};this.enableButton=function(a){d.find(".fc-"+a+"-button").removeAttr("disabled").removeClass(f+"-state-disabled")};this.getViewsWithButtons=function(){return e};var d=g(),e=[],f}function hb(a){function b(a,b){c(a,function(c){var d=g.isArray(a.events),e,f;if(b==G){if(c)for(e=0;e<c.length;e++)f=c[e],(f=d?f:z(f,a))&&F.push.apply(F,m(f));K--;K||D(F)}})}function c(b,d){var e,
f=p.sourceFetchers,h;for(e=0;e<f.length;e++){h=f[e].call(u,b,E.clone(),L.clone(),a.timezone,d);if(!0===h)return;if("object"==typeof h){c(h,d);return}}if(e=b.events)g.isFunction(e)?(q(),e.call(u,E.clone(),L.clone(),a.timezone,function(a){d(a);l()})):g.isArray(e)?d(e):d();else if(b.url){var db=b.success,k=b.error,eb=b.complete;e=g.isFunction(b.data)?b.data():b.data;e=g.extend({},e||{});f=N(b.startParam,a.startParam);h=N(b.endParam,a.endParam);var m=N(b.timezoneParam,a.timezoneParam);f&&(e[f]=E.format());
h&&(e[h]=L.format());a.timezone&&"local"!=a.timezone&&(e[m]=a.timezone);q();g.ajax(g.extend({},ib,b,{data:e,success:function(a){a=a||[];var b=Z(db,this,arguments);g.isArray(b)&&(a=b);d(a)},error:function(){Z(k,this,arguments);d()},complete:function(){Z(eb,this,arguments);l()}}))}else d()}function d(a){var b=p.sourceNormalizers,c;g.isFunction(a)||g.isArray(a)?c={events:a}:"string"===typeof a?c={url:a}:"object"===typeof a&&(c=g.extend({},a));if(c){c.className?"string"===typeof c.className&&(c.className=
c.className.split(/\s+/)):c.className=[];g.isArray(c.events)&&(c.origArray=c.events,c.events=g.map(c.events,function(a){return z(a,c)}));for(a=0;a<b.length;a++)b[a].call(u,c);return c}}function e(a,b){return a&&b&&f(a)==f(b)}function f(a){return("object"===typeof a?a.origArray||a.googleCalendarId||a.url||a.events:null)||a}function h(a){var b={};g.each(a,function(a,c){/^_|^(id|allDay|start|end)$/.test(a)||void 0!==c&&/undefined|null|boolean|number|string/.test(g.type(c))&&(b[a]=c)});return b}function k(a){return g.isFunction(a)?
g.grep(F,a):null!=a?(a+="",g.grep(F,function(b){return b._id==a})):F}function q(){M++||C("loading",null,!0,H())}function l(){--M||C("loading",null,!1,H())}function z(b,c){var d={},e,f,h;a.eventDataTransform&&(b=a.eventDataTransform(b));c&&c.eventDataTransform&&(b=c.eventDataTransform(b));g.extend(d,b);c&&(d.source=c);d._id=b._id||(void 0===b.id?"_fc"+jb++:b.id+"");d.className=b.className?"string"==typeof b.className?b.className.split(/\s+/):b.className:[];e=b.start||b.date;f=b.end;wa(e)&&(e=n.duration(e));
wa(f)&&(f=n.duration(f));if(b.dow||n.isDuration(e)||n.isDuration(f))d.start=e?n.duration(e):null,d.end=f?n.duration(f):null,d._recurring=!0;else{if(e&&(e=u.moment(e),!e.isValid()))return!1;f&&(f=u.moment(f),f.isValid()||(f=null));h=b.allDay;void 0===h&&(h=N(c?c.allDayDefault:void 0,a.allDayDefault));d.start=e;d.end=f;d.allDay=h;x(d);ba(d)}return d}function x(b){null==b.allDay&&(b.allDay=!(b.start.hasTime()||b.end&&b.end.hasTime()));b.allDay?(b.start.stripTime(),b.end&&b.end.stripTime()):(b.start.hasTime()||
(b.start=u.rezoneDate(b.start)),b.end&&!b.end.hasTime()&&(b.end=u.rezoneDate(b.end)));b.end&&!b.end.isAfter(b.start)&&(b.end=null);b.end||(b.end=a.forceEventDuration?u.getDefaultEventEnd(b.allDay,b.start):null)}function I(a){var b;a.end||(b=a.allDay,null==b&&(b=!a.start.hasTime()),a={start:a.start,end:u.getDefaultEventEnd(b,a.start)});return a}function m(a,b,c){var d=[],e,f,h,k,l,q;b=b||E;c=c||L;if(a)if(a._recurring){if(f=a.dow)for(e={},h=0;h<f.length;h++)e[f[h]]=!0;for(b=b.clone().stripTime();b.isBefore(c);){if(!e||
e[b.day()])k=a.start,l=a.end,f=b.clone(),q=null,k&&(f=f.time(k)),l&&(q=b.clone().time(l)),h=g.extend({},a),k=!k&&!l,l=h,l.start=f,l.end=q,l.allDay=k,x(l),ba(l),d.push(h);b.add(1,"days")}}else d.push(a);return d}function r(a,b){var c={},d,e,f;b=b||{};b.start||(b.start=a.start.clone());void 0===b.end&&(b.end=a.end?a.end.clone():null);null==b.allDay&&(b.allDay=a.allDay);x(b);d=null!==a._end&&null===b.end;e=b.allDay?Ta(b.start,a._start):W(b.start,a._start);!d&&b.end&&(f=W(b.end,b.start).subtract(W(a._end||
u.getDefaultEventEnd(a._allDay,a._start),a._start)));g.each(b,function(a,b){/^_|^(id|allDay|start|end)$/.test(a)||void 0!==b&&(c[a]=b)});d=t(k(a._id),d,b.allDay,e,f,c);return{dateDelta:e,durationDelta:f,undo:d}}function t(a,b,c,d,e,f){var h=u.getIsAmbigTimezone(),k=[];d&&!d.valueOf()&&(d=null);e&&!e.valueOf()&&(e=null);g.each(a,function(a,l){var q,m;q={start:l.start.clone(),end:l.end?l.end.clone():null,allDay:l.allDay};g.each(f,function(a){q[a]=l[a]});m={start:l._start,end:l._end,allDay:l._allDay};
b&&(m.end=null);m.allDay=c;x(m);d&&(m.start.add(d),m.end&&m.end.add(d));e&&(m.end||(m.end=u.getDefaultEventEnd(m.allDay,m.start)),m.end.add(e));h&&!m.allDay&&(d||e)&&(m.start.stripZone(),m.end&&m.end.stripZone());g.extend(l,f,m);ba(l);k.push(function(){g.extend(l,q);ba(l)})});return function(){for(var a=0;a<k.length;a++)k[a]()}}function w(){var b=a.businessHours,c={className:"fc-nonbusiness",start:"09:00",end:"17:00",dow:[1,2,3,4,5],rendering:"inverse-background"},d=u.getView(),e;b&&(e="object"===
typeof b?g.extend({},c,b):c);return e?m(z(e),d.start,d.end):[]}function y(b,c){var d=c.source||{},e=N(c.constraint,d.constraint,a.eventConstraint),d=N(c.overlap,d.overlap,a.eventOverlap);b=I(b);return A(b,e,d,c)}function B(b){return A(b,a.selectConstraint,a.selectOverlap)}function A(a,b,c,d){var e,f;a={start:a.start.clone().stripZone(),end:a.end.clone().stripZone()};if(null!=b){e="businessHours"===b?w():"object"===typeof b?m(z(b)):k(b);f=!1;for(b=0;b<e.length;b++){var h=e[b],g=a,l=h.start.clone().stripZone(),
h=u.getEventEnd(h).stripZone();if(g.start>=l&&g.end<=h){f=!0;break}}if(!f)return!1}for(b=0;b<F.length;b++)if(e=F[b],!d||d._id!==e._id)if(l=e,f=a,g=l.start.clone().stripZone(),l=u.getEventEnd(l).stripZone(),f.start<l&&f.end>g&&(!1===c||"function"===typeof c&&!c(e,d)||d&&(f=N(e.overlap,(e.source||{}).overlap),!1===f||"function"===typeof f&&!f(d,e))))return!1;return!0}var u=this;u.isFetchNeeded=function(a,b){return!E||a.clone().stripZone()<E.clone().stripZone()||b.clone().stripZone()>L.clone().stripZone()};
u.fetchEvents=function(a,c){E=a;L=c;F=[];var d=++G,e=J.length;K=e;for(var f=0;f<e;f++)b(J[f],d)};u.addEventSource=function(a){if(a=d(a))J.push(a),K++,b(a,G)};u.removeEventSource=function(a){J=g.grep(J,function(b){return!e(b,a)});F=g.grep(F,function(b){return!e(b.source,a)});D(F)};u.updateEvent=function(a){a.start=u.moment(a.start);a.end=a.end?u.moment(a.end):null;r(a,h(a));D(F)};u.renderEvent=function(a,b){var c=z(a),d,e;if(c){c=m(c);for(d=0;d<c.length;d++)e=c[d],e.source||(b&&(v.events.push(e),e.source=
v),F.push(e));D(F);return c}return[]};u.removeEvents=function(a){var b,c;null==a?a=function(){return!0}:g.isFunction(a)||(b=a+"",a=function(a){return a._id==b});F=g.grep(F,a,!0);for(c=0;c<J.length;c++)g.isArray(J[c].events)&&(J[c].events=g.grep(J[c].events,a,!0));D(F)};u.clientEvents=k;u.mutateEvent=r;u.normalizeEventDateProps=x;u.ensureVisibleEventRange=I;var C=u.trigger,H=u.getView,D=u.reportEvents,v={events:[]},J=[v],E,L,G=0,K=0,M=0,F=[];g.each((a.events?[a.events]:[]).concat(a.eventSources||[]),
function(a,b){var c=d(b);c&&J.push(c)});u.getBusinessHoursEvents=w;u.isEventRangeAllowed=y;u.isSelectionRangeAllowed=B;u.isExternalDropRangeAllowed=function(a,b){var c;b&&(c=g.extend({},b,a),c=m(z(c))[0]);if(c)return y(a,c);a=I(a);return B(a)}}function ba(a){a._allDay=a.allDay;a._start=a.start.clone();a._end=a.end?a.end.clone():null}var R={titleRangeSeparator:" \u2014 ",monthYearFormat:"MMMM YYYY",defaultTimedEventDuration:"02:00:00",defaultAllDayEventDuration:{days:1},forceEventDuration:!1,nextDayThreshold:"09:00:00",
defaultView:"month",aspectRatio:1.35,header:{left:"title",center:"",right:"today prev,next"},weekends:!0,weekNumbers:!1,weekNumberTitle:"W",weekNumberCalculation:"local",lazyFetching:!0,startParam:"start",endParam:"end",timezoneParam:"timezone",timezone:!1,isRTL:!1,defaultButtonText:{prev:"prev",next:"next",prevYear:"prev year",nextYear:"next year",today:"today",month:"month",week:"week",day:"day"},buttonIcons:{prev:"left-single-arrow",next:"right-single-arrow",prevYear:"left-double-arrow",nextYear:"right-double-arrow"},
theme:!1,themeButtonIcons:{prev:"circle-triangle-w",next:"circle-triangle-e",prevYear:"seek-prev",nextYear:"seek-next"},dragOpacity:.75,dragRevertDuration:500,dragScroll:!0,unselectAuto:!0,dropAccept:"*",eventLimit:!1,eventLimitText:"more",eventLimitClick:"popover",dayPopoverFormat:"LL",handleWindowResize:!0,windowResizeDelay:200},fb={header:{left:"next,prev today",center:"",right:"title"},buttonIcons:{prev:"right-single-arrow",next:"left-single-arrow",prevYear:"right-double-arrow",nextYear:"left-double-arrow"},
themeButtonIcons:{prev:"circle-triangle-e",next:"circle-triangle-w",nextYear:"seek-prev",prevYear:"seek-next"}},p=g.fullCalendar={version:"2.2.5"},P=p.views={};g.fn.fullCalendar=function(a){var b=Array.prototype.slice.call(arguments,1),c=this;this.each(function(d,e){var f=g(e),h=f.data("fullCalendar");"string"===typeof a?h&&g.isFunction(h[a])&&(h=h[a].apply(h,b),d||(c=h),"destroy"===a&&f.removeData("fullCalendar")):h||(h=new cb(f,a),f.data("fullCalendar",h),h.render())});return c};var S=p.langs={};
p.datepickerLang=function(a,b,c){var d=S[a]||(S[a]={});d.isRTL=c.isRTL;d.weekNumberTitle=c.weekHeader;g.each(kb,function(a,b){d[a]=b(c)});g.datepicker&&(g.datepicker.regional[b]=g.datepicker.regional[a]=c,g.datepicker.regional.en=g.datepicker.regional[""],g.datepicker.setDefaults(c))};p.lang=function(a,b){var c,d;c=S[a]||(S[a]={});b&&t(c,b);d=D(a);g.each(lb,function(a,b){void 0===c[a]&&(c[a]=b(d,c))});R.lang=a};var kb={defaultButtonText:function(a){return{prev:a.prevText.replace(/&.*?;/g,""),next:a.nextText.replace(/&.*?;/g,
""),today:a.currentText.replace(/&.*?;/g,"")}},monthYearFormat:function(a){return a.showMonthAfterYear?"YYYY["+a.yearSuffix+"] MMMM":"MMMM YYYY["+a.yearSuffix+"]"}},lb={dayOfMonthFormat:function(a,b){var c=a.longDateFormat("l"),c=c.replace(/^Y+[^\w\s]*|[^\w\s]*Y+$/g,"");return c=b.isRTL?c+" ddd":"ddd "+c},smallTimeFormat:function(a){return a.longDateFormat("LT").replace(":mm","(:mm)").replace(/(\Wmm)$/,"($1)").replace(/\s*a$/i,"a")},extraSmallTimeFormat:function(a){return a.longDateFormat("LT").replace(":mm",
"(:mm)").replace(/(\Wmm)$/,"($1)").replace(/\s*a$/i,"t")},noMeridiemTimeFormat:function(a){return a.longDateFormat("LT").replace(/\s*a$/i,"")}};p.lang("en",{dayPopoverFormat:"dddd, MMMM D"});p.intersectionToSeg=fa;p.applyAll=Z;p.debounce=ia;var Na="sun mon tue wed thu fri sat".split(" "),va="year month week day hour minute second millisecond".split(" "),xa={}.hasOwnProperty,Va=/^\s*\d{4}-\d\d$/,Wa=/^\s*\d{4}-(?:(\d\d-\d\d)|(W\d\d$)|(W\d\d-\d)|(\d\d\d))((T| )(\d\d(:\d\d(:\d\d(\.\d+)?)?)?)?)?$/,y=n.fn,
C=g.extend({},y),Oa,oa,Pa;p.moment=function(){return ja(arguments)};p.moment.utc=function(){var a=ja(arguments,!0);a.hasTime()&&a.utc();return a};p.moment.parseZone=function(){return ja(arguments,!0,!0)};y.clone=function(){var a=C.clone.apply(this,arguments);za(this,a);this._fullCalendar&&(a._fullCalendar=!0);return a};y.time=function(a){if(!this._fullCalendar)return C.time.apply(this,arguments);if(null==a)return n.duration({hours:this.hours(),minutes:this.minutes(),seconds:this.seconds(),milliseconds:this.milliseconds()});
this._ambigTime=!1;n.isDuration(a)||n.isMoment(a)||(a=n.duration(a));var b=0;n.isDuration(a)&&(b=24*Math.floor(a.asDays()));return this.hours(b+a.hours()).minutes(a.minutes()).seconds(a.seconds()).milliseconds(a.milliseconds())};y.stripTime=function(){var a;this._ambigTime||(a=this.toArray(),this.utc(),oa(this,a.slice(0,3)),this._ambigZone=this._ambigTime=!0);return this};y.hasTime=function(){return!this._ambigTime};y.stripZone=function(){var a,b;this._ambigZone||(a=this.toArray(),b=this._ambigTime,
this.utc(),oa(this,a),b&&(this._ambigTime=!0),this._ambigZone=!0);return this};y.hasZone=function(){return!this._ambigZone};y.zone=function(a){null!=a&&(this._ambigZone=this._ambigTime=!1);return C.zone.apply(this,arguments)};y.local=function(){var a=this.toArray(),b=this._ambigZone;C.local.apply(this,arguments);b&&Pa(this,a);return this};y.format=function(){return this._fullCalendar&&arguments[0]?Ba(this,Ea(arguments[0])):this._ambigTime?M(this,"YYYY-MM-DD"):this._ambigZone?M(this,"YYYY-MM-DD[T]HH:mm:ss"):
C.format.apply(this,arguments)};y.toISOString=function(){return this._ambigTime?M(this,"YYYY-MM-DD"):this._ambigZone?M(this,"YYYY-MM-DD[T]HH:mm:ss"):C.toISOString.apply(this,arguments)};y.isWithin=function(a,b){var c=ka([this,a,b]);return c[0]>=c[1]&&c[0]<c[2]};y.isSame=function(a,b){var c;if(!this._fullCalendar)return C.isSame.apply(this,arguments);if(b)return c=ka([this,a],!0),C.isSame.call(c[0],c[1],b);a=p.moment.parseZone(a);return C.isSame.call(this,a)&&!!this._ambigTime===!!a._ambigTime&&!!this._ambigZone===
!!a._ambigZone};g.each(["isBefore","isAfter"],function(a,b){y[b]=function(a,d){var c;if(!this._fullCalendar)return C[b].apply(this,arguments);c=ka([this,a]);return C[b].call(c[0],c[1],d)}});oa=(Oa="_d"in n()&&"updateOffset"in n)?function(a,b){a._d.setTime(Date.UTC.apply(Date,b));n.updateOffset(a,!1)}:Aa;Pa=Oa?function(a,b){a._d.setTime(+new Date(b[0]||0,b[1]||0,b[2]||0,b[3]||0,b[4]||0,b[5]||0,b[6]||0));n.updateOffset(a,!1)}:Aa;var Ca={t:function(a){return M(a,"a").charAt(0)},T:function(a){return M(a,
"A").charAt(0)}};p.formatRange=Da;var Xa={Y:"year",M:"month",D:"day",d:"day",A:"second",a:"second",T:"second",t:"second",H:"second",h:"second",m:"second",s:"second"},ma={};p.Class=E;E.extend=function(a){var b=this,c;a=a||{};xa.call(a,"constructor")&&(c=a.constructor);"function"!==typeof c&&(c=a.constructor=function(){b.apply(this,arguments)});c.prototype=Y(b.prototype);ha(a,c.prototype);ha(b,c);return c};E.mixin=function(a){ha(a.prototype||a,this.prototype)};var mb=E.extend({isHidden:!0,options:null,
el:null,documentMousedownProxy:null,margin:10,constructor:function(a){this.options=a||{}},show:function(){this.isHidden&&(this.el||this.render(),this.el.show(),this.position(),this.isHidden=!1,this.trigger("show"))},hide:function(){this.isHidden||(this.el.hide(),this.isHidden=!0,this.trigger("hide"))},render:function(){var a=this,b=this.options;this.el=g('<div class="fc-popover"/>').addClass(b.className||"").css({top:0,left:0}).append(b.content).appendTo(b.parentEl);this.el.on("click",".fc-close",
function(){a.hide()});if(b.autoHide)g(document).on("mousedown",this.documentMousedownProxy=g.proxy(this,"documentMousedown"))},documentMousedown:function(a){this.el&&!g(a.target).closest(this.el).length&&this.hide()},destroy:function(){this.hide();this.el&&(this.el.remove(),this.el=null);g(document).off("mousedown",this.documentMousedownProxy)},position:function(){var a=this.options,b=this.el.offsetParent().offset(),c=this.el.outerWidth(),d=this.el.outerHeight(),e=g(window),f=sa(this.el),h,k,q,l;
q=a.top||0;l=void 0!==a.left?a.left:void 0!==a.right?a.right-c:0;f.is(window)||f.is(document)?(f=e,k=h=0):(k=f.offset(),h=k.top,k=k.left);h+=e.scrollTop();k+=e.scrollLeft();!1!==a.viewportConstrain&&(q=Math.min(q,h+f.outerHeight()-d-this.margin),q=Math.max(q,h+this.margin),l=Math.min(l,k+f.outerWidth()-c-this.margin),l=Math.max(l,k+this.margin));this.el.css({top:q-b.top,left:l-b.left})},trigger:function(a){this.options[a]&&this.options[a].apply(this,Array.prototype.slice.call(arguments,1))}}),nb=
E.extend({grid:null,rowCoords:null,colCoords:null,containerEl:null,minX:null,maxX:null,minY:null,maxY:null,constructor:function(a){this.grid=a},build:function(){this.rowCoords=this.grid.computeRowCoords();this.colCoords=this.grid.computeColCoords();this.computeBounds()},clear:function(){this.colCoords=this.rowCoords=null},getCell:function(a,b){var c=this.rowCoords,d=this.colCoords,e=null,f=null,h,g;if(this.inBounds(a,b)){for(h=0;h<c.length;h++)if(g=c[h],b>=g.top&&b<g.bottom){e=h;break}for(h=0;h<d.length;h++)if(g=
d[h],a>=g.left&&a<g.right){f=h;break}if(null!==e&&null!==f)return c=this.grid.getCell(e,f),c.grid=this.grid,c}return null},computeBounds:function(){var a;this.containerEl&&(a=this.containerEl.offset(),this.minX=a.left,this.maxX=a.left+this.containerEl.outerWidth(),this.minY=a.top,this.maxY=a.top+this.containerEl.outerHeight())},inBounds:function(a,b){return this.containerEl?a>=this.minX&&a<this.maxX&&b>=this.minY&&b<this.maxY:!0}}),ob=E.extend({coordMaps:null,constructor:function(a){this.coordMaps=
a},build:function(){var a=this.coordMaps,b;for(b=0;b<a.length;b++)a[b].build()},getCell:function(a,b){var c=this.coordMaps,d=null,e;for(e=0;e<c.length&&!d;e++)d=c[e].getCell(a,b);return d},clear:function(){var a=this.coordMaps,b;for(b=0;b<a.length;b++)a[b].clear()}}),ca=E.extend({coordMap:null,options:null,isListening:!1,isDragging:!1,origCell:null,cell:null,mouseX0:null,mouseY0:null,mousemoveProxy:null,mouseupProxy:null,scrollEl:null,scrollBounds:null,scrollTopVel:null,scrollLeftVel:null,scrollIntervalId:null,
scrollHandlerProxy:null,scrollSensitivity:30,scrollSpeed:200,scrollIntervalMs:50,constructor:function(a,b){this.coordMap=a;this.options=b||{}},mousedown:function(a){1!=a.which||a.ctrlKey||(a.preventDefault(),this.startListening(a),this.options.distance||this.startDrag(a))},startListening:function(a){var b;this.isListening||(a&&this.options.scroll&&(b=sa(g(a.target)),b.is(window)||b.is(document)||(this.scrollEl=b,this.scrollHandlerProxy=ia(g.proxy(this,"scrollHandler"),100),this.scrollEl.on("scroll",
this.scrollHandlerProxy))),this.computeCoords(),a&&(this.origCell=b=this.getCell(a),this.mouseX0=a.pageX,this.mouseY0=a.pageY),g(document).on("mousemove",this.mousemoveProxy=g.proxy(this,"mousemove")).on("mouseup",this.mouseupProxy=g.proxy(this,"mouseup")).on("selectstart",this.preventDefault),this.isListening=!0,this.trigger("listenStart",a))},computeCoords:function(){this.coordMap.build();this.computeScrollBounds()},mousemove:function(a){var b,c;this.isDragging||(b=this.options.distance||1,c=Math.pow(a.pageX-
this.mouseX0,2)+Math.pow(a.pageY-this.mouseY0,2),c>=b*b&&this.startDrag(a));this.isDragging&&this.drag(a)},startDrag:function(a){this.isListening||this.startListening();this.isDragging||(this.isDragging=!0,this.trigger("dragStart",a),(a=this.getCell(a))&&this.cellOver(a))},drag:function(a){var b;this.isDragging&&(b=this.getCell(a),Ha(b,this.cell)||(this.cell&&this.cellOut(),b&&this.cellOver(b)),this.dragScroll(a))},cellOver:function(a){this.cell=a;this.trigger("cellOver",a,Ha(a,this.origCell))},cellOut:function(){this.cell&&
(this.trigger("cellOut",this.cell),this.cell=null)},mouseup:function(a){this.stopDrag(a);this.stopListening(a)},stopDrag:function(a){this.isDragging&&(this.stopScrolling(),this.trigger("dragStop",a),this.isDragging=!1)},stopListening:function(a){this.isListening&&(this.scrollEl&&(this.scrollEl.off("scroll",this.scrollHandlerProxy),this.scrollHandlerProxy=null),g(document).off("mousemove",this.mousemoveProxy).off("mouseup",this.mouseupProxy).off("selectstart",this.preventDefault),this.mouseupProxy=
this.mousemoveProxy=null,this.isListening=!1,this.trigger("listenStop",a),this.origCell=this.cell=null,this.coordMap.clear())},getCell:function(a){return this.coordMap.getCell(a.pageX,a.pageY)},trigger:function(a){this.options[a]&&this.options[a].apply(this,Array.prototype.slice.call(arguments,1))},preventDefault:function(a){a.preventDefault()},computeScrollBounds:function(){var a=this.scrollEl,b;a&&(b=a.offset(),this.scrollBounds={top:b.top,left:b.left,bottom:b.top+a.outerHeight(),right:b.left+a.outerWidth()})},
dragScroll:function(a){var b=this.scrollSensitivity,c=this.scrollBounds,d,e,f,g=0,k=0;c&&(d=(b-(a.pageY-c.top))/b,e=(b-(c.bottom-a.pageY))/b,f=(b-(a.pageX-c.left))/b,a=(b-(c.right-a.pageX))/b,0<=d&&1>=d?g=d*this.scrollSpeed*-1:0<=e&&1>=e&&(g=e*this.scrollSpeed),0<=f&&1>=f?k=f*this.scrollSpeed*-1:0<=a&&1>=a&&(k=a*this.scrollSpeed));this.setScrollVel(g,k)},setScrollVel:function(a,b){this.scrollTopVel=a;this.scrollLeftVel=b;this.constrainScrollVel();!this.scrollTopVel&&!this.scrollLeftVel||this.scrollIntervalId||
(this.scrollIntervalId=setInterval(g.proxy(this,"scrollIntervalFunc"),this.scrollIntervalMs))},constrainScrollVel:function(){var a=this.scrollEl;0>this.scrollTopVel?0>=a.scrollTop()&&(this.scrollTopVel=0):0<this.scrollTopVel&&a.scrollTop()+a[0].clientHeight>=a[0].scrollHeight&&(this.scrollTopVel=0);0>this.scrollLeftVel?0>=a.scrollLeft()&&(this.scrollLeftVel=0):0<this.scrollLeftVel&&a.scrollLeft()+a[0].clientWidth>=a[0].scrollWidth&&(this.scrollLeftVel=0)},scrollIntervalFunc:function(){var a=this.scrollEl,
b=this.scrollIntervalMs/1E3;this.scrollTopVel&&a.scrollTop(a.scrollTop()+this.scrollTopVel*b);this.scrollLeftVel&&a.scrollLeft(a.scrollLeft()+this.scrollLeftVel*b);this.constrainScrollVel();this.scrollTopVel||this.scrollLeftVel||this.stopScrolling()},stopScrolling:function(){this.scrollIntervalId&&(clearInterval(this.scrollIntervalId),this.scrollIntervalId=null,this.computeCoords())},scrollHandler:function(){this.scrollIntervalId||this.computeCoords()}}),pb=E.extend({options:null,sourceEl:null,el:null,
parentEl:null,top0:null,left0:null,mouseY0:null,mouseX0:null,topDelta:null,leftDelta:null,mousemoveProxy:null,isFollowing:!1,isHidden:!1,isAnimating:!1,constructor:function(a,b){this.options=b=b||{};this.sourceEl=a;this.parentEl=b.parentEl?g(b.parentEl):a.parent()},start:function(a){this.isFollowing||(this.isFollowing=!0,this.mouseY0=a.pageY,this.mouseX0=a.pageX,this.leftDelta=this.topDelta=0,this.isHidden||this.updatePosition(),g(document).on("mousemove",this.mousemoveProxy=g.proxy(this,"mousemove")))},
stop:function(a,b){function c(){this.isAnimating=!1;d.destroyEl();this.top0=this.left0=null;b&&b()}var d=this,e=this.options.revertDuration;this.isFollowing&&!this.isAnimating&&(this.isFollowing=!1,g(document).off("mousemove",this.mousemoveProxy),a&&e&&!this.isHidden?(this.isAnimating=!0,this.el.animate({top:this.top0,left:this.left0},{duration:e,complete:c})):c())},getEl:function(){var a=this.el;a||(this.sourceEl.width(),a=this.el=this.sourceEl.clone().css({position:"absolute",visibility:"",display:this.isHidden?
"none":"",margin:0,right:"auto",bottom:"auto",width:this.sourceEl.width(),height:this.sourceEl.height(),opacity:this.options.opacity||"",zIndex:this.options.zIndex}).appendTo(this.parentEl));return a},destroyEl:function(){this.el&&(this.el.remove(),this.el=null)},updatePosition:function(){var a,b;this.getEl();null===this.top0&&(this.sourceEl.width(),a=this.sourceEl.offset(),b=this.el.offsetParent().offset(),this.top0=a.top-b.top,this.left0=a.left-b.left);this.el.css({top:this.top0+this.topDelta,left:this.left0+
this.leftDelta})},mousemove:function(a){this.topDelta=a.pageY-this.mouseY0;this.leftDelta=a.pageX-this.mouseX0;this.isHidden||this.updatePosition()},hide:function(){this.isHidden||(this.isHidden=!0,this.el&&this.el.hide())},show:function(){this.isHidden&&(this.isHidden=!1,this.updatePosition(),this.getEl().show())}}),Qa=E.extend({view:null,isRTL:null,cellHtml:"<td/>",constructor:function(a){this.view=a;this.isRTL=a.opt("isRTL")},rowHtml:function(a,b){var c=this.getHtmlRenderer("cell",a),d="",e,f;
b=b||0;for(e=0;e<this.colCnt;e++)f=this.getCell(b,e),d+=c(f);d=this.bookendCells(d,a,b);return"<tr>"+d+"</tr>"},bookendCells:function(a,b,c){var d=this.getHtmlRenderer("intro",b)(c||0);c=this.getHtmlRenderer("outro",b)(c||0);b=this.isRTL?c:d;d=this.isRTL?d:c;return"string"===typeof a?b+a+d:a.prepend(b).append(d)},getHtmlRenderer:function(a,b){var c=this.view,d,e,f,g;d=a+"Html";b&&(e=b+ya(a)+"Html");if(e&&(g=c[e]))f=c;else if(e&&(g=this[e]))f=this;else if(g=c[d])f=c;else if(g=this[d])f=this;return"function"===
typeof g?function(){return g.apply(f,arguments)||""}:function(){return g||""}}}),H=p.Grid=Qa.extend({start:null,end:null,rowCnt:0,colCnt:0,rowData:null,colData:null,el:null,coordMap:null,elsByFill:null,documentDragStartProxy:null,colHeadFormat:null,eventTimeFormat:null,displayEventEnd:null,constructor:function(){Qa.apply(this,arguments);this.coordMap=new nb(this);this.elsByFill={};this.documentDragStartProxy=g.proxy(this,"documentDragStart")},render:function(){this.bindHandlers()},destroy:function(){this.unbindHandlers()},
computeColHeadFormat:function(){},computeEventTimeFormat:function(){return this.view.opt("smallTimeFormat")},computeDisplayEventEnd:function(){return!1},setRange:function(a){var b=this.view;this.start=a.start.clone();this.end=a.end.clone();this.rowData=[];this.colData=[];this.updateCells();this.colHeadFormat=b.opt("columnFormat")||this.computeColHeadFormat();this.eventTimeFormat=b.opt("timeFormat")||this.computeEventTimeFormat();this.displayEventEnd=b.opt("displayEventEnd");null==this.displayEventEnd&&
(this.displayEventEnd=this.computeDisplayEventEnd())},updateCells:function(){},rangeToSegs:function(a){},getCell:function(a,b){var c;null==b&&("number"===typeof a?(b=a%this.colCnt,a=Math.floor(a/this.colCnt)):(b=a.col,a=a.row));c={row:a,col:b};g.extend(c,this.getRowData(a),this.getColData(b));g.extend(c,this.computeCellRange(c));return c},computeCellRange:function(a){},getRowData:function(a){return this.rowData[a]||{}},getColData:function(a){return this.colData[a]||{}},getRowEl:function(a){},getColEl:function(a){},
getCellDayEl:function(a){return this.getColEl(a.col)||this.getRowEl(a.row)},computeRowCoords:function(){var a=[],b,c,d;for(b=0;b<this.rowCnt;b++)c=this.getRowEl(b),d={top:c.offset().top},0<b&&(a[b-1].bottom=d.top),a.push(d);d.bottom=d.top+c.outerHeight();return a},computeColCoords:function(){var a=[],b,c,d;for(b=0;b<this.colCnt;b++)c=this.getColEl(b),d={left:c.offset().left},0<b&&(a[b-1].right=d.left),a.push(d);d.right=d.left+c.outerWidth();return a},bindHandlers:function(){var a=this;this.el.on("mousedown",
function(b){g(b.target).is(".fc-event-container *, .fc-more")||g(b.target).closest(".fc-popover").length||a.dayMousedown(b)});this.bindSegHandlers();g(document).on("dragstart",this.documentDragStartProxy)},unbindHandlers:function(){g(document).off("dragstart",this.documentDragStartProxy)},dayMousedown:function(a){var b=this,c=this.view,d=c.opt("selectable"),e,f,g=new ca(this.coordMap,{scroll:c.opt("dragScroll"),dragStart:function(){c.unselect()},cellOver:function(a,c){var h=g.origCell;h&&(e=c?a:null,
d&&((f=b.computeSelection(h,a))?b.renderSelection(f):X()))},cellOut:function(a){f=e=null;b.destroySelection();K()},listenStop:function(a){e&&c.trigger("dayClick",b.getCellDayEl(e),e.start,a);f&&c.reportSelection(f,a);K()}});g.mousedown(a)},renderRangeHelper:function(a,b){var c;c=b?Y(b.event):{};c.start=a.start.clone();c.end=a.end?a.end.clone():null;c.allDay=null;this.view.calendar.normalizeEventDateProps(c);c.className=(c.className||[]).concat("fc-helper");b||(c.editable=!1);this.renderHelper(c,b)},
renderHelper:function(a,b){},destroyHelper:function(){},renderSelection:function(a){this.renderHighlight(a)},destroySelection:function(){this.destroyHighlight()},computeSelection:function(a,b){var c=[a.start,a.end,b.start,b.end];c.sort(Ua);c={start:c[0].clone(),end:c[3].clone()};return this.view.calendar.isSelectionRangeAllowed(c)?c:null},renderHighlight:function(a){this.renderFill("highlight",this.rangeToSegs(a))},destroyHighlight:function(){this.destroyFill("highlight")},highlightSegClasses:function(){return["fc-highlight"]},
renderFill:function(a,b){},destroyFill:function(a){var b=this.elsByFill[a];b&&(b.remove(),delete this.elsByFill[a])},renderFillSegEls:function(a,b){var c=this,d=this[a+"SegEl"],e="",f=[],h;if(b.length){for(h=0;h<b.length;h++)e+=this.fillSegHtml(a,b[h]);g(e).each(function(a,e){var h=b[a],k=g(e);d&&(k=d.call(c,h,k));k&&(k=g(k),k.is(c.fillSegTag)&&(h.el=k,f.push(h)))})}return f},fillSegTag:"div",fillSegHtml:function(a,b){var c=this[a+"SegClasses"],d=this[a+"SegStyles"],c=c?c.call(this,b):[],d=d?d.call(this,
b):"";return"<"+this.fillSegTag+(c.length?' class="'+c.join(" ")+'"':"")+(d?' style="'+d+'"':"")+" />"},headHtml:function(){return'<div class="fc-row '+this.view.widgetHeaderClass+'"><table><thead>'+this.rowHtml("head")+"</thead></table></div>"},headCellHtml:function(a){a=a.start;return'<th class="fc-day-header '+this.view.widgetHeaderClass+" fc-"+Na[a.day()]+'">'+B(a.format(this.colHeadFormat))+"</th>"},bgCellHtml:function(a){var b=this.view;a=a.start;var c=this.getDayClasses(a);c.unshift("fc-day",
b.widgetContentClass);return'<td class="'+c.join(" ")+'" data-date="'+a.format("YYYY-MM-DD")+'"></td>'},getDayClasses:function(a){var b=this.view,c=b.calendar.getNow().stripTime(),d=["fc-"+Na[a.day()]];"month"===b.name&&a.month()!=b.intervalStart.month()&&d.push("fc-other-month");a.isSame(c,"day")?d.push("fc-today",b.highlightStateClass):a<c?d.push("fc-past"):d.push("fc-future");return d}});H.mixin({mousedOverSeg:null,isDraggingSeg:!1,isResizingSeg:!1,segs:null,renderEvents:function(a){a=this.eventsToSegs(a);
var b=[],c=[],d,e;for(d=0;d<a.length;d++){e=a[d];var f=Ia(e.event);"background"===f||"inverse-background"===f?b.push(e):c.push(e)}b=this.renderBgSegs(b)||b;c=this.renderFgSegs(c)||c;this.segs=b.concat(c)},destroyEvents:function(){this.triggerSegMouseout();this.destroyFgSegs();this.destroyBgSegs();this.segs=null},getEventSegs:function(){return this.segs||[]},renderFgSegs:function(a){},destroyFgSegs:function(){},renderFgSegEls:function(a,b){var c=this.view,d="",e=[],f;if(a.length){for(f=0;f<a.length;f++)d+=
this.fgSegHtml(a[f],b);g(d).each(function(b,d){var f=a[b],h=c.resolveEventEl(f.event,g(d));h&&(h.data("fc-seg",f),f.el=h,e.push(f))})}return e},fgSegHtml:function(a,b){},renderBgSegs:function(a){return this.renderFill("bgEvent",a)},destroyBgSegs:function(){this.destroyFill("bgEvent")},bgEventSegEl:function(a,b){return this.view.resolveEventEl(a.event,b)},bgEventSegClasses:function(a){a=a.event;return["fc-bgevent"].concat(a.className,(a.source||{}).className||[])},bgEventSegStyles:function(a){var b=
this.view;a=a.event;var c=a.source||{},d=a.color,e=c.color,f=b.opt("eventColor");return(b=a.backgroundColor||d||c.backgroundColor||e||b.opt("eventBackgroundColor")||f)?"background-color:"+b:""},businessHoursSegClasses:function(a){return["fc-nonbusiness","fc-bgevent"]},bindSegHandlers:function(){var a=this,b=this.view;g.each({mouseenter:function(b,d){a.triggerSegMouseover(b,d)},mouseleave:function(b,d){a.triggerSegMouseout(b,d)},click:function(a,d){return b.trigger("eventClick",this,a.event,d)},mousedown:function(c,
d){g(d.target).is(".fc-resizer")&&b.isEventResizable(c.event)?a.segResizeMousedown(c,d):b.isEventDraggable(c.event)&&a.segDragMousedown(c,d)}},function(b,d){a.el.on(b,".fc-event-container > *",function(b){var c=g(this).data("fc-seg");if(c&&!a.isDraggingSeg&&!a.isResizingSeg)return d.call(this,c,b)})})},triggerSegMouseover:function(a,b){this.mousedOverSeg||(this.mousedOverSeg=a,this.view.trigger("eventMouseover",a.el[0],a.event,b))},triggerSegMouseout:function(a,b){b=b||{};this.mousedOverSeg&&(a=a||
this.mousedOverSeg,this.mousedOverSeg=null,this.view.trigger("eventMouseout",a.el[0],a.event,b))},segDragMousedown:function(a,b){var c=this,d=this.view,e=a.el,f=a.event,g,k=new pb(a.el,{parentEl:d.el,opacity:d.opt("dragOpacity"),revertDuration:d.opt("dragRevertDuration"),zIndex:2}),q=new ca(d.coordMap,{distance:5,scroll:d.opt("dragScroll"),listenStart:function(a){k.hide();k.start(a)},dragStart:function(b){c.triggerSegMouseout(a,b);c.isDraggingSeg=!0;d.hideEvent(f);d.trigger("eventDragStart",e[0],
f,b,{})},cellOver:function(b,e){(g=c.computeEventDrop(a.cell||q.origCell,b,f))?(d.renderDrag(g,a)?k.hide():k.show(),e&&(g=null)):(k.show(),X())},cellOut:function(){g=null;d.destroyDrag();k.show();K()},dragStop:function(a){k.stop(!g,function(){c.isDraggingSeg=!1;d.destroyDrag();d.showEvent(f);d.trigger("eventDragStop",e[0],f,a,{});g&&d.reportEventDrop(f,g,e,a)});K()},listenStop:function(){k.stop()}});q.mousedown(b)},computeEventDrop:function(a,b,c){var d=a.start;a=b.start;d.hasTime()===a.hasTime()?
(a=W(a,d),b=c.start.clone().add(a),d=null===c.end?null:c.end.clone().add(a),a=c.allDay):(b=a.clone(),d=null,a=!a.hasTime());b={start:b,end:d,allDay:a};return this.view.calendar.isEventRangeAllowed(b,c)?b:null},documentDragStart:function(a,b){var c=this.view,d;c.opt("droppable")&&(d=g(a.target),c=c.opt("dropAccept"),(g.isFunction(c)?c.call(d[0],d):d.is(c))&&this.startExternalDrag(d,a,b))},startExternalDrag:function(a,b,c){var d=this,e=$a(a),f;c=new ca(this.coordMap,{cellOver:function(a){(f=d.computeExternalDrop(a,
e))?d.renderDrag(f):X()},cellOut:function(){f=null;d.destroyDrag();K()}});g(document).one("dragstop",function(b,c){d.destroyDrag();K();f&&d.view.reportExternalDrop(e,f,a,b,c)});c.startDrag(b)},computeExternalDrop:function(a,b){var c={start:a.start.clone(),end:null};b.startTime&&!c.start.hasTime()&&c.start.time(b.startTime);b.duration&&(c.end=c.start.clone().add(b.duration));return this.view.calendar.isExternalDropRangeAllowed(c,b.eventProps)?c:null},renderDrag:function(a,b){},destroyDrag:function(){},
segResizeMousedown:function(a,b){var c=this,d=this.view,e=d.calendar,f=a.el,g=a.event,k=g.start,q=e.getEventEnd(g),l;(new ca(this.coordMap,{distance:5,scroll:d.opt("dragScroll"),dragStart:function(b){c.triggerSegMouseout(a,b);c.isResizingSeg=!0;d.trigger("eventResizeStart",f[0],g,b,{})},cellOver:function(b){l=b.end;l.isAfter(k)||(l=k.clone().add(W(b.end,b.start)));l.isSame(q)?l=null:e.isEventRangeAllowed({start:k,end:l},g)?(c.renderEventResize({start:k,end:l},a),d.hideEvent(g)):(l=null,X())},cellOut:function(){l=
null;c.destroyEventResize();d.showEvent(g);K()},dragStop:function(a){c.isResizingSeg=!1;c.destroyEventResize();d.showEvent(g);K();d.trigger("eventResizeStop",f[0],g,a,{});l&&d.reportEventResize(g,l,f,a)}})).mousedown(b)},renderEventResize:function(a,b){},destroyEventResize:function(){},getEventTimeText:function(a,b){b=b||this.eventTimeFormat;return a.end&&this.displayEventEnd?this.view.formatRange(a,b):a.start.format(b)},getSegClasses:function(a,b,c){var d=a.event;a=["fc-event",a.isStart?"fc-start":
"fc-not-start",a.isEnd?"fc-end":"fc-not-end"].concat(d.className,d.source?d.source.className:[]);b&&a.push("fc-draggable");c&&a.push("fc-resizable");return a},getEventSkinCss:function(a){var b=this.view,c=a.source||{},d=a.color,e=c.color,f=b.opt("eventColor"),g=a.backgroundColor||d||c.backgroundColor||e||b.opt("eventBackgroundColor")||f,d=a.borderColor||d||c.borderColor||e||b.opt("eventBorderColor")||f;a=a.textColor||c.textColor||b.opt("eventTextColor");b=[];g&&b.push("background-color:"+g);d&&b.push("border-color:"+
d);a&&b.push("color:"+a);return b.join(";")},eventsToSegs:function(a,b){var c=this.eventsToRanges(a),d=[],e;for(e=0;e<c.length;e++)d.push.apply(d,this.eventRangeToSegs(c[e],b));return d},eventsToRanges:function(a){var b=this;a=Ya(a);var c=[];g.each(a,function(a,e){e.length&&c.push.apply(c,"inverse-background"===Ia(e[0])?b.eventsToInverseRanges(e):b.eventsToNormalRanges(e))});return c},eventsToNormalRanges:function(a){var b=this.view.calendar,c=[],d,e,f,g;for(d=0;d<a.length;d++)e=a[d],f=e.start.clone().stripZone(),
g=b.getEventEnd(e).stripZone(),c.push({event:e,start:f,end:g,eventStartMS:+f,eventDurationMS:g-f});return c},eventsToInverseRanges:function(a){var b=this.view,c=b.start.clone().stripZone(),b=b.end.clone().stripZone(),d=this.eventsToNormalRanges(a),e=[];a=a[0];var f,g;d.sort(Za);for(f=0;f<d.length;f++)g=d[f],g.start>c&&e.push({event:a,start:c,end:g.start}),c=g.end;c<b&&e.push({event:a,start:c,end:b});return e},eventRangeToSegs:function(a,b){var c,d,e;c=b?b(a):this.rangeToSegs(a);for(d=0;d<c.length;d++)e=
c[d],e.event=a.event,e.eventStartMS=a.eventStartMS,e.eventDurationMS=a.eventDurationMS;return c}});p.compareSegs=aa;p.dataAttrPrefix="";var da=H.extend({numbersVisible:!1,bottomCoordPadding:0,breakOnWeeks:null,cellDates:null,dayToCellOffsets:null,rowEls:null,dayEls:null,helperEls:null,render:function(a){var b=this.view,c=this.rowCnt,d=c*this.colCnt,e="",f;for(f=0;f<c;f++)e+=this.dayRowHtml(f,a);this.el.html(e);this.rowEls=this.el.find(".fc-row");this.dayEls=this.el.find(".fc-day");for(a=0;a<d;a++)c=
this.getCell(a),b.trigger("dayRender",null,c.start,this.dayEls.eq(a));H.prototype.render.call(this)},destroy:function(){this.destroySegPopover();H.prototype.destroy.call(this)},dayRowHtml:function(a,b){var c=["fc-row","fc-week",this.view.widgetContentClass];b&&c.push("fc-rigid");return'<div class="'+c.join(" ")+'"><div class="fc-bg"><table>'+this.rowHtml("day",a)+'</table></div><div class="fc-content-skeleton"><table>'+(this.numbersVisible?"<thead>"+this.rowHtml("number",a)+"</thead>":"")+"</table></div></div>"},
dayCellHtml:function(a){return this.bgCellHtml(a)},computeColHeadFormat:function(){return 1<this.rowCnt?"ddd":1<this.colCnt?this.view.opt("dayOfMonthFormat"):"dddd"},computeEventTimeFormat:function(){return this.view.opt("extraSmallTimeFormat")},computeDisplayEventEnd:function(){return 1==this.colCnt},updateCells:function(){var a,b,c;this.updateCellDates();a=this.cellDates;if(this.breakOnWeeks){b=a[0].day();for(c=1;c<a.length&&a[c].day()!=b;c++);b=Math.ceil(a.length/c)}else b=1,c=a.length;this.rowCnt=
b;this.colCnt=c},updateCellDates:function(){for(var a=this.view,b=this.start.clone(),c=[],d=-1,e=[];b.isBefore(this.end);)a.isHiddenDay(b)?e.push(d+.5):(d++,e.push(d),c.push(b.clone())),b.add(1,"days");this.cellDates=c;this.dayToCellOffsets=e},computeCellRange:function(a){var b=this.colCnt;a=this.cellDates[a.row*b+(this.isRTL?b-a.col-1:a.col)].clone();b=a.clone().add(1,"day");return{start:a,end:b}},getRowEl:function(a){return this.rowEls.eq(a)},getColEl:function(a){return this.dayEls.eq(a)},getCellDayEl:function(a){return this.dayEls.eq(a.row*
this.colCnt+a.col)},computeRowCoords:function(){var a=H.prototype.computeRowCoords.call(this);a[a.length-1].bottom+=this.bottomCoordPadding;return a},rangeToSegs:function(a){var b=this.isRTL,c=this.rowCnt,d=this.colCnt,e=[],f,g,k,q,l,n,x;a=this.view.computeDayRange(a);f=this.dateToCellOffset(a.start);a=this.dateToCellOffset(a.end.subtract(1,"days"));for(g=0;g<c;g++)k=g*d,q=k+d-1,x=Math.max(k,f),q=Math.min(q,a),x=Math.ceil(x),q=Math.floor(q),x<=q&&(l=x===f,n=q===a,x-=k,q-=k,k={row:g,isStart:l,isEnd:n},
b?(k.leftCol=d-q-1,k.rightCol=d-x-1):(k.leftCol=x,k.rightCol=q),e.push(k));return e},dateToCellOffset:function(a){var b=this.dayToCellOffsets;a=a.diff(this.start,"days");return 0>a?b[0]-1:a>=b.length?b[b.length-1]+1:b[a]},renderDrag:function(a,b){var c;this.renderHighlight(this.view.calendar.ensureVisibleEventRange(a));if(b&&!b.el.closest(this.el).length)return this.renderRangeHelper(a,b),c=this.view.opt("dragOpacity"),void 0!==c&&this.helperEls.css("opacity",c),!0},destroyDrag:function(){this.destroyHighlight();
this.destroyHelper()},renderEventResize:function(a,b){this.renderHighlight(a);this.renderRangeHelper(a,b)},destroyEventResize:function(){this.destroyHighlight();this.destroyHelper()},renderHelper:function(a,b){var c=[],d=this.eventsToSegs([a]),e,d=this.renderFgSegEls(d);e=this.renderSegRows(d);this.rowEls.each(function(a,d){var f=g(d),h=g('<div class="fc-helper-skeleton"><table/></div>'),l;l=b&&b.row===a?b.el.position().top:f.find(".fc-content-skeleton tbody").position().top;h.css("top",l).find("table").append(e[a].tbodyEl);
f.append(h);c.push(h[0])});this.helperEls=g(c)},destroyHelper:function(){this.helperEls&&(this.helperEls.remove(),this.helperEls=null)},fillSegTag:"td",renderFill:function(a,b){var c=[],d,e,f;b=this.renderFillSegEls(a,b);for(d=0;d<b.length;d++)e=b[d],f=this.renderFillRow(a,e),this.rowEls.eq(e.row).append(f),c.push(f[0]);this.elsByFill[a]=g(c);return b},renderFillRow:function(a,b){var c=this.colCnt,d=b.leftCol,e=b.rightCol+1,f,h;f=g('<div class="fc-'+a.toLowerCase()+'-skeleton"><table><tr/></table></div>');
h=f.find("tr");0<d&&h.append('<td colspan="'+d+'"/>');h.append(b.el.attr("colspan",e-d));e<c&&h.append('<td colspan="'+(c-e)+'"/>');this.bookendCells(h,a);return f}});da.mixin({rowStructs:null,destroyEvents:function(){this.destroySegPopover();H.prototype.destroyEvents.apply(this,arguments)},getEventSegs:function(){return H.prototype.getEventSegs.call(this).concat(this.popoverSegs||[])},renderBgSegs:function(a){a=g.grep(a,function(a){return a.event.allDay});return H.prototype.renderBgSegs.call(this,
a)},renderFgSegs:function(a){var b;a=this.renderFgSegEls(a);b=this.rowStructs=this.renderSegRows(a);this.rowEls.each(function(a,d){g(d).find(".fc-content-skeleton > table").append(b[a].tbodyEl)});return a},destroyFgSegs:function(){for(var a=this.rowStructs||[],b;b=a.pop();)b.tbodyEl.remove();this.rowStructs=null},renderSegRows:function(a){var b=[],c;a=this.groupSegRows(a);for(c=0;c<a.length;c++)b.push(this.renderSegRow(c,a[c]));return b},fgSegHtml:function(a,b){var c=this.view,d=a.event,e=c.isEventDraggable(d),
c=!b&&d.allDay&&a.isEnd&&c.isEventResizable(d),e=this.getSegClasses(a,e,c),f=this.getEventSkinCss(d),g="",k;e.unshift("fc-day-grid-event");!d.allDay&&a.isStart&&(g='<span class="fc-time">'+B(this.getEventTimeText(d))+"</span>");k='<span class="fc-title">'+(B(d.title||"")||"&nbsp;")+"</span>";return'<a class="'+e.join(" ")+'"'+(d.url?' href="'+B(d.url)+'"':"")+(f?' style="'+f+'"':"")+'><div class="fc-content">'+(this.isRTL?k+" "+g:g+" "+k)+"</div>"+(c?'<div class="fc-resizer"/>':"")+"</a>"},renderSegRow:function(a,
b){function c(a){for(;p<a;)(w=(l[n-1]||[])[p])?w.attr("rowspan",parseInt(w.attr("rowspan")||1,10)+1):(w=g("<td/>"),m.append(w)),q[n][p]=w,l[n][p]=w,p++}var d=this.colCnt,e=this.buildSegLevels(b),f=Math.max(1,e.length),h=g("<tbody/>"),k=[],q=[],l=[],n,x,p,m,r,t,w;for(n=0;n<f;n++){x=e[n];p=0;m=g("<tr/>");k.push([]);q.push([]);l.push([]);if(x)for(r=0;r<x.length;r++){t=x[r];c(t.leftCol);w=g('<td class="fc-event-container"/>').append(t.el);for(t.leftCol!=t.rightCol?w.attr("colspan",t.rightCol-t.leftCol+
1):l[n][p]=w;p<=t.rightCol;)q[n][p]=w,k[n][p]=t,p++;m.append(w)}c(d);this.bookendCells(m,"eventSkeleton");h.append(m)}return{row:a,tbodyEl:h,cellMatrix:q,segMatrix:k,segLevels:e,segs:b}},buildSegLevels:function(a){var b=[],c,d,e;a.sort(aa);for(c=0;c<a.length;c++){d=a[c];for(e=0;e<b.length;e++){var f;a:{var g,k=b[e];for(g=0;g<k.length;g++)if(f=k[g],f.leftCol<=d.rightCol&&f.rightCol>=d.leftCol){f=!0;break a}f=!1}if(!f)break}d.level=e;(b[e]||(b[e]=[])).push(d)}for(e=0;e<b.length;e++)b[e].sort(ab);return b},
groupSegRows:function(a){var b=[],c;for(c=0;c<this.rowCnt;c++)b.push([]);for(c=0;c<a.length;c++)b[a[c].row].push(a[c]);return b}});da.mixin({segPopover:null,popoverSegs:null,destroySegPopover:function(){this.segPopover&&this.segPopover.hide()},limitRows:function(a){var b=this.rowStructs||[],c,d;for(c=0;c<b.length;c++)this.unlimitRow(c),d=a?"number"===typeof a?a:this.computeRowLevelLimit(c):!1,!1!==d&&this.limitRow(c,d)},computeRowLevelLimit:function(a){var b=this.rowEls.eq(a).height();a=this.rowStructs[a].tbodyEl.children();
var c,d;for(c=0;c<a.length;c++)if(d=a.eq(c).removeClass("fc-limited"),d.position().top+d.outerHeight()>b)return c;return!1},limitRow:function(a,b){function c(c){for(;h<c;)k=d.getCell(a,h),m=d.getCellSegs(k,b),m.length&&(w=l[b-1][h],D=d.renderMoreLink(k,m),u=g("<div/>").append(D),w.append(u),f.push(u[0])),h++}var d=this,e=this.rowStructs[a],f=[],h=0,k,q,l,n,p,t,m,r,y,w,B,A,C,u,D;if(b&&b<e.segLevels.length){q=e.segLevels[b-1];l=e.cellMatrix;n=e.tbodyEl.children().slice(b).addClass("fc-limited").get();
for(p=0;p<q.length;p++){t=q[p];c(t.leftCol);y=[];for(r=0;h<=t.rightCol;)k=this.getCell(a,h),m=this.getCellSegs(k,b),y.push(m),r+=m.length,h++;if(r){w=l[b-1][t.leftCol];r=w.attr("rowspan")||1;B=[];for(A=0;A<y.length;A++)C=g('<td class="fc-more-cell"/>').attr("rowspan",r),m=y[A],k=this.getCell(a,t.leftCol+A),D=this.renderMoreLink(k,[t].concat(m)),u=g("<div/>").append(D),C.append(u),B.push(C[0]),f.push(C[0]);w.addClass("fc-limited").after(g(B));n.push(w[0])}}c(this.colCnt);e.moreEls=g(f);e.limitedEls=
g(n)}},unlimitRow:function(a){a=this.rowStructs[a];a.moreEls&&(a.moreEls.remove(),a.moreEls=null);a.limitedEls&&(a.limitedEls.removeClass("fc-limited"),a.limitedEls=null)},renderMoreLink:function(a,b){var c=this,d=this.view;return g('<a class="fc-more"/>').text(this.getMoreLinkText(b.length)).on("click",function(e){var f=d.opt("eventLimitClick"),h=a.start,k=g(this),n=c.getCellDayEl(a),l=c.getCellSegs(a),l=c.resliceDaySegs(l,h),p=c.resliceDaySegs(b,h);"function"===typeof f&&(f=d.trigger("eventLimitClick",
null,{date:h,dayEl:n,moreEl:k,segs:l,hiddenSegs:p},e));"popover"===f?c.showSegPopover(a,k,l):"string"===typeof f&&d.calendar.zoomTo(h,f)})},showSegPopover:function(a,b,c){var d=this,e=this.view;b=b.parent();var f;f=1==this.rowCnt?e.el:this.rowEls.eq(a.row);a={className:"fc-more-popover",content:this.renderSegPopoverContent(a,c),parentEl:this.el,top:f.offset().top,autoHide:!0,viewportConstrain:e.opt("popoverViewportConstrain"),hide:function(){d.segPopover.destroy();d.segPopover=null;d.popoverSegs=
null}};this.isRTL?a.right=b.offset().left+b.outerWidth()+1:a.left=b.offset().left-1;this.segPopover=new mb(a);this.segPopover.show()},renderSegPopoverContent:function(a,b){var c=this.view,d=c.opt("theme"),e=a.start.format(c.opt("dayPopoverFormat")),c=g('<div class="fc-header '+c.widgetHeaderClass+'"><span class="fc-close '+(d?"ui-icon ui-icon-closethick":"fc-icon fc-icon-x")+'"></span><span class="fc-title">'+B(e)+'</span><div class="fc-clear"/></div><div class="fc-body '+c.widgetContentClass+'"><div class="fc-event-container"></div></div>'),
d=c.find(".fc-event-container");this.popoverSegs=b=this.renderFgSegEls(b,!0);for(e=0;e<b.length;e++)b[e].cell=a,d.append(b[e].el);return c},resliceDaySegs:function(a,b){var c=g.map(a,function(a){return a.event}),d=b.clone().stripTime(),e=d.clone().add(1,"days"),f={start:d,end:e};return this.eventsToSegs(c,function(a){return(a=fa(a,f))?[a]:[]})},getMoreLinkText:function(a){var b=this.view.opt("eventLimitText");return"function"===typeof b?b(a):"+"+a+" "+b},getCellSegs:function(a,b){for(var c=this.rowStructs[a.row].segMatrix,
d=b||0,e=[],f;d<c.length;)(f=c[d][a.col])&&e.push(f),d++;return e}});var Ra=H.extend({slotDuration:null,snapDuration:null,minTime:null,maxTime:null,axisFormat:null,dayEls:null,slatEls:null,slatTops:null,helperEl:null,businessHourSegs:null,constructor:function(){H.apply(this,arguments);this.processOptions()},render:function(){this.el.html(this.renderHtml());this.dayEls=this.el.find(".fc-day");this.slatEls=this.el.find(".fc-slats tr");this.computeSlatTops();this.renderBusinessHours();H.prototype.render.call(this)},
renderBusinessHours:function(){var a=this.view.calendar.getBusinessHoursEvents();this.businessHourSegs=this.renderFill("businessHours",this.eventsToSegs(a),"bgevent")},renderHtml:function(){return'<div class="fc-bg"><table>'+this.rowHtml("slotBg")+'</table></div><div class="fc-slats"><table>'+this.slatRowHtml()+"</table></div>"},slotBgCellHtml:function(a){return this.bgCellHtml(a)},slatRowHtml:function(){for(var a=this.view,b=this.isRTL,c="",d=0===this.slotDuration.asMinutes()%15,e=n.duration(+this.minTime),
f,g;e<this.maxTime;)f=this.start.clone().time(e),g=f.minutes(),f='<td class="fc-axis fc-time '+a.widgetContentClass+'" '+a.axisStyleAttr()+">"+(d&&g?"":"<span>"+B(f.format(this.axisFormat))+"</span>")+"</td>",c+="<tr "+(g?'class="fc-minor"':"")+">"+(b?"":f)+'<td class="'+a.widgetContentClass+'"/>'+(b?f:"")+"</tr>",e.add(this.slotDuration);return c},processOptions:function(){var a=this.view,b=a.opt("slotDuration"),c=a.opt("snapDuration"),b=n.duration(b),c=c?n.duration(c):b;this.slotDuration=b;this.snapDuration=
c;this.minTime=n.duration(a.opt("minTime"));this.maxTime=n.duration(a.opt("maxTime"));this.axisFormat=a.opt("axisFormat")||a.opt("smallTimeFormat")},computeColHeadFormat:function(){return 1<this.colCnt?this.view.opt("dayOfMonthFormat"):"dddd"},computeEventTimeFormat:function(){return this.view.opt("noMeridiemTimeFormat")},computeDisplayEventEnd:function(){return!0},updateCells:function(){var a=this.view,b=[],c;for(c=this.start.clone();c.isBefore(this.end);)b.push({day:c.clone()}),c.add(1,"day"),c=
a.skipHiddenDays(c);this.isRTL&&b.reverse();this.colData=b;this.colCnt=b.length;this.rowCnt=Math.ceil((this.maxTime-this.minTime)/this.snapDuration)},computeCellRange:function(a){var b=this.computeSnapTime(a.row);a=this.view.calendar.rezoneDate(a.day).time(b);b=a.clone().add(this.snapDuration);return{start:a,end:b}},getColEl:function(a){return this.dayEls.eq(a)},computeSnapTime:function(a){return n.duration(this.minTime+this.snapDuration*a)},rangeToSegs:function(a){var b=this.colCnt,c=[],d,e;a={start:a.start.clone().stripZone(),
end:a.end.clone().stripZone()};for(e=0;e<b;e++)if(d=this.colData[e].day,d={start:d.clone().time(this.minTime),end:d.clone().time(this.maxTime)},d=fa(a,d))d.col=e,c.push(d);return c},resize:function(){this.computeSlatTops();this.updateSegVerticals()},computeRowCoords:function(){var a=this.el.offset().top,b=[],c,d;for(c=0;c<this.rowCnt;c++)d={top:a+this.computeTimeTop(this.computeSnapTime(c))},0<c&&(b[c-1].bottom=d.top),b.push(d);d.bottom=d.top+this.computeTimeTop(this.computeSnapTime(c));return b},
computeDateTop:function(a,b){return this.computeTimeTop(n.duration(a.clone().stripZone()-b.clone().stripTime()))},computeTimeTop:function(a){var b=(a-this.minTime)/this.slotDuration,c,b=Math.max(0,b),b=Math.min(this.slatEls.length,b);a=Math.floor(b);b-=a;c=this.slatTops[a];return b?(a=this.slatTops[a+1],c+(a-c)*b):c},computeSlatTops:function(){var a=[],b;this.slatEls.each(function(c,d){b=g(d).position().top;a.push(b)});a.push(b+this.slatEls.last().outerHeight());this.slatTops=a},renderDrag:function(a,
b){var c;if(b)return this.renderRangeHelper(a,b),c=this.view.opt("dragOpacity"),void 0!==c&&this.helperEl.css("opacity",c),!0;this.renderHighlight(this.view.calendar.ensureVisibleEventRange(a))},destroyDrag:function(){this.destroyHelper();this.destroyHighlight()},renderEventResize:function(a,b){this.renderRangeHelper(a,b)},destroyEventResize:function(){this.destroyHelper()},renderHelper:function(a,b){var c=this.eventsToSegs([a]),d,e,f,h,c=this.renderFgSegEls(c);d=this.renderSegTable(c);for(e=0;e<
c.length;e++)f=c[e],b&&b.col===f.col&&(h=b.el,f.el.css({left:h.css("left"),right:h.css("right"),"margin-left":h.css("margin-left"),"margin-right":h.css("margin-right")}));this.helperEl=g('<div class="fc-helper-skeleton"/>').append(d).appendTo(this.el)},destroyHelper:function(){this.helperEl&&(this.helperEl.remove(),this.helperEl=null)},renderSelection:function(a){this.view.opt("selectHelper")?this.renderRangeHelper(a):this.renderHighlight(a)},destroySelection:function(){this.destroyHelper();this.destroyHighlight()},
renderFill:function(a,b,c){var d,e,f,h,k,n,l,p,t;if(b.length){b=this.renderFillSegEls(a,b);d=this.groupSegCols(b);c=c||a.toLowerCase();e=g('<div class="fc-'+c+'-skeleton"><table><tr/></table></div>');f=e.find("tr");for(h=0;h<d.length;h++)if(k=d[h],n=g("<td/>").appendTo(f),k.length)for(n=g('<div class="fc-'+c+'-container"/>').appendTo(n),l=this.colData[h].day,p=0;p<k.length;p++)t=k[p],n.append(t.el.css({top:this.computeDateTop(t.start,l),bottom:-this.computeDateTop(t.end,l)}));this.bookendCells(f,
a);this.el.append(e);this.elsByFill[a]=e}return b}});Ra.mixin({eventSkeletonEl:null,renderFgSegs:function(a){a=this.renderFgSegEls(a);this.el.append(this.eventSkeletonEl=g('<div class="fc-content-skeleton"/>').append(this.renderSegTable(a)));return a},destroyFgSegs:function(a){this.eventSkeletonEl&&(this.eventSkeletonEl.remove(),this.eventSkeletonEl=null)},renderSegTable:function(a){var b=g("<table><tr/></table>"),c=b.find("tr"),d,e,f,h,k;d=this.groupSegCols(a);this.computeSegVerticals(a);for(a=0;a<
d.length;a++){e=h=d[a];e.sort(aa);var n=e,l=[];for(k=0;k<n.length;k++){f=n[k];for(e=0;e<l.length&&Ka(f,l[e]).length;e++);f.level=e;(l[e]||(l[e]=[])).push(f)}e=l;var p,t=e;for(p=0;p<t.length;p++)for(l=t[p],n=0;n<l.length;n++)for(k=l[n],k.forwardSegs=[],f=p+1;f<t.length;f++)Ka(k,t[f],k.forwardSegs);if(f=e[0]){for(e=0;e<f.length;e++)Ja(f[e]);for(e=0;e<f.length;e++)na(f[e],0,0)}k=g('<div class="fc-event-container"/>');for(e=0;e<h.length;e++)f=h[e],f.el.css(this.generateSegPositionCss(f)),30>f.bottom-
f.top&&f.el.addClass("fc-short"),k.append(f.el);c.append(g("<td/>").append(k))}this.bookendCells(c,"eventSkeleton");return b},updateSegVerticals:function(){var a=(this.segs||[]).concat(this.businessHourSegs||[]),b;this.computeSegVerticals(a);for(b=0;b<a.length;b++)a[b].el.css(this.generateSegVerticalCss(a[b]))},computeSegVerticals:function(a){var b,c;for(b=0;b<a.length;b++)c=a[b],c.top=this.computeDateTop(c.start,c.start),c.bottom=this.computeDateTop(c.end,c.start)},fgSegHtml:function(a,b){var c=
this.view,d=a.event,e=c.isEventDraggable(d),f=!b&&a.isEnd&&c.isEventResizable(d),e=this.getSegClasses(a,e,f),g=this.getEventSkinCss(d),k,n,l;e.unshift("fc-time-grid-event");if(c.isMultiDayEvent(d)){if(a.isStart||a.isEnd)k=this.getEventTimeText(a),n=this.getEventTimeText(a,"LT"),l=this.getEventTimeText({start:a.start})}else k=this.getEventTimeText(d),n=this.getEventTimeText(d,"LT"),l=this.getEventTimeText({start:d.start});return'<a class="'+e.join(" ")+'"'+(d.url?' href="'+B(d.url)+'"':"")+(g?' style="'+
g+'"':"")+'><div class="fc-content">'+(k?'<div class="fc-time" data-start="'+B(l)+'" data-full="'+B(n)+'"><span>'+B(k)+"</span></div>":"")+(d.title?'<div class="fc-title">'+B(d.title)+"</div>":"")+'</div><div class="fc-bg"/>'+(f?'<div class="fc-resizer"/>':"")+"</a>"},generateSegPositionCss:function(a){var b=this.view.opt("slotEventOverlap"),c=a.backwardCoord,d=a.forwardCoord,e=this.generateSegVerticalCss(a),f;b&&(d=Math.min(1,c+2*(d-c)));this.isRTL?f=1-d:(f=c,c=1-d);e.zIndex=a.level+1;e.left=100*
f+"%";e.right=100*c+"%";b&&a.forwardPressure&&(e[this.isRTL?"marginLeft":"marginRight"]=20);return e},generateSegVerticalCss:function(a){return{top:a.top,bottom:-a.bottom}},groupSegCols:function(a){var b=[],c;for(c=0;c<this.colCnt;c++)b.push([]);for(c=0;c<a.length;c++)b[a[c].col].push(a[c]);return b}});var Q=p.View=E.extend({type:null,name:null,calendar:null,options:null,coordMap:null,el:null,start:null,end:null,intervalStart:null,intervalEnd:null,intervalDuration:null,intervalUnit:null,isSelected:!1,
scrollerEl:null,scrollTop:null,widgetHeaderClass:null,widgetContentClass:null,highlightStateClass:null,nextDayThreshold:null,isHiddenDayHash:null,documentMousedownProxy:null,constructor:function(a,b,c){this.calendar=a;this.options=b;this.type=this.name=c;this.nextDayThreshold=n.duration(this.opt("nextDayThreshold"));this.initTheming();this.initHiddenDays();this.documentMousedownProxy=g.proxy(this,"documentMousedown");this.initialize()},initialize:function(){},opt:function(a){var b;b=this.options[a];
if(void 0!==b)return b;b=this.calendar.options[a];return g.isPlainObject(b)&&!/(Time|Duration)$/.test(a)?V(b,this.type):b},trigger:function(a,b){var c=this.calendar;return c.trigger.apply(c,[a,b||this].concat(Array.prototype.slice.call(arguments,2),[this]))},setDate:function(a){this.setRange(this.computeRange(a))},setRange:function(a){g.extend(this,a)},computeRange:function(a){var b=n.duration(this.opt("duration")||this.constructor.duration||{days:1}),c=ua(b);a=a.clone().startOf(c);var d=a.clone().add(b),
e,f;ga("days",b)?(a.stripTime(),d.stripTime()):(a.hasTime()||(a=this.calendar.rezoneDate(a)),d.hasTime()||(d=this.calendar.rezoneDate(d)));e=a.clone();e=this.skipHiddenDays(e);f=d.clone();f=this.skipHiddenDays(f,-1,!0);return{intervalDuration:b,intervalUnit:c,intervalStart:a,intervalEnd:d,start:e,end:f}},computePrevDate:function(a){return this.skipHiddenDays(a.clone().startOf(this.intervalUnit).subtract(this.intervalDuration),-1)},computeNextDate:function(a){return this.skipHiddenDays(a.clone().startOf(this.intervalUnit).add(this.intervalDuration))},
computeTitle:function(){return this.formatRange({start:this.intervalStart,end:this.intervalEnd},this.opt("titleFormat")||this.computeTitleFormat(),this.opt("titleRangeSeparator"))},computeTitleFormat:function(){return"year"==this.intervalUnit?"YYYY":"month"==this.intervalUnit?this.opt("monthYearFormat"):1<this.intervalDuration.as("days")?"ll":"LL"},formatRange:function(a,b,c){var d=a.end;d.hasTime()||(d=d.clone().subtract(1));return Da(a.start,d,b,c,this.opt("isRTL"))},renderView:function(){this.render();
this.updateSize();this.initializeScroll();this.trigger("viewRender",this,this,this.el);g(document).on("mousedown",this.documentMousedownProxy)},render:function(){},destroyView:function(){this.unselect();this.destroyViewEvents();this.destroy();this.trigger("viewDestroy",this,this,this.el);g(document).off("mousedown",this.documentMousedownProxy)},destroy:function(){this.el.empty()},initTheming:function(){var a=this.opt("theme")?"ui":"fc";this.widgetHeaderClass=a+"-widget-header";this.widgetContentClass=
a+"-widget-content";this.highlightStateClass=a+"-state-highlight"},updateSize:function(a){a&&this.recordScroll();this.updateHeight();this.updateWidth()},updateWidth:function(){},updateHeight:function(){var a=this.calendar;this.setHeight(a.getSuggestedViewHeight(),a.isHeightAuto())},setHeight:function(a,b){},computeScrollerHeight:function(a,b){var c,d;b=b||this.scrollerEl;c=this.el.add(b);c.css({position:"relative",left:-1});d=this.el.outerHeight()-b.height();c.css({position:"",left:""});return a-
d},initializeScroll:function(){},recordScroll:function(){this.scrollerEl&&(this.scrollTop=this.scrollerEl.scrollTop())},restoreScroll:function(){null!==this.scrollTop&&this.scrollerEl.scrollTop(this.scrollTop)},renderViewEvents:function(a){this.renderEvents(a);this.eventSegEach(function(a){this.trigger("eventAfterRender",a.event,a.event,a.el)});this.trigger("eventAfterAllRender")},renderEvents:function(){},destroyViewEvents:function(){this.eventSegEach(function(a){this.trigger("eventDestroy",a.event,
a.event,a.el)});this.destroyEvents()},destroyEvents:function(){},resolveEventEl:function(a,b){var c=this.trigger("eventRender",a,a,b);!1===c?b=null:c&&!0!==c&&(b=g(c));return b},showEvent:function(a){this.eventSegEach(function(a){a.el.css("visibility","")},a)},hideEvent:function(a){this.eventSegEach(function(a){a.el.css("visibility","hidden")},a)},eventSegEach:function(a,b){var c=this.getEventSegs(),d;for(d=0;d<c.length;d++)b&&c[d].event._id!==b._id||a.call(this,c[d])},getEventSegs:function(){return[]},
isEventDraggable:function(a){var b=a.source||{};return N(a.startEditable,b.startEditable,this.opt("eventStartEditable"),a.editable,b.editable,this.opt("editable"))},reportEventDrop:function(a,b,c,d){var e=this.calendar,f=e.mutateEvent(a,b);this.triggerEventDrop(a,f.dateDelta,function(){f.undo();e.reportEventChange()},c,d);e.reportEventChange()},triggerEventDrop:function(a,b,c,d,e){this.trigger("eventDrop",d[0],a,b,c,e,{})},reportExternalDrop:function(a,b,c,d,e){var f=a.eventProps,h;f&&(f=g.extend({},
f,b),h=this.calendar.renderEvent(f,a.stick)[0]);this.triggerExternalDrop(h,b,c,d,e)},triggerExternalDrop:function(a,b,c,d,e){this.trigger("drop",c[0],b.start,d,e);a&&this.trigger("eventReceive",null,a)},renderDrag:function(a,b){},destroyDrag:function(){},isEventResizable:function(a){var b=a.source||{};return N(a.durationEditable,b.durationEditable,this.opt("eventDurationEditable"),a.editable,b.editable,this.opt("editable"))},reportEventResize:function(a,b,c,d){var e=this.calendar,f=e.mutateEvent(a,
{end:b});this.triggerEventResize(a,f.durationDelta,function(){f.undo();e.reportEventChange()},c,d);e.reportEventChange()},triggerEventResize:function(a,b,c,d,e){this.trigger("eventResize",d[0],a,b,c,e,{})},select:function(a,b){this.unselect(b);this.renderSelection(a);this.reportSelection(a,b)},renderSelection:function(a){},reportSelection:function(a,b){this.isSelected=!0;this.trigger("select",null,a.start,a.end,b)},unselect:function(a){this.isSelected&&(this.isSelected=!1,this.destroySelection(),
this.trigger("unselect",null,a))},destroySelection:function(){},documentMousedown:function(a){var b;this.isSelected&&this.opt("unselectAuto")&&1==a.which&&!a.ctrlKey&&((b=this.opt("unselectCancel"))&&g(a.target).closest(b).length||this.unselect(a))},initHiddenDays:function(){var a=this.opt("hiddenDays")||[],b=[],c=0,d;!1===this.opt("weekends")&&a.push(0,6);for(d=0;7>d;d++)(b[d]=-1!==g.inArray(d,a))||c++;if(!c)throw"invalid hiddenDays";this.isHiddenDayHash=b},isHiddenDay:function(a){n.isMoment(a)&&
(a=a.day());return this.isHiddenDayHash[a]},skipHiddenDays:function(a,b,c){a=a.clone();for(b=b||1;this.isHiddenDayHash[(a.day()+(c?b:0)+7)%7];)a.add(b,"days");return a},computeDayRange:function(a){var b=a.start.clone().stripTime();a=a.end;var c=null,d;a&&(c=a.clone().stripTime(),(d=+a.time())&&d>=this.nextDayThreshold&&c.add(1,"days"));if(!a||c<=b)c=b.clone().add(1,"days");return{start:b,end:c}},isMultiDayEvent:function(a){a=this.computeDayRange(a);return 1<a.end.diff(a.start,"days")}});p.sourceNormalizers=
[];p.sourceFetchers=[];var ib={dataType:"json",cache:!1},jb=1,Sa=P.basic=Q.extend({dayGrid:null,dayNumbersVisible:!1,weekNumbersVisible:!1,weekNumberWidth:null,headRowEl:null,initialize:function(){this.dayGrid=new da(this);this.coordMap=this.dayGrid.coordMap},setRange:function(a){Q.prototype.setRange.call(this,a);this.dayGrid.breakOnWeeks=/year|month|week/.test(this.intervalUnit);this.dayGrid.setRange(a)},computeRange:function(a){a=Q.prototype.computeRange.call(this,a);/year|month/.test(a.intervalUnit)&&
(a.start.startOf("week"),a.start=this.skipHiddenDays(a.start),a.end.weekday()&&(a.end.add(1,"week").startOf("week"),a.end=this.skipHiddenDays(a.end,-1,!0)));return a},render:function(){this.dayNumbersVisible=1<this.dayGrid.rowCnt;this.weekNumbersVisible=this.opt("weekNumbers");this.dayGrid.numbersVisible=this.dayNumbersVisible||this.weekNumbersVisible;this.el.addClass("fc-basic-view").html(this.renderHtml());this.headRowEl=this.el.find("thead .fc-row");this.scrollerEl=this.el.find(".fc-day-grid-container");
this.dayGrid.coordMap.containerEl=this.scrollerEl;this.dayGrid.el=this.el.find(".fc-day-grid");this.dayGrid.render(this.hasRigidRows())},destroy:function(){this.dayGrid.destroy();Q.prototype.destroy.call(this)},renderHtml:function(){return'<table><thead><tr><td class="'+this.widgetHeaderClass+'">'+this.dayGrid.headHtml()+'</td></tr></thead><tbody><tr><td class="'+this.widgetContentClass+'"><div class="fc-day-grid-container"><div class="fc-day-grid"/></div></td></tr></tbody></table>'},headIntroHtml:function(){if(this.weekNumbersVisible)return'<th class="fc-week-number '+
this.widgetHeaderClass+'" '+this.weekNumberStyleAttr()+"><span>"+B(this.opt("weekNumberTitle"))+"</span></th>"},numberIntroHtml:function(a){if(this.weekNumbersVisible)return'<td class="fc-week-number" '+this.weekNumberStyleAttr()+"><span>"+this.calendar.calculateWeekNumber(this.dayGrid.getCell(a,0).start)+"</span></td>"},dayIntroHtml:function(){if(this.weekNumbersVisible)return'<td class="fc-week-number '+this.widgetContentClass+'" '+this.weekNumberStyleAttr()+"></td>"},introHtml:function(){if(this.weekNumbersVisible)return'<td class="fc-week-number" '+
this.weekNumberStyleAttr()+"></td>"},numberCellHtml:function(a){a=a.start;var b;if(!this.dayNumbersVisible)return"<td/>";b=this.dayGrid.getDayClasses(a);b.unshift("fc-day-number");return'<td class="'+b.join(" ")+'" data-date="'+a.format()+'">'+a.date()+"</td>"},weekNumberStyleAttr:function(){return null!==this.weekNumberWidth?'style="width:'+this.weekNumberWidth+'px"':""},hasRigidRows:function(){var a=this.opt("eventLimit");return a&&"number"!==typeof a},updateWidth:function(){this.weekNumbersVisible&&
(this.weekNumberWidth=qa(this.el.find(".fc-week-number")))},setHeight:function(a,b){var c=this.opt("eventLimit"),d;ea(this.scrollerEl);U(this.headRowEl);this.dayGrid.destroySegPopover();c&&"number"===typeof c&&this.dayGrid.limitRows(c);d=this.computeScrollerHeight(a);this.setGridHeight(d,b);c&&"number"!==typeof c&&this.dayGrid.limitRows(c);!b&&ra(this.scrollerEl,d)&&(A(this.headRowEl,ta(this.scrollerEl)),d=this.computeScrollerHeight(a),this.scrollerEl.height(d),this.restoreScroll())},setGridHeight:function(a,
b){b?this.dayGrid.rowEls.height(""):pa(this.dayGrid.rowEls,a,!0)},renderEvents:function(a){this.dayGrid.renderEvents(a);this.updateHeight()},getEventSegs:function(){return this.dayGrid.getEventSegs()},destroyEvents:function(){this.recordScroll();this.dayGrid.destroyEvents()},renderDrag:function(a,b){return this.dayGrid.renderDrag(a,b)},destroyDrag:function(){this.dayGrid.destroyDrag()},renderSelection:function(a){this.dayGrid.renderSelection(a)},destroySelection:function(){this.dayGrid.destroySelection()}});
t(R,{fixedWeekCount:!0});(P.month=Sa.extend({computeRange:function(a){a=Sa.prototype.computeRange.call(this,a);this.isFixedWeeks()&&a.end.add(6-a.end.diff(a.start,"weeks"),"weeks");return a},setGridHeight:function(a,b){(b=b||"variable"===this.opt("weekMode"))&&(a*=this.rowCnt/6);pa(this.dayGrid.rowEls,a,!b)},isFixedWeeks:function(){var a=this.opt("weekMode");return a?"fixed"===a:this.opt("fixedWeekCount")}})).duration={months:1};P.basicWeek={type:"basic",duration:{weeks:1}};P.basicDay={type:"basic",
duration:{days:1}};t(R,{allDaySlot:!0,allDayText:"all-day",scrollTime:"06:00:00",slotDuration:"00:30:00",minTime:"00:00:00",maxTime:"24:00:00",slotEventOverlap:!0});P.agenda=Q.extend({timeGrid:null,dayGrid:null,axisWidth:null,noScrollRowEls:null,bottomRuleEl:null,bottomRuleHeight:null,initialize:function(){this.timeGrid=new Ra(this);this.opt("allDaySlot")?(this.dayGrid=new da(this),this.coordMap=new ob([this.dayGrid.coordMap,this.timeGrid.coordMap])):this.coordMap=this.timeGrid.coordMap},setRange:function(a){Q.prototype.setRange.call(this,
a);this.timeGrid.setRange(a);this.dayGrid&&this.dayGrid.setRange(a)},render:function(){this.el.addClass("fc-agenda-view").html(this.renderHtml());this.scrollerEl=this.el.find(".fc-time-grid-container");this.timeGrid.coordMap.containerEl=this.scrollerEl;this.timeGrid.el=this.el.find(".fc-time-grid");this.timeGrid.render();this.bottomRuleEl=g('<hr class="'+this.widgetHeaderClass+'"/>').appendTo(this.timeGrid.el);this.dayGrid&&(this.dayGrid.el=this.el.find(".fc-day-grid"),this.dayGrid.render(),this.dayGrid.bottomCoordPadding=
this.dayGrid.el.next("hr").outerHeight());this.noScrollRowEls=this.el.find(".fc-row:not(.fc-scroller *)")},destroy:function(){this.timeGrid.destroy();this.dayGrid&&this.dayGrid.destroy();Q.prototype.destroy.call(this)},renderHtml:function(){return'<table><thead><tr><td class="'+this.widgetHeaderClass+'">'+this.timeGrid.headHtml()+'</td></tr></thead><tbody><tr><td class="'+this.widgetContentClass+'">'+(this.dayGrid?'<div class="fc-day-grid"/><hr class="'+this.widgetHeaderClass+'"/>':"")+'<div class="fc-time-grid-container"><div class="fc-time-grid"/></div></td></tr></tbody></table>'},
headIntroHtml:function(){var a,b;return this.opt("weekNumbers")?(a=this.timeGrid.getCell(0).start,a=this.calendar.calculateWeekNumber(a),b=this.opt("weekNumberTitle"),a=this.opt("isRTL")?a+b:b+a,'<th class="fc-axis fc-week-number '+this.widgetHeaderClass+'" '+this.axisStyleAttr()+"><span>"+B(a)+"</span></th>"):'<th class="fc-axis '+this.widgetHeaderClass+'" '+this.axisStyleAttr()+"></th>"},dayIntroHtml:function(){return'<td class="fc-axis '+this.widgetContentClass+'" '+this.axisStyleAttr()+"><span>"+
(this.opt("allDayHtml")||B(this.opt("allDayText")))+"</span></td>"},slotBgIntroHtml:function(){return'<td class="fc-axis '+this.widgetContentClass+'" '+this.axisStyleAttr()+"></td>"},introHtml:function(){return'<td class="fc-axis" '+this.axisStyleAttr()+"></td>"},axisStyleAttr:function(){return null!==this.axisWidth?'style="width:'+this.axisWidth+'px"':""},updateSize:function(a){a&&this.timeGrid.resize();Q.prototype.updateSize.call(this,a)},updateWidth:function(){this.axisWidth=qa(this.el.find(".fc-axis"))},
setHeight:function(a,b){var c;null===this.bottomRuleHeight&&(this.bottomRuleHeight=this.bottomRuleEl.outerHeight());this.bottomRuleEl.hide();this.scrollerEl.css("overflow","");ea(this.scrollerEl);U(this.noScrollRowEls);this.dayGrid&&(this.dayGrid.destroySegPopover(),(c=this.opt("eventLimit"))&&"number"!==typeof c&&(c=5),c&&this.dayGrid.limitRows(c));b||(c=this.computeScrollerHeight(a),ra(this.scrollerEl,c)?(A(this.noScrollRowEls,ta(this.scrollerEl)),c=this.computeScrollerHeight(a),this.scrollerEl.height(c),
this.restoreScroll()):(this.scrollerEl.height(c).css("overflow","hidden"),this.bottomRuleEl.show()))},initializeScroll:function(){function a(){b.scrollerEl.scrollTop(d)}var b=this,c=n.duration(this.opt("scrollTime")),d=this.timeGrid.computeTimeTop(c);(d=Math.ceil(d))&&d++;a();setTimeout(a,0)},renderEvents:function(a){var b=[],c=[],d;for(d=0;d<a.length;d++)a[d].allDay?b.push(a[d]):c.push(a[d]);this.timeGrid.renderEvents(c);this.dayGrid&&this.dayGrid.renderEvents(b);this.updateHeight()},getEventSegs:function(){return this.timeGrid.getEventSegs().concat(this.dayGrid?
this.dayGrid.getEventSegs():[])},destroyEvents:function(){this.recordScroll();this.timeGrid.destroyEvents();this.dayGrid&&this.dayGrid.destroyEvents()},renderDrag:function(a,b){if(a.start.hasTime())return this.timeGrid.renderDrag(a,b);if(this.dayGrid)return this.dayGrid.renderDrag(a,b)},destroyDrag:function(){this.timeGrid.destroyDrag();this.dayGrid&&this.dayGrid.destroyDrag()},renderSelection:function(a){a.start.hasTime()||a.end.hasTime()?this.timeGrid.renderSelection(a):this.dayGrid&&this.dayGrid.renderSelection(a)},
destroySelection:function(){this.timeGrid.destroySelection();this.dayGrid&&this.dayGrid.destroySelection()}});P.agendaWeek={type:"agenda",duration:{weeks:1}};P.agendaDay={type:"agenda",duration:{days:1}}});
