(function(){function D(a){a=a.toUpperCase();for(var c=E.length,b=0,f=0;f<c;++f)for(var d=E[f],e=d[1].length;a.substr(0,e)==d[1];a=a.substr(e))b+=d[0];return b}function F(a){a=a.toUpperCase();for(var c=G.length,b=1,f=1;0<a.length;f*=c)b+=G.indexOf(a.charAt(a.length-1))*f,a=a.substr(0,a.length-1);return b}var H=CKEDITOR.htmlParser.fragment.prototype,t=CKEDITOR.htmlParser.element.prototype;H.onlyChild=t.onlyChild=function(){var a=this.children;return 1==a.length&&a[0]||null};t.removeAnyChildWithName=
function(a){for(var c=this.children,b=[],f,d=0;d<c.length;d++)f=c[d],f.name&&(f.name==a&&(b.push(f),c.splice(d--,1)),b=b.concat(f.removeAnyChildWithName(a)));return b};t.getAncestor=function(a){for(var c=this.parent;c&&(!c.name||!c.name.match(a));)c=c.parent;return c};H.firstChild=t.firstChild=function(a){for(var c,b=0;b<this.children.length;b++)if(c=this.children[b],a(c)||c.name&&(c=c.firstChild(a)))return c;return null};t.addStyle=function(a,c,b){var f="";if("string"==typeof c)f+=a+":"+c+";";else{if("object"==
typeof a)for(var d in a)a.hasOwnProperty(d)&&(f+=d+":"+a[d]+";");else f+=a;b=c}this.attributes||(this.attributes={});a=this.attributes.style||"";a=(b?[f,a]:[a,f]).join(";");this.attributes.style=a.replace(/^;|;(?=;)/,"")};t.getStyle=function(a){var c=this.attributes.style;if(c)return c=CKEDITOR.tools.parseCssText(c,1),c[a]};CKEDITOR.dtd.parentOf=function(a){var c={},b;for(b in this)-1==b.indexOf("$")&&this[b][a]&&(c[b]=1);return c};var L=/^([.\d]*)+(em|ex|px|gd|rem|vw|vh|vm|ch|mm|cm|in|pt|pc|deg|rad|ms|s|hz|khz){1}?/i,
I=/^(?:\b0[^\s]*\s*){1,4}$/,C={ol:{decimal:/\d+/,"lower-roman":/^m{0,4}(cm|cd|d?c{0,3})(xc|xl|l?x{0,3})(ix|iv|v?i{0,3})$/,"upper-roman":/^M{0,4}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$/,"lower-alpha":/^[a-z]+$/,"upper-alpha":/^[A-Z]+$/},ul:{disc:/[l\u00B7\u2002]/,circle:/[\u006F\u00D8]/,square:/[\u006E\u25C6]/}},E=[[1E3,"M"],[900,"CM"],[500,"D"],[400,"CD"],[100,"C"],[90,"XC"],[50,"L"],[40,"XL"],[10,"X"],[9,"IX"],[5,"V"],[4,"IV"],[1,"I"]],G="ABCDEFGHIJKLMNOPQRSTUVWXYZ",x=0,y=null,A,J=CKEDITOR.plugins.pastefromword=
{utils:{createListBulletMarker:function(a,c){var b=new CKEDITOR.htmlParser.element("cke:listbullet");b.attributes={"cke:listsymbol":a[0]};b.add(new CKEDITOR.htmlParser.text(c));return b},isListBulletIndicator:function(a){if(/mso-list\s*:\s*Ignore/i.test(a.attributes&&a.attributes.style))return!0},isContainingOnlySpaces:function(a){var c;return(c=a.onlyChild())&&/^(:?\s|&nbsp;)+$/.test(c.value)},resolveList:function(a){var c=a.attributes,b;if((b=a.removeAnyChildWithName("cke:listbullet"))&&b.length&&
(b=b[0]))return a.name="cke:li",c.style&&(c.style=J.filters.stylesFilter([["text-indent"],["line-height"],[/^margin(:?-left)?$/,null,function(a){a=a.split(" ");a=CKEDITOR.tools.convertToPx(a[3]||a[1]||a[0]);!x&&null!==y&&a>y&&(x=a-y);y=a;c["cke:indent"]=x&&Math.ceil(a/x)+1||1}],[/^mso-list$/,null,function(a){a=a.split(" ");var b=Number(a[0].match(/\d+/));a=Number(a[1].match(/\d+/));1==a&&(b!==A&&(c["cke:reset"]=1),A=b);c["cke:indent"]=a}]])(c.style,a)||""),c["cke:indent"]||(y=0,c["cke:indent"]=1),
CKEDITOR.tools.extend(c,b.attributes),!0;A=y=x=null;return!1},getStyleComponents:function(){var a=CKEDITOR.dom.element.createFromHtml('<div style="position:absolute;left:-9999px;top:-9999px;"></div>',CKEDITOR.document);CKEDITOR.document.getBody().append(a);return function(c,b,f){a.setStyle(c,b);c={};b=f.length;for(var d=0;d<b;d++)c[f[d]]=a.getStyle(f[d]);return c}}(),listDtdParents:CKEDITOR.dtd.parentOf("ol")},filters:{flattenList:function(a,c){c="number"==typeof c?c:1;var b=a.attributes,f;switch(b.type){case "a":f=
"lower-alpha";break;case "1":f="decimal"}for(var d=a.children,e,h=0;h<d.length;h++)if(e=d[h],e.name in CKEDITOR.dtd.$listItem){var k=e.attributes,g=e.children,r=g[g.length-1];r.name in CKEDITOR.dtd.$list&&(a.add(r,h+1),--g.length||d.splice(h--,1));e.name="cke:li";b.start&&!h&&(k.value=b.start);J.filters.stylesFilter([["tab-stops",null,function(a){(a=a.split(" ")[1].match(L))&&(y=CKEDITOR.tools.convertToPx(a[0]))}],1==c?["mso-list",null,function(a){a=a.split(" ");a=Number(a[0].match(/\d+/));a!==A&&
(k["cke:reset"]=1);A=a}]:null])(k.style);k["cke:indent"]=c;k["cke:listtype"]=a.name;k["cke:list-style-type"]=f}else if(e.name in CKEDITOR.dtd.$list){arguments.callee.apply(this,[e,c+1]);d=d.slice(0,h).concat(e.children).concat(d.slice(h+1));a.children=[];e=0;for(g=d.length;e<g;e++)a.add(d[e]);d=a.children}delete a.name;b["cke:list"]=1},assembleList:function(a){var c=a.children,b,f,d,e,h,k;a=[];for(var g,r,l,p,n,u,q=0;q<c.length;q++)if(b=c[q],"cke:li"==b.name)if(b.name="li",f=b.attributes,l=(l=f["cke:listsymbol"])&&
l.match(/^(?:[(]?)([^\s]+?)([.)]?)$/),p=n=u=null,f["cke:ignored"])c.splice(q--,1);else{f["cke:reset"]&&(k=e=h=null);d=Number(f["cke:indent"]);d!=e&&(r=g=null);if(l){if(r&&C[r][g].test(l[1]))p=r,n=g;else for(var v in C)for(var z in C[v])if(C[v][z].test(l[1]))if("ol"==v&&/alpha|roman/.test(z)){if(g=/roman/.test(z)?D(l[1]):F(l[1]),!u||g<u)u=g,p=v,n=z}else{p=v;n=z;break}!p&&(p=l[2]?"ol":"ul")}else p=f["cke:listtype"]||"ol",n=f["cke:list-style-type"];r=p;g=n||("ol"==p?"decimal":"disc");n&&n!=("ol"==p?
"decimal":"disc")&&b.addStyle("list-style-type",n);if("ol"==p&&l){switch(n){case "decimal":u=Number(l[1]);break;case "lower-roman":case "upper-roman":u=D(l[1]);break;case "lower-alpha":case "upper-alpha":u=F(l[1])}b.attributes.value=u}if(k){if(d>e)a.push(k=new CKEDITOR.htmlParser.element(p)),k.add(b),h.add(k);else{if(d<e){e-=d;for(var w;e--&&(w=k.parent);)k=w.parent}k.add(b)}c.splice(q--,1)}else a.push(k=new CKEDITOR.htmlParser.element(p)),k.add(b),c[q]=k;h=b;e=d}else k&&(k=e=h=null);for(q=0;q<a.length;q++)if(k=
a[q],v=k.children,g=g=void 0,z=k.children.length,w=g=void 0,c=/list-style-type:(.*?)(?:;|$)/,e=CKEDITOR.plugins.pastefromword.filters.stylesFilter,g=k.attributes,!c.exec(g.style)){for(h=0;h<z;h++)if(g=v[h],g.attributes.value&&Number(g.attributes.value)==h+1&&delete g.attributes.value,g=c.exec(g.attributes.style))if(g[1]!=w&&w){w=null;break}else w=g[1];if(w){for(h=0;h<z;h++)g=v[h].attributes,g.style&&(g.style=e([["list-style-type"]])(g.style)||"");k.addStyle("list-style-type",w)}}A=y=x=null},falsyFilter:function(){return!1},
stylesFilter:function(a,c){return function(b,f){var d=[];(b||"").replace(/&quot;/g,'"').replace(/\s*([^ :;]+)\s*:\s*([^;]+)\s*(?=;|$)/g,function(b,e,g){e=e.toLowerCase();"font-family"==e&&(g=g.replace(/["']/g,""));for(var h,l,k,n=0;n<a.length;n++)if(a[n]&&(b=a[n][0],h=a[n][1],l=a[n][2],k=a[n][3],e.match(b)&&(!h||g.match(h)))){e=k||e;c&&(l=l||g);"function"==typeof l&&(l=l(g,f,e));l&&l.push&&(e=l[0],l=l[1]);"string"==typeof l&&d.push([e,l]);return}!c&&d.push([e,g])});for(var e=0;e<d.length;e++)d[e]=
d[e].join(":");return d.length?d.join(";")+";":!1}},elementMigrateFilter:function(a,c){return a?function(b){var f=c?(new CKEDITOR.style(a,c))._.definition:a;b.name=f.element;CKEDITOR.tools.extend(b.attributes,CKEDITOR.tools.clone(f.attributes));b.addStyle(CKEDITOR.style.getStyleText(f))}:function(){}},styleMigrateFilter:function(a,c){var b=this.elementMigrateFilter;return a?function(f,d){var e=new CKEDITOR.htmlParser.element(null),h={};h[c]=f;b(a,h)(e);e.children=d.children;d.children=[e];e.filter=
function(){};e.parent=d}:function(){}},bogusAttrFilter:function(a,c){if(-1==c.name.indexOf("cke:"))return!1},applyStyleFilter:null},getRules:function(a,c){var b=CKEDITOR.dtd,f=CKEDITOR.tools.extend({},b.$block,b.$listItem,b.$tableContent),d=a.config,e=this.filters,h=e.falsyFilter,k=e.stylesFilter,g=e.elementMigrateFilter,r=CKEDITOR.tools.bind(this.filters.styleMigrateFilter,this.filters),l=this.utils.createListBulletMarker,p=e.flattenList,n=e.assembleList,u=this.utils.isListBulletIndicator,q=this.utils.isContainingOnlySpaces,
v=this.utils.resolveList,z=function(a){a=CKEDITOR.tools.convertToPx(a);return isNaN(a)?a:a+"px"},w=this.utils.getStyleComponents,y=this.utils.listDtdParents,t=!1!==d.pasteFromWordRemoveFontStyles,x=!1!==d.pasteFromWordRemoveStyles;return{elementNames:[[/meta|link|script/,""]],root:function(a){a.filterChildren(c);n(a)},elements:{"^":function(a){var c;CKEDITOR.env.gecko&&(c=e.applyStyleFilter)&&c(a)},$:function(a){var m=a.name||"",B=a.attributes;m in f&&B.style&&(B.style=k([[/^(:?width|height)$/,null,
z]])(B.style)||"");if(m.match(/h\d/)){a.filterChildren(c);if(v(a))return;g(d["format_"+m])(a)}else if(m in b.$inline)a.filterChildren(c),q(a)&&delete a.name;else if(-1!=m.indexOf(":")&&-1==m.indexOf("cke")){a.filterChildren(c);if("v:imagedata"==m){if(m=a.attributes["o:href"])a.attributes.src=m;a.name="img";return}delete a.name}m in y&&(a.filterChildren(c),n(a))},style:function(a){if(CKEDITOR.env.gecko){a=(a=a.onlyChild().value.match(/\/\* Style Definitions \*\/([\s\S]*?)\/\*/))&&a[1];var c={};a&&
(a.replace(/[\n\r]/g,"").replace(/(.+?)\{(.+?)\}/g,function(a,b,B){b=b.split(",");a=b.length;for(var m=0;m<a;m++)CKEDITOR.tools.trim(b[m]).replace(/^(\w+)(\.[\w-]+)?$/g,function(a,b,m){b=b||"*";m=m.substring(1,m.length);m.match(/MsoNormal/)||(c[b]||(c[b]={}),m?c[b][m]=B:c[b]=B)})}),e.applyStyleFilter=function(a){var b=c["*"]?"*":a.name,m=a.attributes&&a.attributes["class"];b in c&&(b=c[b],"object"==typeof b&&(b=b[m]),b&&a.addStyle(b,!0))})}return!1},p:function(a){if(/MsoListParagraph/i.exec(a.attributes["class"])||
a.getStyle("mso-list")){var b=a.firstChild(function(a){return a.type==CKEDITOR.NODE_TEXT&&!q(a.parent)});(b=b&&b.parent)&&b.addStyle("mso-list","Ignore")}a.filterChildren(c);v(a)||(d.enterMode==CKEDITOR.ENTER_BR?(delete a.name,a.add(new CKEDITOR.htmlParser.element("br"))):g(d["format_"+(d.enterMode==CKEDITOR.ENTER_P?"p":"div")])(a))},div:function(a){var c=a.onlyChild();if(c&&"table"==c.name){var b=a.attributes;c.attributes=CKEDITOR.tools.extend(c.attributes,b);b.style&&c.addStyle(b.style);c=new CKEDITOR.htmlParser.element("div");
c.addStyle("clear","both");a.add(c);delete a.name}},td:function(a){a.getAncestor("thead")&&(a.name="th")},ol:p,ul:p,dl:p,font:function(a){if(u(a.parent))delete a.name;else{a.filterChildren(c);var b=a.attributes,d=b.style,e=a.parent;"font"==e.name?(CKEDITOR.tools.extend(e.attributes,a.attributes),d&&e.addStyle(d),delete a.name):(d=d||"",b.color&&("#000000"!=b.color&&(d+="color:"+b.color+";"),delete b.color),b.face&&(d+="font-family:"+b.face+";",delete b.face),b.size&&(d+="font-size:"+(3<b.size?"large":
3>b.size?"small":"medium")+";",delete b.size),a.name="span",a.addStyle(d))}},span:function(a){if(u(a.parent))return!1;a.filterChildren(c);if(q(a))return delete a.name,null;if(u(a)){var b=a.firstChild(function(a){return a.value||"img"==a.name}),e=(b=b&&(b.value||"l."))&&b.match(/^(?:[(]?)([^\s]+?)([.)]?)$/);if(e)return b=l(e,b),(a=a.getAncestor("span"))&&/ mso-hide:\s*all|display:\s*none /.test(a.attributes.style)&&(b.attributes["cke:ignored"]=1),b}if(e=(b=a.attributes)&&b.style)b.style=k([["line-height"],
[/^font-family$/,null,t?null:r(d.font_style,"family")],[/^font-size$/,null,t?null:r(d.fontSize_style,"size")],[/^color$/,null,t?null:r(d.colorButton_foreStyle,"color")],[/^background-color$/,null,t?null:r(d.colorButton_backStyle,"color")]])(e,a)||"";b.style||delete b.style;CKEDITOR.tools.isEmpty(b)&&delete a.name;return null},b:g(d.coreStyles_bold),i:g(d.coreStyles_italic),u:g(d.coreStyles_underline),s:g(d.coreStyles_strike),sup:g(d.coreStyles_superscript),sub:g(d.coreStyles_subscript),a:function(a){a=
a.attributes;a.href&&a.href.match(/^file:\/\/\/[\S]+#/i)&&(a.href=a.href.replace(/^file:\/\/\/[^#]+/i,""))},"cke:listbullet":function(a){a.getAncestor(/h\d/)&&!d.pasteFromWordNumberedHeadingToList&&delete a.name}},attributeNames:[[/^onmouse(:?out|over)/,""],[/^onload$/,""],[/(?:v|o):\w+/,""],[/^lang/,""]],attributes:{style:k(x?[[/^list-style-type$/,null],[/^margin$|^margin-(?!bottom|top)/,null,function(a,b,c){if(b.name in{p:1,div:1}){b="ltr"==d.contentsLangDirection?"margin-left":"margin-right";if("margin"==
c)a=w(c,a,[b])[b];else if(c!=b)return null;if(a&&!I.test(a))return[b,a]}return null}],[/^clear$/],[/^border.*|margin.*|vertical-align|float$/,null,function(a,b){if("img"==b.name)return a}],[/^width|height$/,null,function(a,b){if(b.name in{table:1,td:1,th:1,img:1})return a}]]:[[/^mso-/],[/-color$/,null,function(a){if("transparent"==a)return!1;if(CKEDITOR.env.gecko)return a.replace(/-moz-use-text-color/g,"transparent")}],[/^margin$/,I],["text-indent","0cm"],["page-break-before"],["tab-stops"],["display",
"none"],t?[/font-?/]:null],x),width:function(a,c){if(c.name in b.$tableContent)return!1},border:function(a,c){if(c.name in b.$tableContent)return!1},"class":h,bgcolor:h,valign:x?h:function(a,b){b.addStyle("vertical-align",a);return!1}},comment:CKEDITOR.env.ie?h:function(a,b){var c=a.match(/<img.*?>/),d=a.match(/^\[if !supportLists\]([\s\S]*?)\[endif\]$/);return d?(d=(c=d[1]||c&&"l.")&&c.match(/>(?:[(]?)([^\s]+?)([.)]?)</),l(d,c)):CKEDITOR.env.gecko&&c?(c=CKEDITOR.htmlParser.fragment.fromHtml(c[0]).children[0],
(d=(d=(d=b.previous)&&d.value.match(/<v:imagedata[^>]*o:href=['"](.*?)['"]/))&&d[1])&&(c.attributes.src=d),c):!1}}}},K=function(){this.dataFilter=new CKEDITOR.htmlParser.filter};K.prototype={toHtml:function(a){a=CKEDITOR.htmlParser.fragment.fromHtml(a);var c=new CKEDITOR.htmlParser.basicWriter;a.writeHtml(c,this.dataFilter);return c.getHtml(!0)}};CKEDITOR.cleanWord=function(a,c){CKEDITOR.env.gecko&&(a=a.replace(/(<\!--\[if[^<]*?\])--\>([\S\s]*?)<\!--(\[endif\]--\>)/gi,"$1$2$3"));CKEDITOR.env.webkit&&
(a=a.replace(/(class="MsoListParagraph[^>]+><\!--\[if !supportLists\]--\>)([^<]+<span[^<]+<\/span>)(<\!--\[endif\]--\>)/gi,"$1<span>$2</span>$3"));var b=new K,f=b.dataFilter;f.addRules(CKEDITOR.plugins.pastefromword.getRules(c,f));c.fire("beforeCleanWord",{filter:f});try{a=b.toHtml(a)}catch(d){alert(c.lang.pastefromword.error)}a=a.replace(/cke:.*?".*?"/g,"");a=a.replace(/style=""/g,"");return a.replace(/<span>/g,"")}})();
