(function(c){c.matchMedia=c.matchMedia||function(c,e){var k,q=c.documentElement,s=q.firstElementChild||q.firstChild,f=c.createElement("body"),g=c.createElement("div");g.id="mq-test-1";g.style.cssText="position:absolute;top:-100em";f.style.background="none";f.appendChild(g);return function(c){g.innerHTML='&shy;<style media="'+c+'"> #mq-test-1 { width: 42px; }</style>';q.insertBefore(f,s);k=42===g.offsetWidth;q.removeChild(f);return{matches:k,media:c}}}(c.document)})(this);
(function(c){function D(){x(!0)}var e={};c.respond=e;e.update=function(){};var k=[],q=function(){var d=!1;try{d=new c.XMLHttpRequest}catch(b){d=new c.ActiveXObject("Microsoft.XMLHTTP")}return function(){return d}}(),s=function(d,b){var a=q();a&&(a.open("GET",d,!0),a.onreadystatechange=function(){4!==a.readyState||200!==a.status&&304!==a.status||b(a.responseText)},4!==a.readyState&&a.send(null))};e.ajax=s;e.queue=k;e.regex={media:/@media[^\{]+\{([^\{\}]*\{[^\}\{]*\})+/gi,keyframes:/@(?:\-(?:o|moz|webkit)\-)?keyframes[^\{]+\{(?:[^\{\}]*\{[^\}\{]*\})+[^\}]*\}/gi,
urls:/(url\()['"]?([^\/\)'"][^:\)'"]+)['"]?(\))/g,findStyles:/@media *([^\{]+)\{([\S\s]+?)$/,only:/(only\s+)?([a-zA-Z]+)\s?/,minw:/\([\s]*min\-width\s*:[\s]*([\s]*[0-9\.]+)(px|em)[\s]*\)/,maxw:/\([\s]*max\-width\s*:[\s]*([\s]*[0-9\.]+)(px|em)[\s]*\)/};e.mediaQueriesSupported=c.matchMedia&&null!==c.matchMedia("only all")&&c.matchMedia("only all").matches;if(!e.mediaQueriesSupported){var f=c.document,g=f.documentElement,t=[],u=[],l=[],y={},v=f.getElementsByTagName("head")[0]||g,I=f.getElementsByTagName("base")[0],
w=v.getElementsByTagName("link"),z,E,A,B=function(){var d,b=f.createElement("div"),a=f.body,c=g.style.fontSize,e=a&&a.style.fontSize,h=!1;b.style.cssText="position:absolute;font-size:1em;width:1em";a||(a=h=f.createElement("body"),a.style.background="none");g.style.fontSize="100%";a.style.fontSize="100%";a.appendChild(b);h&&g.insertBefore(a,g.firstChild);d=b.offsetWidth;h?g.removeChild(a):a.removeChild(b);g.style.fontSize=c;e&&(a.style.fontSize=e);return d=A=parseFloat(d)},x=function(d){var b=g.clientWidth,
a="CSS1Compat"===f.compatMode&&b||f.body.clientWidth||b,b={},e=w[w.length-1],p=(new Date).getTime();if(d&&z&&30>p-z)c.clearTimeout(E),E=c.setTimeout(x,30);else{z=p;for(var h in t)if(t.hasOwnProperty(h)){d=t[h];var p=d.minw,r=d.maxw,m=null===p,k=null===r;p&&(p=parseFloat(p)*(-1<p.indexOf("em")?A||B():1));r&&(r=parseFloat(r)*(-1<r.indexOf("em")?A||B():1));d.hasquery&&(m&&k||!(m||a>=p)||!(k||a<=r))||(b[d.media]||(b[d.media]=[]),b[d.media].push(u[d.rules]))}for(var n in l)l.hasOwnProperty(n)&&l[n]&&l[n].parentNode===
v&&v.removeChild(l[n]);l.length=0;for(var C in b)b.hasOwnProperty(C)&&(h=f.createElement("style"),n=b[C].join("\n"),h.type="text/css",h.media=C,v.insertBefore(h,e.nextSibling),h.styleSheet?h.styleSheet.cssText=n:h.appendChild(f.createTextNode(n)),l.push(h))}},F=function(d,b,a){var c=d.replace(e.regex.keyframes,"").match(e.regex.media),f=c&&c.length||0;b=b.substring(0,b.lastIndexOf("/"));var h=!f&&a;b.length&&(b+="/");h&&(f=1);for(var g=0;g<f;g++){var m,k,n;h?(m=a,u.push(d.replace(e.regex.urls,"$1"+
b+"$2$3"))):(m=c[g].match(e.regex.findStyles)&&RegExp.$1,u.push(RegExp.$2&&RegExp.$2.replace(e.regex.urls,"$1"+b+"$2$3")));k=m.split(",");n=k.length;for(var l=0;l<n;l++)m=k[l],t.push({media:m.split("(")[0].match(e.regex.only)&&RegExp.$2||"all",rules:u.length-1,hasquery:-1<m.indexOf("("),minw:m.match(e.regex.minw)&&parseFloat(RegExp.$1)+(RegExp.$2||""),maxw:m.match(e.regex.maxw)&&parseFloat(RegExp.$1)+(RegExp.$2||"")})}x()},G=function(){if(k.length){var d=k.shift();s(d.href,function(b){F(b,d.href,
d.media);y[d.href]=!0;c.setTimeout(function(){G()},0)})}},H=function(){for(var d=0;d<w.length;d++){var b=w[d],a=b.href,e=b.media,f=b.rel&&"stylesheet"===b.rel.toLowerCase();if(a&&f&&!y[a])if(b.styleSheet&&b.styleSheet.rawCssText)F(b.styleSheet.rawCssText,a,e),y[a]=!0;else if(!/^([a-zA-Z:]*\/\/)/.test(a)&&!I||a.replace(RegExp.$1,"").split("/")[0]===c.location.host)"//"===a.substring(0,2)&&(a=c.location.protocol+a),k.push({href:a,media:e})}G()};H();e.update=H;e.getEmValue=B;c.addEventListener?c.addEventListener("resize",
D,!1):c.attachEvent&&c.attachEvent("onresize",D)}})(this);
