/*
   Copyright 2015-2016 SpryMedia Ltd.

 This source file is free software, available under the following license:
   MIT license - http://datatables.net/license/mit

 This source file is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 or FITNESS FOR A PARTICULAR PURPOSE. See the license files for details.

 For details please refer to: http://www.datatables.net/extensions/select
 Select for DataTables 1.2.2
 2015-2016 SpryMedia Ltd - datatables.net/license/mit
*/
(function(f){"function"===typeof define&&define.amd?define(["jquery","datatables.net"],function(l){return f(l,window,document)}):"object"===typeof exports?module.exports=function(l,m){l||(l=window);m&&m.fn.dataTable||(m=require("datatables.net")(l,m).$);return f(m,l,l.document)}:f(jQuery,window,document)})(function(f,l,m,h){function z(a,b,c){var d;d=function(c,b){if(c>b){var d=b;b=c;c=d}var e=!1;return a.columns(":visible").indexes().filter(function(a){a===c&&(e=!0);return a===b?(e=!1,!0):e})};var e=
function(c,b){var d=a.rows({search:"applied"}).indexes();if(d.indexOf(c)>d.indexOf(b)){var e=b;b=c;c=e}var f=!1;return d.filter(function(a){a===c&&(f=!0);return a===b?(f=!1,!0):f})};a.cells({selected:!0}).any()||c?(d=d(c.column,b.column),c=e(c.row,b.row)):(d=d(0,b.column),c=e(0,b.row));c=a.cells(c,d).flatten();a.cells(b,{selected:!0}).any()?a.cells(c).deselect():a.cells(c).select()}function v(a){var b=a.settings()[0]._select.selector;f(a.table().container()).off("mousedown.dtSelect",b).off("mouseup.dtSelect",
b).off("click.dtSelect",b);f("body").off("click.dtSelect"+a.table().node().id)}function B(a){var b=f(a.table().container()),c=a.settings()[0],d=c._select.selector;b.on("mousedown.dtSelect",d,function(c){if(c.shiftKey||c.metaKey||c.ctrlKey)b.css("-moz-user-select","none").one("selectstart.dtSelect",d,function(){return!1})}).on("mouseup.dtSelect",d,function(){b.css("-moz-user-select","")}).on("click.dtSelect",d,function(c){var b=a.select.items();if(!l.getSelection||!f.trim(l.getSelection().toString())){var d=
a.settings()[0];if(f(c.target).closest("div.dataTables_wrapper")[0]==a.table().container()){var e=a.cell(f(c.target).closest("td, th"));if(e.any()){var g=f.Event("user-select.dt");k(a,g,[b,e,c]);g.isDefaultPrevented()||(g=e.index(),"row"===b?(b=g.row,w(c,a,d,"row",b)):"column"===b?(b=e.index().column,w(c,a,d,"column",b)):"cell"===b&&(b=e.index(),w(c,a,d,"cell",b)),d._select_lastCell=g)}}}});f("body").on("click.dtSelect"+a.table().node().id,function(b){!c._select.blurable||f(b.target).parents().filter(a.table().container()).length||
b.target.getRootNode()!==m||f(b.target).parents("div.DTE").length||t(c,!0)})}function k(a,b,c,d){if(!d||a.flatten().length)"string"===typeof b&&(b+=".dt"),c.unshift(a),f(a.table().node()).trigger(b,c)}function C(a){var b=a.settings()[0];if(b._select.info&&b.aanFeatures.i){var c=a.rows({selected:!0}).flatten().length,d=a.columns({selected:!0}).flatten().length,e=a.cells({selected:!0}).flatten().length,p=function(c,b,d){c.append(f('<span class="select-item"/>').append(a.i18n("select."+b+"s",{_:"%d "+
b+"s selected",0:"",1:"1 "+b+" selected"},d)))};f.each(b.aanFeatures.i,function(b,a){a=f(a);var g=f('<span class="select-info"/>');p(g,"row",c);p(g,"column",d);p(g,"cell",e);var n=a.children("span.select-info");n.length&&n.remove();""!==g.text()&&a.append(g)})}}function E(a){var b=new g.Api(a);a.aoRowCreatedCallback.push({fn:function(c,b,e){b=a.aoData[e];b._select_selected&&f(c).addClass(a._select.className);c=0;for(e=a.aoColumns.length;c<e;c++)(a.aoColumns[c]._select_selected||b._selected_cells&&
b._selected_cells[c])&&f(b.anCells[c]).addClass(a._select.className)},sName:"select-deferRender"});b.on("preXhr.dt.dtSelect",function(){var c=b.rows({selected:!0}).ids(!0).filter(function(b){return b!==h}),a=b.cells({selected:!0}).eq(0).map(function(c){var a=b.row(c.row).id(!0);return a?{row:a,column:c.column}:h}).filter(function(b){return b!==h});b.one("draw.dt.dtSelect",function(){b.rows(c).select();a.any()&&a.each(function(c){b.cells(c.row,c.column).select()})})});b.on("draw.dtSelect.dt select.dtSelect.dt deselect.dtSelect.dt info.dt",
function(){C(b)});b.on("destroy.dtSelect",function(){v(b);b.off(".dtSelect")})}function D(a,b,c,d){var e=a[b+"s"]({search:"applied"}).indexes();d=f.inArray(d,e);var g=f.inArray(c,e);if(a[b+"s"]({selected:!0}).any()||-1!==d){if(d>g){var n=g,g=d;d=n}e.splice(g+1,e.length);e.splice(0,d)}else e.splice(f.inArray(c,e)+1,e.length);a[b](c,{selected:!0}).any()?(e.splice(f.inArray(c,e),1),a[b+"s"](e).deselect()):a[b+"s"](e).select()}function t(a,b){if(b||"single"===a._select.style){var c=new g.Api(a);c.rows({selected:!0}).deselect();
c.columns({selected:!0}).deselect();c.cells({selected:!0}).deselect()}}function w(a,b,c,d,e){var f=b.select.style(),g=b[d](e,{selected:!0}).any();"os"===f?a.ctrlKey||a.metaKey?b[d](e).select(!g):a.shiftKey?"cell"===d?z(b,e,c._select_lastCell||null):D(b,d,e,c._select_lastCell?c._select_lastCell[d]:null):(a=b[d+"s"]({selected:!0}),g&&1===a.flatten().length?b[d](e).deselect():(a.deselect(),b[d](e).select())):"multi+shift"==f?a.shiftKey?"cell"===d?z(b,e,c._select_lastCell||null):D(b,d,e,c._select_lastCell?
c._select_lastCell[d]:null):b[d](e).select(!g):b[d](e).select(!g)}function u(a,b){return function(c){return c.i18n("buttons."+a,b)}}function x(a){a=a._eventNamespace;return"draw.dt.DT"+a+" select.dt.DT"+a+" deselect.dt.DT"+a}var g=f.fn.dataTable;g.select={};g.select.version="1.2.2";g.select.init=function(a){var b=a.settings()[0],c=b.oInit.select,d=g.defaults.select,c=c===h?d:c,d="row",e="api",p=!1,n=!0,A="td, th",l="selected",k=!1;b._select={};!0===c?(e="os",k=!0):"string"===typeof c?(e=c,k=!0):f.isPlainObject(c)&&
(c.blurable!==h&&(p=c.blurable),c.info!==h&&(n=c.info),c.items!==h&&(d=c.items),c.style!==h&&(e=c.style,k=!0),c.selector!==h&&(A=c.selector),c.className!==h&&(l=c.className));a.select.selector(A);a.select.items(d);a.select.style(e);a.select.blurable(p);a.select.info(n);b._select.className=l;f.fn.dataTable.ext.order["select-checkbox"]=function(b,c){return this.api().column(c,{order:"index"}).nodes().map(function(c){return"row"===b._select.items?f(c).parent().hasClass(b._select.className):"cell"===
b._select.items?f(c).hasClass(b._select.className):!1})};!k&&f(a.table().node()).hasClass("selectable")&&a.select.style("os")};f.each([{type:"row",prop:"aoData"},{type:"column",prop:"aoColumns"}],function(a,b){g.ext.selector[b.type].push(function(c,a,e){a=a.selected;var d,f=[];if(a===h)return e;for(var g=0,k=e.length;g<k;g++)d=c[b.prop][e[g]],(!0===a&&!0===d._select_selected||!1===a&&!d._select_selected)&&f.push(e[g]);return f})});g.ext.selector.cell.push(function(a,b,c){b=b.selected;var d,e=[];if(b===
h)return c;for(var f=0,g=c.length;f<g;f++)d=a.aoData[c[f].row],(!0===b&&d._selected_cells&&!0===d._selected_cells[c[f].column]||!(!1!==b||d._selected_cells&&d._selected_cells[c[f].column]))&&e.push(c[f]);return e});var q=g.Api.register,r=g.Api.registerPlural;q("select()",function(){return this.iterator("table",function(a){g.select.init(new g.Api(a))})});q("select.blurable()",function(a){return a===h?this.context[0]._select.blurable:this.iterator("table",function(b){b._select.blurable=a})});q("select.info()",
function(a){return C===h?this.context[0]._select.info:this.iterator("table",function(b){b._select.info=a})});q("select.items()",function(a){return a===h?this.context[0]._select.items:this.iterator("table",function(b){b._select.items=a;k(new g.Api(b),"selectItems",[a])})});q("select.style()",function(a){return a===h?this.context[0]._select.style:this.iterator("table",function(b){b._select.style=a;b._select_init||E(b);var c=new g.Api(b);v(c);"api"!==a&&B(c);k(new g.Api(b),"selectStyle",[a])})});q("select.selector()",
function(a){return a===h?this.context[0]._select.selector:this.iterator("table",function(b){v(new g.Api(b));b._select.selector=a;"api"!==b._select.style&&B(new g.Api(b))})});r("rows().select()","row().select()",function(a){var b=this;if(!1===a)return this.deselect();this.iterator("row",function(b,a){t(b);b.aoData[a]._select_selected=!0;f(b.aoData[a].nTr).addClass(b._select.className)});this.iterator("table",function(c,a){k(b,"select",["row",b[a]],!0)});return this});r("columns().select()","column().select()",
function(a){var b=this;if(!1===a)return this.deselect();this.iterator("column",function(b,a){t(b);b.aoColumns[a]._select_selected=!0;var c=(new g.Api(b)).column(a);f(c.header()).addClass(b._select.className);f(c.footer()).addClass(b._select.className);c.nodes().to$().addClass(b._select.className)});this.iterator("table",function(a,d){k(b,"select",["column",b[d]],!0)});return this});r("cells().select()","cell().select()",function(a){var b=this;if(!1===a)return this.deselect();this.iterator("cell",
function(b,a,e){t(b);a=b.aoData[a];a._selected_cells===h&&(a._selected_cells=[]);a._selected_cells[e]=!0;a.anCells&&f(a.anCells[e]).addClass(b._select.className)});this.iterator("table",function(a,d){k(b,"select",["cell",b[d]],!0)});return this});r("rows().deselect()","row().deselect()",function(){var a=this;this.iterator("row",function(b,a){b.aoData[a]._select_selected=!1;f(b.aoData[a].nTr).removeClass(b._select.className)});this.iterator("table",function(b,c){k(a,"deselect",["row",a[c]],!0)});return this});
r("columns().deselect()","column().deselect()",function(){var a=this;this.iterator("column",function(b,a){b.aoColumns[a]._select_selected=!1;var c=new g.Api(b),e=c.column(a);f(e.header()).removeClass(b._select.className);f(e.footer()).removeClass(b._select.className);c.cells(null,a).indexes().each(function(a){var c=b.aoData[a.row],d=c._selected_cells;!c.anCells||d&&d[a.column]||f(c.anCells[a.column]).removeClass(b._select.className)})});this.iterator("table",function(b,c){k(a,"deselect",["column",
a[c]],!0)});return this});r("cells().deselect()","cell().deselect()",function(){var a=this;this.iterator("cell",function(b,a,d){a=b.aoData[a];a._selected_cells[d]=!1;a.anCells&&!b.aoColumns[d]._select_selected&&f(a.anCells[d]).removeClass(b._select.className)});this.iterator("table",function(b,c){k(a,"deselect",["cell",a[c]],!0)});return this});var y=0;f.extend(g.ext.buttons,{selected:{text:u("selected","Selected"),className:"buttons-selected",init:function(a,b,c){var d=this;c._eventNamespace=".select"+
y++;a.on(x(c),function(){var a=d.rows({selected:!0}).any()||d.columns({selected:!0}).any()||d.cells({selected:!0}).any();d.enable(a)});this.disable()},destroy:function(a,b,c){a.off(c._eventNamespace)}},selectedSingle:{text:u("selectedSingle","Selected single"),className:"buttons-selected-single",init:function(a,b,c){var d=this;c._eventNamespace=".select"+y++;a.on(x(c),function(){var b=a.rows({selected:!0}).flatten().length+a.columns({selected:!0}).flatten().length+a.cells({selected:!0}).flatten().length;
d.enable(1===b)});this.disable()},destroy:function(a,b,c){a.off(c._eventNamespace)}},selectAll:{text:u("selectAll","Select all"),className:"buttons-select-all",action:function(){this[this.select.items()+"s"]().select()}},selectNone:{text:u("selectNone","Deselect all"),className:"buttons-select-none",action:function(){t(this.settings()[0],!0)},init:function(a,b,c){var d=this;c._eventNamespace=".select"+y++;a.on(x(c),function(){var b=a.rows({selected:!0}).flatten().length+a.columns({selected:!0}).flatten().length+
a.cells({selected:!0}).flatten().length;d.enable(0<b)});this.disable()},destroy:function(a,b,c){a.off(c._eventNamespace)}}});f.each(["Row","Column","Cell"],function(a,b){var c=b.toLowerCase();g.ext.buttons["select"+b+"s"]={text:u("select"+b+"s","Select "+c+"s"),className:"buttons-select-"+c+"s",action:function(){this.select.items(c)},init:function(a){var b=this;a.on("selectItems.dt.DT",function(a,d,e){b.active(e===c)})}}});f(m).on("preInit.dt.dtSelect",function(a,b){"dt"===a.namespace&&g.select.init(new g.Api(b))});
return g.select});
