/*
 @package noty - jQuery Notification Plugin
 @version version: 2.3.8
 @contributors https://github.com/needim/noty/graphs/contributors

 @documentation Examples and Documentation - http://needim.github.com/noty/

 @license Licensed under the MIT licenses: http://www.opensource.org/licenses/mit-license.php
*/
var $jscomp={scope:{},findInternal:function(a,b,d){a instanceof String&&(a=String(a));for(var c=a.length,e=0;e<c;e++){var f=a[e];if(b.call(d,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(d.get||d.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,b,d,c){if(b){d=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var e=a[c];e in d||(d[e]={});d=d[e]}a=a[a.length-1];c=d[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,d){return $jscomp.findInternal(this,a,d).v}},"es6-impl","es3");"function"!==typeof Object.create&&(Object.create=function(a){function b(){}b.prototype=a;return new b});
var NotyObject={init:function(a){this.options=$.extend({},$.noty.defaults,a);this.options.layout=this.options.custom?$.noty.layouts.inline:$.noty.layouts[this.options.layout];$.noty.themes[this.options.theme]?this.options.theme=$.noty.themes[this.options.theme]:this.options.themeClassName=this.options.theme;this.options=$.extend({},this.options,this.options.layout.options);this.options.id="noty_"+(new Date).getTime()*Math.floor(1E6*Math.random());this._build();return this},_build:function(){var a=
$('<div class="noty_bar noty_type_'+this.options.type+'"></div>').attr("id",this.options.id);a.append(this.options.template).find(".noty_text").html(this.options.text);this.$bar=null!==this.options.layout.parent.object?$(this.options.layout.parent.object).css(this.options.layout.parent.css).append(a):a;this.options.themeClassName&&this.$bar.addClass(this.options.themeClassName).addClass("noty_container_type_"+this.options.type);if(this.options.buttons){this.options.closeWith=[];this.options.timeout=
!1;a=$("<div/>").addClass("noty_buttons");null!==this.options.layout.parent.object?this.$bar.find(".noty_bar").append(a):this.$bar.append(a);var b=this;$.each(this.options.buttons,function(a,c){var d=$("<button/>").addClass(c.addClass?c.addClass:"gray").html(c.text).attr("id",c.id?c.id:"button-"+a).attr("title",c.title).appendTo(b.$bar.find(".noty_buttons")).on("click",function(a){$.isFunction(c.onClick)&&c.onClick.call(d,b,a)})})}this.$message=this.$bar.find(".noty_message");this.$closeButton=this.$bar.find(".noty_close");
this.$buttons=this.$bar.find(".noty_buttons");$.noty.store[this.options.id]=this},show:function(){var a=this;a.options.custom?a.options.custom.find(a.options.layout.container.selector).append(a.$bar):$(a.options.layout.container.selector).append(a.$bar);a.options.theme&&a.options.theme.style&&a.options.theme.style.apply(a);"function"===$.type(a.options.layout.css)?this.options.layout.css.apply(a.$bar):a.$bar.css(this.options.layout.css||{});a.$bar.addClass(a.options.layout.addClass);a.options.layout.container.style.apply($(a.options.layout.container.selector),
[a.options.within]);a.showing=!0;a.options.theme&&a.options.theme.style&&a.options.theme.callback.onShow.apply(this);if(-1<$.inArray("click",a.options.closeWith))a.$bar.css("cursor","pointer").one("click",function(b){a.stopPropagation(b);a.options.callback.onCloseClick&&a.options.callback.onCloseClick.apply(a);a.close()});if(-1<$.inArray("hover",a.options.closeWith))a.$bar.one("mouseenter",function(){a.close()});if(-1<$.inArray("button",a.options.closeWith))a.$closeButton.one("click",function(b){a.stopPropagation(b);
a.close()});-1==$.inArray("button",a.options.closeWith)&&a.$closeButton.remove();a.options.callback.onShow&&a.options.callback.onShow.apply(a);"string"==typeof a.options.animation.open?(a.$bar.css("height",a.$bar.innerHeight()),a.$bar.on("click",function(b){a.wasClicked=!0}),a.$bar.show().addClass(a.options.animation.open).one("webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend",function(){a.options.callback.afterShow&&a.options.callback.afterShow.apply(a);a.showing=!1;a.shown=
!0;a.hasOwnProperty("wasClicked")&&(a.$bar.off("click",function(b){a.wasClicked=!0}),a.close())})):a.$bar.animate(a.options.animation.open,a.options.animation.speed,a.options.animation.easing,function(){a.options.callback.afterShow&&a.options.callback.afterShow.apply(a);a.showing=!1;a.shown=!0});a.options.timeout&&a.$bar.delay(a.options.timeout).promise().done(function(){a.close()});return this},close:function(){if(!(this.closed||this.$bar&&this.$bar.hasClass("i-am-closing-now"))){var a=this;if(this.showing)a.$bar.queue(function(){a.close.apply(a)});
else if(this.shown||this.showing)if(a.$bar.addClass("i-am-closing-now"),a.options.callback.onClose&&a.options.callback.onClose.apply(a),"string"==typeof a.options.animation.close)a.$bar.addClass(a.options.animation.close).one("webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend",function(){a.options.callback.afterClose&&a.options.callback.afterClose.apply(a);a.closeCleanUp()});else a.$bar.clearQueue().stop().animate(a.options.animation.close,a.options.animation.speed,a.options.animation.easing,
function(){a.options.callback.afterClose&&a.options.callback.afterClose.apply(a)}).promise().done(function(){a.closeCleanUp()});else{var b=[];$.each($.noty.queue,function(d,c){c.options.id!=a.options.id&&b.push(c)});$.noty.queue=b}}},closeCleanUp:function(){var a=this;a.options.modal&&($.notyRenderer.setModalCount(-1),0==$.notyRenderer.getModalCount()&&$(".noty_modal").fadeOut(a.options.animation.fadeSpeed,function(){$(this).remove()}));$.notyRenderer.setLayoutCountFor(a,-1);0==$.notyRenderer.getLayoutCountFor(a)&&
$(a.options.layout.container.selector).remove();"undefined"!==typeof a.$bar&&null!==a.$bar&&("string"==typeof a.options.animation.close?(a.$bar.css("transition","all 100ms ease").css("border",0).css("margin",0).height(0),a.$bar.one("transitionend webkitTransitionEnd oTransitionEnd MSTransitionEnd",function(){a.$bar.remove();a.$bar=null;a.closed=!0;a.options.theme.callback&&a.options.theme.callback.onClose&&a.options.theme.callback.onClose.apply(a)})):(a.$bar.remove(),a.$bar=null,a.closed=!0));delete $.noty.store[a.options.id];
a.options.theme.callback&&a.options.theme.callback.onClose&&a.options.theme.callback.onClose.apply(a);a.options.dismissQueue||($.noty.ontap=!0,$.notyRenderer.render());0<a.options.maxVisible&&a.options.dismissQueue&&$.notyRenderer.render()},setText:function(a){this.closed||(this.options.text=a,this.$bar.find(".noty_text").html(a));return this},setType:function(a){this.closed||(this.options.type=a,this.options.theme.style.apply(this),this.options.theme.callback.onShow.apply(this));return this},setTimeout:function(a){if(!this.closed){var b=
this;this.options.timeout=a;b.$bar.delay(b.options.timeout).promise().done(function(){b.close()})}return this},stopPropagation:function(a){a=a||window.event;"undefined"!==typeof a.stopPropagation?a.stopPropagation():a.cancelBubble=!0},closed:!1,showing:!1,shown:!1};$.notyRenderer={};
$.notyRenderer.init=function(a){a=Object.create(NotyObject).init(a);a.options.killer&&$.noty.closeAll();a.options.force?$.noty.queue.unshift(a):$.noty.queue.push(a);$.notyRenderer.render();return"object"==$.noty.returns?a:a.options.id};
$.notyRenderer.render=function(){var a=$.noty.queue[0];"object"===$.type(a)?a.options.dismissQueue?0<a.options.maxVisible?$(a.options.layout.container.selector+" > li").length<a.options.maxVisible&&$.notyRenderer.show($.noty.queue.shift()):$.notyRenderer.show($.noty.queue.shift()):$.noty.ontap&&($.notyRenderer.show($.noty.queue.shift()),$.noty.ontap=!1):$.noty.ontap=!0};
$.notyRenderer.show=function(a){a.options.modal&&($.notyRenderer.createModalFor(a),$.notyRenderer.setModalCount(1));a.options.custom?0==a.options.custom.find(a.options.layout.container.selector).length?a.options.custom.append($(a.options.layout.container.object).addClass("i-am-new")):a.options.custom.find(a.options.layout.container.selector).removeClass("i-am-new"):0==$(a.options.layout.container.selector).length?$("body").append($(a.options.layout.container.object).addClass("i-am-new")):$(a.options.layout.container.selector).removeClass("i-am-new");
$.notyRenderer.setLayoutCountFor(a,1);a.show()};$.notyRenderer.createModalFor=function(a){if(0==$(".noty_modal").length){var b=$("<div/>").addClass("noty_modal").addClass(a.options.theme).data("noty_modal_count",0);a.options.theme.modal&&a.options.theme.modal.css&&b.css(a.options.theme.modal.css);b.prependTo($("body")).fadeIn(a.options.animation.fadeSpeed);if(-1<$.inArray("backdrop",a.options.closeWith))b.on("click",function(a){$.noty.closeAll()})}};
$.notyRenderer.getLayoutCountFor=function(a){return $(a.options.layout.container.selector).data("noty_layout_count")||0};$.notyRenderer.setLayoutCountFor=function(a,b){return $(a.options.layout.container.selector).data("noty_layout_count",$.notyRenderer.getLayoutCountFor(a)+b)};$.notyRenderer.getModalCount=function(){return $(".noty_modal").data("noty_modal_count")||0};$.notyRenderer.setModalCount=function(a){return $(".noty_modal").data("noty_modal_count",$.notyRenderer.getModalCount()+a)};
$.fn.noty=function(a){a.custom=$(this);return $.notyRenderer.init(a)};$.noty={};$.noty.queue=[];$.noty.ontap=!0;$.noty.layouts={};$.noty.themes={};$.noty.returns="object";$.noty.store={};$.noty.get=function(a){return $.noty.store.hasOwnProperty(a)?$.noty.store[a]:!1};$.noty.close=function(a){return $.noty.get(a)?$.noty.get(a).close():!1};$.noty.setText=function(a,b){return $.noty.get(a)?$.noty.get(a).setText(b):!1};$.noty.setType=function(a,b){return $.noty.get(a)?$.noty.get(a).setType(b):!1};
$.noty.clearQueue=function(){$.noty.queue=[]};$.noty.closeAll=function(){$.noty.clearQueue();$.each($.noty.store,function(a,b){b.close()})};var windowAlert=window.alert;$.noty.consumeAlert=function(a){window.alert=function(b){a?a.text=b:a={text:b};$.notyRenderer.init(a)}};$.noty.stopConsumeAlert=function(){window.alert=windowAlert};
$.noty.defaults={layout:"top",theme:"defaultTheme",type:"alert",text:"",dismissQueue:!0,template:'<div class="noty_message"><span class="noty_text"></span><div class="noty_close"></div></div>',animation:{open:{height:"toggle"},close:{height:"toggle"},easing:"swing",speed:500,fadeSpeed:"fast"},timeout:!1,force:!1,modal:!1,maxVisible:5,killer:!1,closeWith:["click"],callback:{onShow:function(){},afterShow:function(){},onClose:function(){},afterClose:function(){},onCloseClick:function(){}},buttons:!1};
$(window).on("resize",function(){$.each($.noty.layouts,function(a,b){b.container.style.apply($(b.container.selector))})});window.noty=function(a){return $.notyRenderer.init(a)};
