var $jscomp={scope:{},findInternal:function(e,m,f){e instanceof String&&(e=String(e));for(var k=e.length,h=0;h<k;h++){var p=e[h];if(m.call(f,p,h,e))return{i:h,v:p}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(e,m,f){if(f.get||f.set)throw new TypeError("ES3 does not support getters and setters.");e!=Array.prototype&&e!=Object.prototype&&(e[m]=f.value)};
$jscomp.getGlobal=function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global&&null!=global?global:e};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(e,m,f,k){if(m){f=$jscomp.global;e=e.split(".");for(k=0;k<e.length-1;k++){var h=e[k];h in f||(f[h]={});f=f[h]}e=e[e.length-1];k=f[e];m=m(k);m!=k&&null!=m&&$jscomp.defineProperty(f,e,{configurable:!0,writable:!0,value:m})}};
$jscomp.polyfill("Array.prototype.find",function(e){return e?e:function(e,f){return $jscomp.findInternal(this,e,f).v}},"es6-impl","es3");
(function(){function e(c){return c.type==CKEDITOR.NODE_TEXT&&0<c.getLength()&&(!k||!c.isReadOnly())}function m(c){return!(c.type==CKEDITOR.NODE_ELEMENT&&c.isBlockBoundary(CKEDITOR.tools.extend({},CKEDITOR.dtd.$empty,CKEDITOR.dtd.$nonEditable)))}function f(c,f){function n(a,b){var d=this,c=new CKEDITOR.dom.walker(a);c.guard=b?m:function(a){!m(a)&&(d._.matchBoundary=!0)};c.evaluator=e;c.breakOnFalse=1;a.startContainer.type==CKEDITOR.NODE_TEXT&&(this.textNode=a.startContainer,this.offset=a.startOffset-
1);this._={matchWord:b,walker:c,matchBoundary:!1}}function w(a,b){var d=c.createRange();d.setStart(a.textNode,b?a.offset:a.offset+1);d.setEndAt(c.editable(),CKEDITOR.POSITION_BEFORE_END);return d}function r(a){var b=c.getSelection().getRanges()[0],d=c.editable();b&&!a?(a=b.clone(),a.collapse(!0)):(a=c.createRange(),a.setStartAt(d,CKEDITOR.POSITION_AFTER_START));a.setEndAt(d,CKEDITOR.POSITION_BEFORE_END);return a}var x=new CKEDITOR.style(CKEDITOR.tools.extend({attributes:{"data-cke-highlight":1},fullMatch:1,
ignoreReadonly:1,childRule:function(){return 0}},c.config.find_highlight,!0));n.prototype={next:function(){return this.move()},back:function(){return this.move(!0)},move:function(a){var b=this.textNode;if(null===b)return h.call(this);this._.matchBoundary=!1;if(b&&a&&0<this.offset)this.offset--;else if(b&&this.offset<b.getLength()-1)this.offset++;else{for(b=null;!b&&!(b=this._.walker[a?"previous":"next"].call(this._.walker),this._.matchWord&&!b||this._.walker._.end););this.offset=(this.textNode=b)?
a?b.getLength()-1:0:0}return h.call(this)}};var t=function(a,b){this._={walker:a,cursors:[],rangeLength:b,highlightRange:null,isMatched:0}};t.prototype={toDomRange:function(){var a=c.createRange(),b=this._.cursors;if(1>b.length){var d=this._.walker.textNode;if(d)a.setStartAfter(d);else return null}else d=b[0],b=b[b.length-1],a.setStart(d.textNode,d.offset),a.setEnd(b.textNode,b.offset+1);return a},updateFromDomRange:function(a){var b=new n(a);this._.cursors=[];do a=b.next(),a.character&&this._.cursors.push(a);
while(a.character);this._.rangeLength=this._.cursors.length},setMatched:function(){this._.isMatched=!0},clearMatched:function(){this._.isMatched=!1},isMatched:function(){return this._.isMatched},highlight:function(){if(!(1>this._.cursors.length)){this._.highlightRange&&this.removeHighlight();var a=this.toDomRange(),b=a.createBookmark();x.applyToRange(a,c);a.moveToBookmark(b);this._.highlightRange=a;b=a.startContainer;b.type!=CKEDITOR.NODE_ELEMENT&&(b=b.getParent());b.scrollIntoView();this.updateFromDomRange(a)}},
removeHighlight:function(){if(this._.highlightRange){var a=this._.highlightRange.createBookmark();x.removeFromRange(this._.highlightRange,c);this._.highlightRange.moveToBookmark(a);this.updateFromDomRange(this._.highlightRange);this._.highlightRange=null}},isReadOnly:function(){return this._.highlightRange?this._.highlightRange.startContainer.isReadOnly():0},moveBack:function(){var a=this._.walker.back(),b=this._.cursors;a.hitMatchBoundary&&(this._.cursors=b=[]);b.unshift(a);b.length>this._.rangeLength&&
b.pop();return a},moveNext:function(){var a=this._.walker.next(),b=this._.cursors;a.hitMatchBoundary&&(this._.cursors=b=[]);b.push(a);b.length>this._.rangeLength&&b.shift();return a},getEndCharacter:function(){var a=this._.cursors;return 1>a.length?null:a[a.length-1].character},getNextCharacterRange:function(a){var b,d;d=this._.cursors;d=(b=d[d.length-1])&&b.textNode?new n(w(b)):this._.walker;return new t(d,a)},getCursors:function(){return this._.cursors}};var y=function(a,b){var d=[-1];b&&(a=a.toLowerCase());
for(var c=0;c<a.length;c++)for(d.push(d[c]+1);0<d[c+1]&&a.charAt(c)!=a.charAt(d[c+1]-1);)d[c+1]=d[d[c+1]-1]+1;this._={overlap:d,state:0,ignoreCase:!!b,pattern:a}};y.prototype={feedCharacter:function(a){for(this._.ignoreCase&&(a=a.toLowerCase());;){if(a==this._.pattern.charAt(this._.state))return this._.state++,this._.state==this._.pattern.length?(this._.state=0,2):1;if(this._.state)this._.state=this._.overlap[this._.state];else return 0}},reset:function(){this._.state=0}};var A=/[.,"'?!;: \u0085\u00a0\u1680\u280e\u2028\u2029\u202f\u205f\u3000]/,
z=function(a){if(!a)return!0;var b=a.charCodeAt(0);return 9<=b&&13>=b||8192<=b&&8202>=b||A.test(a)},l={searchRange:null,matchRange:null,find:function(a,b,d,e,f,g){this.matchRange?(this.matchRange.removeHighlight(),this.matchRange=this.matchRange.getNextCharacterRange(a.length)):this.matchRange=new t(new n(this.searchRange),a.length);for(var l=new y(a,!b),q=0,m="%";null!==m;){for(this.matchRange.moveNext();m=this.matchRange.getEndCharacter();){q=l.feedCharacter(m);if(2==q)break;this.matchRange.moveNext().hitMatchBoundary&&
l.reset()}if(2==q){if(d){var k=this.matchRange.getCursors(),h=k[k.length-1],k=k[0],u=c.createRange();u.setStartAt(c.editable(),CKEDITOR.POSITION_AFTER_START);u.setEnd(k.textNode,k.offset);k=u;h=w(h);k.trim();h.trim();k=new n(k,!0);h=new n(h,!0);if(!z(k.back().character)||!z(h.next().character))continue}this.matchRange.setMatched();!1!==f&&this.matchRange.highlight();return!0}}this.matchRange.clearMatched();this.matchRange.removeHighlight();return e&&!g?(this.searchRange=r(1),this.matchRange=null,
arguments.callee.apply(this,Array.prototype.slice.call(arguments).concat([!0]))):!1},replaceCounter:0,replace:function(a,b,d,e,f,g,h){k=1;a=this.hasMatchOptionsChanged(b,e,f);if(!this.matchRange||!this.matchRange.isMatched()||this.matchRange._.isReplaced||this.matchRange.isReadOnly()||a)a&&this.matchRange&&(this.matchRange.clearMatched(),this.matchRange.removeHighlight(),this.matchRange=null),a=this.find(b,e,f,g,!h);else{this.matchRange.removeHighlight();b=this.matchRange.toDomRange();d=c.document.createText(d);
if(!h){var l=c.getSelection();l.selectRanges([b]);c.fire("saveSnapshot")}b.deleteContents();b.insertNode(d);h||(l.selectRanges([b]),c.fire("saveSnapshot"));this.matchRange.updateFromDomRange(b);h||this.matchRange.highlight();this.matchRange._.isReplaced=!0;this.replaceCounter++;a=1}k=0;return a},matchOptions:null,hasMatchOptionsChanged:function(a,b,c){a=[a,b,c].join(".");b=this.matchOptions&&this.matchOptions!=a;this.matchOptions=a;return b}},g=c.lang.find;return{title:g.title,resizable:CKEDITOR.DIALOG_RESIZE_NONE,
minWidth:350,minHeight:170,buttons:[CKEDITOR.dialog.cancelButton(c,{label:c.lang.common.close})],contents:[{id:"find",label:g.find,title:g.find,accessKey:"",elements:[{type:"hbox",widths:["230px","90px"],children:[{type:"text",id:"txtFindFind",label:g.findWhat,isChanged:!1,labelLayout:"horizontal",accessKey:"F"},{type:"button",id:"btnFind",align:"left",style:"width:100%",label:g.find,onClick:function(){var a=this.getDialog();l.find(a.getValueOf("find","txtFindFind"),a.getValueOf("find","txtFindCaseChk"),
a.getValueOf("find","txtFindWordChk"),a.getValueOf("find","txtFindCyclic"))||alert(g.notFoundMsg)}}]},{type:"fieldset",className:"cke_dialog_find_fieldset",label:CKEDITOR.tools.htmlEncode(g.findOptions),style:"margin-top:29px",children:[{type:"vbox",padding:0,children:[{type:"checkbox",id:"txtFindCaseChk",isChanged:!1,label:g.matchCase},{type:"checkbox",id:"txtFindWordChk",isChanged:!1,label:g.matchWord},{type:"checkbox",id:"txtFindCyclic",isChanged:!1,"default":!0,label:g.matchCyclic}]}]}]},{id:"replace",
label:g.replace,accessKey:"M",elements:[{type:"hbox",widths:["230px","90px"],children:[{type:"text",id:"txtFindReplace",label:g.findWhat,isChanged:!1,labelLayout:"horizontal",accessKey:"F"},{type:"button",id:"btnFindReplace",align:"left",style:"width:100%",label:g.replace,onClick:function(){var a=this.getDialog();l.replace(a,a.getValueOf("replace","txtFindReplace"),a.getValueOf("replace","txtReplace"),a.getValueOf("replace","txtReplaceCaseChk"),a.getValueOf("replace","txtReplaceWordChk"),a.getValueOf("replace",
"txtReplaceCyclic"))||alert(g.notFoundMsg)}}]},{type:"hbox",widths:["230px","90px"],children:[{type:"text",id:"txtReplace",label:g.replaceWith,isChanged:!1,labelLayout:"horizontal",accessKey:"R"},{type:"button",id:"btnReplaceAll",align:"left",style:"width:100%",label:g.replaceAll,isChanged:!1,onClick:function(){var a=this.getDialog();l.replaceCounter=0;l.searchRange=r(1);l.matchRange&&(l.matchRange.removeHighlight(),l.matchRange=null);for(c.fire("saveSnapshot");l.replace(a,a.getValueOf("replace",
"txtFindReplace"),a.getValueOf("replace","txtReplace"),a.getValueOf("replace","txtReplaceCaseChk"),a.getValueOf("replace","txtReplaceWordChk"),!1,!0););l.replaceCounter?(alert(g.replaceSuccessMsg.replace(/%1/,l.replaceCounter)),c.fire("saveSnapshot")):alert(g.notFoundMsg)}}]},{type:"fieldset",label:CKEDITOR.tools.htmlEncode(g.findOptions),children:[{type:"vbox",padding:0,children:[{type:"checkbox",id:"txtReplaceCaseChk",isChanged:!1,label:g.matchCase},{type:"checkbox",id:"txtReplaceWordChk",isChanged:!1,
label:g.matchWord},{type:"checkbox",id:"txtReplaceCyclic",isChanged:!1,"default":!0,label:g.matchCyclic}]}]}]}],onLoad:function(){var a=this,b,c=0;this.on("hide",function(){c=0});this.on("show",function(){c=1});this.selectPage=CKEDITOR.tools.override(this.selectPage,function(e){return function(d){e.call(a,d);var f=a._.tabs[d],g;g="find"===d?"txtFindWordChk":"txtReplaceWordChk";b=a.getContentElement(d,"find"===d?"txtFindFind":"txtFindReplace");a.getContentElement(d,g);f.initialized||(CKEDITOR.document.getById(b._.inputId),
f.initialized=!0);if(c){var k;d="find"===d?1:0;var f=1-d,h,l=v.length;for(h=0;h<l;h++)g=this.getContentElement(p[d],v[h][d]),k=this.getContentElement(p[f],v[h][f]),k.setValue(g.getValue())}}})},onShow:function(){l.searchRange=r();var a=this.getParentEditor().getSelection().getSelectedText(),b=this.getContentElement(f,"find"==f?"txtFindFind":"txtFindReplace");b.setValue(a);b.select();this.selectPage(f);this[("find"==f&&this._.editor.readOnly?"hide":"show")+"Page"]("replace")},onHide:function(){var a;
l.matchRange&&l.matchRange.isMatched()&&(l.matchRange.removeHighlight(),(a=l.matchRange.toDomRange())&&c.getSelection().selectRanges([a]),c.focus());delete l.matchRange},onFocus:function(){return"replace"==f?this.getContentElement("replace","txtFindReplace"):this.getContentElement("find","txtFindFind")}}}var k,h=function(){return{textNode:this.textNode,offset:this.offset,character:this.textNode?this.textNode.getText().charAt(this.offset):null,hitMatchBoundary:this._.matchBoundary}},p=["find","replace"],
v=[["txtFindFind","txtFindReplace"],["txtFindCaseChk","txtReplaceCaseChk"],["txtFindWordChk","txtReplaceWordChk"],["txtFindCyclic","txtReplaceCyclic"]];CKEDITOR.dialog.add("find",function(c){return f(c,"find")});CKEDITOR.dialog.add("replace",function(c){return f(c,"replace")})})();
