(function(){var I,R,p,l,S,x,A,f,T,U,J,V,W,r,X,m,B,C,t,D,K,L,q,Y,u,h,E,M,Z,z,N,F,n,y,O,v,G,P,H,aa,Q,ea,ba,w=[].slice,ca={}.hasOwnProperty,da=function(b,a){function c(){this.constructor=b}for(var d in a)ca.call(a,d)&&(b[d]=a[d]);c.prototype=a.prototype;b.prototype=new c;b.__super__=a.prototype;return b},fa=[].indexOf||function(b){for(var a=0,c=this.length;a<c;a++)if(a in this&&this[a]===b)return a;return-1};p={catchupTime:100,initialRate:.03,minTime:250,ghostTime:100,maxProgressPerFrame:20,easeFactor:1.25,
startOnPageLoad:!0,restartOnPushState:!0,restartOnRequestAfter:500,target:"body",elements:{checkInterval:100,selectors:["body"]},eventLag:{minSamples:10,sampleCount:3,lagThreshold:3},ajax:{trackMethods:["GET"],trackWebSockets:!0,ignoreURLs:[]}};u=function(){var b;return null!=(b="undefined"!==typeof performance&&null!==performance?"function"===typeof performance.now?performance.now():void 0:void 0)?b:+new Date};E=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||
window.msRequestAnimationFrame;C=window.cancelAnimationFrame||window.mozCancelAnimationFrame;null==E&&(E=function(b){return setTimeout(b,50)},C=function(b){return clearTimeout(b)});Z=function(b){var a,c;a=u();c=function(){var d;d=u()-a;return 33<=d?(a=u(),b(d,function(){return E(c)})):setTimeout(c,33-d)};return c()};M=function(){var b,a,c;c=arguments[0];a=arguments[1];b=3<=arguments.length?w.call(arguments,2):[];return"function"===typeof c[a]?c[a].apply(c,b):c[a]};t=function(){var b,a,c,d,e,k,g;a=
arguments[0];d=2<=arguments.length?w.call(arguments,1):[];k=0;for(g=d.length;k<g;k++)if(c=d[k])for(b in c)ca.call(c,b)&&(e=c[b],null!=a[b]&&"object"===typeof a[b]&&null!=e&&"object"===typeof e?t(a[b],e):a[b]=e);return a};X=function(b){var a,c,d,e,k;e=c=a=0;for(k=b.length;e<k;e++)d=b[e],c+=Math.abs(d),a++;return c/a};l=function(){function b(){}b.prototype.on=function(a,b,d,e){var c;null==e&&(e=!1);null==this.bindings&&(this.bindings={});null==(c=this.bindings)[a]&&(c[a]=[]);return this.bindings[a].push({handler:b,
ctx:d,once:e})};b.prototype.once=function(a,b,d){return this.on(a,b,d,!0)};b.prototype.off=function(a,b){var c,e;if(null!=(null!=(c=this.bindings)?c[a]:void 0)){if(null==b)return delete this.bindings[a];c=0;for(e=[];c<this.bindings[a].length;)this.bindings[a][c].handler===b?e.push(this.bindings[a].splice(c,1)):e.push(c++);return e}};b.prototype.trigger=function(){var a,b,d,e,k,g,f;d=arguments[0];a=2<=arguments.length?w.call(arguments,1):[];if(null!=(b=this.bindings)&&b[d]){k=0;for(f=[];k<this.bindings[d].length;)g=
this.bindings[d][k],e=g.handler,b=g.ctx,g=g.once,e.apply(null!=b?b:this,a),g?f.push(this.bindings[d].splice(k,1)):f.push(k++);return f}};return b}();f=window.Pace||{};window.Pace=f;t(f,l.prototype);h=f.options=t({},p,window.paceOptions,function(b,a){var c;null==b&&(b="options");null==a&&(a=!0);if(c=document.querySelector("[data-pace-"+b+"]")){c=c.getAttribute("data-pace-"+b);if(!a)return c;try{return JSON.parse(c)}catch(d){return"undefined"!==typeof console&&null!==console?console.error("Error parsing inline pace options",
d):void 0}}}());Q=["ajax","document","eventLag","elements"];l=0;for(x=Q.length;l<x;l++)n=Q[l],!0===h[n]&&(h[n]=p[n]);A=function(b){function a(){return ea=a.__super__.constructor.apply(this,arguments)}da(a,b);return a}(Error);R=function(){function b(){this.progress=0}b.prototype.getElement=function(){var a;if(null==this.el){a=document.querySelector(h.target);if(!a)throw new A;this.el=document.createElement("div");this.el.className="pace pace-active";document.body.className=document.body.className.replace(/pace-done/g,
"");document.body.className+=" pace-running";this.el.innerHTML='<div class="pace-progress">\n  <div class="pace-progress-inner"></div>\n</div>\n<div class="pace-activity"></div>';null!=a.firstChild?a.insertBefore(this.el,a.firstChild):a.appendChild(this.el)}return this.el};b.prototype.finish=function(){var a;a=this.getElement();a.className=a.className.replace("pace-active","");a.className+=" pace-inactive";document.body.className=document.body.className.replace("pace-running","");return document.body.className+=
" pace-done"};b.prototype.update=function(a){this.progress=a;return this.render()};b.prototype.destroy=function(){try{this.getElement().parentNode.removeChild(this.getElement())}catch(a){A=a}return this.el=void 0};b.prototype.render=function(){var a,b,d,e,k,g;if(null==document.querySelector(h.target))return!1;a=this.getElement();d="translate3d("+this.progress+"%, 0, 0)";g=["webkitTransform","msTransform","transform"];e=0;for(k=g.length;e<k;e++)b=g[e],a.children[0].style[b]=d;if(!this.lastRenderedProgress||
this.lastRenderedProgress|0!==this.progress|0)a.children[0].setAttribute("data-progress-text",""+(this.progress|0)+"%"),100<=this.progress?b="99":(b=10>this.progress?"0":"",b+=this.progress|0),a.children[0].setAttribute("data-progress",""+b);return this.lastRenderedProgress=this.progress};b.prototype.done=function(){return 100<=this.progress};return b}();p=function(){function b(){this.bindings={}}b.prototype.trigger=function(a,b){var c,e,k,g,f;if(null!=this.bindings[a]){g=this.bindings[a];f=[];e=
0;for(k=g.length;e<k;e++)c=g[e],f.push(c.call(this,b));return f}};b.prototype.on=function(a,b){var c;null==(c=this.bindings)[a]&&(c[a]=[]);return this.bindings[a].push(b)};return b}();P=window.XMLHttpRequest;G=window.XDomainRequest;v=window.WebSocket;D=function(b,a){var c,d;d=[];for(c in a.prototype)try{null==b[c]&&"function"!==typeof a[c]?"function"===typeof Object.defineProperty?d.push(Object.defineProperty(b,c,{get:function(){return a.prototype[c]},configurable:!0,enumerable:!0})):d.push(b[c]=
a.prototype[c]):d.push(void 0)}catch(e){}return d};q=[];f.ignore=function(){var b,a;a=arguments[0];b=2<=arguments.length?w.call(arguments,1):[];q.unshift("ignore");b=a.apply(null,b);q.shift();return b};f.track=function(){var b,a;a=arguments[0];b=2<=arguments.length?w.call(arguments,1):[];q.unshift("track");b=a.apply(null,b);q.shift();return b};F=function(b){var a;null==b&&(b="GET");return"track"===q[0]?"force":!q.length&&h.ajax&&("socket"===b&&h.ajax.trackWebSockets||(a=b.toUpperCase(),0<=fa.call(h.ajax.trackMethods,
a)))?!0:!1};T=function(b){function a(){var b,d=this;a.__super__.constructor.apply(this,arguments);b=function(a){var b;b=a.open;return a.open=function(c,e,k){F(c)&&d.trigger("request",{type:c,url:e,request:a});return b.apply(a,arguments)}};window.XMLHttpRequest=function(a){a=new P(a);b(a);return a};try{D(window.XMLHttpRequest,P)}catch(e){}if(null!=G){window.XDomainRequest=function(){var a;a=new G;b(a);return a};try{D(window.XDomainRequest,G)}catch(e){}}if(null!=v&&h.ajax.trackWebSockets){window.WebSocket=
function(a,b){var c;c=null!=b?new v(a,b):new v(a);F("socket")&&d.trigger("request",{type:"socket",url:a,protocols:b,request:c});return c};try{D(window.WebSocket,v)}catch(e){}}}da(a,b);return a}(p);H=null;K=function(){null==H&&(H=new T);return H};N=function(b){var a,c,d,e;e=h.ajax.ignoreURLs;c=0;for(d=e.length;c<d;c++)if(a=e[c],"string"===typeof a){if(-1!==b.indexOf(a))return!0}else if(a.test(b))return!0;return!1};K().on("request",function(b){var a,c,d,e;e=b.type;d=b.request;if(!(N(b.url)||f.running||
!1===h.restartOnRequestAfter&&"force"!==F(e)))return c=arguments,a=h.restartOnRequestAfter||0,"boolean"===typeof a&&(a=0),setTimeout(function(){var a,b,h,m;if("socket"===e?2>d.readyState:0<(a=d.readyState)&&4>a){f.restart();h=f.sources;m=[];a=0;for(b=h.length;a<b;a++)if(n=h[a],n instanceof I){n.watch.apply(n,c);break}else m.push(void 0);return m}},a)});I=function(){function b(){var a=this;this.elements=[];K().on("request",function(){return a.watch.apply(a,arguments)})}b.prototype.watch=function(a){var b,
d;d=a.type;b=a.request;if(!N(a.url))return a="socket"===d?new V(b):new W(b),this.elements.push(a)};return b}();W=function(){return function(b){var a,c,d,e,f,g=this;this.progress=0;if(null!=window.ProgressEvent)for(b.addEventListener("progress",function(a){return a.lengthComputable?g.progress=100*a.loaded/a.total:g.progress+=(100-g.progress)/2},!1),f=["load","abort","timeout","error"],c=0,d=f.length;c<d;c++)a=f[c],b.addEventListener(a,function(){return g.progress=100},!1);else e=b.onreadystatechange,
b.onreadystatechange=function(){var a;0===(a=b.readyState)||4===a?g.progress=100:3===b.readyState&&(g.progress=50);return"function"===typeof e?e.apply(null,arguments):void 0}}}();V=function(){return function(b){var a,c,d,e,f=this;this.progress=0;e=["error","open"];c=0;for(d=e.length;c<d;c++)a=e[c],b.addEventListener(a,function(){return f.progress=100},!1)}}();l=function(){return function(b){var a,c,d;null==b&&(b={});this.elements=[];null==b.selectors&&(b.selectors=[]);d=b.selectors;a=0;for(c=d.length;a<
c;a++)b=d[a],this.elements.push(new S(b))}}();S=function(){function b(a){this.selector=a;this.progress=0;this.check()}b.prototype.check=function(){var a=this;return document.querySelector(this.selector)?this.done():setTimeout(function(){return a.check()},h.elements.checkInterval)};b.prototype.done=function(){return this.progress=100};return b}();p=function(){function b(){var a,b,d=this;this.progress=null!=(b=this.states[document.readyState])?b:100;a=document.onreadystatechange;document.onreadystatechange=
function(){null!=d.states[document.readyState]&&(d.progress=d.states[document.readyState]);return"function"===typeof a?a.apply(null,arguments):void 0}}b.prototype.states={loading:0,interactive:50,complete:100};return b}();x=function(){return function(){var b,a,c,d,e,f=this;b=this.progress=0;e=[];d=0;c=u();a=setInterval(function(){var g;g=u()-c-50;c=u();e.push(g);e.length>h.eventLag.sampleCount&&e.shift();b=X(e);return++d>=h.eventLag.minSamples&&b<h.eventLag.lagThreshold?(f.progress=100,clearInterval(a)):
f.progress=3/(b+3)*100},50)}}();J=function(){function b(a){this.source=a;this.last=this.sinceLastUpdate=0;this.rate=h.initialRate;this.progress=this.lastProgress=this.catchup=0;null!=this.source&&(this.progress=M(this.source,"progress"))}b.prototype.tick=function(a,b){null==b&&(b=M(this.source,"progress"));100<=b&&(this.done=!0);b===this.last?this.sinceLastUpdate+=a:(this.sinceLastUpdate&&(this.rate=(b-this.last)/this.sinceLastUpdate),this.catchup=(b-this.progress)/h.catchupTime,this.sinceLastUpdate=
0,this.last=b);b>this.progress&&(this.progress+=this.catchup*a);this.progress+=(1-Math.pow(this.progress/100,h.easeFactor))*this.rate*a;this.progress=Math.min(this.lastProgress+h.maxProgressPerFrame,this.progress);this.progress=Math.max(0,this.progress);return this.lastProgress=this.progress=Math.min(100,this.progress)};return b}();B=r=O=m=z=y=null;f.running=!1;L=function(){if(h.restartOnPushState)return f.restart()};null!=window.history.pushState&&(aa=window.history.pushState,window.history.pushState=
function(){L();return aa.apply(window.history,arguments)});null!=window.history.replaceState&&(ba=window.history.replaceState,window.history.replaceState=function(){L();return ba.apply(window.history,arguments)});U={ajax:I,elements:l,document:p,eventLag:x};(Y=function(){var b,a,c,d,e;f.sources=y=[];e=["ajax","elements","document","eventLag"];a=0;for(d=e.length;a<d;a++)b=e[a],!1!==h[b]&&y.push(new U[b](h[b]));b=null!=(c=h.extraSources)?c:[];c=0;for(a=b.length;c<a;c++)n=b[c],y.push(new n(h));f.bar=
m=new R;z=[];return O=new J})();f.stop=function(){f.trigger("stop");f.running=!1;m.destroy();B=!0;null!=r&&("function"===typeof C&&C(r),r=null);return Y()};f.restart=function(){f.trigger("restart");f.stop();return f.start()};f.go=function(){var b;f.running=!0;m.render();b=u();B=!1;return r=Z(function(a,c){var d,e,k,g,l,p,q,r,t,v,w,x;d=q=0;e=!0;g=r=0;for(v=y.length;r<v;g=++r)for(n=y[g],p=null!=z[g]?z[g]:z[g]=[],g=null!=(x=n.elements)?x:[n],l=t=0,w=g.length;t<w;l=++t)k=g[l],k=null!=p[l]?p[l]:p[l]=new J(k),
e&=k.done,k.done||(d++,q+=k.tick(a));m.update(O.tick(a,q/d));return m.done()||e||B?(m.update(100),f.trigger("done"),setTimeout(function(){m.finish();f.running=!1;return f.trigger("hide")},Math.max(h.ghostTime,Math.max(h.minTime-(u()-b),0)))):c()})};f.start=function(b){t(h,b);f.running=!0;try{m.render()}catch(a){A=a}return document.querySelector(".pace")?(f.trigger("start"),f.go()):setTimeout(f.start,50)};"function"===typeof define&&define.amd?define(["pace"],function(){return f}):"object"===typeof exports?
module.exports=f:h.startOnPageLoad&&f.start()}).call(this);
