(function(){var I,R,q,m,S,z,A,h,T,U,J,V,W,s,X,n,B,C,u,D,K,L,r,Y,t,k,E,M,Z,y,N,F,p,x,O,v,G,P,H,$,Q,da,aa,w=[].slice,ba={}.hasOwnProperty,ca=function(b,a){function d(){this.constructor=b}for(var c in a)ba.call(a,c)&&(b[c]=a[c]);d.prototype=a.prototype;b.prototype=new d;b.__super__=a.prototype;return b},ea=[].indexOf||function(b){for(var a=0,d=this.length;a<d;a++)if(a in this&&this[a]===b)return a;return-1};q={catchupTime:100,initialRate:0.03,minTime:250,ghostTime:100,maxProgressPerFrame:20,easeFactor:1.25,
startOnPageLoad:!0,restartOnPushState:!0,restartOnRequestAfter:500,target:"body",elements:{checkInterval:100,selectors:["body"]},eventLag:{minSamples:10,sampleCount:3,lagThreshold:3},ajax:{trackMethods:["GET"],trackWebSockets:!0,ignoreURLs:[]}};t=function(){var b;return null!=(b="undefined"!==typeof performance&&null!==performance?"function"===typeof performance.now?performance.now():void 0:void 0)?b:+new Date};E=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||
window.msRequestAnimationFrame;C=window.cancelAnimationFrame||window.mozCancelAnimationFrame;null==E&&(E=function(b){return setTimeout(b,50)},C=function(b){return clearTimeout(b)});Z=function(b){var a,d;a=t();d=function(){var c;c=t()-a;return 33<=c?(a=t(),b(c,function(){return E(d)})):setTimeout(d,33-c)};return d()};M=function(){var b,a,d;d=arguments[0];a=arguments[1];b=3<=arguments.length?w.call(arguments,2):[];return"function"===typeof d[a]?d[a].apply(d,b):d[a]};u=function(){var b,a,d,c,e,f,g;a=
arguments[0];c=2<=arguments.length?w.call(arguments,1):[];f=0;for(g=c.length;f<g;f++)if(d=c[f])for(b in d)ba.call(d,b)&&(e=d[b],null!=a[b]&&"object"===typeof a[b]&&null!=e&&"object"===typeof e?u(a[b],e):a[b]=e);return a};X=function(b){var a,d,c,e,f;e=d=a=0;for(f=b.length;e<f;e++)c=b[e],d+=Math.abs(c),a++;return d/a};m=function(){function b(){}b.prototype.on=function(a,b,c,e){var f;null==e&&(e=!1);null==this.bindings&&(this.bindings={});null==(f=this.bindings)[a]&&(f[a]=[]);return this.bindings[a].push({handler:b,
ctx:c,once:e})};b.prototype.once=function(a,b,c){return this.on(a,b,c,!0)};b.prototype.off=function(a,b){var c,e;if(null!=(null!=(c=this.bindings)?c[a]:void 0)){if(null==b)return delete this.bindings[a];c=0;for(e=[];c<this.bindings[a].length;)this.bindings[a][c].handler===b?e.push(this.bindings[a].splice(c,1)):e.push(c++);return e}};b.prototype.trigger=function(){var a,b,c,e,f,g,l;c=arguments[0];a=2<=arguments.length?w.call(arguments,1):[];if(null!=(b=this.bindings)&&b[c]){f=0;for(l=[];f<this.bindings[c].length;)g=
this.bindings[c][f],e=g.handler,b=g.ctx,g=g.once,e.apply(null!=b?b:this,a),g?l.push(this.bindings[c].splice(f,1)):l.push(f++);return l}};return b}();h=window.Pace||{};window.Pace=h;u(h,m.prototype);k=h.options=u({},q,window.paceOptions,function(b,a){var d;null==b&&(b="options");null==a&&(a=!0);if(d=document.querySelector("[data-pace-"+b+"]")){d=d.getAttribute("data-pace-"+b);if(!a)return d;try{return JSON.parse(d)}catch(c){return"undefined"!==typeof console&&null!==console?console.error("Error parsing inline pace options",
c):void 0}}}());Q=["ajax","document","eventLag","elements"];m=0;for(z=Q.length;m<z;m++)p=Q[m],!0===k[p]&&(k[p]=q[p]);A=function(b){function a(){return da=a.__super__.constructor.apply(this,arguments)}ca(a,b);return a}(Error);R=function(){function b(){this.progress=0}b.prototype.getElement=function(){var a;if(null==this.el){a=document.querySelector(k.target);if(!a)throw new A;this.el=document.createElement("div");this.el.className="pace pace-active";document.body.className=document.body.className.replace(/pace-done/g,
"");document.body.className+=" pace-running";this.el.innerHTML='<div class="pace-progress">\n  <div class="pace-progress-inner"></div>\n</div>\n<div class="pace-activity"></div>';null!=a.firstChild?a.insertBefore(this.el,a.firstChild):a.appendChild(this.el)}return this.el};b.prototype.finish=function(){var a;a=this.getElement();a.className=a.className.replace("pace-active","");a.className+=" pace-inactive";document.body.className=document.body.className.replace("pace-running","");return document.body.className+=
" pace-done"};b.prototype.update=function(a){this.progress=a;return this.render()};b.prototype.destroy=function(){try{this.getElement().parentNode.removeChild(this.getElement())}catch(a){A=a}return this.el=void 0};b.prototype.render=function(){var a,b,c,e,f,g;if(null==document.querySelector(k.target))return!1;a=this.getElement();c="translate3d("+this.progress+"%, 0, 0)";g=["webkitTransform","msTransform","transform"];e=0;for(f=g.length;e<f;e++)b=g[e],a.children[0].style[b]=c;if(!this.lastRenderedProgress||
this.lastRenderedProgress|0!==this.progress|0)a.children[0].setAttribute("data-progress-text",""+(this.progress|0)+"%"),100<=this.progress?b="99":(b=10>this.progress?"0":"",b+=this.progress|0),a.children[0].setAttribute("data-progress",""+b);return this.lastRenderedProgress=this.progress};b.prototype.done=function(){return 100<=this.progress};return b}();q=function(){function b(){this.bindings={}}b.prototype.trigger=function(a,b){var c,e,f,g,l;if(null!=this.bindings[a]){g=this.bindings[a];l=[];e=
0;for(f=g.length;e<f;e++)c=g[e],l.push(c.call(this,b));return l}};b.prototype.on=function(a,b){var c;null==(c=this.bindings)[a]&&(c[a]=[]);return this.bindings[a].push(b)};return b}();P=window.XMLHttpRequest;G=window.XDomainRequest;v=window.WebSocket;D=function(b,a){var d,c;c=[];for(d in a.prototype)try{null==b[d]&&"function"!==typeof a[d]?"function"===typeof Object.defineProperty?c.push(Object.defineProperty(b,d,{get:function(){return a.prototype[d]},configurable:!0,enumerable:!0})):c.push(b[d]=
a.prototype[d]):c.push(void 0)}catch(e){}return c};r=[];h.ignore=function(){var b,a;a=arguments[0];b=2<=arguments.length?w.call(arguments,1):[];r.unshift("ignore");b=a.apply(null,b);r.shift();return b};h.track=function(){var b,a;a=arguments[0];b=2<=arguments.length?w.call(arguments,1):[];r.unshift("track");b=a.apply(null,b);r.shift();return b};F=function(b){var a;null==b&&(b="GET");return"track"===r[0]?"force":!r.length&&k.ajax&&("socket"===b&&k.ajax.trackWebSockets||(a=b.toUpperCase(),0<=ea.call(k.ajax.trackMethods,
a)))?!0:!1};T=function(b){function a(){var b,c=this;a.__super__.constructor.apply(this,arguments);b=function(b){var a;a=b.open;return b.open=function(d,e,f){F(d)&&c.trigger("request",{type:d,url:e,request:b});return a.apply(b,arguments)}};window.XMLHttpRequest=function(a){a=new P(a);b(a);return a};try{D(window.XMLHttpRequest,P)}catch(e){}if(null!=G){window.XDomainRequest=function(){var a;a=new G;b(a);return a};try{D(window.XDomainRequest,G)}catch(f){}}if(null!=v&&k.ajax.trackWebSockets){window.WebSocket=
function(a,b){var d;d=null!=b?new v(a,b):new v(a);F("socket")&&c.trigger("request",{type:"socket",url:a,protocols:b,request:d});return d};try{D(window.WebSocket,v)}catch(g){}}}ca(a,b);return a}(q);H=null;K=function(){null==H&&(H=new T);return H};N=function(b){var a,d,c,e;e=k.ajax.ignoreURLs;d=0;for(c=e.length;d<c;d++)if(a=e[d],"string"===typeof a){if(-1!==b.indexOf(a))return!0}else if(a.test(b))return!0;return!1};K().on("request",function(b){var a,d,c,e;e=b.type;c=b.request;if(!(N(b.url)||h.running||
!1===k.restartOnRequestAfter&&"force"!==F(e)))return d=arguments,a=k.restartOnRequestAfter||0,"boolean"===typeof a&&(a=0),setTimeout(function(){var a,b,k,n;if("socket"===e?2>c.readyState:0<(a=c.readyState)&&4>a){h.restart();k=h.sources;n=[];a=0;for(b=k.length;a<b;a++)if(p=k[a],p instanceof I){p.watch.apply(p,d);break}else n.push(void 0);return n}},a)});I=function(){function b(){var a=this;this.elements=[];K().on("request",function(){return a.watch.apply(a,arguments)})}b.prototype.watch=function(a){var b,
c;c=a.type;b=a.request;if(!N(a.url))return a="socket"===c?new V(b):new W(b),this.elements.push(a)};return b}();W=function(){return function(b){var a,d,c,e,f,g=this;this.progress=0;if(null!=window.ProgressEvent)for(b.addEventListener("progress",function(a){return a.lengthComputable?g.progress=100*a.loaded/a.total:g.progress+=(100-g.progress)/2},!1),f=["load","abort","timeout","error"],d=0,c=f.length;d<c;d++)a=f[d],b.addEventListener(a,function(){return g.progress=100},!1);else e=b.onreadystatechange,
b.onreadystatechange=function(){var a;0===(a=b.readyState)||4===a?g.progress=100:3===b.readyState&&(g.progress=50);return"function"===typeof e?e.apply(null,arguments):void 0}}}();V=function(){return function(b){var a,d,c,e,f=this;this.progress=0;e=["error","open"];d=0;for(c=e.length;d<c;d++)a=e[d],b.addEventListener(a,function(){return f.progress=100},!1)}}();m=function(){return function(b){var a,d,c;null==b&&(b={});this.elements=[];null==b.selectors&&(b.selectors=[]);c=b.selectors;a=0;for(d=c.length;a<
d;a++)b=c[a],this.elements.push(new S(b))}}();S=function(){function b(a){this.selector=a;this.progress=0;this.check()}b.prototype.check=function(){var a=this;return document.querySelector(this.selector)?this.done():setTimeout(function(){return a.check()},k.elements.checkInterval)};b.prototype.done=function(){return this.progress=100};return b}();q=function(){function b(){var a,b,c=this;this.progress=null!=(b=this.states[document.readyState])?b:100;a=document.onreadystatechange;document.onreadystatechange=
function(){null!=c.states[document.readyState]&&(c.progress=c.states[document.readyState]);return"function"===typeof a?a.apply(null,arguments):void 0}}b.prototype.states={loading:0,interactive:50,complete:100};return b}();z=function(){return function(){var b,a,d,c,e,f=this;b=this.progress=0;e=[];c=0;d=t();a=setInterval(function(){var g;g=t()-d-50;d=t();e.push(g);e.length>k.eventLag.sampleCount&&e.shift();b=X(e);return++c>=k.eventLag.minSamples&&b<k.eventLag.lagThreshold?(f.progress=100,clearInterval(a)):
f.progress=3/(b+3)*100},50)}}();J=function(){function b(a){this.source=a;this.last=this.sinceLastUpdate=0;this.rate=k.initialRate;this.progress=this.lastProgress=this.catchup=0;null!=this.source&&(this.progress=M(this.source,"progress"))}b.prototype.tick=function(a,b){var c;null==b&&(b=M(this.source,"progress"));100<=b&&(this.done=!0);b===this.last?this.sinceLastUpdate+=a:(this.sinceLastUpdate&&(this.rate=(b-this.last)/this.sinceLastUpdate),this.catchup=(b-this.progress)/k.catchupTime,this.sinceLastUpdate=
0,this.last=b);b>this.progress&&(this.progress+=this.catchup*a);c=1-Math.pow(this.progress/100,k.easeFactor);this.progress+=c*this.rate*a;this.progress=Math.min(this.lastProgress+k.maxProgressPerFrame,this.progress);this.progress=Math.max(0,this.progress);return this.lastProgress=this.progress=Math.min(100,this.progress)};return b}();B=s=O=n=y=x=null;h.running=!1;L=function(){if(k.restartOnPushState)return h.restart()};null!=window.history.pushState&&($=window.history.pushState,window.history.pushState=
function(){L();return $.apply(window.history,arguments)});null!=window.history.replaceState&&(aa=window.history.replaceState,window.history.replaceState=function(){L();return aa.apply(window.history,arguments)});U={ajax:I,elements:m,document:q,eventLag:z};(Y=function(){var b,a,d,c,e;h.sources=x=[];e=["ajax","elements","document","eventLag"];a=0;for(c=e.length;a<c;a++)b=e[a],!1!==k[b]&&x.push(new U[b](k[b]));b=null!=(d=k.extraSources)?d:[];d=0;for(a=b.length;d<a;d++)p=b[d],x.push(new p(k));h.bar=n=
new R;y=[];return O=new J})();h.stop=function(){h.trigger("stop");h.running=!1;n.destroy();B=!0;null!=s&&("function"===typeof C&&C(s),s=null);return Y()};h.restart=function(){h.trigger("restart");h.stop();return h.start()};h.go=function(){var b;h.running=!0;n.render();b=t();B=!1;return s=Z(function(a,d){var c,e,f,g,l,m,q,r,s,u,v,w;c=q=0;e=!0;g=r=0;for(u=x.length;r<u;g=++r)for(p=x[g],m=null!=y[g]?y[g]:y[g]=[],g=null!=(w=p.elements)?w:[p],l=s=0,v=g.length;s<v;l=++s)f=g[l],f=null!=m[l]?m[l]:m[l]=new J(f),
e&=f.done,f.done||(c++,q+=f.tick(a));n.update(O.tick(a,q/c));return n.done()||e||B?(n.update(100),h.trigger("done"),setTimeout(function(){n.finish();h.running=!1;return h.trigger("hide")},Math.max(k.ghostTime,Math.max(k.minTime-(t()-b),0)))):d()})};h.start=function(b){u(k,b);h.running=!0;try{n.render()}catch(a){A=a}return document.querySelector(".pace")?(h.trigger("start"),h.go()):setTimeout(h.start,50)};"function"===typeof define&&define.amd?define(["pace"],function(){return h}):"object"===typeof exports?
module.exports=h:k.startOnPageLoad&&h.start()}).call(this);
