/*
: Copyright (c) 2012-2015 Dan Grossman. All rights reserved.
 @license: Licensed under the MIT license. See http://www.opensource.org/licenses/mit-license.php
 @website: https://www.improvely.com/
*/
var $jscomp={scope:{},findInternal:function(f,m,d){f instanceof String&&(f=String(f));for(var e=f.length,p=0;p<e;p++){var a=f[p];if(m.call(d,a,p,f))return{i:p,v:a}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(f,m,d){if(d.get||d.set)throw new TypeError("ES3 does not support getters and setters.");f!=Array.prototype&&f!=Object.prototype&&(f[m]=d.value)};
$jscomp.getGlobal=function(f){return"undefined"!=typeof window&&window===f?f:"undefined"!=typeof global&&null!=global?global:f};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(f,m,d,e){if(m){d=$jscomp.global;f=f.split(".");for(e=0;e<f.length-1;e++){var p=f[e];p in d||(d[p]={});d=d[p]}f=f[f.length-1];e=d[f];m=m(e);m!=e&&null!=m&&$jscomp.defineProperty(d,f,{configurable:!0,writable:!0,value:m})}};
$jscomp.polyfill("Array.prototype.find",function(f){return f?f:function(f,d){return $jscomp.findInternal(this,f,d).v}},"es6-impl","es3");
(function(f,m){if("function"===typeof define&&define.amd)define(["moment","jquery","exports"],function(d,a,b){f.daterangepicker=m(f,b,d,a)});else if("undefined"!==typeof exports){var d=require("moment"),e;try{e=require("jquery")}catch(p){if(e=window.jQuery,!e)throw Error("jQuery dependency not found");}m(f,exports,d,e)}else f.daterangepicker=m(f,{},f.moment,f.jQuery||f.Zepto||f.ender||f.$)})(this,function(f,m,d,e){var p=function(a,b,c){this.parentEl="body";this.element=e(a);this.isShowing=!1;if("object"!==
typeof b||null===b)b={};this.parentEl="object"===typeof b&&b.parentEl&&e(b.parentEl).length?e(b.parentEl):e(this.parentEl);this.container=e('<div class="daterangepicker dropdown-menu"><div class="calendar first left"></div><div class="calendar second right"></div><div class="ranges"><div class="range_inputs"><div class="daterangepicker_start_input"><label for="daterangepicker_start"></label><input class="input-mini" type="text" name="daterangepicker_start" value="" /></div><div class="daterangepicker_end_input"><label for="daterangepicker_end"></label><input class="input-mini" type="text" name="daterangepicker_end" value="" /></div><button class="applyBtn" disabled="disabled"></button>&nbsp;<button class="cancelBtn"></button></div></div></div>').appendTo(this.parentEl);
this.setOptions(b,c);this.container.find(".calendar").on("click.daterangepicker",".prev",e.proxy(this.clickPrev,this)).on("click.daterangepicker",".next",e.proxy(this.clickNext,this)).on("click.daterangepicker","td.available",e.proxy(this.clickDate,this)).on("mouseenter.daterangepicker","td.available",e.proxy(this.hoverDate,this)).on("mouseleave.daterangepicker","td.available",e.proxy(this.updateFormInputs,this)).on("change.daterangepicker","select.yearselect",e.proxy(this.updateMonthYear,this)).on("change.daterangepicker",
"select.monthselect",e.proxy(this.updateMonthYear,this)).on("change.daterangepicker","select.hourselect,select.minuteselect,select.secondselect,select.ampmselect",e.proxy(this.updateTime,this));this.container.find(".ranges").on("click.daterangepicker","button.applyBtn",e.proxy(this.clickApply,this)).on("click.daterangepicker","button.cancelBtn",e.proxy(this.clickCancel,this)).on("click.daterangepicker",".daterangepicker_start_input,.daterangepicker_end_input",e.proxy(this.showCalendars,this)).on("change.daterangepicker",
".daterangepicker_start_input,.daterangepicker_end_input",e.proxy(this.inputsChanged,this)).on("keydown.daterangepicker",".daterangepicker_start_input,.daterangepicker_end_input",e.proxy(this.inputsKeydown,this)).on("click.daterangepicker","li",e.proxy(this.clickRange,this)).on("mouseenter.daterangepicker","li",e.proxy(this.enterRange,this)).on("mouseleave.daterangepicker","li",e.proxy(this.updateFormInputs,this));if(this.element.is("input"))this.element.on({"click.daterangepicker":e.proxy(this.show,
this),"focus.daterangepicker":e.proxy(this.show,this),"keyup.daterangepicker":e.proxy(this.updateFromControl,this),"keydown.daterangepicker":e.proxy(this.keydown,this)});else this.element.on("click.daterangepicker",e.proxy(this.toggle,this))};p.prototype={constructor:p,setOptions:function(a,b){this.startDate=d().startOf("day");this.endDate=d().endOf("day");this.timeZone=d().utcOffset();this.timePickerSeconds=this.timePicker=this.showWeekNumbers=this.showDropdowns=this.dateLimit=this.maxDate=this.minDate=
!1;this.timePickerIncrement=30;this.timePicker12Hour=!0;this.singleDatePicker=!1;this.ranges={};this.opens="right";this.element.hasClass("pull-right")&&(this.opens="left");this.drops="down";this.element.hasClass("dropup")&&(this.drops="up");this.buttonClasses=["btn","btn-small btn-sm"];this.applyClass="btn-success";this.cancelClass="btn-default";this.format="MM/DD/YYYY";this.separator=" - ";this.locale={applyLabel:"Apply",cancelLabel:"Cancel",fromLabel:"From",toLabel:"To",weekLabel:"W",customRangeLabel:"Custom Range",
daysOfWeek:d.weekdaysMin(),monthNames:d.monthsShort(),firstDay:d.localeData()._week.dow};this.cb=function(){};"string"===typeof a.format&&(this.format=a.format);"string"===typeof a.separator&&(this.separator=a.separator);"string"===typeof a.startDate&&(this.startDate=d(a.startDate,this.format));"string"===typeof a.endDate&&(this.endDate=d(a.endDate,this.format));"string"===typeof a.minDate&&(this.minDate=d(a.minDate,this.format));"string"===typeof a.maxDate&&(this.maxDate=d(a.maxDate,this.format));
"object"===typeof a.startDate&&(this.startDate=d(a.startDate));"object"===typeof a.endDate&&(this.endDate=d(a.endDate));"object"===typeof a.minDate&&(this.minDate=d(a.minDate));"object"===typeof a.maxDate&&(this.maxDate=d(a.maxDate));"string"===typeof a.applyClass&&(this.applyClass=a.applyClass);"string"===typeof a.cancelClass&&(this.cancelClass=a.cancelClass);"object"===typeof a.dateLimit&&(this.dateLimit=a.dateLimit);"object"===typeof a.locale&&("object"===typeof a.locale.daysOfWeek&&(this.locale.daysOfWeek=
a.locale.daysOfWeek.slice()),"object"===typeof a.locale.monthNames&&(this.locale.monthNames=a.locale.monthNames.slice()),"number"===typeof a.locale.firstDay&&(this.locale.firstDay=a.locale.firstDay),"string"===typeof a.locale.applyLabel&&(this.locale.applyLabel=a.locale.applyLabel),"string"===typeof a.locale.cancelLabel&&(this.locale.cancelLabel=a.locale.cancelLabel),"string"===typeof a.locale.fromLabel&&(this.locale.fromLabel=a.locale.fromLabel),"string"===typeof a.locale.toLabel&&(this.locale.toLabel=
a.locale.toLabel),"string"===typeof a.locale.weekLabel&&(this.locale.weekLabel=a.locale.weekLabel),"string"===typeof a.locale.customRangeLabel&&(this.locale.customRangeLabel=a.locale.customRangeLabel));"string"===typeof a.opens&&(this.opens=a.opens);"string"===typeof a.drops&&(this.drops=a.drops);"boolean"===typeof a.showWeekNumbers&&(this.showWeekNumbers=a.showWeekNumbers);"string"===typeof a.buttonClasses&&(this.buttonClasses=[a.buttonClasses]);"object"===typeof a.buttonClasses&&(this.buttonClasses=
a.buttonClasses);"boolean"===typeof a.showDropdowns&&(this.showDropdowns=a.showDropdowns);"boolean"===typeof a.singleDatePicker&&(this.singleDatePicker=a.singleDatePicker)&&(this.endDate=this.startDate.clone());"boolean"===typeof a.timePicker&&(this.timePicker=a.timePicker);"boolean"===typeof a.timePickerSeconds&&(this.timePickerSeconds=a.timePickerSeconds);"number"===typeof a.timePickerIncrement&&(this.timePickerIncrement=a.timePickerIncrement);"boolean"===typeof a.timePicker12Hour&&(this.timePicker12Hour=
a.timePicker12Hour);if(0!=this.locale.firstDay)for(var c=this.locale.firstDay;0<c;)this.locale.daysOfWeek.push(this.locale.daysOfWeek.shift()),c--;var n,h;if("undefined"===typeof a.startDate&&"undefined"===typeof a.endDate&&e(this.element).is("input[type=text]")){var g=e(this.element).val(),k=g.split(this.separator),c=n=null;2==k.length?(c=d(k[0],this.format),n=d(k[1],this.format)):this.singleDatePicker&&""!==g&&(c=d(g,this.format),n=d(g,this.format));null!==c&&null!==n&&(this.startDate=c,this.endDate=
n)}"string"===typeof a.timeZone||"number"===typeof a.timeZone?(this.timeZone="string"===typeof a.timeZone&&"undefined"!==typeof d.tz?-1*d.tz.zone(a.timeZone).parse(new Date):a.timeZone,this.startDate.utcOffset(this.timeZone),this.endDate.utcOffset(this.timeZone)):this.timeZone=d(this.startDate).utcOffset();if("object"===typeof a.ranges){for(h in a.ranges)c="string"===typeof a.ranges[h][0]?d(a.ranges[h][0],this.format):d(a.ranges[h][0]),n="string"===typeof a.ranges[h][1]?d(a.ranges[h][1],this.format):
d(a.ranges[h][1]),this.minDate&&c.isBefore(this.minDate)&&(c=d(this.minDate)),this.maxDate&&n.isAfter(this.maxDate)&&(n=d(this.maxDate)),this.minDate&&n.isBefore(this.minDate)||this.maxDate&&c.isAfter(this.maxDate)||(this.ranges[h]=[c,n]);c="<ul>";for(h in this.ranges)c+="<li>"+h+"</li>";c+="<li>"+this.locale.customRangeLabel+"</li>";c+="</ul>";this.container.find(".ranges ul").remove();this.container.find(".ranges").prepend(c)}"function"===typeof b&&(this.cb=b);this.timePicker||(this.startDate=this.startDate.startOf("day"),
this.endDate=this.endDate.endOf("day"));this.singleDatePicker?(this.opens="right",this.container.addClass("single"),this.container.find(".calendar.right").show(),this.container.find(".calendar.left").hide(),this.timePicker?this.container.find(".ranges .daterangepicker_start_input, .ranges .daterangepicker_end_input").hide():this.container.find(".ranges").hide(),this.container.find(".calendar.right").hasClass("single")||this.container.find(".calendar.right").addClass("single")):(this.container.removeClass("single"),
this.container.find(".calendar.right").removeClass("single"),this.container.find(".ranges").show());this.oldStartDate=this.startDate.clone();this.oldEndDate=this.endDate.clone();this.oldChosenLabel=this.chosenLabel;this.leftCalendar={month:d([this.startDate.year(),this.startDate.month(),1,this.startDate.hour(),this.startDate.minute(),this.startDate.second()]),calendar:[]};this.rightCalendar={month:d([this.endDate.year(),this.endDate.month(),1,this.endDate.hour(),this.endDate.minute(),this.endDate.second()]),
calendar:[]};if("right"==this.opens||"center"==this.opens)h=this.container.find(".calendar.first"),c=this.container.find(".calendar.second"),c.hasClass("single")&&(c.removeClass("single"),h.addClass("single")),h.removeClass("left").addClass("right"),c.removeClass("right").addClass("left"),this.singleDatePicker&&(h.show(),c.hide());"undefined"!==typeof a.ranges||this.singleDatePicker||this.container.addClass("show-calendar");this.container.removeClass("opensleft opensright").addClass("opens"+this.opens);
this.updateView();this.updateCalendars();var l=this.container;e.each(this.buttonClasses,function(a,b){l.find("button").addClass(b)});this.container.find(".daterangepicker_start_input label").html(this.locale.fromLabel);this.container.find(".daterangepicker_end_input label").html(this.locale.toLabel);this.applyClass.length&&this.container.find(".applyBtn").addClass(this.applyClass);this.cancelClass.length&&this.container.find(".cancelBtn").addClass(this.cancelClass);this.container.find(".applyBtn").html(this.locale.applyLabel);
this.container.find(".cancelBtn").html(this.locale.cancelLabel)},setStartDate:function(a){"string"===typeof a&&(this.startDate=d(a,this.format).utcOffset(this.timeZone));"object"===typeof a&&(this.startDate=d(a));this.timePicker||(this.startDate=this.startDate.startOf("day"));this.oldStartDate=this.startDate.clone();this.updateView();this.updateCalendars();this.updateInputText()},setEndDate:function(a){"string"===typeof a&&(this.endDate=d(a,this.format).utcOffset(this.timeZone));"object"===typeof a&&
(this.endDate=d(a));this.timePicker||(this.endDate=this.endDate.endOf("day"));this.oldEndDate=this.endDate.clone();this.updateView();this.updateCalendars();this.updateInputText()},updateView:function(){this.leftCalendar.month.month(this.startDate.month()).year(this.startDate.year()).hour(this.startDate.hour()).minute(this.startDate.minute());this.rightCalendar.month.month(this.endDate.month()).year(this.endDate.year()).hour(this.endDate.hour()).minute(this.endDate.minute());this.updateFormInputs()},
updateFormInputs:function(){this.container.find("input[name=daterangepicker_start]").val(this.startDate.format(this.format));this.container.find("input[name=daterangepicker_end]").val(this.endDate.format(this.format));this.startDate.isSame(this.endDate)||this.startDate.isBefore(this.endDate)?this.container.find("button.applyBtn").removeAttr("disabled"):this.container.find("button.applyBtn").attr("disabled","disabled")},updateFromControl:function(){if(this.element.is("input")&&this.element.val().length){var a=
this.element.val().split(this.separator),b=null,c=null;2===a.length&&(b=d(a[0],this.format).utcOffset(this.timeZone),c=d(a[1],this.format).utcOffset(this.timeZone));if(this.singleDatePicker||null===b||null===c)c=b=d(this.element.val(),this.format).utcOffset(this.timeZone);c.isBefore(b)||(this.oldStartDate=this.startDate.clone(),this.oldEndDate=this.endDate.clone(),this.startDate=b,this.endDate=c,this.startDate.isSame(this.oldStartDate)&&this.endDate.isSame(this.oldEndDate)||this.notify(),this.updateCalendars())}},
keydown:function(a){9!==a.keyCode&&13!==a.keyCode||this.hide()},notify:function(){this.updateView();this.cb(this.startDate,this.endDate,this.chosenLabel)},move:function(){var a=0,b=0,c=e(window).width();this.parentEl.is("body")||(a=this.parentEl.offset().top-this.parentEl.scrollTop(),b=this.parentEl.offset().left-this.parentEl.scrollLeft(),c=this.parentEl[0].clientWidth+this.parentEl.offset().left);a="up"==this.drops?this.element.offset().top-this.container.outerHeight()-a:this.element.offset().top+
this.element.outerHeight()-a;this.container["up"==this.drops?"addClass":"removeClass"]("dropup");"left"==this.opens?(this.container.css({top:a,right:c-this.element.offset().left-this.element.outerWidth(),left:"auto"}),0>this.container.offset().left&&this.container.css({right:"auto",left:9})):"center"==this.opens?(this.container.css({top:a,left:this.element.offset().left-b+this.element.outerWidth()/2-this.container.outerWidth()/2,right:"auto"}),0>this.container.offset().left&&this.container.css({right:"auto",
left:9})):(this.container.css({top:a,left:this.element.offset().left-b,right:"auto"}),this.container.offset().left+this.container.outerWidth()>e(window).width()&&this.container.css({left:"auto",right:0}))},toggle:function(a){this.element.hasClass("active")?this.hide():this.show()},show:function(a){this.isShowing||(this.element.addClass("active"),this.container.show(),this.move(),this._outsideClickProxy=e.proxy(function(a){this.outsideClick(a)},this),e(document).on("mousedown.daterangepicker",this._outsideClickProxy).on("touchend.daterangepicker",
this._outsideClickProxy).on("click.daterangepicker","[data-toggle=dropdown]",this._outsideClickProxy).on("focusin.daterangepicker",this._outsideClickProxy),this.isShowing=!0,this.element.trigger("show.daterangepicker",this))},outsideClick:function(a){var b=e(a.target);"focusin"==a.type||b.closest(this.element).length||b.closest(this.container).length||b.closest(".calendar-date").length||this.hide()},hide:function(a){this.isShowing&&(e(document).off(".daterangepicker"),this.element.removeClass("active"),
this.container.hide(),this.startDate.isSame(this.oldStartDate)&&this.endDate.isSame(this.oldEndDate)||this.notify(),this.oldStartDate=this.startDate.clone(),this.oldEndDate=this.endDate.clone(),this.isShowing=!1,this.element.trigger("hide.daterangepicker",this))},enterRange:function(a){a=a.target.innerHTML;a==this.locale.customRangeLabel?this.updateView():(a=this.ranges[a],this.container.find("input[name=daterangepicker_start]").val(a[0].format(this.format)),this.container.find("input[name=daterangepicker_end]").val(a[1].format(this.format)))},
showCalendars:function(){this.container.addClass("show-calendar");this.move();this.element.trigger("showCalendar.daterangepicker",this)},hideCalendars:function(){this.container.removeClass("show-calendar");this.element.trigger("hideCalendar.daterangepicker",this)},inputsChanged:function(a){var b=e(a.target);a=d(b.val(),this.format);a.isValid()&&("daterangepicker_start"===b.attr("name")?(b=!1!==this.minDate&&a.isBefore(this.minDate)?this.minDate:a,a=this.endDate):(b=this.startDate,a=!1!==this.maxDate&&
a.isAfter(this.maxDate)?this.maxDate:a),this.setCustomDates(b,a))},inputsKeydown:function(a){13===a.keyCode&&(this.inputsChanged(a),this.notify())},updateInputText:function(){this.element.is("input")&&!this.singleDatePicker?(this.element.val(this.startDate.format(this.format)+this.separator+this.endDate.format(this.format)),this.element.trigger("change")):this.element.is("input")&&(this.element.val(this.endDate.format(this.format)),this.element.trigger("change"))},clickRange:function(a){this.chosenLabel=
a=a.target.innerHTML;a==this.locale.customRangeLabel?this.showCalendars():(a=this.ranges[a],this.startDate=a[0],this.endDate=a[1],this.timePicker||(this.startDate.startOf("day"),this.endDate.endOf("day")),this.leftCalendar.month.month(this.startDate.month()).year(this.startDate.year()).hour(this.startDate.hour()).minute(this.startDate.minute()),this.rightCalendar.month.month(this.endDate.month()).year(this.endDate.year()).hour(this.endDate.hour()).minute(this.endDate.minute()),this.updateCalendars(),
this.updateInputText(),this.hideCalendars(),this.hide(),this.element.trigger("apply.daterangepicker",this))},clickPrev:function(a){e(a.target).parents(".calendar").hasClass("left")?this.leftCalendar.month.subtract(1,"month"):this.rightCalendar.month.subtract(1,"month");this.updateCalendars()},clickNext:function(a){e(a.target).parents(".calendar").hasClass("left")?this.leftCalendar.month.add(1,"month"):this.rightCalendar.month.add(1,"month");this.updateCalendars()},hoverDate:function(a){var b=e(a.target).attr("data-title"),
c=b.substr(1,1),b=b.substr(3,1);e(a.target).parents(".calendar").hasClass("left")?this.container.find("input[name=daterangepicker_start]").val(this.leftCalendar.calendar[c][b].format(this.format)):this.container.find("input[name=daterangepicker_end]").val(this.rightCalendar.calendar[c][b].format(this.format))},setCustomDates:function(a,b){this.chosenLabel=this.locale.customRangeLabel;if(a.isAfter(b)){var c=this.endDate.diff(this.startDate);b=d(a).add(c,"ms");this.maxDate&&b.isAfter(this.maxDate)&&
(b=this.maxDate.clone())}this.startDate=a;this.endDate=b;this.updateView();this.updateCalendars()},clickDate:function(a){var b=e(a.target).attr("data-title"),c=b.substr(1,1),n=b.substr(3,1),b=e(a.target).parents(".calendar"),h;b.hasClass("left")?(h=this.leftCalendar.calendar[c][n],c=this.endDate,"object"===typeof this.dateLimit&&(n=d(h).add(this.dateLimit).startOf("day"),c.isAfter(n)&&(c=n))):(h=this.startDate,c=this.rightCalendar.calendar[c][n],"object"===typeof this.dateLimit&&(n=d(c).subtract(this.dateLimit).startOf("day"),
h.isBefore(n)&&(h=n)));this.singleDatePicker&&b.hasClass("left")?c=h.clone():this.singleDatePicker&&b.hasClass("right")&&(h=c.clone());b.find("td").removeClass("active");e(a.target).addClass("active");this.setCustomDates(h,c);this.timePicker||c.endOf("day");this.singleDatePicker&&!this.timePicker&&this.clickApply()},clickApply:function(a){this.updateInputText();this.hide();this.element.trigger("apply.daterangepicker",this)},clickCancel:function(a){this.startDate=this.oldStartDate;this.endDate=this.oldEndDate;
this.chosenLabel=this.oldChosenLabel;this.updateView();this.updateCalendars();this.hide();this.element.trigger("cancel.daterangepicker",this)},updateMonthYear:function(a){var b=(a=e(a.target).closest(".calendar").hasClass("left"))?"left":"right",c=this.container.find(".calendar."+b),d=parseInt(c.find(".monthselect").val(),10),c=c.find(".yearselect").val();a||this.singleDatePicker||!(c<this.startDate.year()||c==this.startDate.year()&&d<this.startDate.month())||(d=this.startDate.month(),c=this.startDate.year());
this.minDate&&(c<this.minDate.year()||c==this.minDate.year()&&d<this.minDate.month())&&(d=this.minDate.month(),c=this.minDate.year());this.maxDate&&(c>this.maxDate.year()||c==this.maxDate.year()&&d>this.maxDate.month())&&(d=this.maxDate.month(),c=this.maxDate.year());this[b+"Calendar"].month.month(d).year(c);this.updateCalendars()},updateTime:function(a){var b=e(a.target).closest(".calendar"),c=b.hasClass("left");a=parseInt(b.find(".hourselect").val(),10);var d=parseInt(b.find(".minuteselect").val(),
10),h=0;this.timePickerSeconds&&(h=parseInt(b.find(".secondselect").val(),10));this.timePicker12Hour&&(b=b.find(".ampmselect").val(),"PM"===b&&12>a&&(a+=12),"AM"===b&&12===a&&(a=0));c?(c=this.startDate.clone(),c.hour(a),c.minute(d),c.second(h),this.startDate=c,this.leftCalendar.month.hour(a).minute(d).second(h),this.singleDatePicker&&(this.endDate=c.clone())):(c=this.endDate.clone(),c.hour(a),c.minute(d),c.second(h),this.endDate=c,this.singleDatePicker&&(this.startDate=c.clone()),this.rightCalendar.month.hour(a).minute(d).second(h));
this.updateView();this.updateCalendars()},updateCalendars:function(){this.leftCalendar.calendar=this.buildCalendar(this.leftCalendar.month.month(),this.leftCalendar.month.year(),this.leftCalendar.month.hour(),this.leftCalendar.month.minute(),this.leftCalendar.month.second(),"left");this.rightCalendar.calendar=this.buildCalendar(this.rightCalendar.month.month(),this.rightCalendar.month.year(),this.rightCalendar.month.hour(),this.rightCalendar.month.minute(),this.rightCalendar.month.second(),"right");
this.container.find(".calendar.left").empty().html(this.renderCalendar(this.leftCalendar.calendar,this.startDate,this.minDate,this.maxDate,"left"));this.container.find(".calendar.right").empty().html(this.renderCalendar(this.rightCalendar.calendar,this.endDate,this.singleDatePicker?this.minDate:this.startDate,this.maxDate,"right"));this.container.find(".ranges li").removeClass("active");var a=!0,b=0,c;for(c in this.ranges)this.timePicker?this.startDate.isSame(this.ranges[c][0])&&this.endDate.isSame(this.ranges[c][1])&&
(a=!1,this.chosenLabel=this.container.find(".ranges li:eq("+b+")").addClass("active").html()):this.startDate.format("YYYY-MM-DD")==this.ranges[c][0].format("YYYY-MM-DD")&&this.endDate.format("YYYY-MM-DD")==this.ranges[c][1].format("YYYY-MM-DD")&&(a=!1,this.chosenLabel=this.container.find(".ranges li:eq("+b+")").addClass("active").html()),b++;a&&(this.chosenLabel=this.container.find(".ranges li:last").addClass("active").html(),this.showCalendars())},buildCalendar:function(a,b,c,e,h,g){var k=d([b,a]).daysInMonth(),
l=d([b,a,1]),f=d([b,a,k]);b=d(l).subtract(1,"month").month();var k=d(l).subtract(1,"month").year(),n=d([k,b]).daysInMonth(),m=l.day();a=[];a.firstDay=l;a.lastDay=f;for(l=0;6>l;l++)a[l]=[];l=n-m+this.locale.firstDay+1;l>n&&(l-=7);m==this.locale.firstDay&&(l=n-6);e=d([k,b,l,12,e,h]).utcOffset(this.timeZone);for(b=h=l=0;42>l;l++,h++,e=d(e).add(24,"hour"))0<l&&0===h%7&&(h=0,b++),a[b][h]=e.clone().hour(c),e.hour(12),this.minDate&&a[b][h].format("YYYY-MM-DD")==this.minDate.format("YYYY-MM-DD")&&a[b][h].isBefore(this.minDate)&&
"left"==g&&(a[b][h]=this.minDate.clone()),this.maxDate&&a[b][h].format("YYYY-MM-DD")==this.maxDate.format("YYYY-MM-DD")&&a[b][h].isAfter(this.maxDate)&&"right"==g&&(a[b][h]=this.maxDate.clone());return a},renderDropdowns:function(a,b,c){var d=a.month();a=a.year();for(var e=c&&c.year()||a+5,g=b&&b.year()||a-50,k='<select class="monthselect">',l=a==g,f=a==e,m=0;12>m;m++)(!l||m>=b.month())&&(!f||m<=c.month())&&(k+="<option value='"+m+"'"+(m===d?" selected='selected'":"")+">"+this.locale.monthNames[m]+
"</option>");b='<select class="yearselect">';for(c=g;c<=e;c++)b+='<option value="'+c+'"'+(c===a?' selected="selected"':"")+">"+c+"</option>";return k+"</select>"+(b+"</select>")},renderCalendar:function(a,b,c,d,h){var g='<div class="calendar-date">',g=g+'<table class="table-condensed">',g=g+"<thead>",g=g+"<tr>";this.showWeekNumbers&&(g+="<th></th>");var g=!c||c.isBefore(a.firstDay)?g+'<th class="prev available"><i class="fa fa-arrow-left icon icon-arrow-left glyphicon glyphicon-arrow-left"></i></th>':
g+"<th></th>",k=this.locale.monthNames[a[1][1].month()]+a[1][1].format(" YYYY");this.showDropdowns&&(k=this.renderDropdowns(a[1][1],c,d));g+='<th colspan="5" class="month">'+k+"</th>";g=!d||d.isAfter(a.lastDay)?g+'<th class="next available"><i class="fa fa-arrow-right icon icon-arrow-right glyphicon glyphicon-arrow-right"></i></th>':g+"<th></th>";g+="</tr>";g+="<tr>";this.showWeekNumbers&&(g+='<th class="week">'+this.locale.weekLabel+"</th>");e.each(this.locale.daysOfWeek,function(a,b){g+="<th>"+
b+"</th>"});g+="</tr>";g+="</thead>";g+="<tbody>";for(k=0;6>k;k++){g+="<tr>";this.showWeekNumbers&&(g+='<td class="week">'+a[k][0].week()+"</td>");for(var l=0;7>l;l++){var f="available ",f=f+(a[k][l].month()==a[1][1].month()?"":"off");c&&a[k][l].isBefore(c,"day")||d&&a[k][l].isAfter(d,"day")?f=" off disabled ":a[k][l].format("YYYY-MM-DD")==b.format("YYYY-MM-DD")?(f+=" active ",a[k][l].format("YYYY-MM-DD")==this.startDate.format("YYYY-MM-DD")&&(f+=" start-date "),a[k][l].format("YYYY-MM-DD")==this.endDate.format("YYYY-MM-DD")&&
(f+=" end-date ")):a[k][l]>=this.startDate&&a[k][l]<=this.endDate&&(f+=" in-range ",a[k][l].isSame(this.startDate)&&(f+=" start-date "),a[k][l].isSame(this.endDate)&&(f+=" end-date "));var m="r"+k+"c"+l,g=g+('<td class="'+f.replace(/\s+/g," ").replace(/^\s?(.*?)\s?$/,"$1")+'" data-title="'+m+'">'+a[k][l].date()+"</td>")}g+="</tr>"}g+="</tbody>";g+="</table>";g+="</div>";if(this.timePicker){g+='<div class="calendar-time">';g+='<select class="hourselect">';k=0;l=23;c&&("left"==h||this.singleDatePicker)&&
b.format("YYYY-MM-DD")==c.format("YYYY-MM-DD")&&(k=c.hour(),b.hour()<k&&b.hour(k),this.timePicker12Hour&&12<=k&&12<=b.hour()&&(k-=12),this.timePicker12Hour&&12==k&&(k=1));d&&("right"==h||this.singleDatePicker)&&b.format("YYYY-MM-DD")==d.format("YYYY-MM-DD")&&(l=d.hour(),b.hour()>l&&b.hour(l),this.timePicker12Hour&&12<=l&&12<=b.hour()&&(l-=12));a=0;f=23;m=b.hour();this.timePicker12Hour&&(a=1,f=12,12<=m&&(m-=12),0===m&&(m=12));for(;a<=f;a++)g=a==m?g+('<option value="'+a+'" selected="selected">'+a+"</option>"):
a<k||a>l?g+('<option value="'+a+'" disabled="disabled" class="disabled">'+a+"</option>"):g+('<option value="'+a+'">'+a+"</option>");g+="</select> : ";g+='<select class="minuteselect">';k=0;l=59;c&&("left"==h||this.singleDatePicker)&&b.format("YYYY-MM-DD h A")==c.format("YYYY-MM-DD h A")&&(k=c.minute(),b.minute()<k&&b.minute(k));d&&("right"==h||this.singleDatePicker)&&b.format("YYYY-MM-DD h A")==d.format("YYYY-MM-DD h A")&&(l=d.minute(),b.minute()>l&&b.minute(l));for(a=0;60>a;a+=this.timePickerIncrement)f=
a,10>f&&(f="0"+f),g=a==b.minute()?g+('<option value="'+a+'" selected="selected">'+f+"</option>"):a<k||a>l?g+('<option value="'+a+'" disabled="disabled" class="disabled">'+f+"</option>"):g+('<option value="'+a+'">'+f+"</option>");g+="</select> ";if(this.timePickerSeconds){g+=': <select class="secondselect">';for(a=0;60>a;a+=this.timePickerIncrement)f=a,10>f&&(f="0"+f),g=a==b.second()?g+('<option value="'+a+'" selected="selected">'+f+"</option>"):g+('<option value="'+a+'">'+f+"</option>");g+="</select>"}this.timePicker12Hour&&
(g+='<select class="ampmselect">',k=a="",c&&("left"==h||this.singleDatePicker)&&b.format("YYYY-MM-DD")==c.format("YYYY-MM-DD")&&12<=c.hour()&&(a=' disabled="disabled" class="disabled"'),d&&("right"==h||this.singleDatePicker)&&b.format("YYYY-MM-DD")==d.format("YYYY-MM-DD")&&12>d.hour()&&(k=' disabled="disabled" class="disabled"'),g=12<=b.hour()?g+('<option value="AM"'+a+'>AM</option><option value="PM" selected="selected"'+k+">PM</option>"):g+('<option value="AM" selected="selected"'+a+'>AM</option><option value="PM"'+
k+">PM</option>"),g+="</select>");g+="</div>"}return g},remove:function(){this.container.remove();this.element.off(".daterangepicker");this.element.removeData("daterangepicker")}};e.fn.daterangepicker=function(a,b){this.each(function(){var c=e(this);c.data("daterangepicker")&&c.data("daterangepicker").remove();c.data("daterangepicker",new p(c,a,b))});return this}});
