(function(r){"object"==typeof exports&&"object"==typeof module?r(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],r):r(CodeMirror)})(function(r){r.defineMode("haxe",function(l,t){function d(a){return{type:a,style:"keyword"}}function r(a,c){for(var e=!1,b;null!=(b=a.next());){if(b==c&&!e)return!0;e=!e&&"\\"==b}}function q(a,c,e){n=a;O=e;return c}function C(a,c){var e=a.next();if('"'==e||"'"==e)return e=aa(e),c.tokenize=e,e(a,c);if(/[\[\]{}\(\),;\:\.]/.test(e))return q(e);
if("0"==e&&a.eat(/x/i))return a.eatWhile(/[\da-f]/i),q("number","number");if(/\d/.test(e)||"-"==e&&a.eat(/\d/))return a.match(/^\d*(?:\.\d*(?!\.))?(?:[eE][+\-]?\d+)?/),q("number","number");if(c.reAllowed&&"~"==e&&a.eat(/\//))return r(a,"/"),a.eatWhile(/[gimsu]/),q("regexp","string-2");if("/"==e){if(a.eat("*"))return e=ba,c.tokenize=e,e(a,c);if(a.eat("/"))return a.skipToEnd(),q("comment","comment");a.eatWhile(H);return q("operator",null,a.current())}if("#"==e)return a.skipToEnd(),q("conditional","meta");
if("@"==e)return a.eat(/:/),a.eatWhile(/[\w_]/),q("metadata","meta");if(H.test(e))return a.eatWhile(H),q("operator",null,a.current());if(/[A-Z]/.test(e))return a.eatWhile(/[\w_<>]/),e=a.current(),q("type","variable-3",e);a.eatWhile(/[\w_]/);var e=a.current(),b=P.propertyIsEnumerable(e)&&P[e];return b&&c.kwAllowed?q(b.type,b.style,e):q("variable","variable",e)}function aa(a){return function(c,b){r(c,a)&&(b.tokenize=C);return q("string","string")}}function ba(a,c){for(var b=!1,h;h=a.next();){if("/"==
h&&b){c.tokenize=C;break}b="*"==h}return q("comment","comment")}function Q(a,c,b,h,d,f){this.indented=a;this.column=c;this.type=b;this.prev=d;this.info=f;null!=h&&(this.align=h)}function R(a){for(var c=f.state,b=c.importedtypes;b;b=b.next)if(b.name==a)return;c.importedtypes={name:a,next:c.importedtypes}}function v(){for(var a=arguments.length-1;0<=a;a--)f.cc.push(arguments[a])}function b(){v.apply(null,arguments);return!0}function S(a,b){for(var c=b;c;c=c.next)if(c.name==a)return!0;return!1}function D(a){var b=
f.state;b.context?(f.marked="def",S(a,b.localVars)||(b.localVars={name:a,next:b.localVars})):b.globalVars&&!S(a,b.globalVars)&&(b.globalVars={name:a,next:b.globalVars})}function I(){f.state.context||(f.state.localVars=ca);f.state.context={prev:f.state.context,vars:f.state.localVars}}function E(){f.state.localVars=f.state.context.vars;f.state.context=f.state.context.prev}function k(a,b){var c=function(){var c=f.state;c.lexical=new Q(c.indented,f.stream.column(),a,null,c.lexical,b)};c.lex=!0;return c}
function g(){var a=f.state;a.lexical.prev&&(")"==a.lexical.type&&(a.indented=a.lexical.indented),a.lexical=a.lexical.prev)}function p(a){function c(e){return e==a?b():";"==a?v():b(c)}return c}function w(a){return"@"==a?b(T):"var"==a?b(k("vardef"),J,p(";"),g):"keyword a"==a?b(k("form"),u,w,g):"keyword b"==a?b(k("form"),w,g):"{"==a?b(k("}"),I,K,g,E):";"==a?b():"attribute"==a?b(U):"function"==a?b(z):"for"==a?b(k("form"),p("("),k(")"),da,p(")"),g,w,g):"variable"==a?b(k("stat"),ea):"switch"==a?b(k("form"),
u,k("}","switch"),p("{"),K,g,g):"case"==a?b(u,p(":")):"default"==a?b(p(":")):"catch"==a?b(k("form"),I,p("("),V,p(")"),w,g,E):"import"==a?b(W,p(";")):"typedef"==a?b(fa):v(k("stat"),u,p(";"),g)}function u(a){return X.hasOwnProperty(a)||"type"==a?b(x):"function"==a?b(z):"keyword c"==a?b(L):"("==a?b(k(")"),L,p(")"),g,x):"operator"==a?b(u):"["==a?b(k("]"),y(L,"]"),g,x):"{"==a?b(k("}"),y(ga,"}"),g,x):b()}function L(a){return a.match(/[;\}\)\],]/)?v():v(u)}function x(a,c){if("operator"==a&&/\+\+|--/.test(c))return b(x);
if("operator"==a||":"==a)return b(u);if(";"!=a){if("("==a)return b(k(")"),y(u,")"),g,x);if("."==a)return b(ha,x);if("["==a)return b(k("]"),u,p("]"),g,x)}}function U(a){if("attribute"==a)return b(U);if("function"==a)return b(z);if("var"==a)return b(J)}function T(a){if(":"==a||"variable"==a)return b(T);if("("==a)return b(k(")"),y(ia,")"),g,w)}function ia(a){if("variable"==a)return b()}function W(a,c){if("variable"==a&&/[A-Z]/.test(c.charAt(0)))return R(c),b();if("variable"==a||"property"==a||"."==a||
"*"==c)return b(W)}function fa(a,c){if("variable"==a&&/[A-Z]/.test(c.charAt(0)))return R(c),b();if("type"==a&&/[A-Z]/.test(c.charAt(0)))return b()}function ea(a){return":"==a?b(g,w):v(x,p(";"),g)}function ha(a){if("variable"==a)return f.marked="property",b()}function ga(a){"variable"==a&&(f.marked="property");if(X.hasOwnProperty(a))return b(p(":"),u)}function y(a,c){function e(h){return","==h?b(a,e):h==c?b():b(p(c))}return function(h){return h==c?b():v(a,e)}}function K(a){return"}"==a?b():v(w,K)}
function J(a,c){return"variable"==a?(D(c),b(F,Y)):b()}function Y(a,c){if("="==c)return b(u,Y);if(","==a)return b(J)}function da(a,c){return"variable"==a?(D(c),b(ja,u)):v()}function ja(a,c){if("in"==c)return b()}function z(a,c){if("variable"==a||"type"==a)return D(c),b(z);if("new"==c)return b(z);if("("==a)return b(k(")"),I,y(V,")"),g,F,w,E)}function F(a){if(":"==a)return b(ka)}function ka(a){if("type"==a||"variable"==a)return b();if("{"==a)return b(k("}"),y(la,"}"),g)}function la(a){if("variable"==
a)return b(F)}function V(a,c){if("variable"==a)return D(c),b(F)}var A=l.indentUnit,Z=d("keyword a"),M=d("keyword b"),B=d("keyword c"),ma=d("operator"),N={type:"atom",style:"atom"},G={type:"attribute",style:"attribute"},n=d("typedef"),P={"if":Z,"while":Z,"else":M,"do":M,"try":M,"return":B,"break":B,"continue":B,"new":B,"throw":B,"var":d("var"),inline:G,"static":G,using:d("import"),"public":G,"private":G,cast:d("cast"),"import":d("import"),macro:d("macro"),"function":d("function"),"catch":d("catch"),
untyped:d("untyped"),callback:d("cb"),"for":d("for"),"switch":d("switch"),"case":d("case"),"default":d("default"),"in":ma,never:d("property_access"),trace:d("trace"),"class":n,"abstract":n,"enum":n,"interface":n,typedef:n,"extends":n,"implements":n,dynamic:n,"true":N,"false":N,"null":N},H=/[+\-*&%=<>!?|]/,O,X={atom:!0,number:!0,variable:!0,string:!0,regexp:!0},f={state:null,column:null,marked:null,cc:null},ca={name:"this",next:null};E.lex=!0;g.lex=!0;return{startState:function(a){a={tokenize:C,reAllowed:!0,
kwAllowed:!0,cc:[],lexical:new Q((a||0)-A,0,"block",!1),localVars:t.localVars,importedtypes:"Int Float String Void Std Bool Dynamic Array".split(" "),context:t.localVars&&{vars:t.localVars},indented:0};t.globalVars&&"object"==typeof t.globalVars&&(a.globalVars=t.globalVars);return a},token:function(a,b){a.sol()&&(b.lexical.hasOwnProperty("align")||(b.lexical.align=!1),b.indented=a.indentation());if(a.eatSpace())return null;var c=b.tokenize(a,b);if("comment"==n)return c;b.reAllowed=!("operator"!=n&&
"keyword c"!=n&&!n.match(/^[\[{}\(,;:]$/));b.kwAllowed="."!=n;a:{var h=n,d=O,m=b.cc;f.state=b;f.stream=a;f.marked=null;f.cc=m;b.lexical.hasOwnProperty("align")||(b.lexical.align=!0);for(;;)if((m.length?m.pop():w)(h,d)){for(;m.length&&m[m.length-1].lex;)m.pop()();if(f.marked){c=f.marked;break a}if(m="variable"==h)b:{for(m=b.localVars;m;m=m.next)if(m.name==d){m=!0;break b}m=void 0}if(m){c="variable-2";break a}if(h="variable"==h)b:if(h=b,/[a-z]/.test(d.charAt(0)))h=!1;else{for(var m=h.importedtypes.length,
g=0;g<m;g++)if(h.importedtypes[g]==d){h=!0;break b}h=void 0}if(h){c="variable-3";break a}break a}}return c},indent:function(a,b){if(a.tokenize!=C)return 0;var c=b&&b.charAt(0),d=a.lexical;"stat"==d.type&&"}"==c&&(d=d.prev);var f=d.type,g=c==f;return"vardef"==f?d.indented+4:"form"==f&&"{"==c?d.indented:"stat"==f||"form"==f?d.indented+A:"switch"!=d.info||g?d.align?d.column+(g?0:1):d.indented+(g?0:A):d.indented+(/^(?:case|default)\b/.test(b)?A:2*A)},electricChars:"{}",blockCommentStart:"/*",blockCommentEnd:"*/",
lineComment:"//"}});r.defineMIME("text/x-haxe","haxe");r.defineMode("hxml",function(){return{startState:function(){return{define:!1,inString:!1}},token:function(l,t){var d=l.peek(),r=l.sol();if("#"==d)return l.skipToEnd(),"comment";if(r&&"-"==d)return d="variable-2",l.eat(/-/),"-"==l.peek()&&(l.eat(/-/),d="keyword a"),"D"==l.peek()&&(l.eat(/[D]/),d="keyword c",t.define=!0),l.eatWhile(/[A-Z]/i),d;d=l.peek();0==t.inString&&"'"==d&&(t.inString=!0,l.next());if(1==t.inString)return l.skipTo("'")||l.skipToEnd(),
"'"==l.peek()&&(l.next(),t.inString=!1),"string";l.next();return null},lineComment:"#"}});r.defineMIME("text/x-hxml","hxml")});
