var $jscomp={scope:{},findInternal:function(a,h,g){a instanceof String&&(a=String(a));for(var k=a.length,d=0;d<k;d++){var f=a[d];if(h.call(g,f,d,a))return{i:d,v:f}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,h,g){if(g.get||g.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[h]=g.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,h,g,k){if(h){g=$jscomp.global;a=a.split(".");for(k=0;k<a.length-1;k++){var d=a[k];d in g||(g[d]={});g=g[d]}a=a[a.length-1];k=g[a];h=h(k);h!=k&&null!=h&&$jscomp.defineProperty(g,a,{configurable:!0,writable:!0,value:h})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,g){return $jscomp.findInternal(this,a,g).v}},"es6-impl","es3");if("undefined"===typeof jQuery)throw Error("multiselect requires jQuery");(function(a){a=a.fn.jquery.split(" ")[0].split(".");if(2>a[0]&&7>a[1])throw Error("multiselect requires jQuery version 1.7 or higher");})(jQuery);
(function(a){"function"===typeof define&&define.amd?define(["jquery"],a):a(jQuery)})(function(a){var h=function(d){function a(b,c){var a=b.prop("id");this.$left=b;this.$right=d(c.right).length?d(c.right):d("#"+a+"_to");this.actions={$leftAll:d(c.leftAll).length?d(c.leftAll):d("#"+a+"_leftAll"),$rightAll:d(c.rightAll).length?d(c.rightAll):d("#"+a+"_rightAll"),$leftSelected:d(c.leftSelected).length?d(c.leftSelected):d("#"+a+"_leftSelected"),$rightSelected:d(c.rightSelected).length?d(c.rightSelected):
d("#"+a+"_rightSelected"),$undo:d(c.undo).length?d(c.undo):d("#"+a+"_undo"),$redo:d(c.redo).length?d(c.redo):d("#"+a+"_redo"),$moveUp:d(c.moveUp).length?d(c.moveUp):d("#"+a+"_move_up"),$moveDown:d(c.moveDown).length?d(c.moveDown):d("#"+a+"_move_down")};delete c.leftAll;delete c.leftSelected;delete c.right;delete c.rightAll;delete c.rightSelected;delete c.undo;delete c.redo;delete c.moveUp;delete c.moveDown;this.options={keepRenderingSort:c.keepRenderingSort,submitAllLeft:void 0!==c.submitAllLeft?
c.submitAllLeft:!0,submitAllRight:void 0!==c.submitAllRight?c.submitAllRight:!0,search:c.search,ignoreDisabled:void 0!==c.ignoreDisabled?c.ignoreDisabled:!1,matchOptgroupBy:void 0!==c.matchOptgroupBy?c.matchOptgroupBy:"label"};delete c.keepRenderingSort;c.submitAllLeft;c.submitAllRight;c.search;c.ignoreDisabled;c.matchOptgroupBy;this.callbacks=c;this.init()}a.prototype={init:function(){var b=this;b.undoStack=[];b.redoStack=[];if(b.$left.find("optgroup").length||b.$right.find("optgroup").length)b.callbacks.sort=
!1;b.options.keepRenderingSort&&(b.skipInitSort=!0,!1!==b.callbacks.sort&&(b.callbacks.sort=function(b,a){return d(b).data("position")>d(a).data("position")?1:-1}),b.$left.find("option").each(function(b,a){d(a).data("position",b)}),b.$right.find("option").each(function(b,a){d(a).data("position",b)}));"function"==typeof b.callbacks.startUp&&b.callbacks.startUp(b.$left,b.$right);b.skipInitSort||"function"!=typeof b.callbacks.sort||(b.$left.mSort(b.callbacks.sort),b.$right.each(function(c,a){d(a).mSort(b.callbacks.sort)}));
b.options.search&&b.options.search.left&&(b.options.search.$left=d(b.options.search.left),b.$left.before(b.options.search.$left));b.options.search&&b.options.search.right&&(b.options.search.$right=d(b.options.search.right),b.$right.before(d(b.options.search.$right)));b.events()},events:function(){var b=this;if(b.options.search&&b.options.search.$left)b.options.search.$left.on("keyup",function(c){b.callbacks.fireSearch(this.value)?(b.$left.find('option:search("'+this.value+'")').mShow(),b.$left.find('option:not(:search("'+
this.value+'"))').mHide(),b.$left.find("option.hidden").parent("optgroup").not(d(":visible").parent()).mHide(),b.$left.find("option:not(.hidden)").parent("optgroup").mShow()):b.$left.find("option, optgroup").mShow()});if(b.options.search&&b.options.search.$right)b.options.search.$right.on("keyup",function(c){b.callbacks.fireSearch(this.value)?(b.$right.find('option:search("'+this.value+'")').mShow(),b.$right.find('option:not(:search("'+this.value+'"))').mHide(),b.$right.find("option.hidden").parent("optgroup").not(d(":visible").parent()).mHide(),
b.$right.find("option:not(.hidden)").parent("optgroup").mShow()):b.$right.find("option, optgroup").mShow()});b.$right.closest("form").on("submit",function(c){b.$left.find("option").prop("selected",b.options.submitAllLeft);b.$right.find("option").prop("selected",b.options.submitAllRight)});b.$left.on("dblclick","option",function(c){c.preventDefault();var a=b.$left.find("option:selected");a.length&&b.moveToRight(a,c)});b.$left.on("keypress",function(c){if(13===c.keyCode){c.preventDefault();var a=b.$left.find("option:selected");
a.length&&b.moveToRight(a,c)}});b.$right.on("dblclick","option",function(c){c.preventDefault();var a=b.$right.find("option:selected");a.length&&b.moveToLeft(a,c)});b.$right.on("keydown",function(c){if(8===c.keyCode||46===c.keyCode){c.preventDefault();var a=b.$right.find("option:selected");a.length&&b.moveToLeft(a,c)}});if(navigator.userAgent.match(/MSIE/i)||0<navigator.userAgent.indexOf("Trident/")||0<navigator.userAgent.indexOf("Edge/"))b.$left.dblclick(function(c){b.actions.$rightSelected.trigger("click")}),
b.$right.dblclick(function(c){b.actions.$leftSelected.trigger("click")});b.actions.$rightSelected.on("click",function(c){c.preventDefault();var a=b.$left.find("option:selected");a.length&&b.moveToRight(a,c);d(this).blur()});b.actions.$leftSelected.on("click",function(c){c.preventDefault();var a=b.$right.find("option:selected");a.length&&b.moveToLeft(a,c);d(this).blur()});b.actions.$rightAll.on("click",function(c){c.preventDefault();var a=b.$left.children(":not(span):not(.hidden)");a.length&&b.moveToRight(a,
c);d(this).blur()});b.actions.$leftAll.on("click",function(c){c.preventDefault();var a=b.$right.children(":not(span):not(.hidden)");a.length&&b.moveToLeft(a,c);d(this).blur()});b.actions.$undo.on("click",function(c){c.preventDefault();b.undo(c)});b.actions.$redo.on("click",function(c){c.preventDefault();b.redo(c)});b.actions.$moveUp.on("click",function(c){c.preventDefault();b.doNotSortRight=!0;c=b.$right.find(":selected:not(span):not(.hidden)");c.first().prev().before(c);d(this).blur()});b.actions.$moveDown.on("click",
function(c){c.preventDefault();b.doNotSortRight=!0;c=b.$right.find(":selected:not(span):not(.hidden)");c.last().next().after(c);d(this).blur()})},moveToRight:function(b,c,a,f){var e=this;console.log(e);if("function"==typeof e.callbacks.moveToRight)return e.callbacks.moveToRight(e,b,c,a,f);if("function"==typeof e.callbacks.beforeMoveToRight&&!a&&!e.callbacks.beforeMoveToRight(e.$left,e.$right,b))return!1;b.each(function(b,c){var a=d(c);if(e.options.ignoreDisabled&&a.is(":disabled"))return!0;if(a.parent().is("optgroup")){var f=
a.parent(),g="optgroup["+e.options.matchOptgroupBy+'="'+f.prop(e.options.matchOptgroupBy)+'"]',g=e.$right.find(g);g.length||(g=f.clone(),g.children().remove());a=g.append(a);f.removeIfEmpty()}e.$right.move(a)});f||(e.undoStack.push(["right",b]),e.redoStack=[]);"function"!=typeof e.callbacks.sort||a||e.doNotSortRight||e.$right.mSort(e.callbacks.sort);"function"!=typeof e.callbacks.afterMoveToRight||a||e.callbacks.afterMoveToRight(e.$left,e.$right,b);return e},moveToLeft:function(b,c,a,f){var e=this;
if("function"==typeof e.callbacks.moveToLeft)return e.callbacks.moveToLeft(e,b,c,a,f);if("function"==typeof e.callbacks.beforeMoveToLeft&&!a&&!e.callbacks.beforeMoveToLeft(e.$left,e.$right,b))return!1;b.each(function(b,a){var c=d(a);if(c.is("optgroup")||c.parent().is("optgroup")){var f=c.is("optgroup")?c:c.parent(),g="optgroup["+e.options.matchOptgroupBy+'="'+f.prop(e.options.matchOptgroupBy)+'"]',g=e.$left.find(g);g.length||(g=f.clone(),g.children().remove());c=g.append(c.is("optgroup")?c.children():
c);f.removeIfEmpty()}e.$left.move(c)});f||(e.undoStack.push(["left",b]),e.redoStack=[]);"function"!=typeof e.callbacks.sort||a||e.$left.mSort(e.callbacks.sort);"function"!=typeof e.callbacks.afterMoveToLeft||a||e.callbacks.afterMoveToLeft(e.$left,e.$right,b);return e},undo:function(b){var c=this.undoStack.pop();if(c)switch(this.redoStack.push(c),c[0]){case "left":this.moveToRight(c[1],b,!1,!0);break;case "right":this.moveToLeft(c[1],b,!1,!0)}},redo:function(b){var c=this.redoStack.pop();if(c)switch(this.undoStack.push(c),
c[0]){case "left":this.moveToLeft(c[1],b,!1,!0);break;case "right":this.moveToRight(c[1],b,!1,!0)}}};return a}(a);a.multiselect={defaults:{startUp:function(d,f){f.find("option").each(function(b,c){if("OPTGROUP"==a(c).parent().prop("tagName")){var f='optgroup[label="'+a(c).parent().attr("label")+'"]';d.find(f+' option[value="'+c.value+'"]').each(function(b,c){c.remove()});d.find(f).removeIfEmpty()}else d.find('option[value="'+c.value+'"]').remove()})},beforeMoveToRight:function(a,f,b){return!0},afterMoveToRight:function(a,
f,b){},beforeMoveToLeft:function(a,f,b){return!0},afterMoveToLeft:function(a,f,b){},sort:function(a,f){return"NA"==a.innerHTML?1:"NA"==f.innerHTML?-1:a.innerHTML>f.innerHTML?1:-1},fireSearch:function(a){return 1<a.length}}};var g=window.navigator.userAgent,k=-3<g.indexOf("MSIE ")+g.indexOf("Trident/")+g.indexOf("Edge/");a.fn.multiselect=function(d){return this.each(function(){var f=a(this),b=f.data("crlcu.multiselect"),c=a.extend({},a.multiselect.defaults,f.data(),"object"===typeof d&&d);b||f.data("crlcu.multiselect",
new h(f,c))})};a.fn.move=function(a){this.append(a).find("option").prop("selected",!1);return this};a.fn.removeIfEmpty=function(){this.children().length||this.remove();return this};a.fn.mShow=function(){this.removeClass("hidden").show();k&&this.each(function(d,f){a(f).parent().is("span")&&a(f).parent().replaceWith(f);a(f).show()});return this};a.fn.mHide=function(){this.addClass("hidden").hide();k&&this.each(function(d,f){a(f).parent().is("span")||a(f).wrap("<span>").hide()});return this};a.fn.mSort=
function(a){this.find("option").sort(a).appendTo(this);return this};a.expr[":"].search=function(d,f,b){return 0<=a(d).text().toUpperCase().indexOf(b[3].toUpperCase())}});
