var $jscomp={scope:{},findInternal:function(a,c,f){a instanceof String&&(a=String(a));for(var l=a.length,k=0;k<l;k++){var n=a[k];if(c.call(f,n,k,a))return{i:k,v:n}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,f){if(f.get||f.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[c]=f.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,c,f,l){if(c){f=$jscomp.global;a=a.split(".");for(l=0;l<a.length-1;l++){var k=a[l];k in f||(f[k]={});f=f[k]}a=a[a.length-1];l=f[a];c=c(l);c!=l&&null!=c&&$jscomp.defineProperty(f,a,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,f){return $jscomp.findInternal(this,a,f).v}},"es6-impl","es3");
CKEDITOR.dialog.add("scaytDialog",function(a){var c=a.scayt,f='<p><img src="'+c.getLogo()+'" /></p><p>'+c.getLocal("version")+c.getVersion()+"</p><p>"+c.getLocal("text_copyrights")+"</p>",l=CKEDITOR.document,k={isChanged:function(){return null===this.newLang||this.currentLang===this.newLang?!1:!0},currentLang:c.getLang(),newLang:null,reset:function(){this.currentLang=c.getLang();this.newLang=null},id:"lang"},f=[{id:"options",label:c.getLocal("tab_options"),onShow:function(){},elements:[{type:"vbox",
id:"scaytOptions",children:function(){var b=c.getApplicationConfig(),a=[],g={"ignore-all-caps-words":"label_allCaps","ignore-domain-names":"label_ignoreDomainNames","ignore-words-with-mixed-cases":"label_mixedCase","ignore-words-with-numbers":"label_mixedWithDigits"},h;for(h in b)b={type:"checkbox"},b.id=h,b.label=c.getLocal(g[h]),a.push(b);return a}(),onShow:function(){this.getChild();for(var b=a.scayt,d=0;d<this.getChild().length;d++)this.getChild()[d].setValue(b.getApplicationConfig()[this.getChild()[d].id])}}]},
{id:"langs",label:c.getLocal("tab_languages"),elements:[{id:"leftLangColumn",type:"vbox",align:"left",widths:["100"],children:[{type:"html",id:"langBox",style:"overflow: hidden; white-space: normal;margin-bottom:15px;",html:'<div><div style="float:left;width:45%;margin-left:5px;" id="left-col-'+a.name+'" class="scayt-lang-list"></div><div style="float:left;width:45%;margin-left:15px;" id="right-col-'+a.name+'" class="scayt-lang-list"></div></div>',onShow:function(){var b=a.scayt.getLang();l.getById("scaytLang_"+
a.name+"_"+b).$.checked=!0}},{type:"html",id:"graytLanguagesHint",html:'<div style="margin:5px auto; width:95%;white-space:normal;" id="'+a.name+'graytLanguagesHint"><span style="width:10px;height:10px;display: inline-block; background:#02b620;vertical-align:top;margin-top:2px;"></span> - This languages are supported by Grammar As You Type(GRAYT).</div>',onShow:function(){var b=l.getById(a.name+"graytLanguagesHint");a.config.grayt_autoStartup||(b.$.style.display="none")}}]}]},{id:"dictionaries",label:c.getLocal("tab_dictionaries"),
elements:[{type:"vbox",id:"rightCol_col__left",children:[{type:"html",id:"dictionaryNote",html:""},{type:"text",id:"dictionaryName",label:c.getLocal("label_fieldNameDic")||"Dictionary name",onShow:function(b){var d=b.sender,g=a.scayt;setTimeout(function(){d.getContentElement("dictionaries","dictionaryNote").getElement().setText("");null!=g.getUserDictionaryName()&&""!=g.getUserDictionaryName()&&d.getContentElement("dictionaries","dictionaryName").setValue(g.getUserDictionaryName())},0)}},{type:"hbox",
id:"notExistDic",align:"left",style:"width:auto;",widths:["50%","50%"],children:[{type:"button",id:"createDic",label:c.getLocal("btn_createDic"),title:c.getLocal("btn_createDic"),onClick:function(){var b=this.getDialog(),d=n,g=a.scayt,h=b.getContentElement("dictionaries","dictionaryName").getValue();g.createUserDictionary(h,function(e){e.error||d.toggleDictionaryButtons.call(b,!0);e.dialog=b;e.command="create";e.name=h;a.fire("scaytUserDictionaryAction",e)},function(e){e.dialog=b;e.command="create";
e.name=h;a.fire("scaytUserDictionaryActionError",e)})}},{type:"button",id:"restoreDic",label:c.getLocal("btn_restoreDic"),title:c.getLocal("btn_restoreDic"),onClick:function(){var b=this.getDialog(),d=a.scayt,g=n,h=b.getContentElement("dictionaries","dictionaryName").getValue();d.restoreUserDictionary(h,function(e){e.dialog=b;e.error||g.toggleDictionaryButtons.call(b,!0);e.command="restore";e.name=h;a.fire("scaytUserDictionaryAction",e)},function(e){e.dialog=b;e.command="restore";e.name=h;a.fire("scaytUserDictionaryActionError",
e)})}}]},{type:"hbox",id:"existDic",align:"left",style:"width:auto;",widths:["50%","50%"],children:[{type:"button",id:"removeDic",label:c.getLocal("btn_deleteDic"),title:c.getLocal("btn_deleteDic"),onClick:function(){var b=this.getDialog(),d=a.scayt,g=n,h=b.getContentElement("dictionaries","dictionaryName"),e=h.getValue();d.removeUserDictionary(e,function(d){h.setValue("");d.error||g.toggleDictionaryButtons.call(b,!1);d.dialog=b;d.command="remove";d.name=e;a.fire("scaytUserDictionaryAction",d)},function(d){d.dialog=
b;d.command="remove";d.name=e;a.fire("scaytUserDictionaryActionError",d)})}},{type:"button",id:"renameDic",label:c.getLocal("btn_renameDic"),title:c.getLocal("btn_renameDic"),onClick:function(){var b=this.getDialog(),d=a.scayt,g=b.getContentElement("dictionaries","dictionaryName").getValue();d.renameUserDictionary(g,function(d){d.dialog=b;d.command="rename";d.name=g;a.fire("scaytUserDictionaryAction",d)},function(d){d.dialog=b;d.command="rename";d.name=g;a.fire("scaytUserDictionaryActionError",d)})}}]},
{type:"html",id:"dicInfo",html:'<div id="dic_info_editor1" style="margin:5px auto; width:95%;white-space:normal;">'+c.getLocal("text_descriptionDic")+"</div>"}]}]},{id:"about",label:c.getLocal("tab_about"),elements:[{type:"html",id:"about",style:"margin: 5px 5px;",html:'<div><div id="scayt_about_">'+f+"</div></div>"}]}];a.on("scaytUserDictionaryAction",function(b){var a=SCAYT.prototype.UILib,g=b.data.dialog,h=g.getContentElement("dictionaries","dictionaryNote").getElement(),e=b.editor.scayt,c;void 0===
b.data.error?(c=e.getLocal("message_success_"+b.data.command+"Dic"),c=c.replace("%s",b.data.name),h.setText(c),a.css(h.$,{color:"blue"})):(""===b.data.name?h.setText(e.getLocal("message_info_emptyDic")):(c=e.getLocal("message_error_"+b.data.command+"Dic"),c=c.replace("%s",b.data.name),h.setText(c)),a.css(h.$,{color:"red"}),null!=e.getUserDictionaryName()&&""!=e.getUserDictionaryName()?g.getContentElement("dictionaries","dictionaryName").setValue(e.getUserDictionaryName()):g.getContentElement("dictionaries",
"dictionaryName").setValue(""))});a.on("scaytUserDictionaryActionError",function(b){var a=SCAYT.prototype.UILib,g=b.data.dialog,c=g.getContentElement("dictionaries","dictionaryNote").getElement(),e=b.editor.scayt,f;""===b.data.name?c.setText(e.getLocal("message_info_emptyDic")):(f=e.getLocal("message_error_"+b.data.command+"Dic"),f=f.replace("%s",b.data.name),c.setText(f));a.css(c.$,{color:"red"});null!=e.getUserDictionaryName()&&""!=e.getUserDictionaryName()?g.getContentElement("dictionaries","dictionaryName").setValue(e.getUserDictionaryName()):
g.getContentElement("dictionaries","dictionaryName").setValue("")});var n={title:c.getLocal("text_title"),resizable:CKEDITOR.DIALOG_RESIZE_BOTH,minWidth:"moono-lisa"==(CKEDITOR.skinName||a.config.skin)?450:340,minHeight:260,onLoad:function(){if(0!=a.config.scayt_uiTabs[1]){var b=n,d=b.getLangBoxes.call(this);d.getParent().setStyle("white-space","normal");b.renderLangList(d);this.definition.minWidth=this.getSize().width;this.resize(this.definition.minWidth,this.definition.minHeight)}},onCancel:function(){k.reset()},
onHide:function(){a.unlockSelection()},onShow:function(){a.fire("scaytDialogShown",this);if(0!=a.config.scayt_uiTabs[2]){var b=a.scayt,d=this.getContentElement("dictionaries","dictionaryName"),c=this.getContentElement("dictionaries","existDic").getElement().getParent(),h=this.getContentElement("dictionaries","notExistDic").getElement().getParent();c.hide();h.hide();null!=b.getUserDictionaryName()&&""!=b.getUserDictionaryName()?(this.getContentElement("dictionaries","dictionaryName").setValue(b.getUserDictionaryName()),
c.show()):(d.setValue(""),h.show())}},onOk:function(){var b=n,d=a.scayt;this.getContentElement("options","scaytOptions");b=b.getChangedOption.call(this);d.commitOption({changedOptions:b})},toggleDictionaryButtons:function(a){var b=this.getContentElement("dictionaries","existDic").getElement().getParent(),c=this.getContentElement("dictionaries","notExistDic").getElement().getParent();a?(b.show(),c.hide()):(b.hide(),c.show())},getChangedOption:function(){var b={};if(1==a.config.scayt_uiTabs[0])for(var d=
this.getContentElement("options","scaytOptions").getChild(),c=0;c<d.length;c++)d[c].isChanged()&&(b[d[c].id]=d[c].getValue());k.isChanged()&&(b[k.id]=a.config.scayt_sLang=k.currentLang=k.newLang);return b},buildRadioInputs:function(b,c,g){var d=new CKEDITOR.dom.element("div"),e="scaytLang_"+a.name+"_"+c,f=CKEDITOR.dom.element.createFromHtml('<input id="'+e+'" type="radio"  value="'+c+'" name="scayt_lang" />'),l=new CKEDITOR.dom.element("label"),n=a.scayt;d.setStyles({"white-space":"normal",position:"relative",
"padding-bottom":"2px"});f.on("click",function(a){k.newLang=a.sender.getValue()});l.appendText(b);l.setAttribute("for",e);g&&a.config.grayt_autoStartup&&l.setStyles({color:"#02b620"});d.append(f);d.append(l);c===n.getLang()&&(f.setAttribute("checked",!0),f.setAttribute("defaultChecked","defaultChecked"));return d},renderLangList:function(b){var d=b.find("#left-col-"+a.name).getItem(0);b=b.find("#right-col-"+a.name).getItem(0);var g=c.getScaytLangList(),h=c.getGraytLangList(),e={},f=[],l=0,k=!1,m;
for(m in g.ltr)e[m]=g.ltr[m];for(m in g.rtl)e[m]=g.rtl[m];for(m in e)f.push([m,e[m]]);f.sort(function(a,b){var c=0;a[1]>b[1]?c=1:a[1]<b[1]&&(c=-1);return c});e={};for(k=0;k<f.length;k++)e[f[k][0]]=f[k][1];f=Math.round(f.length/2);for(m in e)l++,k=m in h.ltr||m in h.rtl,this.buildRadioInputs(e[m],m,k).appendTo(l<=f?d:b)},getLangBoxes:function(){return this.getContentElement("langs","langBox").getElement()},contents:function(a,c){var b=[],d=c.config.scayt_uiTabs;if(d){for(var e in d)1==d[e]&&b.push(a[e]);
b.push(a[a.length-1])}else return a;return b}(f,a)};return n});
