var $jscomp={scope:{},findInternal:function(g,r,e){g instanceof String&&(g=String(g));for(var h=g.length,n=0;n<h;n++){var m=g[n];if(r.call(e,m,n,g))return{i:n,v:m}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(g,r,e){if(e.get||e.set)throw new TypeError("ES3 does not support getters and setters.");g!=Array.prototype&&g!=Object.prototype&&(g[r]=e.value)};
$jscomp.getGlobal=function(g){return"undefined"!=typeof window&&window===g?g:"undefined"!=typeof global&&null!=global?global:g};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(g,r,e,h){if(r){e=$jscomp.global;g=g.split(".");for(h=0;h<g.length-1;h++){var n=g[h];n in e||(e[n]={});e=e[n]}g=g[g.length-1];h=e[g];r=r(h);r!=h&&null!=r&&$jscomp.defineProperty(e,g,{configurable:!0,writable:!0,value:r})}};
$jscomp.polyfill("Array.prototype.find",function(g){return g?g:function(g,e){return $jscomp.findInternal(this,g,e).v}},"es6-impl","es3");
(function(){function g(){return!1}function r(a,b){var c,d=[];a.filterChildren(b);for(c=a.children.length-1;0<=c;c--)d.unshift(a.children[c]),a.children[c].remove();c=a.attributes;var f=a,k=!0,p;for(p in c)if(k)k=!1;else{var q=new CKEDITOR.htmlParser.element(a.name);q.attributes[p]=c[p];f.add(q);f=q;delete c[p]}for(c=0;c<d.length;c++)f.add(d[c])}var e,h,n,m,l=CKEDITOR.tools,y=["o:p","xml","script","meta","link"],x={},w=0;CKEDITOR.plugins.pastefromword={};CKEDITOR.cleanWord=function(a,b){var c=!!a.match(/mso-list:\s*l\d+\s+level\d+\s+lfo\d+/);
a=a.replace(/<!\[/g,"\x3c!--[").replace(/\]>/g,"]--\x3e");var d=CKEDITOR.htmlParser.fragment.fromHtml(a);m=new CKEDITOR.htmlParser.filter({root:function(a){a.filterChildren(m);CKEDITOR.plugins.pastefromword.lists.cleanup(e.createLists(a))},elementNames:[[/^\?xml:namespace$/,""],[/^v:shapetype/,""],[new RegExp(y.join("|")),""]],elements:{a:function(a){if(a.attributes.name){if("_GoBack"==a.attributes.name){delete a.name;return}if(a.attributes.name.match(/^OLE_LINK\d+$/)){delete a.name;return}}if(a.attributes.href&&
a.attributes.href.match(/#.+$/)){var b=a.attributes.href.match(/#(.+)$/)[1];x[b]=a}a.attributes.name&&x[a.attributes.name]&&(a=x[a.attributes.name],a.attributes.href=a.attributes.href.replace(/.*#(.*)$/,"#$1"))},div:function(a){h.createStyleStack(a,m,b)},img:function(a){if(a.parent){var b=a.parent.attributes;(b=b.style||b.STYLE)&&b.match(/mso\-list:\s?Ignore/)&&(a.attributes["cke-ignored"]=!0)}h.mapStyles(a,{width:function(b){h.setStyle(a,"width",b+"px")},height:function(b){h.setStyle(a,"height",
b+"px")}});a.attributes.src&&a.attributes.src.match(/^file:\/\//)&&a.attributes.alt&&a.attributes.alt.match(/^https?:\/\//)&&(a.attributes.src=a.attributes.alt)},p:function(a){a.filterChildren(m);if(a.attributes.style&&a.attributes.style.match(/display:\s*none/i))return!1;if(e.thisIsAListItem(b,a))e.convertToFakeListItem(b,a);else{var c=a.getAscendant(function(a){return"ul"==a.name||"ol"==a.name}),k=l.parseCssText(a.attributes.style);c&&!c.attributes["cke-list-level"]&&k["mso-list"]&&k["mso-list"].match(/level/)&&
(c.attributes["cke-list-level"]=k["mso-list"].match(/level(\d+)/)[1])}h.createStyleStack(a,m,b)},pre:function(a){e.thisIsAListItem(b,a)&&e.convertToFakeListItem(b,a);h.createStyleStack(a,m,b)},h1:function(a){e.thisIsAListItem(b,a)&&e.convertToFakeListItem(b,a);h.createStyleStack(a,m,b)},font:function(a){if(a.getHtml().match(/^\s*$/))return(new CKEDITOR.htmlParser.text(" ")).insertAfter(a),!1;b&&!0===b.config.pasteFromWordRemoveFontStyles&&a.attributes.size&&delete a.attributes.size;r(a,m)},ul:function(a){if(c)return"li"==
a.parent.name&&0===l.indexOf(a.parent.children,a)&&h.setStyle(a.parent,"list-style-type","none"),e.dissolveList(a),!1},li:function(a){c&&(a.attributes.style=h.normalizedStyles(a,b),h.pushStylesLower(a))},ol:function(a){if(c)return"li"==a.parent.name&&0===l.indexOf(a.parent.children,a)&&h.setStyle(a.parent,"list-style-type","none"),e.dissolveList(a),!1},span:function(a){a.filterChildren(m);a.attributes.style=h.normalizedStyles(a,b);if(!a.attributes.style||a.attributes.style.match(/^mso\-bookmark:OLE_LINK\d+$/)||
a.getHtml().match(/^(\s|&nbsp;)+$/)){for(var c=a.children.length-1;0<=c;c--)a.children[c].insertAfter(a);return!1}h.createStyleStack(a,m,b)},table:function(a){a._tdBorders={};a.filterChildren(m);var b,c=0,d;for(d in a._tdBorders)a._tdBorders[d]>c&&(c=a._tdBorders[d],b=d);h.setStyle(a,"border",b)},td:function(a){var b=a.getAscendant("table"),c=b._tdBorders,d=["border","border-top","border-right","border-bottom","border-left"],b=l.parseCssText(b.attributes.style),f=b.background||b.BACKGROUND;f&&h.setStyle(a,
"background",f,!0);(b=b["background-color"]||b["BACKGROUND-COLOR"])&&h.setStyle(a,"background-color",b,!0);var b=l.parseCssText(a.attributes.style),k;for(k in b)f=b[k],delete b[k],b[k.toLowerCase()]=f;for(k=0;k<d.length;k++)b[d[k]]&&(f=b[d[k]],c[f]=c[f]?c[f]+1:1);h.pushStylesLower(a,{background:!0})},"v:imagedata":g,"v:shape":function(a){var b=!1;a.parent.getFirst(function(c){"img"==c.name&&c.attributes&&c.attributes["v:shapes"]==a.attributes.id&&(b=!0)});if(b)return!1;var c="";a.forEach(function(a){a.attributes&&
a.attributes.src&&(c=a.attributes.src)},CKEDITOR.NODE_ELEMENT,!0);a.filterChildren(m);a.name="img";a.attributes.src=a.attributes.src||c;delete a.attributes.type},style:function(){return!1}},attributes:{style:function(a,c){return h.normalizedStyles(c,b)||!1},"class":function(a){a=a.replace(/msonormal|msolistparagraph\w*/ig,"");return""===a?!1:a},cellspacing:g,cellpadding:g,border:g,valign:g,"v:shapes":g,"o:spid":g},comment:function(a){a.match(/\[if.* supportFields.*\]/)&&w++;"[endif]"==a&&(w=0<w?w-
1:0);return!1},text:function(a){return w?"":a.replace(/&nbsp;/g," ")}});var f=new CKEDITOR.htmlParser.basicWriter;m.applyTo(d);d.writeHtml(f);return f.getHtml()};CKEDITOR.plugins.pastefromword.styles={setStyle:function(a,b,c,d){var f=l.parseCssText(a.attributes.style);d&&f[b]||(""===c?delete f[b]:f[b]=c,a.attributes.style=CKEDITOR.tools.writeCssText(f))},mapStyles:function(a,b){for(var c in b)if(a.attributes[c]){if("function"===typeof b[c])b[c](a.attributes[c]);else h.setStyle(a,b[c],a.attributes[c]);
delete a.attributes[c]}},normalizedStyles:function(a,b){var c="background-color:transparent border-image:none color:windowtext direction:ltr mso- text-indent visibility:visible div:border:none".split(" "),d="font-family font font-size color background-color line-height text-decoration".split(" "),f=function(){for(var a=[],b=0;b<arguments.length;b++)arguments[b]&&a.push(arguments[b]);return-1!==l.indexOf(c,a.join(":"))},k=b&&!0===b.config.pasteFromWordRemoveFontStyles,p=l.parseCssText(a.attributes.style);
"cke:li"==a.name&&p["TEXT-INDENT"]&&p.MARGIN&&(a.attributes["cke-indentation"]=e.getElementIndentation(a),p.MARGIN=p.MARGIN.replace(/(([\w\.]+ ){3,3})[\d\.]+(\w+$)/,"$10$3"));for(var q=l.objectKeys(p),g=0;g<q.length;g++){var h=q[g].toLowerCase(),u=p[q[g]],v=CKEDITOR.tools.indexOf;(k&&-1!==v(d,h.toLowerCase())||f(null,h,u)||f(null,h.replace(/\-.*$/,"-"))||f(null,h)||f(a.name,h,u)||f(a.name,h.replace(/\-.*$/,"-"))||f(a.name,h)||f(u))&&delete p[q[g]]}return CKEDITOR.tools.writeCssText(p)},createStyleStack:function(a,
b,c){var d=[];a.filterChildren(b);for(b=a.children.length-1;0<=b;b--)d.unshift(a.children[b]),a.children[b].remove();h.sortStyles(a);b=l.parseCssText(h.normalizedStyles(a,c));c=a;var f="span"===a.name,k;for(k in b)if(!k.match(/margin|text\-align|width|border|padding/i))if(f)f=!1;else{var e=new CKEDITOR.htmlParser.element("span");e.attributes.style=k+":"+b[k];c.add(e);c=e;delete b[k]}"{}"!==JSON.stringify(b)?a.attributes.style=CKEDITOR.tools.writeCssText(b):delete a.attributes.style;for(b=0;b<d.length;b++)c.add(d[b])},
sortStyles:function(a){for(var b=["border","border-bottom","font-size","background"],c=l.parseCssText(a.attributes.style),d=l.objectKeys(c),f=[],k=[],e=0;e<d.length;e++)-1!==l.indexOf(b,d[e].toLowerCase())?f.push(d[e]):k.push(d[e]);f.sort(function(a,c){var d=l.indexOf(b,a.toLowerCase()),f=l.indexOf(b,c.toLowerCase());return d-f});d=[].concat(f,k);f={};for(e=0;e<d.length;e++)f[d[e]]=c[d[e]];a.attributes.style=CKEDITOR.tools.writeCssText(f)},pushStylesLower:function(a,b){if(!a.attributes.style||0===
a.children.length)return!1;b=b||{};var c={"list-style-type":!0,width:!0,border:!0,"border-":!0},d=l.parseCssText(a.attributes.style),f;for(f in d)if(!(f.toLowerCase()in c||c[f.toLowerCase().replace(/\-.*$/,"-")]||f.toLowerCase()in b)){for(var e=!1,p=0;p<a.children.length;p++){var q=a.children[p];q.type===CKEDITOR.NODE_ELEMENT&&(e=!0,h.setStyle(q,f,d[f]))}e&&delete d[f]}a.attributes.style=CKEDITOR.tools.writeCssText(d);return!0}};h=CKEDITOR.plugins.pastefromword.styles;CKEDITOR.plugins.pastefromword.lists=
{thisIsAListItem:function(a,b){return n.isEdgeListItem(a,b)||b.attributes.style&&b.attributes.style.match(/mso\-list:\s?l\d/)&&"li"!==b.parent.name||b.attributes["cke-dissolved"]||b.getHtml().match(/<!\-\-\[if !supportLists]\-\->/)||b.getHtml().match(/^( )*.*?[\.\)] ( ){2,700}/)?!0:!1},convertToFakeListItem:function(a,b){n.isEdgeListItem(a,b)&&n.assignListLevels(a,b);this.getListItemInfo(b);if(!b.attributes["cke-dissolved"]){var c;b.forEach(function(a){!c&&"img"==a.name&&a.attributes["cke-ignored"]&&
"*"==a.attributes.alt&&(c="\u00b7",a.remove())},CKEDITOR.NODE_ELEMENT);b.forEach(function(a){c||a.value.match(/^ /)||(c=a.value)},CKEDITOR.NODE_TEXT);if("undefined"==typeof c)return;b.attributes["cke-symbol"]=c.replace(/ .*$/,"");e.removeSymbolText(b)}if(b.attributes.style){var d=l.parseCssText(b.attributes.style);d["margin-left"]&&(delete d["margin-left"],b.attributes.style=CKEDITOR.tools.writeCssText(d))}b.name="cke:li"},convertToRealListItems:function(a){var b=[];a.forEach(function(a){"cke:li"==
a.name&&(a.name="li",b.push(a))},CKEDITOR.NODE_ELEMENT,!1);return b},removeSymbolText:function(a){var b,c=a.attributes["cke-symbol"];a.forEach(function(d){!b&&d.value.match(c.replace(")","\\)").replace("(",""))&&(d.value=d.value.replace(c,""),d.parent.getHtml().match(/^(\s|&nbsp;)*$/)&&(b=d.parent!==a?d.parent:null))},CKEDITOR.NODE_TEXT);b&&b.remove()},setListSymbol:function(a,b,c){c=c||1;var d=l.parseCssText(a.attributes.style);if("ol"==a.name){if(a.attributes.type||d["list-style-type"])return;var f=
{"[ivx]":"lower-roman","[IVX]":"upper-roman","[a-z]":"lower-alpha","[A-Z]":"upper-alpha","\\d":"decimal"},k;for(k in f)if(e.getSubsectionSymbol(b).match(new RegExp(k))){d["list-style-type"]=f[k];break}a.attributes["cke-list-style-type"]=d["list-style-type"]}else f={"\u00b7":"disc",o:"circle","\u00a7":"square"},!d["list-style-type"]&&f[b]&&(d["list-style-type"]=f[b]);e.setListSymbol.removeRedundancies(d,c);(a.attributes.style=CKEDITOR.tools.writeCssText(d))||delete a.attributes.style},setListStart:function(a){for(var b=
[],c=0,d=0;d<a.children.length;d++)b.push(a.children[d].attributes["cke-symbol"]||"");b[0]||c++;switch(a.attributes["cke-list-style-type"]){case "lower-roman":case "upper-roman":a.attributes.start=e.toArabic(e.getSubsectionSymbol(b[c]))-c;break;case "lower-alpha":case "upper-alpha":a.attributes.start=e.getSubsectionSymbol(b[c]).replace(/\W/g,"").toLowerCase().charCodeAt(0)-96-c;break;case "decimal":a.attributes.start=parseInt(e.getSubsectionSymbol(b[c]),10)-c||1}"1"==a.attributes.start&&delete a.attributes.start;
delete a.attributes["cke-list-style-type"]},numbering:{toNumber:function(a,b){function c(a){a=a.toUpperCase();for(var b=1,c=1;0<a.length;c*=26)b+="ABCDEFGHIJKLMNOPQRSTUVWXYZ".indexOf(a.charAt(a.length-1))*c,a=a.substr(0,a.length-1);return b}function d(a){var b=[[1E3,"M"],[900,"CM"],[500,"D"],[400,"CD"],[100,"C"],[90,"XC"],[50,"L"],[40,"XL"],[10,"X"],[9,"IX"],[5,"V"],[4,"IV"],[1,"I"]];a=a.toUpperCase();for(var c=b.length,d=0,f=0;f<c;++f)for(var e=b[f],u=e[1].length;a.substr(0,u)==e[1];a=a.substr(u))d+=
e[0];return d}return"decimal"==b?Number(a):"upper-roman"==b||"lower-roman"==b?d(a.toUpperCase()):"lower-alpha"==b||"upper-alpha"==b?c(a):1},getStyle:function(a){a=a.slice(0,1);var b={i:"lower-roman",v:"lower-roman",x:"lower-roman",l:"lower-roman",m:"lower-roman",I:"upper-roman",V:"upper-roman",X:"upper-roman",L:"upper-roman",M:"upper-roman"}[a];b||(b="decimal",a.match(/[a-z]/)&&(b="lower-alpha"),a.match(/[A-Z]/)&&(b="upper-alpha"));return b}},getSubsectionSymbol:function(a){return(a.match(/([\da-zA-Z]+).?$/)||
["placeholder",1])[1]},setListDir:function(a){var b=0,c=0;a.forEach(function(a){"li"==a.name&&("rtl"==(a.attributes.dir||a.attributes.DIR||"").toLowerCase()?c++:b++)},CKEDITOR.ELEMENT_NODE);c>b&&(a.attributes.dir="rtl")},createList:function(a){return(a.attributes["cke-symbol"].match(/([\da-np-zA-NP-Z]).?/)||[])[1]?new CKEDITOR.htmlParser.element("ol"):new CKEDITOR.htmlParser.element("ul")},createLists:function(a){var b,c,d,f=e.convertToRealListItems(a);if(0===f.length)return[];var k=e.groupLists(f);
for(a=0;a<k.length;a++){var h=k[a],g=h[0];for(d=0;d<h.length;d++)if(1==h[d].attributes["cke-list-level"]){g=h[d];break}var g=[e.createList(g)],l=g[0],t=[g[0]];l.insertBefore(h[0]);for(d=0;d<h.length;d++){b=h[d];for(c=b.attributes["cke-list-level"];c>g.length;){var u=e.createList(b),v=l.children;0<v.length?v[v.length-1].add(u):(v=new CKEDITOR.htmlParser.element("li",{style:"list-style-type:none"}),v.add(u),l.add(v));g.push(u);t.push(u);l=u;c==g.length&&e.setListSymbol(u,b.attributes["cke-symbol"],
c)}for(;c<g.length;)g.pop(),l=g[g.length-1],c==g.length&&e.setListSymbol(l,b.attributes["cke-symbol"],c);b.remove();l.add(b)}g[0].children.length&&(d=g[0].children[0].attributes["cke-symbol"],!d&&1<g[0].children.length&&(d=g[0].children[1].attributes["cke-symbol"]),d&&e.setListSymbol(g[0],d));for(d=0;d<t.length;d++)e.setListStart(t[d]);for(d=0;d<h.length;d++)this.determineListItemValue(h[d])}return f},cleanup:function(a){var b=["cke-list-level","cke-symbol","cke-list-id","cke-indentation","cke-dissolved"],
c,d;for(c=0;c<a.length;c++)for(d=0;d<b.length;d++)delete a[c].attributes[b[d]]},determineListItemValue:function(a){if("ol"===a.parent.name){var b=this.calculateValue(a),c=a.attributes["cke-symbol"].match(/[a-z0-9]+/gi),d;c&&(c=c[c.length-1],d=a.parent.attributes["cke-list-style-type"]||this.numbering.getStyle(c),c=this.numbering.toNumber(c,d),c!==b&&(a.attributes.value=c))}},calculateValue:function(a){if(!a.parent)return 1;var b=a.parent;a=a.getIndex();var c=null,d,f,e;for(e=a;0<=e&&null===c;e--)f=
b.children[e],f.attributes&&void 0!==f.attributes.value&&(d=e,c=parseInt(f.attributes.value,10));null===c&&(c=void 0!==b.attributes.start?parseInt(b.attributes.start,10):1,d=0);return c+(a-d)},dissolveList:function(a){function b(a){return 50<=a?"l"+b(a-50):40<=a?"xl"+b(a-40):10<=a?"x"+b(a-10):9==a?"ix":5<=a?"v"+b(a-5):4==a?"iv":1<=a?"i"+b(a-1):""}function c(a,b){function c(b,d){return b&&b.parent?a(b.parent)?c(b.parent,d+1):c(b.parent,d):d}return c(b,0)}var d=function(a){return function(b){return b.name==
a}},f=function(a){return d("ul")(a)||d("ol")(a)},e=CKEDITOR.tools.array,g=[],q,m;a.forEach(function(a){g.push(a)},CKEDITOR.NODE_ELEMENT,!1);q=e.filter(g,d("li"));var t=e.filter(g,f);e.forEach(t,function(a){var g=a.attributes.type,h=parseInt(a.attributes.start,10)||1,k=c(f,a)+1;g||(g=l.parseCssText(a.attributes.style)["list-style-type"]);e.forEach(e.filter(a.children,d("li")),function(c,d){var e;switch(g){case "disc":e="\u00b7";break;case "circle":e="o";break;case "square":e="\u00a7";break;case "1":case "decimal":e=
h+d+".";break;case "a":case "lower-alpha":e=String.fromCharCode(97+h-1+d)+".";break;case "A":case "upper-alpha":e=String.fromCharCode(65+h-1+d)+".";break;case "i":case "lower-roman":e=b(h+d)+".";break;case "I":case "upper-roman":e=b(h+d).toUpperCase()+".";break;default:e="ul"==a.name?"\u00b7":h+d+"."}c.attributes["cke-symbol"]=e;c.attributes["cke-list-level"]=k})});q=e.reduce(q,function(a,b){var c=b.children[0];if(c&&c.name&&c.attributes.style&&c.attributes.style.match(/mso-list:/i)){h.pushStylesLower(b,
{"list-style-type":!0,display:!0});var d=l.parseCssText(c.attributes.style,!0);h.setStyle(b,"mso-list",d["mso-list"],!0);h.setStyle(c,"mso-list","");delete b["cke-list-level"];(c=d.display?"display":d.DISPLAY?"DISPLAY":"")&&h.setStyle(b,"display",d[c],!0)}if(1===b.children.length&&f(b.children[0]))return a;b.name="p";b.attributes["cke-dissolved"]=!0;a.push(b);return a},[]);for(m=q.length-1;0<=m;m--)q[m].insertAfter(a);for(m=t.length-1;0<=m;m--)delete t[m].name},groupLists:function(a){var b,c,d=[[a[0]]],
f=d[0];c=a[0];c.attributes["cke-indentation"]=c.attributes["cke-indentation"]||e.getElementIndentation(c);for(b=1;b<a.length;b++){c=a[b];var g=a[b-1];c.attributes["cke-indentation"]=c.attributes["cke-indentation"]||e.getElementIndentation(c);c.previous!==g&&(e.chopDiscontinuousLists(f,d),d.push(f=[]));f.push(c)}e.chopDiscontinuousLists(f,d);return d},chopDiscontinuousLists:function(a,b){for(var c={},d=[[]],f,g=0;g<a.length;g++){var h=c[a[g].attributes["cke-list-level"]],m=this.getListItemInfo(a[g]),
n,t;h?(t=h.type.match(/alpha/)&&7==h.index?"alpha":t,t="o"==a[g].attributes["cke-symbol"]&&14==h.index?"alpha":t,n=e.getSymbolInfo(a[g].attributes["cke-symbol"],t),m=this.getListItemInfo(a[g]),(h.type!=n.type||f&&m.id!=f.id&&!this.isAListContinuation(a[g]))&&d.push([])):n=e.getSymbolInfo(a[g].attributes["cke-symbol"]);for(f=parseInt(a[g].attributes["cke-list-level"],10)+1;20>f;f++)c[f]&&delete c[f];c[a[g].attributes["cke-list-level"]]=n;d[d.length-1].push(a[g]);f=m}[].splice.apply(b,[].concat([l.indexOf(b,
a),1],d))},isAListContinuation:function(a){var b=a;do if((b=b.previous)&&b.type===CKEDITOR.NODE_ELEMENT){if(void 0===b.attributes["cke-list-level"])break;if(b.attributes["cke-list-level"]===a.attributes["cke-list-level"])return b.attributes["cke-list-id"]===a.attributes["cke-list-id"]}while(b);return!1},getElementIndentation:function(a){a=l.parseCssText(a.attributes.style);if(a.margin||a.MARGIN){a.margin=a.margin||a.MARGIN;var b={styles:{margin:a.margin}};CKEDITOR.filter.transformationsTools.splitMarginShorthand(b);
a["margin-left"]=b.styles["margin-left"]}return parseInt(l.convertToPx(a["margin-left"]||"0px"),10)},toArabic:function(a){return a.match(/[ivxl]/i)?a.match(/^l/i)?50+e.toArabic(a.slice(1)):a.match(/^lx/i)?40+e.toArabic(a.slice(1)):a.match(/^x/i)?10+e.toArabic(a.slice(1)):a.match(/^ix/i)?9+e.toArabic(a.slice(2)):a.match(/^v/i)?5+e.toArabic(a.slice(1)):a.match(/^iv/i)?4+e.toArabic(a.slice(2)):a.match(/^i/i)?1+e.toArabic(a.slice(1)):e.toArabic(a.slice(1)):0},getSymbolInfo:function(a,b){var c=a.toUpperCase()==
a?"upper-":"lower-",d={"\u00b7":["disc",-1],o:["circle",-2],"\u00a7":["square",-3]};if(a in d||b&&b.match(/(disc|circle|square)/))return{index:d[a][1],type:d[a][0]};if(a.match(/\d/))return{index:a?parseInt(e.getSubsectionSymbol(a),10):0,type:"decimal"};a=a.replace(/\W/g,"").toLowerCase();return!b&&a.match(/[ivxl]+/i)||b&&"alpha"!=b||"roman"==b?{index:e.toArabic(a),type:c+"roman"}:a.match(/[a-z]/i)?{index:a.charCodeAt(0)-97,type:c+"alpha"}:{index:-1,type:"disc"}},getListItemInfo:function(a){if(void 0!==
a.attributes["cke-list-id"])return{id:a.attributes["cke-list-id"],level:a.attributes["cke-list-level"]};var b=l.parseCssText(a.attributes.style)["mso-list"],c={id:"0",level:"1"};b&&(b+=" ",c.level=b.match(/level(.+?)\s+/)[1],c.id=b.match(/l(\d+?)\s+/)[1]);a.attributes["cke-list-level"]=void 0!==a.attributes["cke-list-level"]?a.attributes["cke-list-level"]:c.level;a.attributes["cke-list-id"]=c.id;return c}};e=CKEDITOR.plugins.pastefromword.lists;CKEDITOR.plugins.pastefromword.heuristics={isEdgeListItem:function(a,
b){return CKEDITOR.env.edge&&a.config.pasteFromWord_heuristicsEdgeList?b.attributes.style&&!b.attributes.style.match(/mso\-list/)&&!!b.find(function(a){var b=l.parseCssText(a.attributes&&a.attributes.style);if(!b)return!1;var c=b["font-family"]||"";return(b.font||b["font-size"]||"").match(/7pt/i)&&!!a.previous||c.match(/symbol/i)},!0).length:!1},assignListLevels:function(a,b){if(!b.attributes||void 0===b.attributes["cke-list-level"]){for(var c=[e.getElementIndentation(b)],d=[b],f=[],g=CKEDITOR.tools.array,
h=g.map;b.next&&b.next.attributes&&!b.next.attributes["cke-list-level"]&&n.isEdgeListItem(a,b.next);)b=b.next,c.push(e.getElementIndentation(b)),d.push(b);var l=h(c,function(a,b){return 0===b?0:a-c[b-1]}),m=this.guessIndentationStep(g.filter(c,function(a){return 0!==a})),f=h(c,function(a){return Math.round(a/m)});-1!==g.indexOf(f,0)&&(f=h(f,function(a){return a+1}));g.forEach(d,function(a,b){a.attributes["cke-list-level"]=f[b]});return{indents:c,levels:f,diffs:l}}},guessIndentationStep:function(a){return a.length?
Math.min.apply(null,a):null}};n=CKEDITOR.plugins.pastefromword.heuristics;e.setListSymbol.removeRedundancies=function(a,b){(1===b&&"disc"===a["list-style-type"]||"decimal"===a["list-style-type"])&&delete a["list-style-type"]};CKEDITOR.plugins.pastefromword.createAttributeStack=r;CKEDITOR.config.pasteFromWord_heuristicsEdgeList=!0})();
