var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(l,p,m){if(m.get||m.set)throw new TypeError("ES3 does not support getters and setters.");l!=Array.prototype&&l!=Object.prototype&&(l[p]=m.value)};$jscomp.getGlobal=function(l){return"undefined"!=typeof window&&window===l?l:"undefined"!=typeof global&&null!=global?global:l};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(l,p,m,n){if(p){m=$jscomp.global;l=l.split(".");for(n=0;n<l.length-1;n++){var v=l[n];v in m||(m[v]={});m=m[v]}l=l[l.length-1];n=m[l];p=p(n);p!=n&&null!=p&&$jscomp.defineProperty(m,l,{configurable:!0,writable:!0,value:p})}};$jscomp.polyfill("Array.prototype.fill",function(l){return l?l:function(l,m,n){var p=this.length||0;0>m&&(m=Math.max(0,p+m));if(null==n||n>p)n=p;n=Number(n);0>n&&(n=Math.max(0,p+n));for(m=Number(m||0);m<n;m++)this[m]=l;return this}},"es6-impl","es3");
document.createElement("canvas").getContext||function(){function l(){return this.context_||(this.context_=new D(this))}function p(a,b,c){var f=N.call(arguments,2);return function(){return a.apply(b,f.concat(N.call(arguments)))}}function m(a){return String(a).replace(/&/g,"&amp;").replace(/"/g,"&quot;")}function n(a){a.namespaces.g_vml_||a.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml","#default#VML");a.namespaces.g_o_||a.namespaces.add("g_o_","urn:schemas-microsoft-com:office:office","#default#VML");
a.styleSheets.ex_canvas_||(a=a.createStyleSheet(),a.owningElement.id="ex_canvas_",a.cssText="canvas{display:inline-block;overflow:hidden;text-align:left;width:300px;height:150px}")}function v(a){var b=a.srcElement;switch(a.propertyName){case "width":b.getContext().clearRect();b.style.width=b.attributes.width.nodeValue+"px";b.firstChild.style.width=b.clientWidth+"px";break;case "height":b.getContext().clearRect(),b.style.height=b.attributes.height.nodeValue+"px",b.firstChild.style.height=b.clientHeight+
"px"}}function U(a){a=a.srcElement;a.firstChild&&(a.firstChild.style.width=a.clientWidth+"px",a.firstChild.style.height=a.clientHeight+"px")}function E(){return[[1,0,0],[0,1,0],[0,0,1]]}function w(a,b){for(var c=E(),f=0;3>f;f++)for(var d=0;3>d;d++){for(var r=0,g=0;3>g;g++)r+=a[f][g]*b[g][d];c[f][d]=r}return c}function O(a,b){b.fillStyle=a.fillStyle;b.lineCap=a.lineCap;b.lineJoin=a.lineJoin;b.lineWidth=a.lineWidth;b.miterLimit=a.miterLimit;b.shadowBlur=a.shadowBlur;b.shadowColor=a.shadowColor;b.shadowOffsetX=
a.shadowOffsetX;b.shadowOffsetY=a.shadowOffsetY;b.strokeStyle=a.strokeStyle;b.globalAlpha=a.globalAlpha;b.font=a.font;b.textAlign=a.textAlign;b.textBaseline=a.textBaseline;b.arcScaleX_=a.arcScaleX_;b.arcScaleY_=a.arcScaleY_;b.lineScale_=a.lineScale_}function P(a){var b=a.indexOf("(",3),c=a.indexOf(")",b+1),b=a.substring(b+1,c).split(",");if(4!=b.length||"a"!=a.charAt(3))b[3]=1;return b}function F(a,b,c){return Math.min(c,Math.max(b,a))}function G(a,b,c){0>c&&c++;1<c&&c--;return 1>6*c?a+6*(b-a)*c:
1>2*c?b:2>3*c?a+(b-a)*(2/3-c)*6:a}function H(a){if(a in I)return I[a];var b,c=1;a=String(a);if("#"==a.charAt(0))b=a;else if(/^rgb/.test(a)){c=P(a);b="#";for(var f,d=0;3>d;d++)f=-1!=c[d].indexOf("%")?Math.floor(parseFloat(c[d])/100*255):+c[d],b+=x[F(f,0,255)];c=+c[3]}else if(/^hsl/.test(a)){d=c=P(a);b=parseFloat(d[0])/360%360;0>b&&b++;f=F(parseFloat(d[1])/100,0,1);d=F(parseFloat(d[2])/100,0,1);if(0==f)f=d=b=d;else{var r=.5>d?d*(1+f):d+f-d*f,g=2*d-r;f=G(g,r,b+1/3);d=G(g,r,b);b=G(g,r,b-1/3)}b="#"+x[Math.floor(255*
f)]+x[Math.floor(255*d)]+x[Math.floor(255*b)];c=c[3]}else b=V[a]||a;return I[a]={color:b,alpha:c}}function D(a){this.m_=E();this.mStack_=[];this.aStack_=[];this.currentPath_=[];this.fillStyle=this.strokeStyle="#000";this.lineWidth=1;this.lineJoin="miter";this.lineCap="butt";this.miterLimit=10;this.globalAlpha=1;this.font="10px sans-serif";this.textAlign="left";this.textBaseline="alphabetic";this.canvas=a;var b="width:"+a.clientWidth+"px;height:"+a.clientHeight+"px;overflow:hidden;position:absolute",
c=a.ownerDocument.createElement("div");c.style.cssText=b;a.appendChild(c);b=c.cloneNode(!1);b.style.backgroundColor="red";b.style.filter="alpha(opacity=0)";a.appendChild(b);this.element_=c;this.lineScale_=this.arcScaleY_=this.arcScaleX_=1}function Q(a,b,c,f){a.currentPath_.push({type:"bezierCurveTo",cp1x:b.x,cp1y:b.y,cp2x:c.x,cp2y:c.y,x:f.x,y:f.y});a.currentX_=f.x;a.currentY_=f.y}function R(a,b){var c=H(a.strokeStyle),f=c.color,c=c.alpha*a.globalAlpha,d=a.lineScale_*a.lineWidth;1>d&&(c*=d);b.push("<g_vml_:stroke",
' opacity="',c,'"',' joinstyle="',a.lineJoin,'"',' miterlimit="',a.miterLimit,'"',' endcap="',W[a.lineCap]||"square",'"',' weight="',d,'px"',' color="',f,'" />')}function S(a,b,c,f){var d=a.fillStyle,r=a.arcScaleX_,g=a.arcScaleY_,e=f.x-c.x,k=f.y-c.y;if(d instanceof z){var h=0,q=f=0,l=0,t=1;if("gradient"==d.type_){h=d.x1_/r;c=d.y1_/g;var m=u(a,d.x0_/r,d.y0_/g),h=u(a,h,c),h=180*Math.atan2(h.x-m.x,h.y-m.y)/Math.PI;0>h&&(h+=360);1E-6>h&&(h=0)}else m=u(a,d.x0_,d.y0_),f=(m.x-c.x)/e,q=(m.y-c.y)/k,t=y.max(e/
(10*r),k/(10*g)),l=2*d.r0_/t,t=2*d.r1_/t-l;r=d.colors_;r.sort(function(a,b){return a.offset-b.offset});g=r.length;m=r[0].color;c=r[g-1].color;e=r[0].alpha*a.globalAlpha;a=r[g-1].alpha*a.globalAlpha;for(var k=[],n=0;n<g;n++){var p=r[n];k.push(p.offset*t+l+" "+p.color)}b.push('<g_vml_:fill type="',d.type_,'"',' method="none" focus="100%"',' color="',m,'"',' color2="',c,'"',' colors="',k.join(","),'"',' opacity="',a,'"',' g_o_:opacity2="',e,'"',' angle="',h,'"',' focusposition="',f,",",q,'" />')}else d instanceof
J?e&&k&&b.push("<g_vml_:fill",' position="',-c.x/e*r*r,",",-c.y/k*g*g,'"',' type="tile"',' src="',d.src_,'" />'):(d=H(a.fillStyle),b.push('<g_vml_:fill color="',d.color,'" opacity="',d.alpha*a.globalAlpha,'" />'))}function u(a,b,c){a=a.m_;return{x:10*(b*a[0][0]+c*a[1][0]+a[2][0])-5,y:10*(b*a[0][1]+c*a[1][1]+a[2][1])-5}}function A(a,b,c){isFinite(b[0][0])&&isFinite(b[0][1])&&isFinite(b[1][0])&&isFinite(b[1][1])&&isFinite(b[2][0])&&isFinite(b[2][1])&&(a.m_=b,c&&(a.lineScale_=X(Y(b[0][0]*b[1][1]-b[0][1]*
b[1][0]))))}function z(a){this.type_=a;this.r1_=this.y1_=this.x1_=this.r0_=this.y0_=this.x0_=0;this.colors_=[]}function J(a,b){if(!a||1!=a.nodeType||"IMG"!=a.tagName)throw new B("TYPE_MISMATCH_ERR");if("complete"!=a.readyState)throw new B("INVALID_STATE_ERR");switch(b){case "repeat":case null:case "":this.repetition_="repeat";break;case "repeat-x":case "repeat-y":case "no-repeat":this.repetition_=b;break;default:throw new B("SYNTAX_ERR");}this.src_=a.src;this.width_=a.width;this.height_=a.height}
function B(a){this.code=this[a];this.message=a+": DOM Exception "+this.code}var y=Math,k=y.round,K=y.sin,L=y.cos,Y=y.abs,X=y.sqrt;navigator.userAgent.match(/MSIE ([\d.]+)?/);var N=Array.prototype.slice;n(document);var T={init:function(a){a=a||document;a.createElement("canvas");a.attachEvent("onreadystatechange",p(this.init_,this,a))},init_:function(a){a=a.getElementsByTagName("canvas");for(var b=0;b<a.length;b++)this.initElement(a[b])},initElement:function(a){if(!a.getContext){a.getContext=l;n(a.ownerDocument);
a.innerHTML="";a.attachEvent("onpropertychange",v);a.attachEvent("onresize",U);var b=a.attributes;b.width&&b.width.specified?a.style.width=b.width.nodeValue+"px":a.width=a.clientWidth;b.height&&b.height.specified?a.style.height=b.height.nodeValue+"px":a.height=a.clientHeight}return a}};T.init();for(var x=[],e=0;16>e;e++)for(var C=0;16>C;C++)x[16*e+C]=e.toString(16)+C.toString(16);var V={aliceblue:"#F0F8FF",antiquewhite:"#FAEBD7",aquamarine:"#7FFFD4",azure:"#F0FFFF",beige:"#F5F5DC",bisque:"#FFE4C4",
black:"#000000",blanchedalmond:"#FFEBCD",blueviolet:"#8A2BE2",brown:"#A52A2A",burlywood:"#DEB887",cadetblue:"#5F9EA0",chartreuse:"#7FFF00",chocolate:"#D2691E",coral:"#FF7F50",cornflowerblue:"#6495ED",cornsilk:"#FFF8DC",crimson:"#DC143C",cyan:"#00FFFF",darkblue:"#00008B",darkcyan:"#008B8B",darkgoldenrod:"#B8860B",darkgray:"#A9A9A9",darkgreen:"#006400",darkgrey:"#A9A9A9",darkkhaki:"#BDB76B",darkmagenta:"#8B008B",darkolivegreen:"#556B2F",darkorange:"#FF8C00",darkorchid:"#9932CC",darkred:"#8B0000",darksalmon:"#E9967A",
darkseagreen:"#8FBC8F",darkslateblue:"#483D8B",darkslategray:"#2F4F4F",darkslategrey:"#2F4F4F",darkturquoise:"#00CED1",darkviolet:"#9400D3",deeppink:"#FF1493",deepskyblue:"#00BFFF",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1E90FF",firebrick:"#B22222",floralwhite:"#FFFAF0",forestgreen:"#228B22",gainsboro:"#DCDCDC",ghostwhite:"#F8F8FF",gold:"#FFD700",goldenrod:"#DAA520",grey:"#808080",greenyellow:"#ADFF2F",honeydew:"#F0FFF0",hotpink:"#FF69B4",indianred:"#CD5C5C",indigo:"#4B0082",ivory:"#FFFFF0",
khaki:"#F0E68C",lavender:"#E6E6FA",lavenderblush:"#FFF0F5",lawngreen:"#7CFC00",lemonchiffon:"#FFFACD",lightblue:"#ADD8E6",lightcoral:"#F08080",lightcyan:"#E0FFFF",lightgoldenrodyellow:"#FAFAD2",lightgreen:"#90EE90",lightgrey:"#D3D3D3",lightpink:"#FFB6C1",lightsalmon:"#FFA07A",lightseagreen:"#20B2AA",lightskyblue:"#87CEFA",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#B0C4DE",lightyellow:"#FFFFE0",limegreen:"#32CD32",linen:"#FAF0E6",magenta:"#FF00FF",mediumaquamarine:"#66CDAA",
mediumblue:"#0000CD",mediumorchid:"#BA55D3",mediumpurple:"#9370DB",mediumseagreen:"#3CB371",mediumslateblue:"#7B68EE",mediumspringgreen:"#00FA9A",mediumturquoise:"#48D1CC",mediumvioletred:"#C71585",midnightblue:"#191970",mintcream:"#F5FFFA",mistyrose:"#FFE4E1",moccasin:"#FFE4B5",navajowhite:"#FFDEAD",oldlace:"#FDF5E6",olivedrab:"#6B8E23",orange:"#FFA500",orangered:"#FF4500",orchid:"#DA70D6",palegoldenrod:"#EEE8AA",palegreen:"#98FB98",paleturquoise:"#AFEEEE",palevioletred:"#DB7093",papayawhip:"#FFEFD5",
peachpuff:"#FFDAB9",peru:"#CD853F",pink:"#FFC0CB",plum:"#DDA0DD",powderblue:"#B0E0E6",rosybrown:"#BC8F8F",royalblue:"#4169E1",saddlebrown:"#8B4513",salmon:"#FA8072",sandybrown:"#F4A460",seagreen:"#2E8B57",seashell:"#FFF5EE",sienna:"#A0522D",skyblue:"#87CEEB",slateblue:"#6A5ACD",slategray:"#708090",slategrey:"#708090",snow:"#FFFAFA",springgreen:"#00FF7F",steelblue:"#4682B4",tan:"#D2B48C",thistle:"#D8BFD8",tomato:"#FF6347",turquoise:"#40E0D0",violet:"#EE82EE",wheat:"#F5DEB3",whitesmoke:"#F5F5F5",yellowgreen:"#9ACD32"},
I={},M={},W={butt:"flat",round:"round"},e=D.prototype;e.clearRect=function(){this.textMeasureEl_&&(this.textMeasureEl_.removeNode(!0),this.textMeasureEl_=null);this.element_.innerHTML=""};e.beginPath=function(){this.currentPath_=[]};e.moveTo=function(a,b){var c=u(this,a,b);this.currentPath_.push({type:"moveTo",x:c.x,y:c.y});this.currentX_=c.x;this.currentY_=c.y};e.lineTo=function(a,b){var c=u(this,a,b);this.currentPath_.push({type:"lineTo",x:c.x,y:c.y});this.currentX_=c.x;this.currentY_=c.y};e.bezierCurveTo=
function(a,b,c,f,d,e){d=u(this,d,e);a=u(this,a,b);c=u(this,c,f);Q(this,a,c,d)};e.quadraticCurveTo=function(a,b,c,f){a=u(this,a,b);c=u(this,c,f);f={x:this.currentX_+2/3*(a.x-this.currentX_),y:this.currentY_+2/3*(a.y-this.currentY_)};Q(this,f,{x:f.x+(c.x-this.currentX_)/3,y:f.y+(c.y-this.currentY_)/3},c)};e.arc=function(a,b,c,f,d,e){c*=10;var g=e?"at":"wa",r=a+L(f)*c-5,k=b+K(f)*c-5;f=a+L(d)*c-5;d=b+K(d)*c-5;r!=f||e||(r+=.125);a=u(this,a,b);r=u(this,r,k);f=u(this,f,d);this.currentPath_.push({type:g,
x:a.x,y:a.y,radius:c,xStart:r.x,yStart:r.y,xEnd:f.x,yEnd:f.y})};e.rect=function(a,b,c,f){this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+c,b+f);this.lineTo(a,b+f);this.closePath()};e.strokeRect=function(a,b,c,f){var d=this.currentPath_;this.beginPath();this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+c,b+f);this.lineTo(a,b+f);this.closePath();this.stroke();this.currentPath_=d};e.fillRect=function(a,b,c,f){var d=this.currentPath_;this.beginPath();this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+
c,b+f);this.lineTo(a,b+f);this.closePath();this.fill();this.currentPath_=d};e.createLinearGradient=function(a,b,c,f){var d=new z("gradient");d.x0_=a;d.y0_=b;d.x1_=c;d.y1_=f;return d};e.createRadialGradient=function(a,b,c,f,d,e){var g=new z("gradientradial");g.x0_=a;g.y0_=b;g.r0_=c;g.x1_=f;g.y1_=d;g.r1_=e;return g};e.drawImage=function(a,b){var c,f,d,e,g,m,l,h;d=a.runtimeStyle.width;e=a.runtimeStyle.height;a.runtimeStyle.width="auto";a.runtimeStyle.height="auto";var q=a.width,n=a.height;a.runtimeStyle.width=
d;a.runtimeStyle.height=e;if(3==arguments.length)c=arguments[1],f=arguments[2],g=m=0,l=d=q,h=e=n;else if(5==arguments.length)c=arguments[1],f=arguments[2],d=arguments[3],e=arguments[4],g=m=0,l=q,h=n;else if(9==arguments.length)g=arguments[1],m=arguments[2],l=arguments[3],h=arguments[4],c=arguments[5],f=arguments[6],d=arguments[7],e=arguments[8];else throw Error("Invalid number of arguments");var t=u(this,c,f),p=[];p.push(" <g_vml_:group",' coordsize="',100,",",100,'"',' coordorigin="0,0"',' style="width:',
10,"px;height:",10,"px;position:absolute;");if(1!=this.m_[0][0]||this.m_[0][1]||1!=this.m_[1][1]||this.m_[1][0]){var v=[];v.push("M11=",this.m_[0][0],",","M12=",this.m_[1][0],",","M21=",this.m_[0][1],",","M22=",this.m_[1][1],",","Dx=",k(t.x/10),",","Dy=",k(t.y/10),"");var w=u(this,c+d,f),x=u(this,c,f+e);c=u(this,c+d,f+e);t.x=y.max(t.x,w.x,x.x,c.x);t.y=y.max(t.y,w.y,x.y,c.y);p.push("padding:0 ",k(t.x/10),"px ",k(t.y/10),"px 0;filter:progid:DXImageTransform.Microsoft.Matrix(",v.join(""),", sizingmethod='clip');")}else p.push("top:",
k(t.y/10),"px;left:",k(t.x/10),"px;");p.push(' ">','<g_vml_:image src="',a.src,'"',' style="width:',10*d,"px;"," height:",10*e,'px"',' cropleft="',g/q,'"',' croptop="',m/n,'"',' cropright="',(q-g-l)/q,'"',' cropbottom="',(n-m-h)/n,'"'," />","</g_vml_:group>");this.element_.insertAdjacentHTML("BeforeEnd",p.join(""))};e.stroke=function(a){for(var b={x:null,y:null},c={x:null,y:null},f=0;f<this.currentPath_.length;f+=5E3){var d=[];d.push("<g_vml_:shape",' filled="',!!a,'"',' style="position:absolute;width:',
10,"px;height:",10,'px;"',' coordorigin="0,0"',' coordsize="',100,",",100,'"',' stroked="',!a,'"',' path="');for(var e=f;e<Math.min(f+5E3,this.currentPath_.length);e++){0==e%5E3&&0<e&&d.push(" m ",k(this.currentPath_[e-1].x),",",k(this.currentPath_[e-1].y));var g=this.currentPath_[e];switch(g.type){case "moveTo":d.push(" m ",k(g.x),",",k(g.y));break;case "lineTo":d.push(" l ",k(g.x),",",k(g.y));break;case "close":d.push(" x ");g=null;break;case "bezierCurveTo":d.push(" c ",k(g.cp1x),",",k(g.cp1y),
",",k(g.cp2x),",",k(g.cp2y),",",k(g.x),",",k(g.y));break;case "at":case "wa":d.push(" ",g.type," ",k(g.x-this.arcScaleX_*g.radius),",",k(g.y-this.arcScaleY_*g.radius)," ",k(g.x+this.arcScaleX_*g.radius),",",k(g.y+this.arcScaleY_*g.radius)," ",k(g.xStart),",",k(g.yStart)," ",k(g.xEnd),",",k(g.yEnd))}if(g){if(null==b.x||g.x<b.x)b.x=g.x;if(null==c.x||g.x>c.x)c.x=g.x;if(null==b.y||g.y<b.y)b.y=g.y;if(null==c.y||g.y>c.y)c.y=g.y}}d.push(' ">');a?S(this,d,b,c):R(this,d);d.push("</g_vml_:shape>");this.element_.insertAdjacentHTML("beforeEnd",
d.join(""))}};e.fill=function(){this.stroke(!0)};e.closePath=function(){this.currentPath_.push({type:"close"})};e.save=function(){var a={};O(this,a);this.aStack_.push(a);this.mStack_.push(this.m_);this.m_=w(E(),this.m_)};e.restore=function(){this.aStack_.length&&(O(this.aStack_.pop(),this),this.m_=this.mStack_.pop())};e.translate=function(a,b){A(this,w([[1,0,0],[0,1,0],[a,b,1]],this.m_),!1)};e.rotate=function(a){var b=L(a);a=K(a);A(this,w([[b,a,0],[-a,b,0],[0,0,1]],this.m_),!1)};e.scale=function(a,
b){this.arcScaleX_*=a;this.arcScaleY_*=b;A(this,w([[a,0,0],[0,b,0],[0,0,1]],this.m_),!0)};e.transform=function(a,b,c,f,d,e){A(this,w([[a,b,0],[c,f,0],[d,e,1]],this.m_),!0)};e.setTransform=function(a,b,c,f,d,e){A(this,[[a,b,0],[c,f,0],[d,e,1]],!0)};e.drawText_=function(a,b,c,e,d){var f=this.m_;e=0;var g=1E3,l=0,n=[],h;h=this.font;if(M[h])h=M[h];else{var q=document.createElement("div").style;try{q.font=h}catch(Z){}h=M[h]={style:q.fontStyle||"normal",variant:q.fontVariant||"normal",weight:q.fontWeight||
"normal",size:q.fontSize||10,family:q.fontFamily||"sans-serif"}}var q=h,p=this.element_;h={};for(var t in q)h[t]=q[t];t=parseFloat(p.currentStyle.fontSize);p=parseFloat(q.size);"number"==typeof q.size?h.size=q.size:-1!=q.size.indexOf("px")?h.size=p:-1!=q.size.indexOf("em")?h.size=t*p:-1!=q.size.indexOf("%")?h.size=t/100*p:-1!=q.size.indexOf("pt")?h.size=p/.75:h.size=t;h.size*=.981;t=h.style+" "+h.variant+" "+h.weight+" "+h.size+"px "+h.family;p=this.element_.currentStyle;q=this.textAlign.toLowerCase();
switch(q){case "left":case "center":case "right":break;case "end":q="ltr"==p.direction?"right":"left";break;case "start":q="rtl"==p.direction?"right":"left";break;default:q="left"}switch(this.textBaseline){case "hanging":case "top":l=h.size/1.75;break;case "middle":break;default:case null:case "alphabetic":case "ideographic":case "bottom":l=-h.size/2.25}switch(q){case "right":e=1E3;g=.05;break;case "center":e=g=500}b=u(this,b+0,c+l);n.push('<g_vml_:line from="',-e,' 0" to="',g,' 0.05" ',' coordsize="100 100" coordorigin="0 0"',
' filled="',!d,'" stroked="',!!d,'" style="position:absolute;width:1px;height:1px;">');d?R(this,n):S(this,n,{x:-e,y:0},{x:g,y:h.size});d=f[0][0].toFixed(3)+","+f[1][0].toFixed(3)+","+f[0][1].toFixed(3)+","+f[1][1].toFixed(3)+",0,0";b=k(b.x/10)+","+k(b.y/10);n.push('<g_vml_:skew on="t" matrix="',d,'" ',' offset="',b,'" origin="',e,' 0" />','<g_vml_:path textpathok="true" />','<g_vml_:textpath on="true" string="',m(a),'" style="v-text-align:',q,";font:",m(t),'" /></g_vml_:line>');this.element_.insertAdjacentHTML("beforeEnd",
n.join(""))};e.fillText=function(a,b,c,e){this.drawText_(a,b,c,e,!1)};e.strokeText=function(a,b,c,e){this.drawText_(a,b,c,e,!0)};e.measureText=function(a){this.textMeasureEl_||(this.element_.insertAdjacentHTML("beforeEnd",'<span style="position:absolute;top:-20000px;left:0;padding:0;margin:0;border:none;white-space:pre;"></span>'),this.textMeasureEl_=this.element_.lastChild);var b=this.element_.ownerDocument;this.textMeasureEl_.innerHTML="";this.textMeasureEl_.style.font=this.font;this.textMeasureEl_.appendChild(b.createTextNode(a));
return{width:this.textMeasureEl_.offsetWidth}};e.clip=function(){};e.arcTo=function(){};e.createPattern=function(a,b){return new J(a,b)};z.prototype.addColorStop=function(a,b){b=H(b);this.colors_.push({offset:a,color:b.color,alpha:b.alpha})};e=B.prototype=Error();e.INDEX_SIZE_ERR=1;e.DOMSTRING_SIZE_ERR=2;e.HIERARCHY_REQUEST_ERR=3;e.WRONG_DOCUMENT_ERR=4;e.INVALID_CHARACTER_ERR=5;e.NO_DATA_ALLOWED_ERR=6;e.NO_MODIFICATION_ALLOWED_ERR=7;e.NOT_FOUND_ERR=8;e.NOT_SUPPORTED_ERR=9;e.INUSE_ATTRIBUTE_ERR=10;
e.INVALID_STATE_ERR=11;e.SYNTAX_ERR=12;e.INVALID_MODIFICATION_ERR=13;e.NAMESPACE_ERR=14;e.INVALID_ACCESS_ERR=15;e.VALIDATION_ERR=16;e.TYPE_MISMATCH_ERR=17;G_vmlCanvasManager=T;CanvasRenderingContext2D=D;CanvasGradient=z;CanvasPattern=J;DOMException=B}();
