var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(l,g,a){if(a.get||a.set)throw new TypeError("ES3 does not support getters and setters.");l!=Array.prototype&&l!=Object.prototype&&(l[g]=a.value)};$jscomp.getGlobal=function(l){return"undefined"!=typeof window&&window===l?l:"undefined"!=typeof global&&null!=global?global:l};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(l,g,a,e){if(g){a=$jscomp.global;l=l.split(".");for(e=0;e<l.length-1;e++){var w=l[e];w in a||(a[w]={});a=a[w]}l=l[l.length-1];e=a[l];g=g(e);g!=e&&null!=g&&$jscomp.defineProperty(a,l,{configurable:!0,writable:!0,value:g})}};$jscomp.polyfill("Array.prototype.fill",function(l){return l?l:function(l,a,e){var g=this.length||0;0>a&&(a=Math.max(0,g+a));if(null==e||e>g)e=g;e=Number(e);0>e&&(e=Math.max(0,g+e));for(a=Number(a||0);a<e;a++)this[a]=l;return this}},"es6-impl","es3");
(function(l){l.plot.plugins.push({init:function(g){function a(b){for(var n=0,c=0,g=0,a=f.series.pie.combine.color,p=[],k=0;k<b.length;++k){var d=b[k].data;l.isArray(d)&&1==d.length&&(d=d[0]);l.isArray(d)?!isNaN(parseFloat(d[1]))&&isFinite(d[1])?d[1]=+d[1]:d[1]=0:d=!isNaN(parseFloat(d))&&isFinite(d)?[1,+d]:[1,0];b[k].data=[d]}for(k=0;k<b.length;++k)n+=b[k].data[0][1];for(k=0;k<b.length;++k)d=b[k].data[0][1],d/n<=f.series.pie.combine.threshold&&(c+=d,g++,a||(a=b[k].color));for(k=0;k<b.length;++k)d=
b[k].data[0][1],(2>g||d/n>f.series.pie.combine.threshold)&&p.push({data:[[1,d]],color:b[k].color,label:b[k].label,angle:d*Math.PI*2/n,percent:d/(n/100)});1<g&&p.push({data:[[1,c]],color:a,label:f.series.pie.combine.label,angle:c*Math.PI*2/n,percent:c/(n/100)});return p}function e(b,n){function g(){c.clearRect(0,0,p,k);x.children().filter(".pieLabel, .pieLabelBackground").remove()}function a(){var b=f.series.pie.shadow.left,n=f.series.pie.shadow.top,d=f.series.pie.shadow.alpha,g=1<f.series.pie.radius?
f.series.pie.radius:t*f.series.pie.radius;if(!(g>=p/2-b||g*f.series.pie.tilt>=k/2-n||10>=g)){c.save();c.translate(b,n);c.globalAlpha=d;c.fillStyle="#000";c.translate(r,z);c.scale(1,f.series.pie.tilt);for(b=1;10>=b;b++)c.beginPath(),c.arc(0,0,g,0,2*Math.PI,!1),c.fill(),g-=b;c.restore()}}function m(){function b(b,n,f){0>=b||isNaN(b)||(f?c.fillStyle=n:(c.strokeStyle=n,c.lineJoin="round"),c.beginPath(),1E-9<Math.abs(b-2*Math.PI)&&c.moveTo(0,0),c.arc(0,0,d,a,a+b/2,!1),c.arc(0,0,d,a+b/2,a+b,!1),c.closePath(),
a+=b,f?c.fill():c.stroke())}function n(){for(var b=g,n=1<f.series.pie.label.radius?f.series.pie.label.radius:t*f.series.pie.label.radius,c=0;c<e.length;++c){if(e[c].percent>=100*f.series.pie.label.threshold){var d;var a;d=e[c];var q=b,h=c;if(0==d.data[0][1])d=!0;else{a=f.legend.labelFormatter;var m=f.series.pie.label.formatter;a=a?a(d.label,d):d.label;m&&(a=m(a,d));m=(q+d.angle+q)/2;q=r+Math.round(Math.cos(m)*n);m=z+Math.round(Math.sin(m)*n)*f.series.pie.tilt;x.append("<span class='pieLabel' id='pieLabel"+
h+"' style='position:absolute;top:"+m+"px;left:"+q+"px;'>"+a+"</span>");h=x.children("#pieLabel"+h);a=m-h.height()/2;m=q-h.width()/2;h.css("top",a);h.css("left",m);0<0-a||0<0-m||0>k-(a+h.height())||0>p-(m+h.width())?d=!1:(0!=f.series.pie.label.background.opacity&&(q=f.series.pie.label.background.color,null==q&&(q=d.color),d="top:"+a+"px;left:"+m+"px;",l("<div class='pieLabelBackground' style='position:absolute;width:"+h.width()+"px;height:"+h.height()+"px;"+d+"background-color:"+q+";'></div>").css("opacity",
f.series.pie.label.background.opacity).insertBefore(h)),d=!0)}if(!d)return!1}b+=e[c].angle}return!0}var g=Math.PI*f.series.pie.startAngle,d=1<f.series.pie.radius?f.series.pie.radius:t*f.series.pie.radius;c.save();c.translate(r,z);c.scale(1,f.series.pie.tilt);c.save();for(var a=g,q=0;q<e.length;++q)e[q].startAngle=a,b(e[q].angle,e[q].color,!0);c.restore();if(0<f.series.pie.stroke.width){c.save();c.lineWidth=f.series.pie.stroke.width;a=g;for(q=0;q<e.length;++q)b(e[q].angle,f.series.pie.stroke.color,
!1);c.restore()}w(c);c.restore();return f.series.pie.label.show?n():!0}if(x){var p=b.getPlaceholder().width(),k=b.getPlaceholder().height(),d=x.children().filter(".legend").children().width()||0;c=n;B=!1;t=Math.min(p,k/f.series.pie.tilt)/2;z=k/2+f.series.pie.offset.top;r=p/2;"auto"==f.series.pie.offset.left?(r=f.legend.position.match("w")?r+d/2:r-d/2,r<t?r=t:r>p-t&&(r=p-t)):r+=f.series.pie.offset.left;var e=b.getData(),d=0;do 0<d&&(t*=.95),d+=1,g(),.8>=f.series.pie.tilt&&a();while(!m()&&10>d);10<=
d&&(g(),x.prepend("<div class='error'>Could not draw pie with labels contained inside canvas</div>"));b.setSeries&&b.insertLegend&&(b.setSeries(e),b.insertLegend())}}function w(b){if(0<f.series.pie.innerRadius){b.save();var n=1<f.series.pie.innerRadius?f.series.pie.innerRadius:t*f.series.pie.innerRadius;b.globalCompositeOperation="destination-out";b.beginPath();b.fillStyle=f.series.pie.stroke.color;b.arc(0,0,n,0,2*Math.PI,!1);b.fill();b.closePath();b.restore();b.save();b.beginPath();b.strokeStyle=
f.series.pie.stroke.color;b.arc(0,0,n,0,2*Math.PI,!1);b.stroke();b.closePath();b.restore()}}function F(b){C("plothover",b)}function G(b){C("plotclick",b)}function C(b,n){var a=g.offset(),e=parseInt(n.pageX-a.left);a:{for(var a=parseInt(n.pageY-a.top),m=g.getData(),p=g.getOptions(),p=1<p.series.pie.radius?p.series.pie.radius:t*p.series.pie.radius,k,d,l=0;l<m.length;++l){var h=m[l];if(h.pie.show){c.save();c.beginPath();c.moveTo(0,0);c.arc(0,0,p,h.startAngle,h.startAngle+h.angle/2,!1);c.arc(0,0,p,h.startAngle+
h.angle/2,h.startAngle+h.angle,!1);c.closePath();k=e-r;d=a-z;if(c.isPointInPath){if(c.isPointInPath(e-r,a-z)){c.restore();e={datapoint:[h.percent,h.data],dataIndex:0,series:h,seriesIndex:l};break a}}else{var u=[[0,0],[p*Math.cos(h.startAngle),p*Math.sin(h.startAngle)],[p*Math.cos(h.startAngle+h.angle/4),p*Math.sin(h.startAngle+h.angle/4)],[p*Math.cos(h.startAngle+h.angle/2),p*Math.sin(h.startAngle+h.angle/2)],[p*Math.cos(h.startAngle+h.angle/1.5),p*Math.sin(h.startAngle+h.angle/1.5)],[p*Math.cos(h.startAngle+
h.angle),p*Math.sin(h.startAngle+h.angle)]];k=[k,d];d=!1;for(var y=-1,w=u.length,A=w-1;++y<w;A=y)(u[y][1]<=k[1]&&k[1]<u[A][1]||u[A][1]<=k[1]&&k[1]<u[y][1])&&k[0]<(u[A][0]-u[y][0])*(k[1]-u[y][1])/(u[A][1]-u[y][1])+u[y][0]&&(d=!d);if(d){c.restore();e={datapoint:[h.percent,h.data],dataIndex:0,series:h,seriesIndex:l};break a}}c.restore()}}e=null}if(f.grid.autoHighlight)for(a=0;a<v.length;++a)m=v[a],m.auto!=b||e&&m.series==e.series||(m=m.series,null==m&&(v=[],g.triggerRedrawOverlay()),m=D(m),-1!=m&&(v.splice(m,
1),g.triggerRedrawOverlay()));e&&(a=e.series,m=D(a),-1==m?(v.push({series:a,auto:b}),g.triggerRedrawOverlay()):b||(v[m].auto=!1));x.trigger(b,[{pageX:n.pageX,pageY:n.pageY},e])}function D(b){for(var a=0;a<v.length;++a)if(v[a].series==b)return a;return-1}var E=null,x=null,f=null,t=null,r=null,z=null,B=!1,c=null,v=[];g.hooks.processOptions.push(function(b,a){a.series.pie.show&&(a.grid.show=!1,"auto"==a.series.pie.label.show&&(a.series.pie.label.show=a.legend.show?!1:!0),"auto"==a.series.pie.radius&&
(a.series.pie.radius=a.series.pie.label.show?.75:1),1<a.series.pie.tilt?a.series.pie.tilt=1:0>a.series.pie.tilt&&(a.series.pie.tilt=0))});g.hooks.bindEvents.push(function(a,c){var b=a.getOptions();b.series.pie.show&&(b.grid.hoverable&&c.unbind("mousemove").mousemove(F),b.grid.clickable&&c.unbind("click").click(G))});g.hooks.processDatapoints.push(function(b,c,g,e){b.getOptions().series.pie.show&&!B&&(B=!0,E=b.getCanvas(),x=l(E).parent(),f=b.getOptions(),b.setData(a(b.getData())))});g.hooks.drawOverlay.push(function(a,
c){if(a.getOptions().series.pie.show){var b=a.getOptions(),f=1<b.series.pie.radius?b.series.pie.radius:t*b.series.pie.radius;c.save();c.translate(r,z);c.scale(1,b.series.pie.tilt);for(var g=0;g<v.length;++g){var e=v[g].series;0>=e.angle||isNaN(e.angle)||(c.fillStyle="rgba(255, 255, 255, "+b.series.pie.highlight.opacity+")",c.beginPath(),1E-9<Math.abs(e.angle-2*Math.PI)&&c.moveTo(0,0),c.arc(0,0,f,e.startAngle,e.startAngle+e.angle/2,!1),c.arc(0,0,f,e.startAngle+e.angle/2,e.startAngle+e.angle,!1),c.closePath(),
c.fill())}w(c);c.restore()}});g.hooks.draw.push(function(a,c){a.getOptions().series.pie.show&&e(a,c)})},options:{series:{pie:{show:!1,radius:"auto",innerRadius:0,startAngle:1.5,tilt:1,shadow:{left:5,top:15,alpha:.02},offset:{top:0,left:"auto"},stroke:{color:"#fff",width:1},label:{show:"auto",formatter:function(g,a){return"<div style='font-size:x-small;text-align:center;padding:2px;color:"+a.color+";'>"+g+"<br/>"+Math.round(a.percent)+"%</div>"},radius:1,background:{color:null,opacity:0},threshold:0},
combine:{threshold:-1,color:null,label:"Other"},highlight:{opacity:.5}}}},name:"pie",version:"1.1"})})(jQuery);
