var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(h,u,r){if(r.get||r.set)throw new TypeError("ES3 does not support getters and setters.");h!=Array.prototype&&h!=Object.prototype&&(h[u]=r.value)};$jscomp.getGlobal=function(h){return"undefined"!=typeof window&&window===h?h:"undefined"!=typeof global&&null!=global?global:h};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(h,u,r,g){if(u){r=$jscomp.global;h=h.split(".");for(g=0;g<h.length-1;g++){var f=h[g];f in r||(r[f]={});r=r[f]}h=h[h.length-1];g=r[h];u=u(g);u!=g&&null!=u&&$jscomp.defineProperty(r,h,{configurable:!0,writable:!0,value:u})}};$jscomp.polyfill("Array.prototype.fill",function(h){return h?h:function(h,r,g){var f=this.length||0;0>r&&(r=Math.max(0,f+r));if(null==g||g>f)g=f;g=Number(g);0>g&&(g=Math.max(0,f+g));for(r=Number(r||0);r<g;r++)this[r]=h;return this}},"es6-impl","es3");
$jscomp.findInternal=function(h,u,r){h instanceof String&&(h=String(h));for(var g=h.length,f=0;f<g;f++){var v=h[f];if(u.call(r,v,f,h))return{i:f,v:v}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(h){return h?h:function(h,r){return $jscomp.findInternal(this,h,r).v}},"es6-impl","es3");
(function(h){h.color={};h.color.make=function(r,g,f,v){var m={};m.r=r||0;m.g=g||0;m.b=f||0;m.a=null!=v?v:1;m.add=function(h,f){for(var g=0;g<h.length;++g)m[h.charAt(g)]+=f;return m.normalize()};m.scale=function(h,f){for(var g=0;g<h.length;++g)m[h.charAt(g)]*=f;return m.normalize()};m.toString=function(){return 1<=m.a?"rgb("+[m.r,m.g,m.b].join()+")":"rgba("+[m.r,m.g,m.b,m.a].join()+")"};m.normalize=function(){function h(h,f,m){return f<h?h:f>m?m:f}m.r=h(0,parseInt(m.r),255);m.g=h(0,parseInt(m.g),255);
m.b=h(0,parseInt(m.b),255);m.a=h(0,m.a,1);return m};m.clone=function(){return h.color.make(m.r,m.b,m.g,m.a)};return m.normalize()};h.color.extract=function(r,g){var f;do{f=r.css(g).toLowerCase();if(""!=f&&"transparent"!=f)break;r=r.parent()}while(r.length&&!h.nodeName(r.get(0),"body"));"rgba(0, 0, 0, 0)"==f&&(f="transparent");return h.color.parse(f)};h.color.parse=function(r){var g,f=h.color.make;if(g=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(r))return f(parseInt(g[1],
10),parseInt(g[2],10),parseInt(g[3],10));if(g=/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]+(?:\.[0-9]+)?)\s*\)/.exec(r))return f(parseInt(g[1],10),parseInt(g[2],10),parseInt(g[3],10),parseFloat(g[4]));if(g=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(r))return f(2.55*parseFloat(g[1]),2.55*parseFloat(g[2]),2.55*parseFloat(g[3]));if(g=/rgba\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\s*\)/.exec(r))return f(2.55*
parseFloat(g[1]),2.55*parseFloat(g[2]),2.55*parseFloat(g[3]),parseFloat(g[4]));if(g=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(r))return f(parseInt(g[1],16),parseInt(g[2],16),parseInt(g[3],16));if(g=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(r))return f(parseInt(g[1]+g[1],16),parseInt(g[2]+g[2],16),parseInt(g[3]+g[3],16));r=h.trim(r).toLowerCase();if("transparent"==r)return f(255,255,255,0);g=u[r]||[0,0,0];return f(g[0],g[1],g[2])};var u={aqua:[0,255,255],azure:[240,255,255],beige:[245,
245,220],black:[0,0,0],blue:[0,0,255],brown:[165,42,42],cyan:[0,255,255],darkblue:[0,0,139],darkcyan:[0,139,139],darkgrey:[169,169,169],darkgreen:[0,100,0],darkkhaki:[189,183,107],darkmagenta:[139,0,139],darkolivegreen:[85,107,47],darkorange:[255,140,0],darkorchid:[153,50,204],darkred:[139,0,0],darksalmon:[233,150,122],darkviolet:[148,0,211],fuchsia:[255,0,255],gold:[255,215,0],green:[0,128,0],indigo:[75,0,130],khaki:[240,230,140],lightblue:[173,216,230],lightcyan:[224,255,255],lightgreen:[144,238,
144],lightgrey:[211,211,211],lightpink:[255,182,193],lightyellow:[255,255,224],lime:[0,255,0],magenta:[255,0,255],maroon:[128,0,0],navy:[0,0,128],olive:[128,128,0],orange:[255,165,0],pink:[255,192,203],purple:[128,0,128],violet:[128,0,128],red:[255,0,0],silver:[192,192,192],white:[255,255,255],yellow:[255,255,0]}})(jQuery);
(function(h){function u(f,g){var m=g.children("."+f)[0];if(null==m&&(m=document.createElement("canvas"),m.className=f,h(m).css({direction:"ltr",position:"absolute",left:0,top:0}).appendTo(g),!m.getContext))if(window.G_vmlCanvasManager)m=window.G_vmlCanvasManager.initElement(m);else throw Error("Canvas is not available. If you're using IE with a fall-back such as Excanvas, then there's either a mistake in your conditional include, or the page has no DOCTYPE and is rendering in Quirks Mode.");this.element=
m;m=this.context=m.getContext("2d");this.pixelRatio=(window.devicePixelRatio||1)/(m.webkitBackingStorePixelRatio||m.mozBackingStorePixelRatio||m.msBackingStorePixelRatio||m.oBackingStorePixelRatio||m.backingStorePixelRatio||1);this.resize(g.width(),g.height());this.textContainer=null;this.text={};this._textCache={}}function r(f,g,m,r){function v(a,b){b=[w].concat(b);for(var c=0;c<a.length;++c)a[c].apply(this,b)}function N(a){for(var b=[],c=0;c<a.length;++c){var d=h.extend(!0,{},k.series);null!=a[c].data?
(d.data=a[c].data,delete a[c].data,h.extend(!0,d,a[c]),a[c].data=d.data):d.data=a[c];b.push(d)}y=b;c=y.length;b=-1;for(a=0;a<y.length;++a)d=y[a].color,null!=d&&(c--,"number"==typeof d&&d>b&&(b=d));c<=b&&(c=b+1);var b=[],e=k.colors,t=e.length,q=0;for(a=0;a<c;a++)d=h.color.parse(e[a%t]||"#666"),0==a%t&&a&&(q=0<=q?.5>q?-q-.2:0:-q),b[a]=d.scale("rgb",1+q);for(a=c=0;a<y.length;++a){d=y[a];null==d.color?(d.color=b[c].toString(),++c):"number"==typeof d.color&&(d.color=b[d.color].toString());if(null==d.lines.show){var x,
e=!0;for(x in d)if(d[x]&&d[x].show){e=!1;break}e&&(d.lines.show=!0)}null==d.lines.zero&&(d.lines.zero=!!d.lines.fill);d.xaxis=J(F,D(d,"x"));d.yaxis=J(H,D(d,"y"))}la()}function D(a,b){var c=a[b+"axis"];"object"==typeof c&&(c=c.n);"number"!=typeof c&&(c=1);return c}function E(){return h.grep(F.concat(H),function(a){return a})}function K(a){var b={},c,d;for(c=0;c<F.length;++c)(d=F[c])&&d.used&&(b["x"+d.n]=d.c2p(a.left));for(c=0;c<H.length;++c)(d=H[c])&&d.used&&(b["y"+d.n]=d.c2p(a.top));void 0!==b.x1&&
(b.x=b.x1);void 0!==b.y1&&(b.y=b.y1);return b}function J(a,b){a[b-1]||(a[b-1]={n:b,direction:a==F?"x":"y",options:h.extend(!0,{},a==F?k.xaxis:k.yaxis)});return a[b-1]}function la(){function a(a,c,b){c<a.datamin&&c!=-d&&(a.datamin=c);b>a.datamax&&b!=d&&(a.datamax=b)}var b=Number.POSITIVE_INFINITY,c=Number.NEGATIVE_INFINITY,d=Number.MAX_VALUE,e,t,q,x,p,B,k,f,l,m,g,n;h.each(E(),function(a,d){d.datamin=b;d.datamax=c;d.used=!1});for(e=0;e<y.length;++e)p=y[e],p.datapoints={points:[]},v(z.processRawData,
[p,p.data,p.datapoints]);for(e=0;e<y.length;++e){p=y[e];g=p.data;n=p.datapoints.format;if(!n){n=[];n.push({x:!0,number:!0,required:!0});n.push({y:!0,number:!0,required:!0});if(p.bars.show||p.lines.show&&p.lines.fill)n.push({y:!0,number:!0,required:!1,defaultValue:0,autoscale:!!(p.bars.show&&p.bars.zero||p.lines.show&&p.lines.zero)}),p.bars.horizontal&&(delete n[n.length-1].y,n[n.length-1].x=!0);p.datapoints.format=n}if(null==p.datapoints.pointsize){p.datapoints.pointsize=n.length;k=p.datapoints.pointsize;
B=p.datapoints.points;var R=p.lines.show&&p.lines.steps;p.xaxis.used=p.yaxis.used=!0;for(t=q=0;t<g.length;++t,q+=k){m=g[t];var U=null==m;if(!U)for(x=0;x<k;++x){f=m[x];if(l=n[x])l.number&&null!=f&&(f=+f,isNaN(f)?f=null:Infinity==f?f=d:-Infinity==f&&(f=-d)),null==f&&(l.required&&(U=!0),null!=l.defaultValue&&(f=l.defaultValue));B[q+x]=f}if(U)for(x=0;x<k;++x)f=B[q+x],null!=f&&(l=n[x],!1!==l.autoscale&&(l.x&&a(p.xaxis,f,f),l.y&&a(p.yaxis,f,f))),B[q+x]=null;else if(R&&0<q&&null!=B[q-k]&&B[q-k]!=B[q]&&B[q-
k+1]!=B[q+1]){for(x=0;x<k;++x)B[q+k+x]=B[q+x];B[q+1]=B[q-k+1];q+=k}}}}for(e=0;e<y.length;++e)p=y[e],v(z.processDatapoints,[p,p.datapoints]);for(e=0;e<y.length;++e){p=y[e];B=p.datapoints.points;k=p.datapoints.pointsize;n=p.datapoints.format;m=q=b;R=g=c;for(t=0;t<B.length;t+=k)if(null!=B[t])for(x=0;x<k;++x)f=B[t+x],(l=n[x])&&!1!==l.autoscale&&f!=d&&f!=-d&&(l.x&&(f<q&&(q=f),f>g&&(g=f)),l.y&&(f<m&&(m=f),f>R&&(R=f)));if(p.bars.show){switch(p.bars.align){case "left":t=0;break;case "right":t=-p.bars.barWidth;
break;default:t=-p.bars.barWidth/2}p.bars.horizontal?(m+=t,R+=t+p.bars.barWidth):(q+=t,g+=t+p.bars.barWidth)}a(p.xaxis,q,g);a(p.yaxis,m,R)}h.each(E(),function(a,d){d.datamin==b&&(d.datamin=null);d.datamax==c&&(d.datamax=null)})}function X(){S&&clearTimeout(S);L.unbind("mousemove",Y);L.unbind("mouseleave",Z);L.unbind("click",aa);v(z.shutdown,[L])}function ma(a){function b(a){return a}var c,d,e=a.options.transform||b,t=a.options.inverseTransform;"x"==a.direction?(c=a.scale=M/Math.abs(e(a.max)-e(a.min)),
d=Math.min(e(a.max),e(a.min))):(c=a.scale=I/Math.abs(e(a.max)-e(a.min)),c=-c,d=Math.max(e(a.max),e(a.min)));a.p2c=e==b?function(a){return(a-d)*c}:function(a){return(e(a)-d)*c};a.c2p=t?function(a){return t(d+a/c)}:function(a){return d+a/c}}function na(a){var b=a.labelWidth,c=a.labelHeight,d=a.options.position,e="x"===a.direction,t=a.options.tickLength,q=k.grid.axisMargin,x=k.grid.labelMargin,p=!0,f=!0,l=!0,m=!1;h.each(e?F:H,function(c,b){b&&b.reserveSpace&&(b===a?m=!0:b.options.position===d&&(m?f=
!1:p=!1),m||(l=!1))});f&&(q=0);null==t&&(t=l?"full":5);isNaN(+t)||(x+=+t);e?(c+=x,"bottom"==d?(n.bottom+=c+q,a.box={top:C.height-n.bottom,height:c}):(a.box={top:n.top+q,height:c},n.top+=c+q)):(b+=x,"left"==d?(a.box={left:n.left+q,width:b},n.left+=b+q):(n.right+=b+q,a.box={left:C.width-n.right,width:b}));a.position=d;a.tickLength=t;a.box.padding=x;a.innermost=p}function oa(){var a=k.grid.minBorderMargin,b;if(null==a)for(b=a=0;b<y.length;++b)a=Math.max(a,2*(y[b].points.radius+y[b].points.lineWidth/
2));var c=a,d=a,e=a,t=a;h.each(E(),function(a,b){if(b.reserveSpace&&b.ticks&&b.ticks.length){var q=b.ticks[b.ticks.length-1];"x"===b.direction?(c=Math.max(c,b.labelWidth/2),q.v<=b.max&&(d=Math.max(d,b.labelWidth/2))):(t=Math.max(t,b.labelHeight/2),q.v<=b.max&&(e=Math.max(e,b.labelHeight/2)))}});n.left=Math.ceil(Math.max(c,n.left));n.right=Math.ceil(Math.max(d,n.right));n.top=Math.ceil(Math.max(e,n.top));n.bottom=Math.ceil(Math.max(t,n.bottom))}function ba(){var a,b=E(),c=k.grid.show;for(a in n){var d=
k.grid.margin||0;n[a]="number"==typeof d?d:d[a]||0}v(z.processOffset,[n]);for(a in n)n[a]="object"==typeof k.grid.borderWidth?n[a]+(c?k.grid.borderWidth[a]:0):n[a]+(c?k.grid.borderWidth:0);h.each(b,function(a,b){b.show=b.options.show;null==b.show&&(b.show=b.used);b.reserveSpace=b.show||b.options.reserveSpace;var c=b.options,d=+(null!=c.min?c.min:b.datamin),e=+(null!=c.max?c.max:b.datamax),f=e-d;if(0==f){if(f=0==e?1:.01,null==c.min&&(d-=f),null==c.max||null!=c.min)e+=f}else{var k=c.autoscaleMargin;
null!=k&&(null==c.min&&(d-=f*k,0>d&&null!=b.datamin&&0<=b.datamin&&(d=0)),null==c.max&&(e+=f*k,0<e&&null!=b.datamax&&0>=b.datamax&&(e=0)))}b.min=d;b.max=e});if(c){d=h.grep(b,function(a){return a.reserveSpace});h.each(d,function(a,b){pa(b);var c=b.options.ticks,d=[];null==c||"number"==typeof c&&0<c?d=b.tickGenerator(b):c&&(d=h.isFunction(c)?c(b):c);var e;b.ticks=[];for(c=0;c<d.length;++c){var f=null,k=d[c];"object"==typeof k?(e=+k[0],1<k.length&&(f=k[1])):e=+k;null==f&&(f=b.tickFormatter(e,b));isNaN(e)||
b.ticks.push({v:e,label:f})}d=b.ticks;b.options.autoscaleMargin&&0<d.length&&(null==b.options.min&&(b.min=Math.min(b.min,d[0].v)),null==b.options.max&&1<d.length&&(b.max=Math.max(b.max,d[d.length-1].v)));d=b.options;c=b.ticks||[];e=d.labelWidth||0;for(var f=d.labelHeight||0,k=e||("x"==b.direction?Math.floor(C.width/(c.length||1)):null),l="flot-"+b.direction+"-axis flot-"+b.direction+b.n+"-axis "+(b.direction+"Axis "+b.direction+b.n+"Axis"),t=d.font||"flot-tick-label tickLabel",m=0;m<c.length;++m){var g=
c[m];g.label&&(g=C.getTextInfo(l,g.label,t,null,k),e=Math.max(e,g.width),f=Math.max(f,g.height))}b.labelWidth=d.labelWidth||e;b.labelHeight=d.labelHeight||f});for(a=d.length-1;0<=a;--a)na(d[a]);oa();h.each(d,function(a,b){"x"==b.direction?(b.box.left=n.left-b.labelWidth/2,b.box.width=C.width-n.left-n.right+b.labelWidth):(b.box.top=n.top-b.labelHeight/2,b.box.height=C.height-n.bottom-n.top+b.labelHeight)})}M=C.width-n.left-n.right;I=C.height-n.bottom-n.top;h.each(b,function(a,b){ma(b)});c&&qa();ra()}
function pa(a){var b=a.options,c=(a.max-a.min)/("number"==typeof b.ticks&&0<b.ticks?b.ticks:.3*Math.sqrt("x"==a.direction?C.width:C.height)),d=-Math.floor(Math.log(c)/Math.LN10),e=b.tickDecimals;null!=e&&d>e&&(d=e);var f=Math.pow(10,-d),k=c/f,l;1.5>k?l=1:3>k?(l=2,2.25<k&&(null==e||d+1<=e)&&(l=2.5,++d)):l=7.5>k?5:10;l*=f;null!=b.minTickSize&&l<b.minTickSize&&(l=b.minTickSize);a.delta=c;a.tickDecimals=Math.max(0,null!=e?e:d);a.tickSize=b.tickSize||l;if("time"==b.mode&&!a.tickGenerator)throw Error("Time mode requires the flot.time plugin.");
a.tickGenerator||(a.tickGenerator=function(a){var b=[],c;c=a.tickSize;c*=Math.floor(a.min/c);var d=0,e=Number.NaN,f;do f=e,e=c+d*a.tickSize,b.push(e),++d;while(e<a.max&&e!=f);return b},a.tickFormatter=function(a,b){var c=b.tickDecimals?Math.pow(10,b.tickDecimals):1,d=""+Math.round(a*c)/c;if(null!=b.tickDecimals){var e=d.indexOf("."),e=-1==e?0:d.length-e-1;if(e<b.tickDecimals)return(e?d:d+".")+(""+c).substr(1,b.tickDecimals-e)}return d});h.isFunction(b.tickFormatter)&&(a.tickFormatter=function(a,c){return""+
b.tickFormatter(a,c)});if(null!=b.alignTicksWithAxis){var p=("x"==a.direction?F:H)[b.alignTicksWithAxis-1];p&&p.used&&p!=a&&(c=a.tickGenerator(a),0<c.length&&(null==b.min&&(a.min=Math.min(a.min,c[0])),null==b.max&&1<c.length&&(a.max=Math.max(a.max,c[c.length-1]))),a.tickGenerator=function(a){var b=[],c,d;for(d=0;d<p.ticks.length;++d)c=(p.ticks[d].v-p.min)/(p.max-p.min),c=a.min+c*(a.max-a.min),b.push(c);return b},a.mode||null!=b.tickDecimals||(c=Math.max(0,-Math.floor(Math.log(a.delta)/Math.LN10)+
1),d=a.tickGenerator(a),1<d.length&&/\..*0$/.test((d[1]-d[0]).toFixed(c))||(a.tickDecimals=c)))}}function ca(){C.clear();v(z.drawBackground,[l]);var a=k.grid;a.show&&a.backgroundColor&&(l.save(),l.translate(n.left,n.top),l.fillStyle=da(k.grid.backgroundColor,I,0,"rgba(255, 255, 255, 0)"),l.fillRect(0,0,M,I),l.restore());a.show&&!a.aboveData&&ea();for(var b=0;b<y.length;++b){v(z.drawSeries,[l,y[b]]);var c=y[b];c.lines.show&&sa(c);c.bars.show&&ta(c);c.points.show&&ua(c)}v(z.draw,[l]);a.show&&a.aboveData&&
ea();C.render();T()}function fa(a,b){for(var c,d,e,f,k=E(),l=0;l<k.length;++l)if(c=k[l],c.direction==b&&(f=b+c.n+"axis",a[f]||1!=c.n||(f=b+"axis"),a[f])){d=a[f].from;e=a[f].to;break}a[f]||(c="x"==b?F[0]:H[0],d=a[b+"1"],e=a[b+"2"]);null!=d&&null!=e&&d>e&&(f=d,d=e,e=f);return{from:d,to:e,axis:c}}function ea(){var a,b,c;l.save();l.translate(n.left,n.top);if(c=k.grid.markings)for(h.isFunction(c)&&(b=w.getAxes(),b.xmin=b.xaxis.min,b.xmax=b.xaxis.max,b.ymin=b.yaxis.min,b.ymax=b.yaxis.max,c=c(b)),a=0;a<
c.length;++a){b=c[a];var d=fa(b,"x"),e=fa(b,"y");null==d.from&&(d.from=d.axis.min);null==d.to&&(d.to=d.axis.max);null==e.from&&(e.from=e.axis.min);null==e.to&&(e.to=e.axis.max);d.to<d.axis.min||d.from>d.axis.max||e.to<e.axis.min||e.from>e.axis.max||(d.from=Math.max(d.from,d.axis.min),d.to=Math.min(d.to,d.axis.max),e.from=Math.max(e.from,e.axis.min),e.to=Math.min(e.to,e.axis.max),d.from==d.to&&e.from==e.to)||(d.from=d.axis.p2c(d.from),d.to=d.axis.p2c(d.to),e.from=e.axis.p2c(e.from),e.to=e.axis.p2c(e.to),
d.from==d.to||e.from==e.to?(l.beginPath(),l.strokeStyle=b.color||k.grid.markingsColor,l.lineWidth=b.lineWidth||k.grid.markingsLineWidth,l.moveTo(d.from,e.from),l.lineTo(d.to,e.to),l.stroke()):(l.fillStyle=b.color||k.grid.markingsColor,l.fillRect(d.from,e.to,d.to-d.from,e.from-e.to)))}b=E();c=k.grid.borderWidth;for(d=0;d<b.length;++d){e=b[d];a=e.box;var f=e.tickLength,q,m,p,B;if(e.show&&0!=e.ticks.length){l.lineWidth=1;"x"==e.direction?(q=0,m="full"==f?"top"==e.position?0:I:a.top-n.top+("top"==e.position?
a.height:0)):(m=0,q="full"==f?"left"==e.position?0:M:a.left-n.left+("left"==e.position?a.width:0));e.innermost||(l.strokeStyle=e.options.color,l.beginPath(),p=B=0,"x"==e.direction?p=M+1:B=I+1,1==l.lineWidth&&("x"==e.direction?m=Math.floor(m)+.5:q=Math.floor(q)+.5),l.moveTo(q,m),l.lineTo(q+p,m+B),l.stroke());l.strokeStyle=e.options.tickColor;l.beginPath();for(a=0;a<e.ticks.length;++a){var g=e.ticks[a].v;p=B=0;isNaN(g)||g<e.min||g>e.max||"full"==f&&("object"==typeof c&&0<c[e.position]||0<c)&&(g==e.min||
g==e.max)||("x"==e.direction?(q=e.p2c(g),B="full"==f?-I:f,"top"==e.position&&(B=-B)):(m=e.p2c(g),p="full"==f?-M:f,"left"==e.position&&(p=-p)),1==l.lineWidth&&("x"==e.direction?q=Math.floor(q)+.5:m=Math.floor(m)+.5),l.moveTo(q,m),l.lineTo(q+p,m+B))}l.stroke()}}c&&(a=k.grid.borderColor,"object"==typeof c||"object"==typeof a?("object"!==typeof c&&(c={top:c,right:c,bottom:c,left:c}),"object"!==typeof a&&(a={top:a,right:a,bottom:a,left:a}),0<c.top&&(l.strokeStyle=a.top,l.lineWidth=c.top,l.beginPath(),
l.moveTo(0-c.left,0-c.top/2),l.lineTo(M,0-c.top/2),l.stroke()),0<c.right&&(l.strokeStyle=a.right,l.lineWidth=c.right,l.beginPath(),l.moveTo(M+c.right/2,0-c.top),l.lineTo(M+c.right/2,I),l.stroke()),0<c.bottom&&(l.strokeStyle=a.bottom,l.lineWidth=c.bottom,l.beginPath(),l.moveTo(M+c.right,I+c.bottom/2),l.lineTo(0,I+c.bottom/2),l.stroke()),0<c.left&&(l.strokeStyle=a.left,l.lineWidth=c.left,l.beginPath(),l.moveTo(0-c.left/2,I+c.bottom),l.lineTo(0-c.left/2,0),l.stroke())):(l.lineWidth=c,l.strokeStyle=k.grid.borderColor,
l.strokeRect(-c/2,-c/2,M+c,I+c)));l.restore()}function qa(){h.each(E(),function(a,b){var c=b.box,d="flot-"+b.direction+"-axis flot-"+b.direction+b.n+"-axis "+(b.direction+"Axis "+b.direction+b.n+"Axis"),e=b.options.font||"flot-tick-label tickLabel",f,k,l,p,m;C.removeText(d);if(b.show&&0!=b.ticks.length)for(var h=0;h<b.ticks.length;++h)f=b.ticks[h],!f.label||f.v<b.min||f.v>b.max||("x"==b.direction?(p="center",k=n.left+b.p2c(f.v),"bottom"==b.position?l=c.top+c.padding:(l=c.top+c.height-c.padding,m=
"bottom")):(m="middle",l=n.top+b.p2c(f.v),"left"==b.position?(k=c.left+c.width-c.padding,p="right"):k=c.left+c.padding),C.addText(d,k,l,f.label,e,null,null,p,m))})}function sa(a){function b(a,b,c,d,e){var f=a.points;a=a.pointsize;var k=null,p=null;l.beginPath();for(var m=a;m<f.length;m+=a){var h=f[m-a],q=f[m-a+1],g=f[m],n=f[m+1];if(null!=h&&null!=g){if(q<=n&&q<e.min){if(n<e.min)continue;h=(e.min-q)/(n-q)*(g-h)+h;q=e.min}else if(n<=q&&n<e.min){if(q<e.min)continue;g=(e.min-q)/(n-q)*(g-h)+h;n=e.min}if(q>=
n&&q>e.max){if(n>e.max)continue;h=(e.max-q)/(n-q)*(g-h)+h;q=e.max}else if(n>=q&&n>e.max){if(q>e.max)continue;g=(e.max-q)/(n-q)*(g-h)+h;n=e.max}if(h<=g&&h<d.min){if(g<d.min)continue;q=(d.min-h)/(g-h)*(n-q)+q;h=d.min}else if(g<=h&&g<d.min){if(h<d.min)continue;n=(d.min-h)/(g-h)*(n-q)+q;g=d.min}if(h>=g&&h>d.max){if(g>d.max)continue;q=(d.max-h)/(g-h)*(n-q)+q;h=d.max}else if(g>=h&&g>d.max){if(h>d.max)continue;n=(d.max-h)/(g-h)*(n-q)+q;g=d.max}h==k&&q==p||l.moveTo(d.p2c(h)+b,e.p2c(q)+c);k=g;p=n;l.lineTo(d.p2c(g)+
b,e.p2c(n)+c)}}l.stroke()}function c(a,b,c){var d=a.points;a=a.pointsize;for(var e=Math.min(Math.max(0,c.min),c.max),f=0,k=!1,h=1,q=0,m=0;!(0<a&&f>d.length+a);){var f=f+a,g=d[f-a],n=d[f-a+h],p=d[f],t=d[f+h];if(k){if(0<a&&null!=g&&null==p){m=f;a=-a;h=2;continue}if(0>a&&f==q+a){l.fill();k=!1;a=-a;h=1;f=q=m+a;continue}}if(null!=g&&null!=p){if(g<=p&&g<b.min){if(p<b.min)continue;n=(b.min-g)/(p-g)*(t-n)+n;g=b.min}else if(p<=g&&p<b.min){if(g<b.min)continue;t=(b.min-g)/(p-g)*(t-n)+n;p=b.min}if(g>=p&&g>b.max){if(p>
b.max)continue;n=(b.max-g)/(p-g)*(t-n)+n;g=b.max}else if(p>=g&&p>b.max){if(g>b.max)continue;t=(b.max-g)/(p-g)*(t-n)+n;p=b.max}k||(l.beginPath(),l.moveTo(b.p2c(g),c.p2c(e)),k=!0);if(n>=c.max&&t>=c.max)l.lineTo(b.p2c(g),c.p2c(c.max)),l.lineTo(b.p2c(p),c.p2c(c.max));else if(n<=c.min&&t<=c.min)l.lineTo(b.p2c(g),c.p2c(c.min)),l.lineTo(b.p2c(p),c.p2c(c.min));else{var v=g,x=p;n<=t&&n<c.min&&t>=c.min?(g=(c.min-n)/(t-n)*(p-g)+g,n=c.min):t<=n&&t<c.min&&n>=c.min&&(p=(c.min-n)/(t-n)*(p-g)+g,t=c.min);n>=t&&n>
c.max&&t<=c.max?(g=(c.max-n)/(t-n)*(p-g)+g,n=c.max):t>=n&&t>c.max&&n<=c.max&&(p=(c.max-n)/(t-n)*(p-g)+g,t=c.max);g!=v&&l.lineTo(b.p2c(v),c.p2c(n));l.lineTo(b.p2c(g),c.p2c(n));l.lineTo(b.p2c(p),c.p2c(t));p!=x&&(l.lineTo(b.p2c(p),c.p2c(t)),l.lineTo(b.p2c(x),c.p2c(t)))}}}}l.save();l.translate(n.left,n.top);l.lineJoin="round";var d=a.lines.lineWidth,e=a.shadowSize;if(0<d&&0<e){l.lineWidth=e;l.strokeStyle="rgba(0,0,0,0.1)";var f=Math.PI/18;b(a.datapoints,Math.sin(f)*(d/2+e/2),Math.cos(f)*(d/2+e/2),a.xaxis,
a.yaxis);l.lineWidth=e/2;b(a.datapoints,Math.sin(f)*(d/2+e/4),Math.cos(f)*(d/2+e/4),a.xaxis,a.yaxis)}l.lineWidth=d;l.strokeStyle=a.color;if(e=V(a.lines,a.color,0,I))l.fillStyle=e,c(a.datapoints,a.xaxis,a.yaxis);0<d&&b(a.datapoints,0,0,a.xaxis,a.yaxis);l.restore()}function ua(a){function b(a,b,c,d,e,f,k,g){var h=a.points;a=a.pointsize;for(var n=0;n<h.length;n+=a){var m=h[n],q=h[n+1];null==m||m<f.min||m>f.max||q<k.min||q>k.max||(l.beginPath(),m=f.p2c(m),q=k.p2c(q)+d,"circle"==g?l.arc(m,q,b,0,e?Math.PI:
2*Math.PI,!1):g(l,m,q,b,e),l.closePath(),c&&(l.fillStyle=c,l.fill()),l.stroke())}}l.save();l.translate(n.left,n.top);var c=a.points.lineWidth,d=a.shadowSize,e=a.points.radius,f=a.points.symbol;0==c&&(c=1E-4);0<c&&0<d&&(d/=2,l.lineWidth=d,l.strokeStyle="rgba(0,0,0,0.1)",b(a.datapoints,e,null,d+d/2,!0,a.xaxis,a.yaxis,f),l.strokeStyle="rgba(0,0,0,0.2)",b(a.datapoints,e,null,d/2,!0,a.xaxis,a.yaxis,f));l.lineWidth=c;l.strokeStyle=a.color;b(a.datapoints,e,V(a.points,a.color),0,!1,a.xaxis,a.yaxis,f);l.restore()}
function ga(a,b,c,d,e,f,k,g,h,l,n){var m,q,p,t;l?(t=q=p=!0,m=!1,l=c,c=b+d,e=b+e,a<l&&(b=a,a=l,l=b,m=!0,q=!1)):(m=q=p=!0,t=!1,l=a+d,a+=e,e=c,c=b,c<e&&(b=c,c=e,e=b,t=!0,p=!1));a<k.min||l>k.max||c<g.min||e>g.max||(l<k.min&&(l=k.min,m=!1),a>k.max&&(a=k.max,q=!1),e<g.min&&(e=g.min,t=!1),c>g.max&&(c=g.max,p=!1),l=k.p2c(l),e=g.p2c(e),a=k.p2c(a),c=g.p2c(c),f&&(h.fillStyle=f(e,c),h.fillRect(l,c,a-l,e-c)),0<n&&(m||q||p||t)&&(h.beginPath(),h.moveTo(l,e),m?h.lineTo(l,c):h.moveTo(l,c),p?h.lineTo(a,c):h.moveTo(a,
c),q?h.lineTo(a,e):h.moveTo(a,e),t?h.lineTo(l,e):h.moveTo(l,e),h.stroke()))}function ta(a){l.save();l.translate(n.left,n.top);l.lineWidth=a.bars.lineWidth;l.strokeStyle=a.color;var b;switch(a.bars.align){case "left":b=0;break;case "right":b=-a.bars.barWidth;break;default:b=-a.bars.barWidth/2}(function(b,d,e,f,k,h){var c=b.points;b=b.pointsize;for(var g=0;g<c.length;g+=b)null!=c[g]&&ga(c[g],c[g+1],c[g+2],d,e,f,k,h,l,a.bars.horizontal,a.bars.lineWidth)})(a.datapoints,b,b+a.bars.barWidth,a.bars.fill?
function(b,d){return V(a.bars,a.color,b,d)}:null,a.xaxis,a.yaxis);l.restore()}function V(a,b,c,d){var e=a.fill;if(!e)return null;if(a.fillColor)return da(a.fillColor,c,d,b);a=h.color.parse(b);a.a="number"==typeof e?e:.4;a.normalize();return a.toString()}function ra(){null!=k.legend.container?h(k.legend.container).html(""):f.find(".legend").remove();if(k.legend.show){for(var a=[],b=[],c=!1,d=k.legend.labelFormatter,e,g,l=0;l<y.length;++l)e=y[l],e.label&&(g=d?d(e.label,e):e.label)&&b.push({label:g,
color:e.color});if(k.legend.sorted)if(h.isFunction(k.legend.sorted))b.sort(k.legend.sorted);else if("reverse"==k.legend.sorted)b.reverse();else{var m="descending"!=k.legend.sorted;b.sort(function(a,b){return a.label==b.label?0:a.label<b.label!=m?1:-1})}for(l=0;l<b.length;++l)d=b[l],0==l%k.legend.noColumns&&(c&&a.push("</tr>"),a.push("<tr>"),c=!0),a.push('<td class="legendColorBox"><div style="border:1px solid '+k.legend.labelBoxBorderColor+';padding:1px"><div style="width:4px;height:0;border:5px solid '+
d.color+';overflow:hidden"></div></div></td><td class="legendLabel">'+d.label+"</td>");c&&a.push("</tr>");0!=a.length&&(b='<table style="font-size:smaller;color:'+k.grid.color+'">'+a.join("")+"</table>",null!=k.legend.container?h(k.legend.container).html(b):(a="",c=k.legend.position,l=k.legend.margin,null==l[0]&&(l=[l,l]),"n"==c.charAt(0)?a+="top:"+(l[1]+n.top)+"px;":"s"==c.charAt(0)&&(a+="bottom:"+(l[1]+n.bottom)+"px;"),"e"==c.charAt(1)?a+="right:"+(l[0]+n.right)+"px;":"w"==c.charAt(1)&&(a+="left:"+
(l[0]+n.left)+"px;"),b=h('<div class="legend">'+b.replace('style="','style="position:absolute;'+a+";")+"</div>").appendTo(f),0!=k.legend.backgroundOpacity&&(c=k.legend.backgroundColor,null==c&&(c=(c=k.grid.backgroundColor)&&"string"==typeof c?h.color.parse(c):h.color.extract(b,"background-color"),c.a=1,c=c.toString()),l=b.children(),h('<div style="position:absolute;width:'+l.width()+"px;height:"+l.height()+"px;"+a+"background-color:"+c+';"> </div>').prependTo(b).css("opacity",k.legend.backgroundOpacity))))}}
function Y(a){k.grid.hoverable&&W("plothover",a,function(a){return 0!=a.hoverable})}function Z(a){k.grid.hoverable&&W("plothover",a,function(a){return!1})}function aa(a){W("plotclick",a,function(a){return 0!=a.clickable})}function W(a,b,c){var d=L.offset(),e=b.pageX-d.left-n.left,l=b.pageY-d.top-n.top,g=K({left:e,top:l});g.pageX=b.pageX;g.pageY=b.pageY;b=k.grid.mouseActiveRadius;var h=b*b+1,m=null,v,r,N;for(v=y.length-1;0<=v;--v)if(c(y[v])){var w=y[v],P=w.xaxis,u=w.yaxis,D=w.datapoints.points,C=P.c2p(e),
G=u.c2p(l),E=b/P.scale,F=b/u.scale;N=w.datapoints.pointsize;P.options.inverseTransform&&(E=Number.MAX_VALUE);u.options.inverseTransform&&(F=Number.MAX_VALUE);if(w.lines.show||w.points.show)for(r=0;r<D.length;r+=N){var A=D[r],z=D[r+1];null==A||A-C>E||A-C<-E||z-G>F||z-G<-F||(A=Math.abs(P.p2c(A)-e),z=Math.abs(u.p2c(z)-l),z=A*A+z*z,z<h&&(h=z,m=[v,r/N]))}if(w.bars.show&&!m){switch(w.bars.align){case "left":P=0;break;case "right":P=-w.bars.barWidth;break;default:P=-w.bars.barWidth/2}w=P+w.bars.barWidth;
for(r=0;r<D.length;r+=N)A=D[r],z=D[r+1],u=D[r+2],null!=A&&(y[v].bars.horizontal?C<=Math.max(u,A)&&C>=Math.min(u,A)&&G>=z+P&&G<=z+w:C>=A+P&&C<=A+w&&G>=Math.min(u,z)&&G<=Math.max(u,z))&&(m=[v,r/N])}}m?(v=m[0],r=m[1],N=y[v].datapoints.pointsize,c={datapoint:y[v].datapoints.points.slice(r*N,(r+1)*N),dataIndex:r,series:y[v],seriesIndex:v}):c=null;c&&(c.pageX=parseInt(c.series.xaxis.p2c(c.datapoint[0])+d.left+n.left,10),c.pageY=parseInt(c.series.yaxis.p2c(c.datapoint[1])+d.top+n.top,10));if(k.grid.autoHighlight){for(d=
0;d<O.length;++d)e=O[d],e.auto!=a||c&&e.series==c.series&&e.point[0]==c.datapoint[0]&&e.point[1]==c.datapoint[1]||ha(e.series,e.point);c&&ia(c.series,c.datapoint,a)}f.trigger(a,[g,c])}function T(){var a=k.interaction.redrawOverlayInterval;-1==a?ja():S||(S=setTimeout(ja,a))}function ja(){S=null;A.save();Q.clear();A.translate(n.left,n.top);var a,b;for(a=0;a<O.length;++a)if(b=O[a],b.series.bars.show)va(b.series,b.point);else{var c=b.series,d=b.point;b=d[0];var d=d[1],e=c.xaxis,f=c.yaxis,k="string"===
typeof c.highlightColor?c.highlightColor:h.color.parse(c.color).scale("a",.5).toString();if(!(b<e.min||b>e.max||d<f.min||d>f.max)){var l=c.points.radius+c.points.lineWidth/2;A.lineWidth=l;A.strokeStyle=k;k=1.5*l;b=e.p2c(b);d=f.p2c(d);A.beginPath();"circle"==c.points.symbol?A.arc(b,d,k,0,2*Math.PI,!1):c.points.symbol(A,b,d,k,!1);A.closePath();A.stroke()}}A.restore();v(z.drawOverlay,[A])}function ia(a,b,c){"number"==typeof a&&(a=y[a]);if("number"==typeof b){var d=a.datapoints.pointsize;b=a.datapoints.points.slice(d*
b,d*(b+1))}d=ka(a,b);-1==d?(O.push({series:a,point:b,auto:c}),T()):c||(O[d].auto=!1)}function ha(a,b){if(null==a&&null==b)O=[],T();else{"number"==typeof a&&(a=y[a]);if("number"==typeof b){var c=a.datapoints.pointsize;b=a.datapoints.points.slice(c*b,c*(b+1))}c=ka(a,b);-1!=c&&(O.splice(c,1),T())}}function ka(a,b){for(var c=0;c<O.length;++c){var d=O[c];if(d.series==a&&d.point[0]==b[0]&&d.point[1]==b[1])return c}return-1}function va(a,b){var c="string"===typeof a.highlightColor?a.highlightColor:h.color.parse(a.color).scale("a",
.5).toString(),d;switch(a.bars.align){case "left":d=0;break;case "right":d=-a.bars.barWidth;break;default:d=-a.bars.barWidth/2}A.lineWidth=a.bars.lineWidth;A.strokeStyle=c;ga(b[0],b[1],b[2]||0,d,d+a.bars.barWidth,function(){return c},a.xaxis,a.yaxis,A,a.bars.horizontal,a.bars.lineWidth)}function da(a,b,c,d){if("string"==typeof a)return a;b=l.createLinearGradient(0,c,0,b);c=0;for(var e=a.colors.length;c<e;++c){var f=a.colors[c];if("string"!=typeof f){var k=h.color.parse(d);null!=f.brightness&&(k=k.scale("rgb",
f.brightness));null!=f.opacity&&(k.a*=f.opacity);f=k.toString()}b.addColorStop(c/(e-1),f)}return b}var y=[],k={colors:["#edc240","#afd8f8","#cb4b4b","#4da74d","#9440ed"],legend:{show:!0,noColumns:1,labelFormatter:null,labelBoxBorderColor:"#ccc",container:null,position:"ne",margin:5,backgroundColor:null,backgroundOpacity:.85,sorted:null},xaxis:{show:null,position:"bottom",mode:null,font:null,color:null,tickColor:null,transform:null,inverseTransform:null,min:null,max:null,autoscaleMargin:null,ticks:null,
tickFormatter:null,labelWidth:null,labelHeight:null,reserveSpace:null,tickLength:null,alignTicksWithAxis:null,tickDecimals:null,tickSize:null,minTickSize:null},yaxis:{autoscaleMargin:.02,position:"left"},xaxes:[],yaxes:[],series:{points:{show:!1,radius:3,lineWidth:2,fill:!0,fillColor:"#ffffff",symbol:"circle"},lines:{lineWidth:2,fill:!1,fillColor:null,steps:!1},bars:{show:!1,lineWidth:2,barWidth:1,fill:!0,fillColor:null,align:"left",horizontal:!1,zero:!0},shadowSize:3,highlightColor:null},grid:{show:!0,
aboveData:!1,color:"#545454",backgroundColor:null,borderColor:null,tickColor:null,margin:0,labelMargin:5,axisMargin:8,borderWidth:2,minBorderMargin:null,markings:null,markingsColor:"#f4f4f4",markingsLineWidth:2,clickable:!1,hoverable:!1,autoHighlight:!0,mouseActiveRadius:10},interaction:{redrawOverlayInterval:1E3/60},hooks:{}},C=null,Q=null,L=null,l=null,A=null,F=[],H=[],n={left:0,right:0,top:0,bottom:0},M=0,I=0,z={processOptions:[],processRawData:[],processDatapoints:[],processOffset:[],drawBackground:[],
drawSeries:[],draw:[],bindEvents:[],drawOverlay:[],shutdown:[]},w=this;w.setData=N;w.setupGrid=ba;w.draw=ca;w.getPlaceholder=function(){return f};w.getCanvas=function(){return C.element};w.getPlotOffset=function(){return n};w.width=function(){return M};w.height=function(){return I};w.offset=function(){var a=L.offset();a.left+=n.left;a.top+=n.top;return a};w.getData=function(){return y};w.getAxes=function(){var a={};h.each(F.concat(H),function(b,c){c&&(a[c.direction+(1!=c.n?c.n:"")+"axis"]=c)});return a};
w.getXAxes=function(){return F};w.getYAxes=function(){return H};w.c2p=K;w.p2c=function(a){var b={},c,d,e;for(c=0;c<F.length;++c)if((d=F[c])&&d.used&&(e="x"+d.n,null==a[e]&&1==d.n&&(e="x"),null!=a[e])){b.left=d.p2c(a[e]);break}for(c=0;c<H.length;++c)if((d=H[c])&&d.used&&(e="y"+d.n,null==a[e]&&1==d.n&&(e="y"),null!=a[e])){b.top=d.p2c(a[e]);break}return b};w.getOptions=function(){return k};w.highlight=ia;w.unhighlight=ha;w.triggerRedrawOverlay=T;w.pointOffset=function(a){return{left:parseInt(F[D(a,"x")-
1].p2c(+a.x)+n.left,10),top:parseInt(H[D(a,"y")-1].p2c(+a.y)+n.top,10)}};w.shutdown=X;w.destroy=function(){X();f.removeData("plot").empty();y=[];A=l=L=Q=C=k=null;F=[];H=[];z=null;O=[];w=null};w.resize=function(){var a=f.width(),b=f.height();C.resize(a,b);Q.resize(a,b)};w.hooks=z;(function(){for(var a={Canvas:u},b=0;b<r.length;++b){var c=r[b];c.init(w,a);c.options&&h.extend(!0,k,c.options)}})(w);(function(a){h.extend(!0,k,a);a&&a.colors&&(k.colors=a.colors);null==k.xaxis.color&&(k.xaxis.color=h.color.parse(k.grid.color).scale("a",
.22).toString());null==k.yaxis.color&&(k.yaxis.color=h.color.parse(k.grid.color).scale("a",.22).toString());null==k.xaxis.tickColor&&(k.xaxis.tickColor=k.grid.tickColor||k.xaxis.color);null==k.yaxis.tickColor&&(k.yaxis.tickColor=k.grid.tickColor||k.yaxis.color);null==k.grid.borderColor&&(k.grid.borderColor=k.grid.color);null==k.grid.tickColor&&(k.grid.tickColor=h.color.parse(k.grid.color).scale("a",.22).toString());var b,c;a=(a=f.css("font-size"))?+a.replace("px",""):13;var d={style:f.css("font-style"),
size:Math.round(.8*a),variant:f.css("font-variant"),weight:f.css("font-weight"),family:f.css("font-family")};c=k.xaxes.length||1;for(a=0;a<c;++a)(b=k.xaxes[a])&&!b.tickColor&&(b.tickColor=b.color),b=h.extend(!0,{},k.xaxis,b),k.xaxes[a]=b,b.font&&(b.font=h.extend({},d,b.font),b.font.color||(b.font.color=b.color),b.font.lineHeight||(b.font.lineHeight=Math.round(1.15*b.font.size)));c=k.yaxes.length||1;for(a=0;a<c;++a)(b=k.yaxes[a])&&!b.tickColor&&(b.tickColor=b.color),b=h.extend(!0,{},k.yaxis,b),k.yaxes[a]=
b,b.font&&(b.font=h.extend({},d,b.font),b.font.color||(b.font.color=b.color),b.font.lineHeight||(b.font.lineHeight=Math.round(1.15*b.font.size)));k.xaxis.noTicks&&null==k.xaxis.ticks&&(k.xaxis.ticks=k.xaxis.noTicks);k.yaxis.noTicks&&null==k.yaxis.ticks&&(k.yaxis.ticks=k.yaxis.noTicks);k.x2axis&&(k.xaxes[1]=h.extend(!0,{},k.xaxis,k.x2axis),k.xaxes[1].position="top");k.y2axis&&(k.yaxes[1]=h.extend(!0,{},k.yaxis,k.y2axis),k.yaxes[1].position="right");k.grid.coloredAreas&&(k.grid.markings=k.grid.coloredAreas);
k.grid.coloredAreasColor&&(k.grid.markingsColor=k.grid.coloredAreasColor);k.lines&&h.extend(!0,k.series.lines,k.lines);k.points&&h.extend(!0,k.series.points,k.points);k.bars&&h.extend(!0,k.series.bars,k.bars);null!=k.shadowSize&&(k.series.shadowSize=k.shadowSize);null!=k.highlightColor&&(k.series.highlightColor=k.highlightColor);for(a=0;a<k.xaxes.length;++a)J(F,a+1).options=k.xaxes[a];for(a=0;a<k.yaxes.length;++a)J(H,a+1).options=k.yaxes[a];for(var e in z)k.hooks[e]&&k.hooks[e].length&&(z[e]=z[e].concat(k.hooks[e]));
v(z.processOptions,[k])})(m);(function(){f.css("padding",0).children().filter(function(){return!h(this).hasClass("flot-overlay")&&!h(this).hasClass("flot-base")}).remove();"static"==f.css("position")&&f.css("position","relative");C=new u("flot-base",f);Q=new u("flot-overlay",f);l=C.context;A=Q.context;L=h(Q.element).unbind();var a=f.data("plot");a&&(a.shutdown(),Q.clear());f.data("plot",w)})();N(g);ba();ca();k.grid.hoverable&&(L.mousemove(Y),L.bind("mouseleave",Z));k.grid.clickable&&L.click(aa);v(z.bindEvents,
[L]);var O=[],S=null}var g=Object.prototype.hasOwnProperty;u.prototype.resize=function(f,g){if(0>=f||0>=g)throw Error("Invalid dimensions for plot, width = "+f+", height = "+g);var h=this.element,r=this.context,v=this.pixelRatio;this.width!=f&&(h.width=f*v,h.style.width=f+"px",this.width=f);this.height!=g&&(h.height=g*v,h.style.height=g+"px",this.height=g);r.restore();r.save();r.scale(v,v)};u.prototype.clear=function(){this.context.clearRect(0,0,this.width,this.height)};u.prototype.render=function(){var f=
this._textCache,h;for(h in f)if(g.call(f,h)){var m=this.getTextLayer(h),r=f[h];m.hide();for(var u in r)if(g.call(r,u)){var G=r[u],D;for(D in G)if(g.call(G,D)){for(var E=G[D].positions,K=0,J;J=E[K];K++)J.active?J.rendered||(m.append(J.element),J.rendered=!0):(E.splice(K--,1),J.rendered&&J.element.detach());0==E.length&&delete G[D]}}m.show()}};u.prototype.getTextLayer=function(f){var g=this.text[f];null==g&&(null==this.textContainer&&(this.textContainer=h("<div class='flot-text'></div>").css({position:"absolute",
top:0,left:0,bottom:0,right:0,"font-size":"smaller",color:"#545454"}).insertAfter(this.element)),g=this.text[f]=h("<div></div>").addClass(f).css({position:"absolute",top:0,left:0,bottom:0,right:0}).appendTo(this.textContainer));return g};u.prototype.getTextInfo=function(f,g,m,r,u){var v,D;g=""+g;r="object"===typeof m?m.style+" "+m.variant+" "+m.weight+" "+m.size+"px/"+m.lineHeight+"px "+m.family:m;v=this._textCache[f];null==v&&(v=this._textCache[f]={});D=v[r];null==D&&(D=v[r]={});v=D[g];null==v&&
(f=h("<div></div>").html(g).css({position:"absolute","max-width":u,top:-9999}).appendTo(this.getTextLayer(f)),"object"===typeof m?f.css({font:r,color:m.color}):"string"===typeof m&&f.addClass(m),v=D[g]={width:f.outerWidth(!0),height:f.outerHeight(!0),element:f,positions:[]},f.detach());return v};u.prototype.addText=function(f,g,h,r,u,G,D,E,K){f=this.getTextInfo(f,r,u,G,D);r=f.positions;"center"==E?g-=f.width/2:"right"==E&&(g-=f.width);"middle"==K?h-=f.height/2:"bottom"==K&&(h-=f.height);for(K=0;u=
r[K];K++)if(u.x==g&&u.y==h){u.active=!0;return}u={active:!0,rendered:!1,element:r.length?f.element.clone():f.element,x:g,y:h};r.push(u);u.element.css({top:Math.round(h),left:Math.round(g),"text-align":E})};u.prototype.removeText=function(f,h,m,r,u,G){if(null==r){if(h=this._textCache[f],null!=h)for(var v in h)if(g.call(h,v)){m=h[v];for(var E in m)if(g.call(m,E))for(f=m[E].positions,r=0;u=f[r];r++)u.active=!1}}else for(f=this.getTextInfo(f,r,u,G).positions,r=0;u=f[r];r++)u.x==h&&u.y==m&&(u.active=!1)};
h.plot=function(f,g,m){return new r(h(f),g,m,h.plot.plugins)};h.plot.version="0.8.2";h.plot.plugins=[];h.fn.plot=function(f,g){return this.each(function(){h.plot(this,f,g)})}})(jQuery);
