(function(k){k.color={};k.color.make=function(u,n,l,p){var h={};h.r=u||0;h.g=n||0;h.b=l||0;h.a=null!=p?p:1;h.add=function(l,k){for(var p=0;p<l.length;++p)h[l.charAt(p)]+=k;return h.normalize()};h.scale=function(l,k){for(var p=0;p<l.length;++p)h[l.charAt(p)]*=k;return h.normalize()};h.toString=function(){return 1<=h.a?"rgb("+[h.r,h.g,h.b].join()+")":"rgba("+[h.r,h.g,h.b,h.a].join()+")"};h.normalize=function(){function l(h,k,p){return k<h?h:k>p?p:k}h.r=l(0,parseInt(h.r),255);h.g=l(0,parseInt(h.g),255);
h.b=l(0,parseInt(h.b),255);h.a=l(0,h.a,1);return h};h.clone=function(){return k.color.make(h.r,h.b,h.g,h.a)};return h.normalize()};k.color.extract=function(u,n){var l;do{l=u.css(n).toLowerCase();if(""!=l&&"transparent"!=l)break;u=u.parent()}while(u.length&&!k.nodeName(u.get(0),"body"));"rgba(0, 0, 0, 0)"==l&&(l="transparent");return k.color.parse(l)};k.color.parse=function(u){var n,l=k.color.make;if(n=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(u))return l(parseInt(n[1],
10),parseInt(n[2],10),parseInt(n[3],10));if(n=/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]+(?:\.[0-9]+)?)\s*\)/.exec(u))return l(parseInt(n[1],10),parseInt(n[2],10),parseInt(n[3],10),parseFloat(n[4]));if(n=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(u))return l(2.55*parseFloat(n[1]),2.55*parseFloat(n[2]),2.55*parseFloat(n[3]));if(n=/rgba\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\s*\)/.exec(u))return l(2.55*
parseFloat(n[1]),2.55*parseFloat(n[2]),2.55*parseFloat(n[3]),parseFloat(n[4]));if(n=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(u))return l(parseInt(n[1],16),parseInt(n[2],16),parseInt(n[3],16));if(n=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(u))return l(parseInt(n[1]+n[1],16),parseInt(n[2]+n[2],16),parseInt(n[3]+n[3],16));u=k.trim(u).toLowerCase();if("transparent"==u)return l(255,255,255,0);n=D[u]||[0,0,0];return l(n[0],n[1],n[2])};var D={aqua:[0,255,255],azure:[240,255,255],beige:[245,
245,220],black:[0,0,0],blue:[0,0,255],brown:[165,42,42],cyan:[0,255,255],darkblue:[0,0,139],darkcyan:[0,139,139],darkgrey:[169,169,169],darkgreen:[0,100,0],darkkhaki:[189,183,107],darkmagenta:[139,0,139],darkolivegreen:[85,107,47],darkorange:[255,140,0],darkorchid:[153,50,204],darkred:[139,0,0],darksalmon:[233,150,122],darkviolet:[148,0,211],fuchsia:[255,0,255],gold:[255,215,0],green:[0,128,0],indigo:[75,0,130],khaki:[240,230,140],lightblue:[173,216,230],lightcyan:[224,255,255],lightgreen:[144,238,
144],lightgrey:[211,211,211],lightpink:[255,182,193],lightyellow:[255,255,224],lime:[0,255,0],magenta:[255,0,255],maroon:[128,0,0],navy:[0,0,128],olive:[128,128,0],orange:[255,165,0],pink:[255,192,203],purple:[128,0,128],violet:[128,0,128],red:[255,0,0],silver:[192,192,192],white:[255,255,255],yellow:[255,255,0]}})(jQuery);
(function(k){function D(l,p){var h=p.children("."+l)[0];if(null==h&&(h=document.createElement("canvas"),h.className=l,k(h).css({direction:"ltr",position:"absolute",left:0,top:0}).appendTo(p),!h.getContext))if(window.G_vmlCanvasManager)h=window.G_vmlCanvasManager.initElement(h);else throw Error("Canvas is not available. If you're using IE with a fall-back such as Excanvas, then there's either a mistake in your conditional include, or the page has no DOCTYPE and is rendering in Quirks Mode.");this.element=
h;h=this.context=h.getContext("2d");this.pixelRatio=(window.devicePixelRatio||1)/(h.webkitBackingStorePixelRatio||h.mozBackingStorePixelRatio||h.msBackingStorePixelRatio||h.oBackingStorePixelRatio||h.backingStorePixelRatio||1);this.resize(p.width(),p.height());this.textContainer=null;this.text={};this._textCache={}}function u(l,p,h,n){function t(a,c){c=[x].concat(c);for(var b=0;b<a.length;++b)a[b].apply(this,c)}function L(a){for(var c=[],b=0;b<a.length;++b){var d=k.extend(!0,{},f.series);null!=a[b].data?
(d.data=a[b].data,delete a[b].data,k.extend(!0,d,a[b]),a[b].data=d.data):d.data=a[b];c.push(d)}w=c;b=w.length;c=-1;for(a=0;a<w.length;++a)d=w[a].color,null!=d&&(b--,"number"==typeof d&&d>c&&(c=d));b<=c&&(b=c+1);var c=[],e=f.colors,r=e.length,v=0;for(a=0;a<b;a++)d=k.color.parse(e[a%r]||"#666"),0==a%r&&a&&(v=0<=v?0.5>v?-v-0.2:0:-v),c[a]=d.scale("rgb",1+v);for(a=b=0;a<w.length;++a){d=w[a];null==d.color?(d.color=c[b].toString(),++b):"number"==typeof d.color&&(d.color=c[d.color].toString());if(null==d.lines.show){var y,
e=!0;for(y in d)if(d[y]&&d[y].show){e=!1;break}e&&(d.lines.show=!0)}null==d.lines.zero&&(d.lines.zero=!!d.lines.fill);d.xaxis=M(G,u(d,"x"));d.yaxis=M(J,u(d,"y"))}ka()}function u(a,c){var b=a[c+"axis"];"object"==typeof b&&(b=b.n);"number"!=typeof b&&(b=1);return b}function F(){return k.grep(G.concat(J),function(a){return a})}function W(a){var c={},b,d;for(b=0;b<G.length;++b)(d=G[b])&&d.used&&(c["x"+d.n]=d.c2p(a.left));for(b=0;b<J.length;++b)(d=J[b])&&d.used&&(c["y"+d.n]=d.c2p(a.top));void 0!==c.x1&&
(c.x=c.x1);void 0!==c.y1&&(c.y=c.y1);return c}function M(a,c){a[c-1]||(a[c-1]={n:c,direction:a==G?"x":"y",options:k.extend(!0,{},a==G?f.xaxis:f.yaxis)});return a[c-1]}function ka(){function a(a,b,c){b<a.datamin&&b!=-d&&(a.datamin=b);c>a.datamax&&c!=d&&(a.datamax=c)}var c=Number.POSITIVE_INFINITY,b=Number.NEGATIVE_INFINITY,d=Number.MAX_VALUE,e,r,v,y,q,B,f,g,l,h,m,E;k.each(F(),function(a,d){d.datamin=c;d.datamax=b;d.used=!1});for(e=0;e<w.length;++e)q=w[e],q.datapoints={points:[]},t(I.processRawData,
[q,q.data,q.datapoints]);for(e=0;e<w.length;++e){q=w[e];m=q.data;E=q.datapoints.format;if(!E){E=[];E.push({x:!0,number:!0,required:!0});E.push({y:!0,number:!0,required:!0});if(q.bars.show||q.lines.show&&q.lines.fill)E.push({y:!0,number:!0,required:!1,defaultValue:0,autoscale:!!(q.bars.show&&q.bars.zero||q.lines.show&&q.lines.zero)}),q.bars.horizontal&&(delete E[E.length-1].y,E[E.length-1].x=!0);q.datapoints.format=E}if(null==q.datapoints.pointsize){q.datapoints.pointsize=E.length;f=q.datapoints.pointsize;
B=q.datapoints.points;var s=q.lines.show&&q.lines.steps;q.xaxis.used=q.yaxis.used=!0;for(r=v=0;r<m.length;++r,v+=f){h=m[r];var T=null==h;if(!T)for(y=0;y<f;++y){g=h[y];if(l=E[y])l.number&&null!=g&&(g=+g,isNaN(g)?g=null:Infinity==g?g=d:-Infinity==g&&(g=-d)),null==g&&(l.required&&(T=!0),null!=l.defaultValue&&(g=l.defaultValue));B[v+y]=g}if(T)for(y=0;y<f;++y)g=B[v+y],null!=g&&(l=E[y],!1!==l.autoscale&&(l.x&&a(q.xaxis,g,g),l.y&&a(q.yaxis,g,g))),B[v+y]=null;else if(s&&0<v&&null!=B[v-f]&&B[v-f]!=B[v]&&B[v-
f+1]!=B[v+1]){for(y=0;y<f;++y)B[v+f+y]=B[v+y];B[v+1]=B[v-f+1];v+=f}}}}for(e=0;e<w.length;++e)q=w[e],t(I.processDatapoints,[q,q.datapoints]);for(e=0;e<w.length;++e){q=w[e];B=q.datapoints.points;f=q.datapoints.pointsize;E=q.datapoints.format;h=v=c;s=m=b;for(r=0;r<B.length;r+=f)if(null!=B[r])for(y=0;y<f;++y)g=B[r+y],(l=E[y])&&!1!==l.autoscale&&g!=d&&g!=-d&&(l.x&&(g<v&&(v=g),g>m&&(m=g)),l.y&&(g<h&&(h=g),g>s&&(s=g)));if(q.bars.show){switch(q.bars.align){case "left":r=0;break;case "right":r=-q.bars.barWidth;
break;default:r=-q.bars.barWidth/2}q.bars.horizontal?(h+=r,s+=r+q.bars.barWidth):(v+=r,m+=r+q.bars.barWidth)}a(q.xaxis,v,m);a(q.yaxis,h,s)}k.each(F(),function(a,d){d.datamin==c&&(d.datamin=null);d.datamax==b&&(d.datamax=null)})}function X(){R&&clearTimeout(R);N.unbind("mousemove",Y);N.unbind("mouseleave",Z);N.unbind("click",$);t(I.shutdown,[N])}function la(a){function c(a){return a}var b,d,e=a.options.transform||c,r=a.options.inverseTransform;"x"==a.direction?(b=a.scale=O/Math.abs(e(a.max)-e(a.min)),
d=Math.min(e(a.max),e(a.min))):(b=a.scale=K/Math.abs(e(a.max)-e(a.min)),b=-b,d=Math.max(e(a.max),e(a.min)));a.p2c=e==c?function(a){return(a-d)*b}:function(a){return(e(a)-d)*b};a.c2p=r?function(a){return r(d+a/b)}:function(a){return d+a/b}}function ma(a){var c=a.labelWidth,b=a.labelHeight,d=a.options.position,e="x"===a.direction,r=a.options.tickLength,v=f.grid.axisMargin,y=f.grid.labelMargin,q=!0,g=!0,l=!0,h=!1;k.each(e?G:J,function(b,c){c&&c.reserveSpace&&(c===a?h=!0:c.options.position===d&&(h?g=
!1:q=!1),h||(l=!1))});g&&(v=0);null==r&&(r=l?"full":5);isNaN(+r)||(y+=+r);e?(b+=y,"bottom"==d?(m.bottom+=b+v,a.box={top:C.height-m.bottom,height:b}):(a.box={top:m.top+v,height:b},m.top+=b+v)):(c+=y,"left"==d?(a.box={left:m.left+v,width:c},m.left+=c+v):(m.right+=c+v,a.box={left:C.width-m.right,width:c}));a.position=d;a.tickLength=r;a.box.padding=y;a.innermost=q}function na(){var a=f.grid.minBorderMargin,c;if(null==a)for(c=a=0;c<w.length;++c)a=Math.max(a,2*(w[c].points.radius+w[c].points.lineWidth/
2));var b=a,d=a,e=a,r=a;k.each(F(),function(a,c){if(c.reserveSpace&&c.ticks&&c.ticks.length){var q=c.ticks[c.ticks.length-1];"x"===c.direction?(b=Math.max(b,c.labelWidth/2),q.v<=c.max&&(d=Math.max(d,c.labelWidth/2))):(r=Math.max(r,c.labelHeight/2),q.v<=c.max&&(e=Math.max(e,c.labelHeight/2)))}});m.left=Math.ceil(Math.max(b,m.left));m.right=Math.ceil(Math.max(d,m.right));m.top=Math.ceil(Math.max(e,m.top));m.bottom=Math.ceil(Math.max(r,m.bottom))}function aa(){var a,c=F(),b=f.grid.show;for(a in m){var d=
f.grid.margin||0;m[a]="number"==typeof d?d:d[a]||0}t(I.processOffset,[m]);for(a in m)m[a]="object"==typeof f.grid.borderWidth?m[a]+(b?f.grid.borderWidth[a]:0):m[a]+(b?f.grid.borderWidth:0);k.each(c,function(a,b){b.show=b.options.show;null==b.show&&(b.show=b.used);b.reserveSpace=b.show||b.options.reserveSpace;var c=b.options,d=+(null!=c.min?c.min:b.datamin),q=+(null!=c.max?c.max:b.datamax),f=q-d;if(0==f){if(f=0==q?1:0.01,null==c.min&&(d-=f),null==c.max||null!=c.min)q+=f}else{var g=c.autoscaleMargin;
null!=g&&(null==c.min&&(d-=f*g,0>d&&null!=b.datamin&&0<=b.datamin&&(d=0)),null==c.max&&(q+=f*g,0<q&&null!=b.datamax&&0>=b.datamax&&(q=0)))}b.min=d;b.max=q});if(b){d=k.grep(c,function(a){return a.reserveSpace});k.each(d,function(a,b){oa(b);var c=b.options.ticks,d=[];null==c||"number"==typeof c&&0<c?d=b.tickGenerator(b):c&&(d=k.isFunction(c)?c(b):c);var q;b.ticks=[];for(c=0;c<d.length;++c){var f=null,g=d[c];"object"==typeof g?(q=+g[0],1<g.length&&(f=g[1])):q=+g;null==f&&(f=b.tickFormatter(q,b));isNaN(q)||
b.ticks.push({v:q,label:f})}d=b.ticks;b.options.autoscaleMargin&&0<d.length&&(null==b.options.min&&(b.min=Math.min(b.min,d[0].v)),null==b.options.max&&1<d.length&&(b.max=Math.max(b.max,d[d.length-1].v)));d=b.options;c=b.ticks||[];q=d.labelWidth||0;for(var f=d.labelHeight||0,g=q||("x"==b.direction?Math.floor(C.width/(c.length||1)):null),l="flot-"+b.direction+"-axis flot-"+b.direction+b.n+"-axis "+(b.direction+"Axis "+b.direction+b.n+"Axis"),h=d.font||"flot-tick-label tickLabel",m=0;m<c.length;++m){var p=
c[m];p.label&&(p=C.getTextInfo(l,p.label,h,null,g),q=Math.max(q,p.width),f=Math.max(f,p.height))}b.labelWidth=d.labelWidth||q;b.labelHeight=d.labelHeight||f});for(a=d.length-1;0<=a;--a)ma(d[a]);na();k.each(d,function(a,b){"x"==b.direction?(b.box.left=m.left-b.labelWidth/2,b.box.width=C.width-m.left-m.right+b.labelWidth):(b.box.top=m.top-b.labelHeight/2,b.box.height=C.height-m.bottom-m.top+b.labelHeight)})}O=C.width-m.left-m.right;K=C.height-m.bottom-m.top;k.each(c,function(a,b){la(b)});b&&pa();qa()}
function oa(a){var c=a.options,b;b="number"==typeof c.ticks&&0<c.ticks?c.ticks:0.3*Math.sqrt("x"==a.direction?C.width:C.height);b=(a.max-a.min)/b;var d=-Math.floor(Math.log(b)/Math.LN10),e=c.tickDecimals;null!=e&&d>e&&(d=e);var f=Math.pow(10,-d),g=b/f,l;1.5>g?l=1:3>g?(l=2,2.25<g&&(null==e||d+1<=e)&&(l=2.5,++d)):l=7.5>g?5:10;l*=f;null!=c.minTickSize&&l<c.minTickSize&&(l=c.minTickSize);a.delta=b;a.tickDecimals=Math.max(0,null!=e?e:d);a.tickSize=c.tickSize||l;if("time"==c.mode&&!a.tickGenerator)throw Error("Time mode requires the flot.time plugin.");
a.tickGenerator||(a.tickGenerator=function(a){var b=[],c;c=a.tickSize;c*=Math.floor(a.min/c);var d=0,e=Number.NaN,q;do q=e,e=c+d*a.tickSize,b.push(e),++d;while(e<a.max&&e!=q);return b},a.tickFormatter=function(a,b){var c=b.tickDecimals?Math.pow(10,b.tickDecimals):1,d=""+Math.round(a*c)/c;if(null!=b.tickDecimals){var e=d.indexOf("."),e=-1==e?0:d.length-e-1;if(e<b.tickDecimals)return(e?d:d+".")+(""+c).substr(1,b.tickDecimals-e)}return d});k.isFunction(c.tickFormatter)&&(a.tickFormatter=function(a,b){return""+
c.tickFormatter(a,b)});if(null!=c.alignTicksWithAxis){var q=("x"==a.direction?G:J)[c.alignTicksWithAxis-1];q&&q.used&&q!=a&&(b=a.tickGenerator(a),0<b.length&&(null==c.min&&(a.min=Math.min(a.min,b[0])),null==c.max&&1<b.length&&(a.max=Math.max(a.max,b[b.length-1]))),a.tickGenerator=function(a){var b=[],c,d;for(d=0;d<q.ticks.length;++d)c=(q.ticks[d].v-q.min)/(q.max-q.min),c=a.min+c*(a.max-a.min),b.push(c);return b},a.mode||null!=c.tickDecimals||(b=Math.max(0,-Math.floor(Math.log(a.delta)/Math.LN10)+
1),d=a.tickGenerator(a),1<d.length&&/\..*0$/.test((d[1]-d[0]).toFixed(b))||(a.tickDecimals=b)))}}function ba(){C.clear();t(I.drawBackground,[g]);var a=f.grid;a.show&&a.backgroundColor&&(g.save(),g.translate(m.left,m.top),g.fillStyle=ca(f.grid.backgroundColor,K,0,"rgba(255, 255, 255, 0)"),g.fillRect(0,0,O,K),g.restore());a.show&&!a.aboveData&&da();for(var c=0;c<w.length;++c){t(I.drawSeries,[g,w[c]]);var b=w[c];b.lines.show&&ra(b);b.bars.show&&sa(b);b.points.show&&ta(b)}t(I.draw,[g]);a.show&&a.aboveData&&
da();C.render();S()}function ea(a,c){for(var b,d,e,f,g=F(),l=0;l<g.length;++l)if(b=g[l],b.direction==c&&(f=c+b.n+"axis",a[f]||1!=b.n||(f=c+"axis"),a[f])){d=a[f].from;e=a[f].to;break}a[f]||(b="x"==c?G[0]:J[0],d=a[c+"1"],e=a[c+"2"]);null!=d&&null!=e&&d>e&&(f=d,d=e,e=f);return{from:d,to:e,axis:b}}function da(){var a,c,b;g.save();g.translate(m.left,m.top);if(b=f.grid.markings)for(k.isFunction(b)&&(c=x.getAxes(),c.xmin=c.xaxis.min,c.xmax=c.xaxis.max,c.ymin=c.yaxis.min,c.ymax=c.yaxis.max,b=b(c)),a=0;a<
b.length;++a){c=b[a];var d=ea(c,"x"),e=ea(c,"y");null==d.from&&(d.from=d.axis.min);null==d.to&&(d.to=d.axis.max);null==e.from&&(e.from=e.axis.min);null==e.to&&(e.to=e.axis.max);d.to<d.axis.min||d.from>d.axis.max||e.to<e.axis.min||e.from>e.axis.max||(d.from=Math.max(d.from,d.axis.min),d.to=Math.min(d.to,d.axis.max),e.from=Math.max(e.from,e.axis.min),e.to=Math.min(e.to,e.axis.max),d.from==d.to&&e.from==e.to)||(d.from=d.axis.p2c(d.from),d.to=d.axis.p2c(d.to),e.from=e.axis.p2c(e.from),e.to=e.axis.p2c(e.to),
d.from==d.to||e.from==e.to?(g.beginPath(),g.strokeStyle=c.color||f.grid.markingsColor,g.lineWidth=c.lineWidth||f.grid.markingsLineWidth,g.moveTo(d.from,e.from),g.lineTo(d.to,e.to),g.stroke()):(g.fillStyle=c.color||f.grid.markingsColor,g.fillRect(d.from,e.to,d.to-d.from,e.from-e.to)))}c=F();b=f.grid.borderWidth;for(d=0;d<c.length;++d){e=c[d];a=e.box;var l=e.tickLength,v,h,q,B;if(e.show&&0!=e.ticks.length){g.lineWidth=1;"x"==e.direction?(v=0,h="full"==l?"top"==e.position?0:K:a.top-m.top+("top"==e.position?
a.height:0)):(h=0,v="full"==l?"left"==e.position?0:O:a.left-m.left+("left"==e.position?a.width:0));e.innermost||(g.strokeStyle=e.options.color,g.beginPath(),q=B=0,"x"==e.direction?q=O+1:B=K+1,1==g.lineWidth&&("x"==e.direction?h=Math.floor(h)+0.5:v=Math.floor(v)+0.5),g.moveTo(v,h),g.lineTo(v+q,h+B),g.stroke());g.strokeStyle=e.options.tickColor;g.beginPath();for(a=0;a<e.ticks.length;++a){var p=e.ticks[a].v;q=B=0;isNaN(p)||p<e.min||p>e.max||"full"==l&&("object"==typeof b&&0<b[e.position]||0<b)&&(p==
e.min||p==e.max)||("x"==e.direction?(v=e.p2c(p),B="full"==l?-K:l,"top"==e.position&&(B=-B)):(h=e.p2c(p),q="full"==l?-O:l,"left"==e.position&&(q=-q)),1==g.lineWidth&&("x"==e.direction?v=Math.floor(v)+0.5:h=Math.floor(h)+0.5),g.moveTo(v,h),g.lineTo(v+q,h+B))}g.stroke()}}b&&(a=f.grid.borderColor,"object"==typeof b||"object"==typeof a?("object"!==typeof b&&(b={top:b,right:b,bottom:b,left:b}),"object"!==typeof a&&(a={top:a,right:a,bottom:a,left:a}),0<b.top&&(g.strokeStyle=a.top,g.lineWidth=b.top,g.beginPath(),
g.moveTo(0-b.left,0-b.top/2),g.lineTo(O,0-b.top/2),g.stroke()),0<b.right&&(g.strokeStyle=a.right,g.lineWidth=b.right,g.beginPath(),g.moveTo(O+b.right/2,0-b.top),g.lineTo(O+b.right/2,K),g.stroke()),0<b.bottom&&(g.strokeStyle=a.bottom,g.lineWidth=b.bottom,g.beginPath(),g.moveTo(O+b.right,K+b.bottom/2),g.lineTo(0,K+b.bottom/2),g.stroke()),0<b.left&&(g.strokeStyle=a.left,g.lineWidth=b.left,g.beginPath(),g.moveTo(0-b.left/2,K+b.bottom),g.lineTo(0-b.left/2,0),g.stroke())):(g.lineWidth=b,g.strokeStyle=f.grid.borderColor,
g.strokeRect(-b/2,-b/2,O+b,K+b)));g.restore()}function pa(){k.each(F(),function(a,c){var b=c.box,d="flot-"+c.direction+"-axis flot-"+c.direction+c.n+"-axis "+(c.direction+"Axis "+c.direction+c.n+"Axis"),e=c.options.font||"flot-tick-label tickLabel",f,g,l,q,h;C.removeText(d);if(c.show&&0!=c.ticks.length)for(var k=0;k<c.ticks.length;++k)f=c.ticks[k],!f.label||f.v<c.min||f.v>c.max||("x"==c.direction?(q="center",g=m.left+c.p2c(f.v),"bottom"==c.position?l=b.top+b.padding:(l=b.top+b.height-b.padding,h=
"bottom")):(h="middle",l=m.top+c.p2c(f.v),"left"==c.position?(g=b.left+b.width-b.padding,q="right"):g=b.left+b.padding),C.addText(d,g,l,f.label,e,null,null,q,h))})}function ra(a){function c(a,b,c,d,e){var f=a.points;a=a.pointsize;var l=null,h=null;g.beginPath();for(var k=a;k<f.length;k+=a){var m=f[k-a],s=f[k-a+1],p=f[k],r=f[k+1];if(null!=m&&null!=p){if(s<=r&&s<e.min){if(r<e.min)continue;m=(e.min-s)/(r-s)*(p-m)+m;s=e.min}else if(r<=s&&r<e.min){if(s<e.min)continue;p=(e.min-s)/(r-s)*(p-m)+m;r=e.min}if(s>=
r&&s>e.max){if(r>e.max)continue;m=(e.max-s)/(r-s)*(p-m)+m;s=e.max}else if(r>=s&&r>e.max){if(s>e.max)continue;p=(e.max-s)/(r-s)*(p-m)+m;r=e.max}if(m<=p&&m<d.min){if(p<d.min)continue;s=(d.min-m)/(p-m)*(r-s)+s;m=d.min}else if(p<=m&&p<d.min){if(m<d.min)continue;r=(d.min-m)/(p-m)*(r-s)+s;p=d.min}if(m>=p&&m>d.max){if(p>d.max)continue;s=(d.max-m)/(p-m)*(r-s)+s;m=d.max}else if(p>=m&&p>d.max){if(m>d.max)continue;r=(d.max-m)/(p-m)*(r-s)+s;p=d.max}m==l&&s==h||g.moveTo(d.p2c(m)+b,e.p2c(s)+c);l=p;h=r;g.lineTo(d.p2c(p)+
b,e.p2c(r)+c)}}g.stroke()}function b(a,b,c){var d=a.points;a=a.pointsize;for(var e=Math.min(Math.max(0,c.min),c.max),f=0,l=!1,h=1,m=0,p=0;!(0<a&&f>d.length+a);){var f=f+a,s=d[f-a],k=d[f-a+h],r=d[f],n=d[f+h];if(l){if(0<a&&null!=s&&null==r){p=f;a=-a;h=2;continue}if(0>a&&f==m+a){g.fill();l=!1;a=-a;h=1;f=m=p+a;continue}}if(null!=s&&null!=r){if(s<=r&&s<b.min){if(r<b.min)continue;k=(b.min-s)/(r-s)*(n-k)+k;s=b.min}else if(r<=s&&r<b.min){if(s<b.min)continue;n=(b.min-s)/(r-s)*(n-k)+k;r=b.min}if(s>=r&&s>b.max){if(r>
b.max)continue;k=(b.max-s)/(r-s)*(n-k)+k;s=b.max}else if(r>=s&&r>b.max){if(s>b.max)continue;n=(b.max-s)/(r-s)*(n-k)+k;r=b.max}l||(g.beginPath(),g.moveTo(b.p2c(s),c.p2c(e)),l=!0);if(k>=c.max&&n>=c.max)g.lineTo(b.p2c(s),c.p2c(c.max)),g.lineTo(b.p2c(r),c.p2c(c.max));else if(k<=c.min&&n<=c.min)g.lineTo(b.p2c(s),c.p2c(c.min)),g.lineTo(b.p2c(r),c.p2c(c.min));else{var t=s,w=r;k<=n&&k<c.min&&n>=c.min?(s=(c.min-k)/(n-k)*(r-s)+s,k=c.min):n<=k&&n<c.min&&k>=c.min&&(r=(c.min-k)/(n-k)*(r-s)+s,n=c.min);k>=n&&k>
c.max&&n<=c.max?(s=(c.max-k)/(n-k)*(r-s)+s,k=c.max):n>=k&&n>c.max&&k<=c.max&&(r=(c.max-k)/(n-k)*(r-s)+s,n=c.max);s!=t&&g.lineTo(b.p2c(t),c.p2c(k));g.lineTo(b.p2c(s),c.p2c(k));g.lineTo(b.p2c(r),c.p2c(n));r!=w&&(g.lineTo(b.p2c(r),c.p2c(n)),g.lineTo(b.p2c(w),c.p2c(n)))}}}}g.save();g.translate(m.left,m.top);g.lineJoin="round";var d=a.lines.lineWidth,e=a.shadowSize;if(0<d&&0<e){g.lineWidth=e;g.strokeStyle="rgba(0,0,0,0.1)";var f=Math.PI/18;c(a.datapoints,Math.sin(f)*(d/2+e/2),Math.cos(f)*(d/2+e/2),a.xaxis,
a.yaxis);g.lineWidth=e/2;c(a.datapoints,Math.sin(f)*(d/2+e/4),Math.cos(f)*(d/2+e/4),a.xaxis,a.yaxis)}g.lineWidth=d;g.strokeStyle=a.color;if(e=U(a.lines,a.color,0,K))g.fillStyle=e,b(a.datapoints,a.xaxis,a.yaxis);0<d&&c(a.datapoints,0,0,a.xaxis,a.yaxis);g.restore()}function ta(a){function c(a,b,c,d,e,f,l,h){var k=a.points;a=a.pointsize;for(var m=0;m<k.length;m+=a){var r=k[m],p=k[m+1];null==r||r<f.min||r>f.max||p<l.min||p>l.max||(g.beginPath(),r=f.p2c(r),p=l.p2c(p)+d,"circle"==h?g.arc(r,p,b,0,e?Math.PI:
2*Math.PI,!1):h(g,r,p,b,e),g.closePath(),c&&(g.fillStyle=c,g.fill()),g.stroke())}}g.save();g.translate(m.left,m.top);var b=a.points.lineWidth,d=a.shadowSize,e=a.points.radius,f=a.points.symbol;0==b&&(b=1E-4);0<b&&0<d&&(d/=2,g.lineWidth=d,g.strokeStyle="rgba(0,0,0,0.1)",c(a.datapoints,e,null,d+d/2,!0,a.xaxis,a.yaxis,f),g.strokeStyle="rgba(0,0,0,0.2)",c(a.datapoints,e,null,d/2,!0,a.xaxis,a.yaxis,f));g.lineWidth=b;g.strokeStyle=a.color;c(a.datapoints,e,U(a.points,a.color),0,!1,a.xaxis,a.yaxis,f);g.restore()}
function fa(a,c,b,d,e,f,g,l,h,k,m){var p,n,t,w;k?(w=n=t=!0,p=!1,k=b,b=c+d,e=c+e,a<k&&(c=a,a=k,k=c,p=!0,n=!1)):(p=n=t=!0,w=!1,k=a+d,a+=e,e=b,b=c,b<e&&(c=b,b=e,e=c,w=!0,t=!1));a<g.min||k>g.max||b<l.min||e>l.max||(k<g.min&&(k=g.min,p=!1),a>g.max&&(a=g.max,n=!1),e<l.min&&(e=l.min,w=!1),b>l.max&&(b=l.max,t=!1),k=g.p2c(k),e=l.p2c(e),a=g.p2c(a),b=l.p2c(b),f&&(h.fillStyle=f(e,b),h.fillRect(k,b,a-k,e-b)),0<m&&(p||n||t||w)&&(h.beginPath(),h.moveTo(k,e),p?h.lineTo(k,b):h.moveTo(k,b),t?h.lineTo(a,b):h.moveTo(a,
b),n?h.lineTo(a,e):h.moveTo(a,e),w?h.lineTo(k,e):h.moveTo(k,e),h.stroke()))}function sa(a){g.save();g.translate(m.left,m.top);g.lineWidth=a.bars.lineWidth;g.strokeStyle=a.color;var c;switch(a.bars.align){case "left":c=0;break;case "right":c=-a.bars.barWidth;break;default:c=-a.bars.barWidth/2}(function(b,c,e,f,l,h){var k=b.points;b=b.pointsize;for(var m=0;m<k.length;m+=b)null!=k[m]&&fa(k[m],k[m+1],k[m+2],c,e,f,l,h,g,a.bars.horizontal,a.bars.lineWidth)})(a.datapoints,c,c+a.bars.barWidth,a.bars.fill?
function(b,c){return U(a.bars,a.color,b,c)}:null,a.xaxis,a.yaxis);g.restore()}function U(a,c,b,d){var e=a.fill;if(!e)return null;if(a.fillColor)return ca(a.fillColor,b,d,c);a=k.color.parse(c);a.a="number"==typeof e?e:0.4;a.normalize();return a.toString()}function qa(){null!=f.legend.container?k(f.legend.container).html(""):l.find(".legend").remove();if(f.legend.show){for(var a=[],c=[],b=!1,d=f.legend.labelFormatter,e,g,h=0;h<w.length;++h)e=w[h],e.label&&(g=d?d(e.label,e):e.label)&&c.push({label:g,
color:e.color});if(f.legend.sorted)if(k.isFunction(f.legend.sorted))c.sort(f.legend.sorted);else if("reverse"==f.legend.sorted)c.reverse();else{var p="descending"!=f.legend.sorted;c.sort(function(a,b){return a.label==b.label?0:a.label<b.label!=p?1:-1})}for(h=0;h<c.length;++h)d=c[h],0==h%f.legend.noColumns&&(b&&a.push("</tr>"),a.push("<tr>"),b=!0),a.push('<td class="legendColorBox"><div style="border:1px solid '+f.legend.labelBoxBorderColor+';padding:1px"><div style="width:4px;height:0;border:5px solid '+
d.color+';overflow:hidden"></div></div></td><td class="legendLabel">'+d.label+"</td>");b&&a.push("</tr>");0!=a.length&&(c='<table style="font-size:smaller;color:'+f.grid.color+'">'+a.join("")+"</table>",null!=f.legend.container?k(f.legend.container).html(c):(a="",b=f.legend.position,h=f.legend.margin,null==h[0]&&(h=[h,h]),"n"==b.charAt(0)?a+="top:"+(h[1]+m.top)+"px;":"s"==b.charAt(0)&&(a+="bottom:"+(h[1]+m.bottom)+"px;"),"e"==b.charAt(1)?a+="right:"+(h[0]+m.right)+"px;":"w"==b.charAt(1)&&(a+="left:"+
(h[0]+m.left)+"px;"),c=k('<div class="legend">'+c.replace('style="','style="position:absolute;'+a+";")+"</div>").appendTo(l),0!=f.legend.backgroundOpacity&&(b=f.legend.backgroundColor,null==b&&(b=(b=f.grid.backgroundColor)&&"string"==typeof b?k.color.parse(b):k.color.extract(c,"background-color"),b.a=1,b=b.toString()),h=c.children(),k('<div style="position:absolute;width:'+h.width()+"px;height:"+h.height()+"px;"+a+"background-color:"+b+';"> </div>').prependTo(c).css("opacity",f.legend.backgroundOpacity))))}}
function Y(a){f.grid.hoverable&&V("plothover",a,function(a){return!1!=a.hoverable})}function Z(a){f.grid.hoverable&&V("plothover",a,function(a){return!1})}function $(a){V("plotclick",a,function(a){return!1!=a.clickable})}function V(a,c,b){var d=N.offset(),e=c.pageX-d.left-m.left,g=c.pageY-d.top-m.top,h=W({left:e,top:g});h.pageX=c.pageX;h.pageY=c.pageY;c=f.grid.mouseActiveRadius;var k=c*c+1,p=null,n,t,x;for(n=w.length-1;0<=n;--n)if(b(w[n])){var H=w[n],u=H.xaxis,L=H.yaxis,E=H.datapoints.points,s=u.c2p(e),
C=L.c2p(g),F=c/u.scale,G=c/L.scale;x=H.datapoints.pointsize;u.options.inverseTransform&&(F=Number.MAX_VALUE);L.options.inverseTransform&&(G=Number.MAX_VALUE);if(H.lines.show||H.points.show)for(t=0;t<E.length;t+=x){var A=E[t],z=E[t+1];null==A||A-s>F||A-s<-F||z-C>G||z-C<-G||(A=Math.abs(u.p2c(A)-e),z=Math.abs(L.p2c(z)-g),z=A*A+z*z,z<k&&(k=z,p=[n,t/x]))}if(H.bars.show&&!p){switch(H.bars.align){case "left":u=0;break;case "right":u=-H.bars.barWidth;break;default:u=-H.bars.barWidth/2}H=u+H.bars.barWidth;
for(t=0;t<E.length;t+=x)A=E[t],z=E[t+1],L=E[t+2],null!=A&&(w[n].bars.horizontal?s<=Math.max(L,A)&&s>=Math.min(L,A)&&C>=z+u&&C<=z+H:s>=A+u&&s<=A+H&&C>=Math.min(L,z)&&C<=Math.max(L,z))&&(p=[n,t/x])}}p?(n=p[0],t=p[1],x=w[n].datapoints.pointsize,b={datapoint:w[n].datapoints.points.slice(t*x,(t+1)*x),dataIndex:t,series:w[n],seriesIndex:n}):b=null;b&&(b.pageX=parseInt(b.series.xaxis.p2c(b.datapoint[0])+d.left+m.left,10),b.pageY=parseInt(b.series.yaxis.p2c(b.datapoint[1])+d.top+m.top,10));if(f.grid.autoHighlight){for(d=
0;d<P.length;++d)e=P[d],e.auto!=a||b&&e.series==b.series&&e.point[0]==b.datapoint[0]&&e.point[1]==b.datapoint[1]||ga(e.series,e.point);b&&ha(b.series,b.datapoint,a)}l.trigger(a,[h,b])}function S(){var a=f.interaction.redrawOverlayInterval;-1==a?ia():R||(R=setTimeout(ia,a))}function ia(){R=null;A.save();Q.clear();A.translate(m.left,m.top);var a,c;for(a=0;a<P.length;++a)if(c=P[a],c.series.bars.show)ua(c.series,c.point);else{var b=c.series,d=c.point;c=d[0];var d=d[1],e=b.xaxis,f=b.yaxis,g="string"===
typeof b.highlightColor?b.highlightColor:k.color.parse(b.color).scale("a",0.5).toString();if(!(c<e.min||c>e.max||d<f.min||d>f.max)){var h=b.points.radius+b.points.lineWidth/2;A.lineWidth=h;A.strokeStyle=g;g=1.5*h;c=e.p2c(c);d=f.p2c(d);A.beginPath();"circle"==b.points.symbol?A.arc(c,d,g,0,2*Math.PI,!1):b.points.symbol(A,c,d,g,!1);A.closePath();A.stroke()}}A.restore();t(I.drawOverlay,[A])}function ha(a,c,b){"number"==typeof a&&(a=w[a]);if("number"==typeof c){var d=a.datapoints.pointsize;c=a.datapoints.points.slice(d*
c,d*(c+1))}d=ja(a,c);-1==d?(P.push({series:a,point:c,auto:b}),S()):b||(P[d].auto=!1)}function ga(a,c){if(null==a&&null==c)P=[],S();else{"number"==typeof a&&(a=w[a]);if("number"==typeof c){var b=a.datapoints.pointsize;c=a.datapoints.points.slice(b*c,b*(c+1))}b=ja(a,c);-1!=b&&(P.splice(b,1),S())}}function ja(a,c){for(var b=0;b<P.length;++b){var d=P[b];if(d.series==a&&d.point[0]==c[0]&&d.point[1]==c[1])return b}return-1}function ua(a,c){var b="string"===typeof a.highlightColor?a.highlightColor:k.color.parse(a.color).scale("a",
0.5).toString(),d;switch(a.bars.align){case "left":d=0;break;case "right":d=-a.bars.barWidth;break;default:d=-a.bars.barWidth/2}A.lineWidth=a.bars.lineWidth;A.strokeStyle=b;fa(c[0],c[1],c[2]||0,d,d+a.bars.barWidth,function(){return b},a.xaxis,a.yaxis,A,a.bars.horizontal,a.bars.lineWidth)}function ca(a,c,b,d){if("string"==typeof a)return a;c=g.createLinearGradient(0,b,0,c);b=0;for(var e=a.colors.length;b<e;++b){var f=a.colors[b];if("string"!=typeof f){var h=k.color.parse(d);null!=f.brightness&&(h=
h.scale("rgb",f.brightness));null!=f.opacity&&(h.a*=f.opacity);f=h.toString()}c.addColorStop(b/(e-1),f)}return c}var w=[],f={colors:["#edc240","#afd8f8","#cb4b4b","#4da74d","#9440ed"],legend:{show:!0,noColumns:1,labelFormatter:null,labelBoxBorderColor:"#ccc",container:null,position:"ne",margin:5,backgroundColor:null,backgroundOpacity:0.85,sorted:null},xaxis:{show:null,position:"bottom",mode:null,font:null,color:null,tickColor:null,transform:null,inverseTransform:null,min:null,max:null,autoscaleMargin:null,
ticks:null,tickFormatter:null,labelWidth:null,labelHeight:null,reserveSpace:null,tickLength:null,alignTicksWithAxis:null,tickDecimals:null,tickSize:null,minTickSize:null},yaxis:{autoscaleMargin:0.02,position:"left"},xaxes:[],yaxes:[],series:{points:{show:!1,radius:3,lineWidth:2,fill:!0,fillColor:"#ffffff",symbol:"circle"},lines:{lineWidth:2,fill:!1,fillColor:null,steps:!1},bars:{show:!1,lineWidth:2,barWidth:1,fill:!0,fillColor:null,align:"left",horizontal:!1,zero:!0},shadowSize:3,highlightColor:null},
grid:{show:!0,aboveData:!1,color:"#545454",backgroundColor:null,borderColor:null,tickColor:null,margin:0,labelMargin:5,axisMargin:8,borderWidth:2,minBorderMargin:null,markings:null,markingsColor:"#f4f4f4",markingsLineWidth:2,clickable:!1,hoverable:!1,autoHighlight:!0,mouseActiveRadius:10},interaction:{redrawOverlayInterval:1E3/60},hooks:{}},C=null,Q=null,N=null,g=null,A=null,G=[],J=[],m={left:0,right:0,top:0,bottom:0},O=0,K=0,I={processOptions:[],processRawData:[],processDatapoints:[],processOffset:[],
drawBackground:[],drawSeries:[],draw:[],bindEvents:[],drawOverlay:[],shutdown:[]},x=this;x.setData=L;x.setupGrid=aa;x.draw=ba;x.getPlaceholder=function(){return l};x.getCanvas=function(){return C.element};x.getPlotOffset=function(){return m};x.width=function(){return O};x.height=function(){return K};x.offset=function(){var a=N.offset();a.left+=m.left;a.top+=m.top;return a};x.getData=function(){return w};x.getAxes=function(){var a={};k.each(G.concat(J),function(c,b){b&&(a[b.direction+(1!=b.n?b.n:"")+
"axis"]=b)});return a};x.getXAxes=function(){return G};x.getYAxes=function(){return J};x.c2p=W;x.p2c=function(a){var c={},b,d,e;for(b=0;b<G.length;++b)if((d=G[b])&&d.used&&(e="x"+d.n,null==a[e]&&1==d.n&&(e="x"),null!=a[e])){c.left=d.p2c(a[e]);break}for(b=0;b<J.length;++b)if((d=J[b])&&d.used&&(e="y"+d.n,null==a[e]&&1==d.n&&(e="y"),null!=a[e])){c.top=d.p2c(a[e]);break}return c};x.getOptions=function(){return f};x.highlight=ha;x.unhighlight=ga;x.triggerRedrawOverlay=S;x.pointOffset=function(a){return{left:parseInt(G[u(a,
"x")-1].p2c(+a.x)+m.left,10),top:parseInt(J[u(a,"y")-1].p2c(+a.y)+m.top,10)}};x.shutdown=X;x.destroy=function(){X();l.removeData("plot").empty();w=[];A=g=N=Q=C=f=null;G=[];J=[];I=null;P=[];x=null};x.resize=function(){var a=l.width(),c=l.height();C.resize(a,c);Q.resize(a,c)};x.hooks=I;(function(){for(var a={Canvas:D},c=0;c<n.length;++c){var b=n[c];b.init(x,a);b.options&&k.extend(!0,f,b.options)}})(x);(function(a){k.extend(!0,f,a);a&&a.colors&&(f.colors=a.colors);null==f.xaxis.color&&(f.xaxis.color=
k.color.parse(f.grid.color).scale("a",0.22).toString());null==f.yaxis.color&&(f.yaxis.color=k.color.parse(f.grid.color).scale("a",0.22).toString());null==f.xaxis.tickColor&&(f.xaxis.tickColor=f.grid.tickColor||f.xaxis.color);null==f.yaxis.tickColor&&(f.yaxis.tickColor=f.grid.tickColor||f.yaxis.color);null==f.grid.borderColor&&(f.grid.borderColor=f.grid.color);null==f.grid.tickColor&&(f.grid.tickColor=k.color.parse(f.grid.color).scale("a",0.22).toString());var c,b;a=(a=l.css("font-size"))?+a.replace("px",
""):13;var d={style:l.css("font-style"),size:Math.round(0.8*a),variant:l.css("font-variant"),weight:l.css("font-weight"),family:l.css("font-family")};b=f.xaxes.length||1;for(a=0;a<b;++a)(c=f.xaxes[a])&&!c.tickColor&&(c.tickColor=c.color),c=k.extend(!0,{},f.xaxis,c),f.xaxes[a]=c,c.font&&(c.font=k.extend({},d,c.font),c.font.color||(c.font.color=c.color),c.font.lineHeight||(c.font.lineHeight=Math.round(1.15*c.font.size)));b=f.yaxes.length||1;for(a=0;a<b;++a)(c=f.yaxes[a])&&!c.tickColor&&(c.tickColor=
c.color),c=k.extend(!0,{},f.yaxis,c),f.yaxes[a]=c,c.font&&(c.font=k.extend({},d,c.font),c.font.color||(c.font.color=c.color),c.font.lineHeight||(c.font.lineHeight=Math.round(1.15*c.font.size)));f.xaxis.noTicks&&null==f.xaxis.ticks&&(f.xaxis.ticks=f.xaxis.noTicks);f.yaxis.noTicks&&null==f.yaxis.ticks&&(f.yaxis.ticks=f.yaxis.noTicks);f.x2axis&&(f.xaxes[1]=k.extend(!0,{},f.xaxis,f.x2axis),f.xaxes[1].position="top");f.y2axis&&(f.yaxes[1]=k.extend(!0,{},f.yaxis,f.y2axis),f.yaxes[1].position="right");f.grid.coloredAreas&&
(f.grid.markings=f.grid.coloredAreas);f.grid.coloredAreasColor&&(f.grid.markingsColor=f.grid.coloredAreasColor);f.lines&&k.extend(!0,f.series.lines,f.lines);f.points&&k.extend(!0,f.series.points,f.points);f.bars&&k.extend(!0,f.series.bars,f.bars);null!=f.shadowSize&&(f.series.shadowSize=f.shadowSize);null!=f.highlightColor&&(f.series.highlightColor=f.highlightColor);for(a=0;a<f.xaxes.length;++a)M(G,a+1).options=f.xaxes[a];for(a=0;a<f.yaxes.length;++a)M(J,a+1).options=f.yaxes[a];for(var e in I)f.hooks[e]&&
f.hooks[e].length&&(I[e]=I[e].concat(f.hooks[e]));t(I.processOptions,[f])})(h);(function(){l.css("padding",0).children().filter(function(){return!k(this).hasClass("flot-overlay")&&!k(this).hasClass("flot-base")}).remove();"static"==l.css("position")&&l.css("position","relative");C=new D("flot-base",l);Q=new D("flot-overlay",l);g=C.context;A=Q.context;N=k(Q.element).unbind();var a=l.data("plot");a&&(a.shutdown(),Q.clear());l.data("plot",x)})();L(p);aa();ba();f.grid.hoverable&&(N.mousemove(Y),N.bind("mouseleave",
Z));f.grid.clickable&&N.click($);t(I.bindEvents,[N]);var P=[],R=null}var n=Object.prototype.hasOwnProperty;D.prototype.resize=function(l,k){if(0>=l||0>=k)throw Error("Invalid dimensions for plot, width = "+l+", height = "+k);var h=this.element,n=this.context,t=this.pixelRatio;this.width!=l&&(h.width=l*t,h.style.width=l+"px",this.width=l);this.height!=k&&(h.height=k*t,h.style.height=k+"px",this.height=k);n.restore();n.save();n.scale(t,t)};D.prototype.clear=function(){this.context.clearRect(0,0,this.width,
this.height)};D.prototype.render=function(){var l=this._textCache,k;for(k in l)if(n.call(l,k)){var h=this.getTextLayer(k),H=l[k];h.hide();for(var t in H)if(n.call(H,t)){var u=H[t],z;for(z in u)if(n.call(u,z)){for(var F=u[z].positions,D=0,M;M=F[D];D++)M.active?M.rendered||(h.append(M.element),M.rendered=!0):(F.splice(D--,1),M.rendered&&M.element.detach());0==F.length&&delete u[z]}}h.show()}};D.prototype.getTextLayer=function(l){var p=this.text[l];null==p&&(null==this.textContainer&&(this.textContainer=
k("<div class='flot-text'></div>").css({position:"absolute",top:0,left:0,bottom:0,right:0,"font-size":"smaller",color:"#545454"}).insertAfter(this.element)),p=this.text[l]=k("<div></div>").addClass(l).css({position:"absolute",top:0,left:0,bottom:0,right:0}).appendTo(this.textContainer));return p};D.prototype.getTextInfo=function(l,p,h,n,t){var u,z;p=""+p;n="object"===typeof h?h.style+" "+h.variant+" "+h.weight+" "+h.size+"px/"+h.lineHeight+"px "+h.family:h;u=this._textCache[l];null==u&&(u=this._textCache[l]=
{});z=u[n];null==z&&(z=u[n]={});u=z[p];null==u&&(l=k("<div></div>").html(p).css({position:"absolute","max-width":t,top:-9999}).appendTo(this.getTextLayer(l)),"object"===typeof h?l.css({font:n,color:h.color}):"string"===typeof h&&l.addClass(h),u=z[p]={width:l.outerWidth(!0),height:l.outerHeight(!0),element:l,positions:[]},l.detach());return u};D.prototype.addText=function(l,k,h,n,t,u,z,F,D){l=this.getTextInfo(l,n,t,u,z);n=l.positions;"center"==F?k-=l.width/2:"right"==F&&(k-=l.width);"middle"==D?h-=
l.height/2:"bottom"==D&&(h-=l.height);for(D=0;t=n[D];D++)if(t.x==k&&t.y==h){t.active=!0;return}t={active:!0,rendered:!1,element:n.length?l.element.clone():l.element,x:k,y:h};n.push(t);t.element.css({top:Math.round(h),left:Math.round(k),"text-align":F})};D.prototype.removeText=function(k,p,h,u,t,D){if(null==u){if(p=this._textCache[k],null!=p)for(var z in p)if(n.call(p,z)){h=p[z];for(var F in h)if(n.call(h,F))for(k=h[F].positions,u=0;t=k[u];u++)t.active=!1}}else for(k=this.getTextInfo(k,u,t,D).positions,
u=0;t=k[u];u++)t.x==p&&t.y==h&&(t.active=!1)};k.plot=function(l,n,h){return new u(k(l),n,h,k.plot.plugins)};k.plot.version="0.8.2";k.plot.plugins=[];k.fn.plot=function(l,n){return this.each(function(){k.plot(this,l,n)})}})(jQuery);
