(function(s){s.plot.plugins.push({init:function(n){function D(a){for(var b=0,c=0,h=0,e=d.series.pie.combine.color,k=[],l=0;l<a.length;++l){var f=a[l].data;s.isArray(f)&&1==f.length&&(f=f[0]);s.isArray(f)?!isNaN(parseFloat(f[1]))&&isFinite(f[1])?f[1]=+f[1]:f[1]=0:f=!isNaN(parseFloat(f))&&isFinite(f)?[1,+f]:[1,0];a[l].data=[f]}for(l=0;l<a.length;++l)b+=a[l].data[0][1];for(l=0;l<a.length;++l)f=a[l].data[0][1],f/b<=d.series.pie.combine.threshold&&(c+=f,h++,e||(e=a[l].color));for(l=0;l<a.length;++l)f=
a[l].data[0][1],(2>h||f/b>d.series.pie.combine.threshold)&&k.push({data:[[1,f]],color:a[l].color,label:a[l].label,angle:f*Math.PI*2/b,percent:f/(b/100)});1<h&&k.push({data:[[1,c]],color:e,label:d.series.pie.combine.label,angle:c*Math.PI*2/b,percent:c/(b/100)});return k}function E(a,b){function m(){c.clearRect(0,0,k,l);w.children().filter(".pieLabel, .pieLabelBackground").remove()}function h(){var a=d.series.pie.shadow.left,b=d.series.pie.shadow.top,f=d.series.pie.shadow.alpha,m=1<d.series.pie.radius?
d.series.pie.radius:t*d.series.pie.radius;if(!(m>=k/2-a||m*d.series.pie.tilt>=l/2-b||10>=m)){c.save();c.translate(a,b);c.globalAlpha=f;c.fillStyle="#000";c.translate(r,x);c.scale(1,d.series.pie.tilt);for(a=1;10>=a;a++)c.beginPath(),c.arc(0,0,m,0,2*Math.PI,!1),c.fill(),m-=a;c.restore()}}function e(){function a(b,d,f){0>=b||isNaN(b)||(f?c.fillStyle=d:(c.strokeStyle=d,c.lineJoin="round"),c.beginPath(),1E-9<Math.abs(b-2*Math.PI)&&c.moveTo(0,0),c.arc(0,0,m,e,e+b/2,!1),c.arc(0,0,m,e+b/2,e+b,!1),c.closePath(),
e+=b,f?c.fill():c.stroke())}function b(){for(var a=f,c=1<d.series.pie.label.radius?d.series.pie.label.radius:t*d.series.pie.label.radius,m=0;m<q.length;++m){if(q[m].percent>=100*d.series.pie.label.threshold){var e;e=q[m];var g=a,h=m;if(0==e.data[0][1])e=!0;else{var n=d.legend.labelFormatter,p=void 0,u=d.series.pie.label.formatter,p=n?n(e.label,e):e.label;u&&(p=u(p,e));n=(g+e.angle+g)/2;g=r+Math.round(Math.cos(n)*c);n=x+Math.round(Math.sin(n)*c)*d.series.pie.tilt;w.append("<span class='pieLabel' id='pieLabel"+
h+"' style='position:absolute;top:"+n+"px;left:"+g+"px;'>"+p+"</span>");h=w.children("#pieLabel"+h);p=n-h.height()/2;n=g-h.width()/2;h.css("top",p);h.css("left",n);0<0-p||0<0-n||0>l-(p+h.height())||0>k-(n+h.width())?e=!1:(0!=d.series.pie.label.background.opacity&&(g=d.series.pie.label.background.color,null==g&&(g=e.color),e="top:"+p+"px;left:"+n+"px;",s("<div class='pieLabelBackground' style='position:absolute;width:"+h.width()+"px;height:"+h.height()+"px;"+e+"background-color:"+g+";'></div>").css("opacity",
d.series.pie.label.background.opacity).insertBefore(h)),e=!0)}if(!e)return!1}a+=q[m].angle}return!0}var f=Math.PI*d.series.pie.startAngle,m=1<d.series.pie.radius?d.series.pie.radius:t*d.series.pie.radius;c.save();c.translate(r,x);c.scale(1,d.series.pie.tilt);c.save();for(var e=f,h=0;h<q.length;++h)q[h].startAngle=e,a(q[h].angle,q[h].color,!0);c.restore();if(0<d.series.pie.stroke.width){c.save();c.lineWidth=d.series.pie.stroke.width;e=f;for(h=0;h<q.length;++h)a(q[h].angle,d.series.pie.stroke.color,
!1);c.restore()}A(c);c.restore();return d.series.pie.label.show?b():!0}if(w){var k=a.getPlaceholder().width(),l=a.getPlaceholder().height(),f=w.children().filter(".legend").children().width()||0;c=b;z=!1;t=Math.min(k,l/d.series.pie.tilt)/2;x=l/2+d.series.pie.offset.top;r=k/2;"auto"==d.series.pie.offset.left?(r=d.legend.position.match("w")?r+f/2:r-f/2,r<t?r=t:r>k-t&&(r=k-t)):r+=d.series.pie.offset.left;var q=a.getData(),f=0;do 0<f&&(t*=0.95),f+=1,m(),0.8>=d.series.pie.tilt&&h();while(!e()&&10>f);10<=
f&&(m(),w.prepend("<div class='error'>Could not draw pie with labels contained inside canvas</div>"));a.setSeries&&a.insertLegend&&(a.setSeries(q),a.insertLegend())}}function A(a){if(0<d.series.pie.innerRadius){a.save();var b=1<d.series.pie.innerRadius?d.series.pie.innerRadius:t*d.series.pie.innerRadius;a.globalCompositeOperation="destination-out";a.beginPath();a.fillStyle=d.series.pie.stroke.color;a.arc(0,0,b,0,2*Math.PI,!1);a.fill();a.closePath();a.restore();a.save();a.beginPath();a.strokeStyle=
d.series.pie.stroke.color;a.arc(0,0,b,0,2*Math.PI,!1);a.stroke();a.closePath();a.restore()}}function G(a){B("plothover",a)}function H(a){B("plotclick",a)}function B(a,b){var m=n.offset(),h=parseInt(b.pageX-m.left);a:{for(var m=parseInt(b.pageY-m.top),e=n.getData(),k=n.getOptions(),k=1<k.series.pie.radius?k.series.pie.radius:t*k.series.pie.radius,l,f,q=0;q<e.length;++q){var g=e[q];if(g.pie.show){c.save();c.beginPath();c.moveTo(0,0);c.arc(0,0,k,g.startAngle,g.startAngle+g.angle/2,!1);c.arc(0,0,k,g.startAngle+
g.angle/2,g.startAngle+g.angle,!1);c.closePath();l=h-r;f=m-x;if(c.isPointInPath){if(c.isPointInPath(h-r,m-x)){c.restore();h={datapoint:[g.percent,g.data],dataIndex:0,series:g,seriesIndex:q};break a}}else{var p=k*Math.cos(g.startAngle),v=k*Math.sin(g.startAngle),s=k*Math.cos(g.startAngle+g.angle/4),y=k*Math.sin(g.startAngle+g.angle/4),D=k*Math.cos(g.startAngle+g.angle/2),z=k*Math.sin(g.startAngle+g.angle/2),A=k*Math.cos(g.startAngle+g.angle/1.5),B=k*Math.sin(g.startAngle+g.angle/1.5),C=k*Math.cos(g.startAngle+
g.angle),E=k*Math.sin(g.startAngle+g.angle),p=[[0,0],[p,v],[s,y],[D,z],[A,B],[C,E]];l=[l,f];f=!1;v=-1;s=p.length;for(y=s-1;++v<s;y=v)(p[v][1]<=l[1]&&l[1]<p[y][1]||p[y][1]<=l[1]&&l[1]<p[v][1])&&l[0]<(p[y][0]-p[v][0])*(l[1]-p[v][1])/(p[y][1]-p[v][1])+p[v][0]&&(f=!f);if(f){c.restore();h={datapoint:[g.percent,g.data],dataIndex:0,series:g,seriesIndex:q};break a}}c.restore()}}h=null}if(d.grid.autoHighlight)for(m=0;m<u.length;++m)e=u[m],e.auto!=a||h&&e.series==h.series||(e=e.series,null==e&&(u=[],n.triggerRedrawOverlay()),
e=F(e),-1!=e&&(u.splice(e,1),n.triggerRedrawOverlay()));h&&(m=h.series,e=F(m),-1==e?(u.push({series:m,auto:a}),n.triggerRedrawOverlay()):a||(u[e].auto=!1));w.trigger(a,[{pageX:b.pageX,pageY:b.pageY},h])}function F(a){for(var b=0;b<u.length;++b)if(u[b].series==a)return b;return-1}var C=null,w=null,d=null,t=null,r=null,x=null,z=!1,c=null,u=[];n.hooks.processOptions.push(function(a,b){b.series.pie.show&&(b.grid.show=!1,"auto"==b.series.pie.label.show&&(b.series.pie.label.show=b.legend.show?!1:!0),"auto"==
b.series.pie.radius&&(b.series.pie.radius=b.series.pie.label.show?0.75:1),1<b.series.pie.tilt?b.series.pie.tilt=1:0>b.series.pie.tilt&&(b.series.pie.tilt=0))});n.hooks.bindEvents.push(function(a,b){var c=a.getOptions();c.series.pie.show&&(c.grid.hoverable&&b.unbind("mousemove").mousemove(G),c.grid.clickable&&b.unbind("click").click(H))});n.hooks.processDatapoints.push(function(a,b,c,h){a.getOptions().series.pie.show&&!z&&(z=!0,C=a.getCanvas(),w=s(C).parent(),d=a.getOptions(),a.setData(D(a.getData())))});
n.hooks.drawOverlay.push(function(a,b){if(a.getOptions().series.pie.show){var c=a.getOptions(),d=1<c.series.pie.radius?c.series.pie.radius:t*c.series.pie.radius;b.save();b.translate(r,x);b.scale(1,c.series.pie.tilt);for(var e=0;e<u.length;++e){var k=u[e].series;0>=k.angle||isNaN(k.angle)||(b.fillStyle="rgba(255, 255, 255, "+c.series.pie.highlight.opacity+")",b.beginPath(),1E-9<Math.abs(k.angle-2*Math.PI)&&b.moveTo(0,0),b.arc(0,0,d,k.startAngle,k.startAngle+k.angle/2,!1),b.arc(0,0,d,k.startAngle+k.angle/
2,k.startAngle+k.angle,!1),b.closePath(),b.fill())}A(b);b.restore()}});n.hooks.draw.push(function(a,b){a.getOptions().series.pie.show&&E(a,b)})},options:{series:{pie:{show:!1,radius:"auto",innerRadius:0,startAngle:1.5,tilt:1,shadow:{left:5,top:15,alpha:0.02},offset:{top:0,left:"auto"},stroke:{color:"#fff",width:1},label:{show:"auto",formatter:function(n,s){return"<div style='font-size:x-small;text-align:center;padding:2px;color:"+s.color+";'>"+n+"<br/>"+Math.round(s.percent)+"%</div>"},radius:1,background:{color:null,
opacity:0},threshold:0},combine:{threshold:-1,color:null,label:"Other"},highlight:{opacity:0.5}}}},name:"pie",version:"1.1"})})(jQuery);
