var $jscomp={scope:{},findInternal:function(a,b,d){a instanceof String&&(a=String(a));for(var c=a.length,e=0;e<c;e++){var f=a[e];if(b.call(d,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(d.get||d.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,b,d,c){if(b){d=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var e=a[c];e in d||(d[e]={});d=d[e]}a=a[a.length-1];c=d[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,d){return $jscomp.findInternal(this,a,d).v}},"es6-impl","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.EXPOSE_ASYNC_EXECUTOR=!0;$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};b.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){d(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var c=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(h){b.reject(h)}};c.prototype.createResolveAndReject_=function(){function a(a){return function(f){c||(c=!0,a.call(b,f))}}var b=this,c=
!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};c.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof c)this.settleSameAsPromise_(a);else{var b;a:switch(typeof a){case "object":b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};c.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(h){this.reject_(h);return}"function"==
typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};c.prototype.reject_=function(a){this.settle_(2,a)};c.prototype.fulfill_=function(a){this.settle_(1,a)};c.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};c.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),
a[b]=null;this.onSettledCallbacks_=null}};var e=new b;c.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};c.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(k){c.reject(k)}};c.prototype.then=function(a,b){function d(a,b){return"function"==typeof a?function(b){try{f(a(b))}catch(l){e(l)}}:b}var f,e,g=new c(function(a,b){f=a;e=b});this.callWhenSettled_(d(a,f),
d(b,e));return g};c.prototype["catch"]=function(a){return this.then(void 0,a)};c.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?e.asyncExecute(c):this.onSettledCallbacks_.push(function(){e.asyncExecute(c)})};c.resolve=function(a){return a instanceof c?a:new c(function(b,c){b(a)})};c.reject=function(a){return new c(function(b,c){c(a)})};
c.race=function(a){return new c(function(b,d){for(var f=$jscomp.makeIterator(a),e=f.next();!e.done;e=f.next())c.resolve(e.value).callWhenSettled_(b,d)})};c.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?c.resolve([]):new c(function(a,f){function e(b){return function(c){g[b]=c;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,c.resolve(d.value).callWhenSettled_(e(g.length-1),f),d=b.next();while(!d.done)})};$jscomp.EXPOSE_ASYNC_EXECUTOR&&(c.$jscomp$new$AsyncExecutor=function(){return new b});
return c},"es6-impl","es3");if("undefined"===typeof jQuery)throw Error("AdminLTE strictly requires jQuery");
var AdminLTEReloadPage=function(a){for(i=0;i<document.forms.length;i++)document.forms[i].reset();blockUI(a);window.location.reload(!0)},blockUI=function(a){a||(a='<i style="font-size: 30px" class="fa fa-refresh fa-spin"></i>');$.msg({bgPath:"/admin_l_t_e/js/msg/1.0.7/",fadeIn:0,autoUnblock:!1,content:a})},unblockUI=function(){$.msg("unblock")},AdminLTENoty=function(a,b,d,c){b||(b="Empty Message");d=d?!0:!1;timeout=c?!1:5E3;switch(a){case "warning":noty({type:"warning",text:b,layout:"topRight",theme:"defaultTheme",
dismissQueue:!0,modal:d,maxVisible:5,timeout:timeout,closeWith:["button"]});break;case "error":noty({type:"error",text:b,layout:"topRight",theme:"defaultTheme",dismissQueue:!0,modal:d,maxVisible:5,timeout:timeout,closeWith:["button"]});break;case "alert":noty({type:"alert",text:b,layout:"topRight",theme:"defaultTheme",dismissQueue:!0,modal:d,maxVisible:5,timeout:timeout,closeWith:["button"]});break;case "notify":noty({type:"notification",text:b,layout:"topRight",theme:"defaultTheme",dismissQueue:!0,
modal:d,maxVisible:5,timeout:timeout,closeWith:["button"]});break;case "success":noty({type:"success",text:b,layout:"topRight",theme:"defaultTheme",dismissQueue:!0,modal:d,maxVisible:5,timeout:timeout,closeWith:["button"]});break;default:noty({type:"notification",text:b,layout:"topRight",theme:"defaultTheme",dismissQueue:!0,modal:d,maxVisible:5,timeout:timeout,closeWith:["button"]})}};$.AdminLTE={};
$.AdminLTE.options={navbarMenuSlimscroll:!0,navbarMenuSlimscrollWidth:"3px",navbarMenuHeight:"200px",animationSpeed:500,sidebarToggleSelector:"[data-toggle='offcanvas']",sidebarPushMenu:!0,sidebarSlimScroll:!0,sidebarExpandOnHover:!1,enableBoxRefresh:!0,enableBSToppltip:!0,BSTooltipSelector:"[data-toggle='tooltip']",enableFastclick:!0,enableControlSidebar:!0,controlSidebarOptions:{toggleBtnSelector:"[data-toggle='control-sidebar']",selector:".control-sidebar",slide:!0},enableBoxWidget:!0,boxWidgetOptions:{boxWidgetIcons:{collapse:"fa-minus",
open:"fa-plus",remove:"fa-times"},boxWidgetSelectors:{remove:'[data-widget="remove"]',collapse:'[data-widget="collapse"]'}},directChat:{enable:!0,contactToggleSelector:'[data-widget="chat-pane-toggle"]'},colors:{lightBlue:"#3c8dbc",red:"#f56954",green:"#00a65a",aqua:"#00c0ef",yellow:"#f39c12",blue:"#0073b7",navy:"#001F3F",teal:"#39CCCC",olive:"#3D9970",lime:"#01FF70",orange:"#FF851B",fuchsia:"#F012BE",purple:"#8E24AA",maroon:"#D81B60",black:"#222222",gray:"#d2d6de"},screenSizes:{xs:480,sm:768,md:992,
lg:1200}};
$(function(){$("body").removeClass("hold-transition");"undefined"!==typeof AdminLTEOptions&&$.extend(!0,$.AdminLTE.options,AdminLTEOptions);var a=$.AdminLTE.options;_init();$.AdminLTE.layout.activate();$.AdminLTE.tree(".sidebar");a.enableControlSidebar&&$.AdminLTE.controlSidebar.activate();a.navbarMenuSlimscroll&&"undefined"!=typeof $.fn.slimscroll&&$(".navbar .menu").slimscroll({height:a.navbarMenuHeight,alwaysVisible:!1,size:a.navbarMenuSlimscrollWidth}).css("width","100%");a.sidebarPushMenu&&$.AdminLTE.pushMenu.activate(a.sidebarToggleSelector);
a.enableBSToppltip&&$("body").tooltip({selector:a.BSTooltipSelector,trigger:"click"});a.enableBoxWidget&&$.AdminLTE.boxWidget.activate();a.enableFastclick&&"undefined"!=typeof FastClick&&FastClick.attach(document.body);if(a.directChat.enable)$(document).on("click",a.directChat.contactToggleSelector,function(){$(this).parents(".direct-chat").first().toggleClass("direct-chat-contacts-open")});$('.btn-group[data-toggle="btn-toggle"]').each(function(){var a=$(this);$(this).find(".btn").on("click",function(b){a.find(".btn.active").removeClass("active");
$(this).addClass("active");b.preventDefault()})})});
function _init(){$.AdminLTE.layout={activate:function(){var a=this;a.fix();a.fixSidebar();$(window,".wrapper").resize(function(){a.fix();a.fixSidebar()})},fix:function(){var a=$(".main-header").outerHeight()+$(".main-footer").outerHeight(),b=$(window).height(),d=$(".sidebar").height();$("body").hasClass("fixed")?$(".content-wrapper, .right-side").css("min-height",b-$(".main-footer").outerHeight()):(b>=d?($(".content-wrapper, .right-side").css("min-height",b-a),a=b-a):($(".content-wrapper, .right-side").css("min-height",
d),a=d),b=$($.AdminLTE.options.controlSidebarOptions.selector),"undefined"!==typeof b&&b.height()>a&&$(".content-wrapper, .right-side").css("min-height",b.height()))},fixSidebar:function(){$("body").hasClass("fixed")?("undefined"==typeof $.fn.slimScroll&&window.console&&window.console.error("Error: the fixed layout requires the slimscroll plugin!"),$.AdminLTE.options.sidebarSlimScroll&&"undefined"!=typeof $.fn.slimScroll&&($(".sidebar").slimScroll({destroy:!0}).height("auto"),$(".sidebar").slimscroll({height:$(window).height()-
$(".main-header").height()+"px",color:"rgba(0,0,0,0.2)",size:"3px"}))):"undefined"!=typeof $.fn.slimScroll&&$(".sidebar").slimScroll({destroy:!0}).height("auto")}};$.AdminLTE.pushMenu={activate:function(a){var b=$.AdminLTE.options.screenSizes;$(document).on("click",a,function(a){a.preventDefault();$(window).width()>b.sm-1?$("body").hasClass("sidebar-collapse")?$("body").removeClass("sidebar-collapse").trigger("expanded.pushMenu"):$("body").addClass("sidebar-collapse").trigger("collapsed.pushMenu"):
$("body").hasClass("sidebar-open")?$("body").removeClass("sidebar-open").removeClass("sidebar-collapse").trigger("collapsed.pushMenu"):$("body").addClass("sidebar-open").trigger("expanded.pushMenu")});$(".content-wrapper").click(function(){$(window).width()<=b.sm-1&&$("body").hasClass("sidebar-open")&&$("body").removeClass("sidebar-open")});($.AdminLTE.options.sidebarExpandOnHover||$("body").hasClass("fixed")&&$("body").hasClass("sidebar-mini"))&&this.expandOnHover()},expandOnHover:function(){var a=
this,b=$.AdminLTE.options.screenSizes.sm-1;$(".main-sidebar").hover(function(){$("body").hasClass("sidebar-mini")&&$("body").hasClass("sidebar-collapse")&&$(window).width()>b&&a.expand()},function(){$("body").hasClass("sidebar-mini")&&$("body").hasClass("sidebar-expanded-on-hover")&&$(window).width()>b&&a.collapse()})},expand:function(){$("body").removeClass("sidebar-collapse").addClass("sidebar-expanded-on-hover")},collapse:function(){$("body").hasClass("sidebar-expanded-on-hover")&&$("body").removeClass("sidebar-expanded-on-hover").addClass("sidebar-collapse")}};
$.AdminLTE.tree=function(a){var b=this,d=$.AdminLTE.options.animationSpeed;$(a).on("click","li a",function(a){var c=$(this),f=c.next();if(f.is(".treeview-menu")&&f.is(":visible")&&!$("body").hasClass("sidebar-collapse"))f.slideUp(d,function(){f.removeClass("menu-open")}),f.parent("li").removeClass("active");else if(f.is(".treeview-menu")&&!f.is(":visible")){var g=c.parents("ul").first();g.find("ul:visible").slideUp(d).removeClass("menu-open");var h=c.parent("li");f.slideDown(d,function(){f.addClass("menu-open");
g.find("li.active").removeClass("active");h.addClass("active");b.layout.fix()})}f.is(".treeview-menu")&&a.preventDefault()})};$.AdminLTE.controlSidebar={activate:function(){var a=this,b=$.AdminLTE.options.controlSidebarOptions,d=$(b.selector);$(b.toggleBtnSelector).on("click",function(c){c.preventDefault();d.hasClass("control-sidebar-open")||$("body").hasClass("control-sidebar-open")?a.close(d,b.slide):a.open(d,b.slide)});var c=$(".control-sidebar-bg");a._fix(c);$("body").hasClass("fixed")?a._fixForFixed(d):
$(".content-wrapper, .right-side").height()<d.height()&&a._fixForContent(d)},open:function(a,b){b?a.addClass("control-sidebar-open"):$("body").addClass("control-sidebar-open")},close:function(a,b){b?a.removeClass("control-sidebar-open"):$("body").removeClass("control-sidebar-open")},_fix:function(a){var b=this;$("body").hasClass("layout-boxed")?(a.css("position","absolute"),a.height($(".wrapper").height()),$(window).resize(function(){b._fix(a)})):a.css({position:"fixed",height:"auto"})},_fixForFixed:function(a){a.css({position:"fixed",
"max-height":"100%",overflow:"auto","padding-bottom":"50px"})},_fixForContent:function(a){$(".content-wrapper, .right-side").css("min-height",a.height())}};$.AdminLTE.boxWidget={selectors:$.AdminLTE.options.boxWidgetOptions.boxWidgetSelectors,icons:$.AdminLTE.options.boxWidgetOptions.boxWidgetIcons,animationSpeed:$.AdminLTE.options.animationSpeed,activate:function(a){var b=this;a||(a=document);$(a).on("click",b.selectors.collapse,function(a){a.preventDefault();b.collapse($(this))});$(a).on("click",
b.selectors.remove,function(a){a.preventDefault();b.remove($(this))})},collapse:function(a){var b=a.parents(".box").first(),d=b.find("> .box-body, > .box-footer, > form  >.box-body, > form > .box-footer");b.hasClass("collapsed-box")?(a.children(":first").removeClass(this.icons.open).addClass(this.icons.collapse),d.slideDown(this.animationSpeed,function(){b.removeClass("collapsed-box")})):(a.children(":first").removeClass(this.icons.collapse).addClass(this.icons.open),d.slideUp(this.animationSpeed,
function(){b.addClass("collapsed-box")}))},remove:function(a){a.parents(".box").first().slideUp(this.animationSpeed)}}}
(function(a){a.fn.boxRefresh=function(b){function d(a){a.append(e);c.onLoadStart.call(a)}var c=a.extend({trigger:".refresh-btn",source:"",onLoadStart:function(a){return a},onLoadDone:function(a){return a}},b),e=a('<div class="overlay"><div class="fa fa-refresh fa-spin"></div></div>');return this.each(function(){if(""===c.source)window.console&&window.console.log("Please specify a source first - boxRefresh()");else{var b=a(this);b.find(c.trigger).first().on("click",function(a){a.preventDefault();d(b);
b.find(".box-body").load(c.source,function(){b.find(e).remove();c.onLoadDone.call(b)})})}})}})(jQuery);(function(a){a.fn.activateBox=function(){a.AdminLTE.boxWidget.activate(this)};a.fn.toggleBox=function(){var b=a(a.AdminLTE.boxWidget.selectors.collapse,this);a.AdminLTE.boxWidget.collapse(b)};a.fn.removeBox=function(){var b=a(a.AdminLTE.boxWidget.selectors.remove,this);a.AdminLTE.boxWidget.remove(b)}})(jQuery);
(function(a){a.fn.todolist=function(b){var d=a.extend({onCheck:function(a){return a},onUncheck:function(a){return a}},b);return this.each(function(){if("undefined"!=typeof a.fn.iCheck)a("input",this).on("ifChecked",function(){var b=a(this).parents("li").first();b.toggleClass("done");d.onCheck.call(b)}),a("input",this).on("ifUnchecked",function(){var b=a(this).parents("li").first();b.toggleClass("done");d.onUncheck.call(b)});else a("input",this).on("change",function(){var b=a(this).parents("li").first();
b.toggleClass("done");a("input",b).is(":checked")?d.onCheck.call(b):d.onUncheck.call(b)})})}})(jQuery);var templateSetup=[];$.fn.addTemplateSetup=function(a,b){b?templateSetup.unshift(a):templateSetup.push(a)};$.fn.applyTemplateSetup=function(){for(var a=templateSetup.length,b=0;b<a;++b)templateSetup[b].apply(this);return this};function sleep(a){return new Promise(resolve=setTimeout(resolve,a))}$.fn.modal.Constructor.prototype.enforceFocus=function(){};
