(function(e){"object"==typeof exports&&"object"==typeof module?e(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],e):e(CodeMirror)})(function(e){e.defineMode("julia",function(e,k){function f(b,a){"undefined"===typeof a&&(a="\\b");return new RegExp("^(("+b.join(")|(")+"))"+a)}function l(b,a){var d=h(b),c=h(b,1);"undefined"===typeof a&&(a="(");return d===a||c===a&&"for"===d?!0:!1}function h(b,a){"undefined"===typeof a&&(a=0);return b.scopes.length<=
a?null:b.scopes[b.scopes.length-(a+1)]}function g(b,a){if(b.match(/^#=/,!1))return a.tokenize=q,a.tokenize(b,a);var d=a.leavingExpr;b.sol()&&(d=!1);a.leavingExpr=!1;if(d&&b.match(/^'+/)||b.match(/^\.{2,3}/))return"operator";if(b.eatSpace())return null;var c=b.peek();if("#"===c)return b.skipToEnd(),"comment";"["===c&&a.scopes.push("[");"("===c&&a.scopes.push("(");var e=h(a);l(a,"[")&&"]"===c&&("for"===e&&a.scopes.pop(),a.scopes.pop(),a.leavingExpr=!0);l(a)&&")"===c&&("for"===e&&a.scopes.pop(),a.scopes.pop(),
a.leavingExpr=!0);var f;(f=b.match(r,!1))&&a.scopes.push(f[0]);b.match(t,!1)&&a.scopes.pop();if(l(a,"[")){if("end"==a.lastToken&&b.match(/^:/))return"operator";if(b.match(/^end/))return"number"}if(b.match(/^::(?![:\$])/))return a.tokenize=u,a.tokenize(b,a);if(!d&&b.match(v)||b.match(/:\./)||b.match(/^{[^}]*}(?=\()/))return"builtin";if(b.match(w))return"operator";if(b.match(/^[0-9\.]/,!1)&&(d=RegExp(/^im\b/),c=!1,b.match(/^\d*\.(?!\.)\d*([Eef][\+\-]?\d+)?/i)&&(c=!0),b.match(/^\d+\.(?!\.)\d*/)&&(c=
!0),b.match(/^\.\d+/)&&(c=!0),b.match(/^0x\.[0-9a-f]+p[\+\-]?\d+/i)&&(c=!0),b.match(/^0x[0-9a-f]+/i)&&(c=!0),b.match(/^0b[01]+/i)&&(c=!0),b.match(/^0o[0-7]+/i)&&(c=!0),b.match(/^[1-9]\d*(e[\+\-]?\d+)?/)&&(c=!0),b.match(/^0(?![\dx])/i)&&(c=!0),c))return b.match(d),a.leavingExpr=!0,"number";if(b.match(/^'/))return a.tokenize=x,a.tokenize(b,a);if(b.match(y))return a.tokenize=z(b.current()),a.tokenize(b,a);if(b.match(m))return"meta";if(b.match(A))return null;if(b.match(B))return"keyword";if(b.match(C))return"builtin";
d=a.isDefinition||"function"==a.lastToken||"macro"==a.lastToken||"type"==a.lastToken||"immutable"==a.lastToken;if(b.match(n)){if(d){if("."===b.peek())return a.isDefinition=!0,"variable";a.isDefinition=!1;return"def"}if(b.match(/^({[^}]*})*\(/,!1))return p(b,a);a.leavingExpr=!0;return"variable"}b.next();return"error"}function p(b,a){var d=b.match(/^(\(\s*)/);d&&(0>a.firstParenPos&&(a.firstParenPos=a.scopes.length),a.scopes.push("("),a.charsAdvanced+=d[1].length);if("("==h(a)&&b.match(/^\)/)&&(a.scopes.pop(),
a.charsAdvanced+=1,a.scopes.length<=a.firstParenPos))return d=b.match(/^\s*?=(?!=)/,!1),b.backUp(a.charsAdvanced),a.firstParenPos=-1,a.charsAdvanced=0,d?"def":"builtin";if(b.match(/^$/g,!1)){for(b.backUp(a.charsAdvanced);a.scopes.length>a.firstParenPos;)a.scopes.pop();a.firstParenPos=-1;a.charsAdvanced=0;return"builtin"}a.charsAdvanced+=b.match(/^([^()]*)/)[1].length;return p(b,a)}function u(b,a){b.match(/.*?(?=,|;|{|}|\(|\)|=|$|\s)/);b.match(/^{/)?a.nestedLevels++:b.match(/^}/)&&a.nestedLevels--;
0<a.nestedLevels?b.match(/.*?(?={|})/):0==a.nestedLevels&&(a.tokenize=g);return"builtin"}function q(b,a){b.match(/^#=/)&&a.nestedLevels++;b.match(/.*?(?=(#=|=#))/)||b.skipToEnd();b.match(/^=#/)&&(a.nestedLevels--,0==a.nestedLevels&&(a.tokenize=g));return"comment"}function x(b,a){var d=!1,c;if(b.match(D))d=!0;else if(c=b.match(/\\u([a-f0-9]{1,4})(?=')/i)){if(c=parseInt(c[1],16),55295>=c||57344<=c)d=!0,b.next()}else if(c=b.match(/\\U([A-Fa-f0-9]{5,8})(?=')/))c=parseInt(c[1],16),1114111>=c&&(d=!0,b.next());
if(d)return a.leavingExpr=!0,a.tokenize=g,"string";b.match(/^[^']+(?=')/)||b.skipToEnd();b.match(/^'/)&&(a.tokenize=g);return"error"}function z(b){b="`"===b||'"""'===b?b:'"';return function(a,d){if(a.eat("\\"))a.next();else{if(a.match(b))return d.tokenize=g,d.leavingExpr=!0,"string";a.eat(/[`"]/)}a.eatWhile(/[^\\`"]/);return"string"}}var w=k.operators||f("\\.?[\\\\%*+\\-<>!=\\/^]=? \\.?[|&\\u00F7\\u2260\\u2264\\u2265] \\u00D7 \\u2208 \\u2209 \\u220B \\u220C \\u2229 \\u222A \\u2286 \\u2288 \\u228A \\u22c5 \\? ~ : \\$ \\.[<>] <<=? >>>?=? \\.[<>=]= ->? \\/\\/ => <: \\bin\\b(?!\\()".split(" "),
""),A=k.delimiters||/^[;,()[\]{}]/,n=k.identifiers||/^[_A-Za-z\u00A1-\uFFFF][\w\u00A1-\uFFFF]*!*/,D=f(["\\\\[0-7]{1,3}","\\\\x[A-Fa-f0-9]{1,2}","\\\\[abefnrtv0%?'\"\\\\]","([^\\u0027\\u005C\\uD800-\\uDFFF]|[\\uD800-\\uDFFF][\\uDC00-\\uDFFF])"],"'"),r=f("begin function type immutable let macro for while quote if else elseif try finally catch do".split(" ")),t=f(["end","else","elseif","catch","finally"]),B=f("if else elseif while for begin let end do try catch finally return break continue global local const export import importall using function macro module baremodule type immutable quote typealias abstract bitstype".split(" ")),
C=f(["true","false","nothing","NaN","Inf"]),m=/^@[_A-Za-z][\w]*/,v=/^:[_A-Za-z\u00A1-\uFFFF][\w\u00A1-\uFFFF]*!*/,y=/^(`|"{3}|([_A-Za-z\u00A1-\uFFFF]*"))/;return{startState:function(){return{tokenize:g,scopes:[],lastToken:null,leavingExpr:!1,isDefinition:!1,nestedLevels:0,charsAdvanced:0,firstParenPos:-1}},token:function(b,a){var d=a.tokenize(b,a),c=b.current();c&&d&&(a.lastToken=c);"."===c&&(d=b.match(n,!1)||b.match(m,!1)||b.match(/\(/,!1)?"operator":"error");return d},indent:function(b,a){var d=
0;if("]"===a||")"===a||"end"===a||"else"===a||"catch"===a||"elseif"===a||"finally"===a)d=-1;return(b.scopes.length+d)*e.indentUnit},electricInput:/\b(end|else|catch|finally)\b/,blockCommentStart:"#=",blockCommentEnd:"=#",lineComment:"#",fold:"indent"}});e.defineMIME("text/x-julia","julia")});
