/*
 jQuery Knob*/
var $jscomp={scope:{},findInternal:function(b,e,d){b instanceof String&&(b=String(b));for(var f=b.length,g=0;g<f;g++){var h=b[g];if(e.call(d,h,g,b))return{i:g,v:h}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(b,e,d){if(d.get||d.set)throw new TypeError("ES3 does not support getters and setters.");b!=Array.prototype&&b!=Object.prototype&&(b[e]=d.value)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(b,e,d,f){if(e){d=$jscomp.global;b=b.split(".");for(f=0;f<b.length-1;f++){var g=b[f];g in d||(d[g]={});d=d[g]}b=b[b.length-1];f=d[b];e=e(f);e!=f&&null!=e&&$jscomp.defineProperty(d,b,{configurable:!0,writable:!0,value:e})}};
$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,d){return $jscomp.findInternal(this,b,d).v}},"es6-impl","es3");
(function(b){"object"===typeof exports?module.exports=b(require("jquery")):"function"===typeof define&&define.amd?define(["jquery"],b):b(jQuery)})(function(b){var e,d,f,g=Math.max,h=Math.min;e={};e.d=b(document);e.t=function(a){return a.originalEvent.touches.length-1};d=function(){var a=this;this.cv=this.v=this.g=this.i=this.$=this.o=null;this.h=this.w=this.y=this.x=0;this.c=this.$c=null;this.t=0;this.isInit=!1;this.rH=this.eH=this.cH=this.dH=this.pColor=this.fgColor=null;this.scale=1;this.relativeHeight=
this.relativeWidth=this.relative=!1;this.$div=null;this.run=function(){var c=function(c,b){for(var k in b)a.o[k]=b[k];a._carve().init();a._configure()._draw()};if(!this.$.data("kontroled")){this.$.data("kontroled",!0);this.extend();this.o=b.extend({min:void 0!==this.$.data("min")?this.$.data("min"):0,max:void 0!==this.$.data("max")?this.$.data("max"):100,stopper:!0,readOnly:this.$.data("readonly")||"readonly"===this.$.attr("readonly"),cursor:!0===this.$.data("cursor")&&30||this.$.data("cursor")||
0,thickness:this.$.data("thickness")&&Math.max(Math.min(this.$.data("thickness"),1),.01)||.35,lineCap:this.$.data("linecap")||"butt",width:this.$.data("width")||200,height:this.$.data("height")||200,displayInput:null==this.$.data("displayinput")||this.$.data("displayinput"),displayPrevious:this.$.data("displayprevious"),fgColor:this.$.data("fgcolor")||"#87CEEB",inputColor:this.$.data("inputcolor"),font:this.$.data("font")||"Arial",fontWeight:this.$.data("font-weight")||"bold",inline:!1,step:this.$.data("step")||
1,rotation:this.$.data("rotation"),draw:null,change:null,cancel:null,release:null,format:function(a){return a},parse:function(a){return parseFloat(a)}},this.o);this.o.flip="anticlockwise"===this.o.rotation||"acw"===this.o.rotation;this.o.inputColor||(this.o.inputColor=this.o.fgColor);this.$.is("fieldset")?(this.v={},this.i=this.$.find("input"),this.i.each(function(c){var k=b(this);a.i[c]=k;a.v[c]=a.o.parse(k.val());k.bind("change blur",function(){var b={};b[c]=k.val();a.val(a._validate(b))})}),this.$.find("legend").remove()):
(this.i=this.$,this.v=this.o.parse(this.$.val()),""===this.v&&(this.v=this.o.min),this.$.bind("change blur",function(){a.val(a._validate(a.o.parse(a.$.val())))}));!this.o.displayInput&&this.$.hide();this.$c=b(document.createElement("canvas")).attr({width:this.o.width,height:this.o.height});this.$div=b('<div style="'+(this.o.inline?"display:inline;":"")+"width:"+this.o.width+"px;height:"+this.o.height+'px;"></div>');this.$.wrap(this.$div).before(this.$c);this.$div=this.$.parent();"undefined"!==typeof G_vmlCanvasManager&&
G_vmlCanvasManager.initElement(this.$c[0]);this.c=this.$c[0].getContext?this.$c[0].getContext("2d"):null;if(!this.c)throw{name:"CanvasNotSupportedException",message:"Canvas not supported. Please use excanvas on IE8.0.",toString:function(){return this.name+": "+this.message}};this.scale=(window.devicePixelRatio||1)/(this.c.webkitBackingStorePixelRatio||this.c.mozBackingStorePixelRatio||this.c.msBackingStorePixelRatio||this.c.oBackingStorePixelRatio||this.c.backingStorePixelRatio||1);this.relativeWidth=
0!==this.o.width%1&&this.o.width.indexOf("%");this.relativeHeight=0!==this.o.height%1&&this.o.height.indexOf("%");this.relative=this.relativeWidth||this.relativeHeight;this._carve();this.v instanceof Object?(this.cv={},this.copy(this.v,this.cv)):this.cv=this.v;this.$.bind("configure",c).parent().bind("configure",c);this._listen()._configure()._xy().init();this.isInit=!0;this.$.val(this.o.format(this.v));this._draw();return this}};this._carve=function(){if(this.relative){var a=this.relativeWidth?this.$div.parent().width()*
parseInt(this.o.width)/100:this.$div.parent().width(),b=this.relativeHeight?this.$div.parent().height()*parseInt(this.o.height)/100:this.$div.parent().height();this.w=this.h=Math.min(a,b)}else this.w=this.o.width,this.h=this.o.height;this.$div.css({width:this.w+"px",height:this.h+"px"});this.$c.attr({width:this.w,height:this.h});1!==this.scale&&(this.$c[0].width*=this.scale,this.$c[0].height*=this.scale,this.$c.width(this.w),this.$c.height(this.h));return this};this._draw=function(){var c=!0;a.g=
a.c;a.clear();a.dH&&(c=a.dH());!1!==c&&a.draw()};this._touch=function(c){var b=function(c){c=a.xy2val(c.originalEvent.touches[a.t].pageX,c.originalEvent.touches[a.t].pageY);c==a.cv||a.cH&&!1===a.cH(c)||(a.change(a._validate(c)),a._draw())};this.t=e.t(c);b(c);e.d.bind("touchmove.k",b).bind("touchend.k",function(){e.d.unbind("touchmove.k touchend.k");a.val(a.cv)});return this};this._mouse=function(c){var b=function(c){c=a.xy2val(c.pageX,c.pageY);c==a.cv||a.cH&&!1===a.cH(c)||(a.change(a._validate(c)),
a._draw())};b(c);e.d.bind("mousemove.k",b).bind("keyup.k",function(c){27===c.keyCode&&(e.d.unbind("mouseup.k mousemove.k keyup.k"),a.eH&&!1===a.eH()||a.cancel())}).bind("mouseup.k",function(c){e.d.unbind("mousemove.k mouseup.k keyup.k");a.val(a.cv)});return this};this._xy=function(){var a=this.$c.offset();this.x=a.left;this.y=a.top;return this};this._listen=function(){this.o.readOnly?this.$.attr("readonly","readonly"):(this.$c.bind("mousedown",function(c){c.preventDefault();a._xy()._mouse(c)}).bind("touchstart",
function(c){c.preventDefault();a._xy()._touch(c)}),this.listen());this.relative&&b(window).resize(function(){a._carve().init();a._draw()});return this};this._configure=function(){this.o.draw&&(this.dH=this.o.draw);this.o.change&&(this.cH=this.o.change);this.o.cancel&&(this.eH=this.o.cancel);this.o.release&&(this.rH=this.o.release);this.o.displayPrevious?(this.pColor=this.h2rgba(this.o.fgColor,"0.4"),this.fgColor=this.h2rgba(this.o.fgColor,"0.6")):this.fgColor=this.o.fgColor;return this};this._clear=
function(){this.$c[0].width=this.$c[0].width};this._validate=function(a){return Math.round(~~((0>a?-.5:.5)+a/this.o.step)*this.o.step*100)/100};this.listen=function(){};this.extend=function(){};this.init=function(){};this.change=function(a){};this.val=function(a){};this.xy2val=function(a,b){};this.draw=function(){};this.clear=function(){this._clear()};this.h2rgba=function(a,b){var c;a=a.substring(1,7);c=[parseInt(a.substring(0,2),16),parseInt(a.substring(2,4),16),parseInt(a.substring(4,6),16)];return"rgba("+
c[0]+","+c[1]+","+c[2]+","+b+")"};this.copy=function(a,b){for(var c in a)b[c]=a[c]}};f=function(){d.call(this);this.w2=this.cursorExt=this.lineWidth=this.radius=this.xy=this.startAngle=null;this.PI2=2*Math.PI;this.extend=function(){this.o=b.extend({bgColor:this.$.data("bgcolor")||"#EEEEEE",angleOffset:this.$.data("angleoffset")||0,angleArc:this.$.data("anglearc")||360,inline:!0},this.o)};this.val=function(a,c){if(null!=a)a=this.o.parse(a),!1!==c&&a!=this.v&&this.rH&&!1===this.rH(a)||(this.v=this.cv=
this.o.stopper?g(h(a,this.o.max),this.o.min):a,this.$.val(this.o.format(this.v)),this._draw());else return this.v};this.xy2val=function(a,c){var b;b=Math.atan2(a-(this.x+this.w2),-(c-this.y-this.w2))-this.angleOffset;this.o.flip&&(b=this.angleArc-b-this.PI2);this.angleArc!=this.PI2&&0>b&&-.5<b?b=0:0>b&&(b+=this.PI2);b=b*(this.o.max-this.o.min)/this.angleArc+this.o.min;this.o.stopper&&(b=g(h(b,this.o.max),this.o.min));return b};this.listen=function(){var a=this,c,e,d=function(b){b.preventDefault();
var d=b.originalEvent;b=d.detail||d.wheelDeltaX;var d=d.detail||d.wheelDeltaY,f=a._validate(a.o.parse(a.$.val()))+(0<b||0<d?a.o.step:0>b||0>d?-a.o.step:0),f=g(h(f,a.o.max),a.o.min);a.val(f,!1);a.rH&&(clearTimeout(c),c=setTimeout(function(){a.rH(f);c=null},100),e||(e=setTimeout(function(){c&&a.rH(f);e=null},200)))},f,l,m=1,n={37:-a.o.step,38:a.o.step,39:a.o.step,40:-a.o.step};this.$.bind("keydown",function(c){var d=c.keyCode;96<=d&&105>=d&&(d=c.keyCode=d-48);f=parseInt(String.fromCharCode(d));isNaN(f)&&
(13!==d&&8!==d&&9!==d&&189!==d&&(190!==d||a.$.val().match(/\./))&&c.preventDefault(),-1<b.inArray(d,[37,38,39,40])&&(c.preventDefault(),c=a.o.parse(a.$.val())+n[d]*m,a.o.stopper&&(c=g(h(c,a.o.max),a.o.min)),a.change(a._validate(c)),a._draw(),l=window.setTimeout(function(){m*=2},30)))}).bind("keyup",function(b){isNaN(f)?l&&(window.clearTimeout(l),l=null,m=1,a.val(a.$.val())):a.$.val()>a.o.max&&a.$.val(a.o.max)||a.$.val()<a.o.min&&a.$.val(a.o.min)});this.$c.bind("mousewheel DOMMouseScroll",d);this.$.bind("mousewheel DOMMouseScroll",
d)};this.init=function(){if(this.v<this.o.min||this.v>this.o.max)this.v=this.o.min;this.$.val(this.v);this.w2=this.w/2;this.cursorExt=this.o.cursor/100;this.xy=this.w2*this.scale;this.lineWidth=this.xy*this.o.thickness;this.lineCap=this.o.lineCap;this.radius=this.xy-this.lineWidth/2;this.o.angleOffset&&(this.o.angleOffset=isNaN(this.o.angleOffset)?0:this.o.angleOffset);this.o.angleArc&&(this.o.angleArc=isNaN(this.o.angleArc)?this.PI2:this.o.angleArc);this.angleOffset=this.o.angleOffset*Math.PI/180;
this.angleArc=this.o.angleArc*Math.PI/180;this.startAngle=1.5*Math.PI+this.angleOffset;this.endAngle=1.5*Math.PI+this.angleOffset+this.angleArc;var a=g(String(Math.abs(this.o.max)).length,String(Math.abs(this.o.min)).length,2)+2;this.o.displayInput&&this.i.css({width:(this.w/2+4>>0)+"px",height:(this.w/3>>0)+"px",position:"absolute","vertical-align":"middle","margin-top":(this.w/3>>0)+"px","margin-left":"-"+(3*this.w/4+2>>0)+"px",border:0,background:"none",font:this.o.fontWeight+" "+(this.w/a>>0)+
"px "+this.o.font,"text-align":"center",color:this.o.inputColor||this.o.fgColor,padding:"0px","-webkit-appearance":"none"})||this.i.css({width:"0px",visibility:"hidden"})};this.change=function(a){this.cv=a;this.$.val(this.o.format(a))};this.angle=function(a){return(a-this.o.min)*this.angleArc/(this.o.max-this.o.min)};this.arc=function(a){var b;a=this.angle(a);this.o.flip?(b=this.endAngle+1E-5,a=b-a-1E-5):(b=this.startAngle-1E-5,a=b+a+1E-5);this.o.cursor&&(b=a-this.cursorExt)&&(a+=this.cursorExt);
return{s:b,e:a,d:this.o.flip&&!this.o.cursor}};this.draw=function(){var a=this.g,b=this.arc(this.cv),d;d=1;a.lineWidth=this.lineWidth;a.lineCap=this.lineCap;"none"!==this.o.bgColor&&(a.beginPath(),a.strokeStyle=this.o.bgColor,a.arc(this.xy,this.xy,this.radius,this.endAngle-1E-5,this.startAngle+1E-5,!0),a.stroke());this.o.displayPrevious&&(d=this.arc(this.v),a.beginPath(),a.strokeStyle=this.pColor,a.arc(this.xy,this.xy,this.radius,d.s,d.e,d.d),a.stroke(),d=this.cv==this.v);a.beginPath();a.strokeStyle=
d?this.o.fgColor:this.fgColor;a.arc(this.xy,this.xy,this.radius,b.s,b.e,b.d);a.stroke()};this.cancel=function(){this.val(this.v)}};b.fn.dial=b.fn.knob=function(a){return this.each(function(){var c=new f;c.o=a;c.$=b(this);c.run()}).parent()}});
