(function(d){"object"==typeof exports&&"object"==typeof module?d(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],d):d(CodeMirror)})(function(d){function l(d,g){for(var e=0;e<d.length;e++)g(d[e],e)}function q(d,g){for(var e=0;e<d.length;e++)if(g(d[e],e))return!0;return!1}d.defineMode("dylan",function(d){function g(a,c,b){c.tokenize=b;return b(a,c)}function e(a,c){var b=a.peek();if("'"==b||'"'==b)return a.next(),g(a,c,m(b,"string"));if("/"==b){a.next();
if(a.eat("*"))return g(a,c,r);if(a.eat("/"))return a.skipToEnd(),"comment";a.backUp(1)}else if(/[+\-\d\.]/.test(b)){if(a.match(/^[+-]?[0-9]*\.[0-9]*([esdx][+-]?[0-9]+)?/i)||a.match(/^[+-]?[0-9]+([esdx][+-]?[0-9]+)/i)||a.match(/^[+-]?\d+/))return"number"}else{if("#"==b){a.next();b=a.peek();if('"'==b)return a.next(),g(a,c,m('"',"string"));if("b"==b)return a.next(),a.eatWhile(/[01]/),"number";if("x"==b)return a.next(),a.eatWhile(/[\da-f]/i),"number";if("o"==b)return a.next(),a.eatWhile(/[0-7]/),"number";
if("#"==b)return a.next(),"punctuation";if("["==b||"("==b)return a.next(),"bracket";if(a.match(/f|t|all-keys|include|key|next|rest/i))return"atom";a.eatWhile(/[-a-zA-Z]/);return"error"}if("~"==b)return a.next(),b=a.peek(),"="==b&&(a.next(),b=a.peek(),"="==b&&a.next()),"operator";if(":"==b){a.next();b=a.peek();if("="==b)return a.next(),"operator";if(":"==b)return a.next(),"punctuation"}else{if(-1!="[](){}".indexOf(b))return a.next(),"bracket";if(-1!=".,".indexOf(b))return a.next(),"punctuation";if(a.match("end"))return"keyword"}}for(var d in f)if(f.hasOwnProperty(d)){var e=
f[d];if(e instanceof Array&&q(e,function(b){return a.match(b)})||a.match(e))return t[d]}if(/[+\-*\/^=<>&|]/.test(b))return a.next(),"operator";if(a.match("define"))return"def";a.eatWhile(/[\w\-]/);if(n.hasOwnProperty(a.current()))return p[a.current()];if(a.current().match(u))return"variable";a.next();return"variable-2"}function r(a,c){for(var b=!1,d=!1,f=0,h;h=a.next();){if("/"==h&&b)if(0<f)f--;else{c.tokenize=e;break}else"*"==h&&d&&f++;b="*"==h;d="/"==h}return"comment"}function m(a,c){return function(b,
d){for(var f=!1,h,g=!1;null!=(h=b.next());){if(h==a&&!f){g=!0;break}f=!f&&"\\"==h}if(g||!f)d.tokenize=e;return c}}var c={unnamedDefinition:["interface"],namedDefinition:"module library macro C-struct C-union C-function C-callable-wrapper".split(" "),typeParameterizedDefinition:["class","C-subtype","C-mapped-subtype"],otherParameterizedDefinition:["method","function","C-variable","C-address"],constantSimpleDefinition:["constant"],variableSimpleDefinition:["variable"],otherSimpleDefinition:["generic",
"domain","C-pointer-type","table"],statement:"if block begin method case for select when unless until while iterate profiling dynamic-bind".split(" "),separator:"finally exception cleanup else elseif afterwards".split(" "),other:"above below by from handler in instance let local otherwise slot subclass then to keyed-by virtual".split(" "),signalingCalls:"signal error cerror break check-type abort".split(" ")};c.otherDefinition=c.unnamedDefinition.concat(c.namedDefinition).concat(c.otherParameterizedDefinition);
c.definition=c.typeParameterizedDefinition.concat(c.otherDefinition);c.parameterizedDefinition=c.typeParameterizedDefinition.concat(c.otherParameterizedDefinition);c.simpleDefinition=c.constantSimpleDefinition.concat(c.variableSimpleDefinition).concat(c.otherSimpleDefinition);c.keyword=c.statement.concat(c.separator).concat(c.other);var u=/^[-_a-zA-Z?!*@<>$%]+/,f={symbolKeyword:"[-_a-zA-Z?!*@<>$%]+:",symbolClass:"<[-_a-zA-Z?!*@<>$%]+>",symbolGlobal:"\\*[-_a-zA-Z?!*@<>$%]+\\*",symbolConstant:"\\$[-_a-zA-Z?!*@<>$%]+"},
t={symbolKeyword:"atom",symbolClass:"tag",symbolGlobal:"variable-2",symbolConstant:"variable-3"},k;for(k in f)f.hasOwnProperty(k)&&(f[k]=new RegExp("^"+f[k]));f.keyword=[/^with(?:out)?-[-_a-zA-Z?!*@<>$%]+/];var v={keyword:"keyword",definition:"def",simpleDefinition:"def",signalingCalls:"builtin"},n={},p={};l(["keyword","definition","simpleDefinition","signalingCalls"],function(a){l(c[a],function(c){n[c]=a;p[c]=v[a]})});return{startState:function(){return{tokenize:e,currentIndent:0}},token:function(a,
c){return a.eatSpace()?null:c.tokenize(a,c)},blockCommentStart:"/*",blockCommentEnd:"*/"}});d.defineMIME("text/x-dylan","dylan")});
